== Historical Note

By the 1800`'s,
the Society of Friends had greatly degenerated from its original purity and power.
The great majority of its members had been born into the
Society (inheriting their membership from their parents),
but had little first-hand experience of the heart-cleansing light, life,
and power of Jesus Christ.
At this time, there was still a remnant of living and weighty members and ministers,
but "`the cares of this world, the deceitfulness of riches,
and the desires for other things`" had opened up
many inroads for the ravishes of the evil one,
whose schemes were carefully calculated for the tearing down of what remained.
 

As early as 1819,
a man by the name of Elias Hicks began to spread new and
unsound doctrines throughout the Society in America.
Though he spoke much of an "`inner light,`" and alleged his
teachings to be in agreement with early Quaker principles,
they were in fact very much at odds with the long-established
beliefs of the Society (and Christianity in general),
and so were rejected and disavowed by the prudent and faithful.
His eloquent sermons exalted a sort of spiritual religion,
speaking much of love for neighbors, abolition of slavery,
and other right-sounding concepts,
but he led his followers into a disregard for the Scriptures,
and a total denial of several fundamentals of Christianity--such as the incarnation,
virgin birth, and divinity of Christ, the atonement by the cross,
the existence of Satan, etc.
He taught that Jesus Christ was nothing more than a good man who,
having followed the light of God, was endowed with divinity, often saying things like,
"`The same power that made Christ a Christian must make us Christians;
and the same power that saved him must save us.`" Eventually,
Hicks and his followers caused the first of two
great divisions in the Society of Friends,
disassociating from "`orthodox`" Quakers,
and initiating their own separatist society of "`Hicksite`" Quakers in 1827.

Perhaps in an attempt to distance themselves from these errors,
and to avoid the false light preached by the Hicksites,
Quakers in England soon began to pull away from some of
the original principles and practices of early Friends,
especially those having to do with entire dependence upon the
immediate influence of God`'s Spirit for true worship,
ministry, and spiritual understanding.
Greatly influenced by the preaching and writings of Joseph John Gurney,
many who had not been seduced by Hicksism began to conform more and
more to a traditional and formal Protestant Christianity that did not
rightly emphasize the revelation and formation of Christ within.
These so-called "`Gurneyites`" progressively departed from
many of the precious truths that God had restored to His
church at the bright commencement of the Society of Friends.
Sadly, by the end of the 1800`'s, the Society was small and degenerate,
and the Christianity of the two largest camps (Hicksites and
Gurneyites) bore little resemblance to the blessed Truth as
professed and upheld by their worthy predecessors.

This brief historical introduction was thought warranted because the following
journal makes frequent mention of these two groups and their leaders,
without offering much context or explanation.

[.signed-section-signature]
Jason R. Henderson

[.signed-section-context-close]
June, 2017
