== Chapter II

[.chapter-synopsis]
* Commencement of Her Diary Entries
* First Poetry
* Death of Her Mother
* A Religious Visit to Salem in Company with Her Father
* A Religious Visit to Meetings in Indiana
* Visit to a Neighboring Monthly Meeting

Tenth Month 19th, 1826.--The forepart of this evening was spent in much quietness,
but towards bed-time a confab ensued which I fear had a
tendency to draw our minds off from a state of watchfulness;
for as it is recorded,
so have I experienced it to be--"`In the multitude of words sin is not lacking;`"
and I know there is often much loss sustained when young persons are assembled
together in asocial way by indulging in light and unnecessary conversation,
jesting, joking, etc.;
which would be dispensed with were we to maintain the true dignity of Christians,
and duly consider,
that for every idle word that men shall speak they shall give an
account in the day of judgment according to the words of our Savior.
As for myself, I can adopt the language of the poet:

[verse]
____
My good resolves are not a few,
Though transient as a cloud;
Today I bid the world adieu,
Tomorrow join the crowd.
____

[.no-indent]
And there seems to be but little hope of amendment.

[verse]
____
May I govern my passions with absolute sway
And grow wiser and better as life wears away.
____

Fourth Month, 1828.

[verse]
____
To thee alone, oh gracious God,
My griefs are fully known,
To thee and to thy blessed Son,
One with thee in thy throne.
My soul does know the path to be
A narrow one indeed,
That leads to blessedness and thee,
But thou hast that decreed.
In judgment, oh most gracious God,
Remember mercy, too,
And with thy wise chastising rod,
My stubborn will subdue.
____

Fifth Month 25th, 1829.--I have been renewedly made sensible this evening,
that it is only as we are brought into a capacity humbly to
acknowledge that of ourselves we can do no good thing,
that we are able to make a just discrimination between the
things that belong to Caesar and those which belong to God.
And although many of us can acknowledge that we have made but
little if any progress in the great work of regeneration,
yet I believe that every tribute that has not
the Divine image and superscription upon it,
offered unto Him, will not only meet with his rejection,
but will fail to be acknowledged by the witness
for truth in the hearts of the children of men.

Ninth Month 14th,
1832.--When for several weeks together our minds are constantly and
solemnly impressed with the necessity of a godly life and conduct,
and that too without any particular distress of body or mind,
ought we not to consider it a special call to holiness
of the most gracious and condescending nature.
"`Oh Lord,
create in me a clean heart and renew a right spirit within me,`"
that I may not suffer in vain all that I have suffered,
if it be yet in vain.

24th.--I mourn like a dove for the day to arrive when
my heart shall be freed from the thraldom of sin.
"`Oh vain and inconstant world!
Oh fleeting and transient life,
when will the sons of men learn to think of you as they ought.`"

Tenth Month 11th.

[verse]
____
Now, if consistent with thy will,
Great God thy promises fulfill,
And bless my father`'s house;
May all our hearts be turned to thee,
Our wills to thine subjected be
That we may pay our vows.

Oh make the towering cedars bow.
Bring all the oaks of Bashan low,
Exalt thy holy name;
Let every soul contrited prove,
Rejoicing only in thy love,
Kindle a lasting flame.

Oh gracious Father, deign to hear,
Lord, we beseech thee, lend an ear
And hear the suppliants`' cry:
Parents and children join in one
To supplicate thy holy throne,
Whose dwelling is on High.
____

+++[+++The foregoing lines were written when the author was in good health,
and only a few months previous to the beginning of a lingering
illness of which mention has been already made in this book,
and the writer believes that the petition contained in those lines was remarkably
answered during this illness in reference to her own case and others of the family.]

Sixth Month 7th, 1833.

[verse]
____
Tis time for amendment, my health has declined,
My vows are all broken, unpaid;
In health I have murmured, midst blessings repined,
And the Lord`'s righteous will disobeyed.

"`Awaken, oh sleeper,`" with sound of alarm,
Hath oft been announced in mine ear;
The thought of destruction, the heart-rending storm,
Hath made me to tremble and fear.

My every resolve, like the dew on the grass,
For amendment, hath vanished away;
And time and experience have taught me at last
That pleasure and health will decay.
____

Eighth Month.

[verse]
____
Lord unto thee I now commit my soul.
Be all my actions under thy control,
My will, my wisdom and my every thought,
Oh may they be to true subjection brought.
Enable me at thy Almighty call,
To take fresh courage and to part with all,
To part with all--No longer let it be
My sin to sorrow and depart from thee.
Sell all thou hast--Oft has this gracious word
Within my bosom secretly been heard,
To part with all.
____

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Ninth Month 2nd, 1833.

[.salutation]
Dear Cousin Miriam Ellis:

Seldom during my late affliction,
have I found it congenial with the health of mind or body to use my pen;
but an unexpected and almost an undesired liberty induces me this afternoon
to acknowledge the receipt of the few lines you sent me some months ago.
Not that I believe you are looking for or desiring thanks from
me for the performance of that which you believed to be,
and no doubt was, your religious duty.
For I do most surely believe that the more we become
acquainted and follow the teachings of the Holy Spirit,
the less we shall seek after or desire the honor that comes not from God only.
My health is very precarious, and I know not how it may terminate.
But will not the Judge of all the earth do right?

[.signed-section-closing]
From your afflicted cousin,

[.signed-section-signature]
Ann Branson

--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Ninth Month 4th.

[.salutation]
Dear sister Lydia, now attending Yearly Meeting.

You know that I am obliged to use my pen seldom and sparingly;
but permit me to tell you that we are getting along very
quietly and quite as comfortably as circumstances will admit.
Mother has no cause for much anxiety on my account,
which I esteem a favor--called to see us yesterday,
you know it is very pleasant to have the company of dear, but far more to be desired,
is the presence of Him who is strength in weakness,
and a present helper in the needful time, to those who put their trust in Him.
Is it a time in which you are sensibly partaking of the bread
from heaven? Or is it a time of withholding? Murmur not if the
latter be your condition at this annual gathering,
for it is surely of the Lord`'s mercies that we are not consumed,
because his compassions fail not.

[.signed-section-closing]
From your afflicted sister,

[.signed-section-signature]
Ann Branson

--

Ninth Month 23rd.

[verse]
____
What shall I render to my God
For all his gifts to me,
For with his wise chastising rod
He`'s gently stricken me.

Gently, for days and months gone by,
The work thou hast renewed,
Hast heard the wanderer`'s bitter cry
In secret solitude.
____

Third Month 12th, 1834--Oh!
Lord God of Hosts, grant ability this day, I beseech You, to do your holy will,
grant light enough to walk in without stumbling.
May your will be done in me, and by me, and through me. Oh!
God of my life, I am in a strait, undertake for me,
that your truth may not be blamed through my omission or commission.
If it be right that I should again be brought into great
tribulation for my own refinement and for the sake of others,
your will be done.
Be pleased to prosper the prayers of your servants of every age and station;
magnified and adored be your worthy name now and forever.

Fifth Month 13th.--Should I ask a blessing for myself,
it would be this,--a cheerful resignation to the Lord`'s will,
even in the most humiliating seasons,
and preservation from the snares of the enemy of my soul`'s peace.
This is what I have in some degree experienced in time past,
and also that peace which the world cannot give.

Fifth Month 27th.--Condescend, O, most Holy Father,
to preserve with your preserving power, those who put their trust in You;
when You permit the overflowing scourge to pass through this land and this place;
when You whet your sword and pass over to destroy and
to make an utter end according to your will and purpose;
Oh! spare the children of this family.
Let us be found abiding in our tents, that your hand may spare us,
and give us willing and obedient minds, and understanding hearts,
to know and to do your will, and to keep your commandments.
And if You call my father to labor in another place, or another part of the land,
grant that your protecting power may support him and those he may leave behind,
for your own blessed name`'s sake, who alone are worthy of all honor,
praise and thanksgiving, now and forever, amen.
And now, Oh!
Lord! if it please You, grant that my health may be so restored,
as that I may be enabled to accompany my father in body or
mind through many deep trials he may have to encounter,
whether by day or by night, whether it be in mental conflict or bodily suffering,
that I may be permitted to bear up his hands when the
raging waves may be permitted to beat vehemently.

Tenth Month 30th, 1835. This evening one year ago, my beloved mother died.
The summons was very sudden.
She retired to bed about nine o`'clock, apparently in usual health;
between the hours of ten and eleven she awoke, and complained of pain in her breast.
My father hastened downstairs to get something for her relief;
he returned in a short time and found her dying.
Her death was believed to have been occasioned
by an abscess in her side breaking inwardly.
For some days before her death my feelings were unusually solemn,
and I believe she felt the same way.
Oh! may I ever remember the solemn warning the blessed Master
saw fit to give us in the removal of my dear mother.
It matters not for her, we have no cause to doubt her preparation.
But the call to her family, friends and neighbors is impressive--"`You also be ready,
for at such an hour as you think not, the Son of Man comes.`"

Fourth Month 15th,
1836.--A feeling of the absence of the Beloved of Souls
has accompanied my mind for some months past.
Oh! when will the winter be past;
the rains over and gone? When shall I experience the light of the glorious
countenance of the Lord to fill my heart as in days that are past,
when He was pleased to lay his chastening hand
upon me and bring forth judgment unto truth;
when He saw fit to appoint many bitter cups for me to drink,
hard for flesh and blood to endure, yes, the very things my soul refused to touch,
did indeed become my sorrowful meat.
But in all these things is the life of my spirit.

Sixth Month 15th.--I arose this morning with the sun,
which shone for a little time with brightness and lustre,
but suddenly its brightness was diminished and almost totally
obscured by a thick mist which covered the whole face of nature,
as far as mine eyes could reach.
What a striking illustration said I, is this which I now see in the visible creation,
of the frequent condition of my own mind.
Many times when nothing is seen outwardly, or felt inwardly, to disquiet my feelings,
how quick, how sudden the transition from pleasant to mournful reflections; a moment,
or the effect of a moment,
is sufficient to cause a train of unpleasant feelings
and reflections to accompany us throughout the day.
But why not learn to wait patiently for the arising of better feelings? Why
not watch and wait with as much hope for this inward tumult to subside,
as for the thick mist to be dispersed and the enlivening rays
of the sun again to break forth and scatter the gloom? Oh!
that I may learn not to speak unadvisedly with my lips,
when my heart is full of trouble,
when many things inwardly and outwardly combine to ruffle and perplex the mind.
May I learn more and more to trust in Him who is able to say to the waves of affliction,
"`Hitherto shall you go and no farther.`"
May his power be daily and hourly borne in mind, sought after and waited for;
not only to preserve us in trouble and to rescue from temptation,
but also to cleanse from every defilement.
That,
as "`the refining pot is for silver and the furnace for
gold,`" may I be the better for all the troubles,
crosses and afflictions permitted to come upon me,
and prepared when done with this state of
probation for that "`city which has foundations,
whose builder and maker is God.`"

Second Month 16th, 1840.--Arrived safely home after an absence of four weeks,
during which time I have visited in company with my beloved father,
the meetings and some of the families belonging to Salem and Springfield quarters;
and I may thankfully acknowledge that Israel`'s unslumbering shepherd has not
been lacking in giving strength and ability to pursue the path of duty,
when at times we seemed almost ready to give out.
He is ever ready to direct and strengthen those who put their trust in Him.
May the remaining days of my life be spent to his honor and glory, who is ever worthy.
What a feeble and unworthy instrument am I to be called
to proclaim the glad tidings of the gospel to others.
But the Lord has a right to make use of such
instruments as He sees fit to employ in his service,
"`Male and female all one in Christ.`"
Therefore let none shrink or give back, who are thus called,
but give up unreservedly to the Divine will.

In the Eighth Month of this year, 1840,
I obtained liberty of the Monthly and Quarterly Meetings (Flushing
Monthly and Short Creek Quarterly) to attend Indiana Yearly Meeting,
and to visit some of the meetings belonging thereto,
and to appoint some meetings among those not in membership with us. My cousin,
Samuel Smith and my aunt Martha Holloway were my companions in
this visit,--both elders of Flushing Monthly Meeting.
Two friends on horseback accompanied us to Mount Gilead,
where Alum Creek Quarterly Meeting is held.
We travelled from Smyrna to Coshocton, a distance of forty miles, the first day.
It was rainy, the road hilly and muddy,
and we did not get to our lodging until after night.
Before reaching the town of Coshocton, we had to descend a long hill,
and it being very dark,
one of the men on horseback had to dismount and feel for the road with his hands.
On reaching the hotel our men friends observed several
very rough looking persons in the bar-room,
and the landlord not any ways behind them in appearance.
Some murders and outrages having been recently committed near this place,
and the town not bearing a good name, caused some anxiety as to the safety of travellers.
After supper my aunt and I were shown to our lodging room, which had a lock to the door;
we fastened ourselves in and slept well until morning.
Not so with our men Friends.
They were shown into a room having three beds in it, without any fastening to the door.
In one of the beds lay a man apparently sound asleep, and snoring quite loud.
Two of our friends retired very soon,
the other stayed reading for some time in a book he found lying on the stand.
While he was reading,
the door of their room was pushed open and a very rough looking man entered.
On being asked what he wanted, he made no reply, but soon retreated.
After the other Friend had gone to bed, Samuel Smith became more uneasy,
and had one of the bedsteads placed against the door.
During the night they found some one was trying to enter the room by pushing at the door.
Samuel Smith then called out in a loud, stern voice, asking who was at the door,
and what was wanted,
saying that he had a mind to get up and go downstairs and find out what was going on,
adding,
here is a man in bed apparently asleep (for nothing as yet seemed to
arouse him) and for aught I know is acting the opossum.
After this all was still until morning;
and at early dawn we were up making ready for our escape from this place.
But before leaving, one of the Friends observed on the opposite side of the street,
the man who bad entered the room before they had all retired;
and on making inquiry who he was, no one seemed to know him.
Soon after we were at Coshocton,
a man and his family stopped at this hotel to tarry for a few days.
While there the man was murdered.

Before we left Coshocton,
some of our company went to view the hill we had descended in the dark,
and found that we had passed over very dangerous ground,
the wheels of our carriage just escaping the precipice.
Thus, through the mercy of our Heavenly Father, we left this town in safety.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Mount Gilead, Ninth Month 20th, 1840.

[.salutation]
My Dear Father,

We are now at the house of our friend,
J+++.+++ W. S. Arrived here yesterday morning in time for meeting,
in good health and without accident.
As yet I have not regretted starting on this journey.
Although it has been sunshine thus far (in a spiritual sense)
yet I doubt not the clouds will be permitted to intervene,
and perhaps continue many days and nights on my tabernacle.
Oh, that I may be so watchful, and so favored, as to dwell in the ward whole nights;
not straining my eyes in the dark, as dear Sarah Grubb says, believing in the Light,
and waiting patiently for its appearance and direction.

You, my dear father, are much before the view of my mind, almost constantly when awake,
and not in meeting.
It may be your spirit goes with us, I hope at least your prayers do.

25th.--We got to Alum Creek this morning.
Attended their meeting for worship in the forenoon,
and their Select Preparative in the afternoon.

It is a low time, at least it feels so to me,
and the Answers to the Queries indicate the same;
and I feel that it is needful for me to keep close to the pointings of the good Shepherd;
to say nothing more nor less than He requires.
This is what I desire to do, and I hope you will crave it for me.

22nd.--Attended Monthly Meeting at Alum Creek, today.
Joseph Edgerton and companion came in after the meeting was nearly gathered.
They rode thirty miles this morning before meeting.
John Wood, Sr., has been here, but has gone towards Indiana.
He had a public meeting at this place, and was silent therein.
This is the way for ministers to mind their steps.

24th.--We are now at Goshen, and attended their Select Quarterly Meeting today.
It is quite sickly in these parts, but our little company keeps well and cheerful,
and perhaps we may be favored to escape all these maladies and get safely home.
I am glad I was at meeting today.
As the bearer of this, A. P., will leave here tomorrow, after Quarterly Meeting closes,
before I have time to add anything to this, I must bid farewell.

[.signed-section-closing]
Affectionately your daughter,

[.signed-section-signature]
Ann Branson

--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Richmond, Indiana, Ninth Mo. 27th, 1840.

[.salutation]
My Dear Father,

This morning arrived at this place,
having Daniel Wood for our pilot from Goshen.
Yesterday we fell in company with John Wood from New York.
He appeared glad to see us and you know we were glad to meet with him.

29th.--Today attended the select Yearly Meeting of ministers and elders.
Truly things are at a low ebb here; much more so than I had any idea of before coming.
The true Israelitish seed is pressed as a cart loaded with sheaves;
I hope to be preserved in faith and patience.
My soul feels in jeopardy.
Pray you for us, and for me, in an especial manner.

[.signed-section-signature]
Ann Branson

--

30th.--Today a public meeting was held.
I thought it was remarkably favored.
A living ministry being largely exercised therein by John Wood and E. R. The
doctrines of our religious Society were opened with clearness and pertinency.
What a favor it is that some (I trust many) are still preserved on the
Ancient Foundation against which the storms and tempests cannot prevail.
My feelings I cannot describe,
on contemplating the goodness and tender mercy of the Lord
towards a gainsaying and rebellious people as we are.

Tenth Month 1st.--This morning the Select Meeting again convened,
and I had to express my belief that there was
something at work like the mole underground,
to sap and undermine the foundation of our religious Society;
and I had to warn Friends against its insidious working.
It seemed to me, that I saw this spirit at work, with my spiritual eye,
as plainly as I could discern with my natural eyes the workings of the mole when it
is seen burrowing in the earth and trying to hide itself from observation.
Several living testimonies were borne in this meeting to the honor and, I trust,
to the promotion of the Truth.
The Meeting for Business in the afternoon was large and crowded.
In the evening attended a meeting of the African Committee.
All were at liberty to attend who chose to do so. One
end of the Yearly Meetinghouse was nearly filled,
and it was indeed a time of disorder and confusion.
It was soon evident that two parties had met,
with sentiments and feelings very adverse one to the other.
One party believed that Friends ought not to use the products of slave labor,
and endeavored to show the necessity, propriety, and practicability,
of abstaining therefrom; pressing their sentiments in away and manner,
which gave evidence that many of them were actuated by a wrong spirit,
and that their zeal was not according to true knowledge.
Some of those who opposed them were also vehement in their expressions of opposition,
and evinced a disposition far from that which characterizes the true Christian.

The confusion, and I might say uproar, which we witnessed on this occasion,
reminded me of what is recorded in the New Testament, when the cry was,
"`Great is Diana of the Ephesians.`"^
footnote:[This dissension continued in Indiana Yearly
Meeting until a separation was brought about,
which occurred in a few years after the above record.]

The Yearly Meeting closed on Third-day of the second week.
Richmond Mid-week Meeting was next day, which I attended,
and had religious service therein, to the relief and peace of my mind.
John Wood was also there and had good service.
His speech and his preaching are not with "`enticing words of
man`'s wisdom but in demonstration of the Spirit and of power.`"

From Richmond we went to Alum Creek,
and I asked and obtained liberty of the Monthly Meeting
to visit some families within their limits.
At Greenwich there had been a large meeting,
consisting of many young and youngish people, and some aged ones.
But some disagreement arising among the heads of the meeting it had been laid down,
and this neighborhood was without a Friends`' Meeting.
It was in this locality I visited families,
and endeavored to lay before Friends the necessity of each and every one
doing his and her part towards healing the breaches that had been made;
so that peace and harmony might be restored.
I had heard nothing about the cause of the difficulty nor who was implicated therein,
but during the visit,
I was led to speak very plainly to some who I believed were causing trouble.
One of this description, after our visit was over,
offered to pilot us to another neighborhood, and was very friendly.
After my return home I was told that some of the
disaffected members who had caused the most trouble,
endeavored to make friends (who were laboring to
restore peace and harmony among them) believe,
that I was in unity and fellowship with them;
speaking in strong terms of approbation of the family visit.
Among those was the individual who offered his services as pilot,
But in a short time this man was taken dangerously ill and was nigh unto death.
He then confessed that I compared him to Judas when I visited him and his family.
Thus the eyes of some Friends who had been blinded,
were opened to see that I had not been engaged in
strengthening a perverse and contentious spirit.

While I was out on this visit I had an appointed meeting at Urbana,
the capitol of Champaign Co., Ohio, which was held to good satisfaction.
In this meeting I was led to speak on the subject of war--the peaceable nature of
the Gospel--and the incompatibility of war with the precepts of our Savior,
etc.
It was marvelous in mine eyes how the Lord gave
me strength and wisdom to treat this subject.
It being court week many of the principal men of the county were at the meeting,
and it was a favored opportunity.
I also appointed a meeting at Troy, the capitol of Miami Co., Ohio.
This meeting was held in the Methodist Meetinghouse;
and being induced by the judgment of another, contrary to my own sense of propriety,
to take my seat in the pulpit, which was a very elevated one,
the meeting was not so satisfactory as it might have been had
I attended to the intimations of duty on my own mind.
I would encourage ministers to attend strictly
to the intimations of truth on their own minds,
and not to be improperly influenced in such cases by
others who may not feel the same scruples.

Fourth Month 26th, 1841.--You only know, oh holy Father,
for what purpose you permit the overflowing surge thus
often to come upon me. Yet I thank you,
and can this moment acknowledge, that it is your arm of power,
that only and alone can sustain me in these proving conflicts;
for had you not interposed when the enemy has come in like a flood,
I had been entirely undone, my confidence had failed,
my foot had slidden into the gulf of despair.
I had fainted had not your mercy upheld me, and given me to believe,
that I should yet see and feel your goodness in the land of the living.

Fifth Month 7th.--Teach me, oh Lord, to number my days and to apply my heart unto wisdom.
Few think enough about the termination of their existence here below;
and the certainty of the coming of that moment when we shall
hear the language--"`Come you blessed of my Father,
inherit the kingdom prepared for you from the
foundation of the world:`" or "`Depart from me,
you cursed, into everlasting fire, prepared for the devil and his angels.`"
I sometimes think my life is such a continual state of conflict and trial,
that perhaps the sands in my hour-glass are nearly run.
But if these trials and conflicts only tend to purify and refine me,
I shall be very thankful that they have been dispensed.

It is not wealth, riches, or the honor of this world that I crave.
It is not change of place or outward circumstances that will make me happy,
but it is a mind resigned to do the Lord`'s will,
to follow Him whithersoever He is pleased to lead.
This is what I desire more than any earthly gain.

But if this had been enough my concern for some years past,
I should have been further advanced in my journey towards Zion,
I should have been more resigned to the will of God,
and more helpful in the Church Militant.
Oh Lord, sanctify me thoroughly,
that I may once more behold your glory and the
excellency of your kingdom as in days past,
and be prepared through mercy to ascribe all honor, glory,
and thanksgiving unto you unto whom it belongs forever and forevermore.
Amen.

Eleventh Month 2nd,
1842.--In taking a retrospect of the time past since the foregoing was written,
I find that much of it has been spent under deep mental
conflict which language cannot fully describe,
yet not without some moments and hours of sunshine interspersed amidst the gloom.
"`For all I bless you most for the severe,`" is the language that now pervades my heart;
I bless, praise and magnify the name of the Lord,
that He has been pleased to try me and prove me as in the night
season--to withdraw the light of his countenance from me,
and to enable me to feel and discover by his holy Spirit,
my utter inability of myself to keep my place or habitation in the Truth.
Oh, holy Father, forgive, I beseech you,
the impatience of my spirit under those close and proving seasons,
and teach me to abide patiently the turnings of your holy hand upon me,
until all the dross, tin, and reprobate silver are consumed.
Oh the unspeakable joy of that soul at times, whose meat and drink it is,
to do the will of our Father in Heaven.
Blessed, praised and adored be his holy name forever, and let all the world say amen;
for He raises up the poor from the dunghill, He has compassion on the work of his hands,
He has many and many a time plucked my feet out of the miry clay,
and from the horrible pit has He again and again rescued me,
even from the pit of despair, into which I should inevitably have sunk forever,
had not the Lord heard my cry, and regarded the groanings of my spirit.

Twelfth Month 25th.--It is a day of peculiar trial to
the rightly-exercised members of our religious Society.
Many among us who once stood in conspicuous stations,
and who were looked upon as waymarks,
have joined as conspirators against the true Israel.
Oh Lord God of Hosts be pleased to turn your hand upon the little ones,
and raise up judges as at the first, and counsellors as in the beginning,
and give not your heritage wholly to reproach.
May it please you to open the eyes of the young people who are
dismayed at the host that have encamped against your devoted servants,
and against the blessed Truth as professed and upheld by our worthy predecessors.
May it please you to open the eyes of the young and rising generation,
who are honestly concerned for the support of our principles and testimonies,
as you did the eyes of the servant of Elisha,
to see your preserving power round about them who fear you:
and that you send them help from your sanctuary,
enabling them to overcome their spiritual enemies,
and to put to flight the armies of the aliens who rise
up to oppose the truth as it is in Jesus.

May the precious young people who are dismayed at the signs of the times,
and who are crying out, "`what shall we do;
who shall show us any good?`" be enabled to know for
themselves the truth and the life as it is in Jesus,
and come to walk therein.

Twelfth Month 4th,
1843.--There is now a spirit of libertinism rearing its head very high in many places.
My spirit is grieved therewith, and earnestly have I desired,
that I may be clear of promoting this spirit in anywise,
either by injudicious remarks concerning it, or by withholding,
when required to speak a word of caution,
counsel or rebuke to those who are indulging therein.
What sorrow does it give to those who are concerned to promote right things in the church!
How it lays waste all right feelings, in the minds of those who give up to be led thereby.
Great pretensions are being made by such to promote the truth;
when their whole course of conduct is directly opposed thereto.

"`My soul, come not you unto their secret,
mine honor be not united to their assembly,`"--for in
their anger have they persecuted the righteous,
"`and in their self will have they digged down a wall.`"
Those who will not submit to their wily working,
and insidious planning and plotting against the truth and its testimonies,
and against those who stand up and oppose them in a Christian spirit, are trampled,
as it were, under foot; and those who are led captive by them, lose their spiritual life,
unless rescued by Divine interposition.
They do indeed dig down a wall, they would lay waste all right,
order and government in the church,
and I would not wonder if many of them should become open ranters,
with no foundation in the truth to rest upon.

Second Month 3rd, 1844.--I feel very weak and low in body and mind.
Oh, that You would support, gracious Father, in these times of trial,
when bodily health and strength are sinking low.

Third Month.
26th.--On reading the Journal of Thomas Scattergood,
my heart has been bowed and contrited in consideration of his deeply tried path,
particularly in England; and in considering, too, that the Lord is able to keep them,
who submit to his wonder-working power in the temple of their hearts,
from fainting and giving out under the fiery baptisms necessary for their own refinement,
and for the sake of the Church.

May I be more willing to acquiesce in the dispensations of extreme poverty of spirit,
weakness and desertion, which my Heavenly Father has been pleased to dispense unto me,
a poor unworthy worm of the dust.
How easy and possible it is for us to conclude in seasons of plenty and Divine favor,
that we could bear these strippings and desertions with Christian patience and meekness,
but when they come,
who is able to endure them rightly? Surely none without the sustaining help of the Lord.

Eighth Month 20th.--It has been nearly two months since I have been out of the house,
except once, having been confined to my room, and most of the time to my bed,
during that period, by severe bodily illness; and, oh,
the poverty of spirit my Heavenly Father has
been pleased to dispense during this illness;
so that the cry of my spirit by day and night could only be, Lord, have mercy upon me,
mercy, unmerited mercy, is all that I have to depend upon.
That mercy that comes through Jesus Christ my Lord and Savior!
What will any poor creature do, who denies the blessed Savior!
Surely the end of such a one must be miserable,
unless favored to experience true repentance before taken hence.

Ninth Month 8th.--My health is so far recovered
as to attend our Yearly Meeting held last week.
I sat all the sittings through in much bodily weakness, sometimes two sittings a day.
But shall I say it was to me a time of rejoicing? No, verily,
this language was almost constantly with me during the week, on this wise,
"`My soul is exceeding sorrowful, even unto death.`"
It appears to me that we will have to be searched from head to foot,
and the superficial daubing removed.
Oh, that we were the recipients of Divine regard to that extent
which has been spoken of. It seems to me that the wounds,
bruises and putrefying sores will have to be searched to the bottom,
before we can say "`the Lord reigns,
let the earth rejoice;`" Let us rather say at this time,
"`The Lord is in his holy habitation, let all the earth keep silence.`"

11th.--It remains with me more fully to commemorate the lovingkindness of the Lord,
and his wonder-working power manifested towards me during my late sore affliction;
so that it appeared plain to me that miracles have not ceased.
When under great bodily weakness and suffering, and but little prospect, if any,
of recovery, this language,
"`I will come and heal you,`" seemed the constant companion of my mind for some days;
and when for a moment a doubt would arise as to my recovery, this would present,
"`Have faith in God.`"
Oh, it is his power, which brings to pass great and wonderful things,
and when my bodily strength was so nearly exhausted in attending our late Yearly
Meeting (as well as at other times) that I seemed ready to sink to the floor,
this language, "`I will help you, I will strengthen you,`" has greatly revived me;
being made at the same time a partaker of the promise.
So that I feel bound to say, the Lord has been very gracious to me every way.
Oh, that I may in true simplicity and faith unfeigned,
learn to trust in Him at all times, dedicating my whole heart unto Him,
and my body to his service;
for "`surely I had fainted unless I had believed to see
the goodness of the Lord in the land of the living.`"
In regard to attending religious meetings,
I may say without boasting that I have not
willfully or knowingly neglected my duty herein;
but have often gone, when, if I had leaned to my own understanding,
I should have concluded it impossible, or impracticable,
so that the language of my heart is at this time, "`Trust in the Lord, oh, my soul,
for in the Lord Jehovah is everlasting strength.`"

Tenth Month 2nd.--Attended a neighboring Monthly Meeting last Second-day,
in which my mind was much engaged for some present, among the young and middle-aged,
and I had to revive the language, "`Walk about Zion, and go round about her;
tell the towers thereof.
Mark you well her bulwarks, consider her palaces;
that you may tell it to the generation following.`"
Expressing my belief that there were those present who
were thus called upon to become acquainted with Zion,
that they might tell it to the generations following.
Dear ______ followed in supplication,
and earnestly besought the Lord on behalf of some present,
that they might be enabled to walk about Zion, etc.
I thought we had a good meeting; dined at Thomas and Anna Edgerton`'s,
who had recently been bereaved of their dear mother and only brother by death.
Before leaving their household,
I felt constrained to bow in vocal supplication on their behalf, as well as my own.
I know not that I ever felt more earnest and fervent in
prayer to the Father of all our sure mercies,
that He would be pleased to remember the prayers and exercise
of departed Friends on behalf of those left behind,
and prepare us to meet in heaven, those with whom we had taken sweet counsel,
and who had earnestly prayed and labored for our preservation and safe landing.
Oh, how impressively was my sister Deborah`'s prayer,
which she uttered just before her death, brought before the view of my mind at this time,
beseeching the Lord to preserve her sisters in the hollow of his holy hand.
And truly, in a wonderful manner,
has this prayer been answered in regard to those who
have since been removed from works to rewards.

Lodged that night at the house of our friend,
J+++.+++ E. In the morning the family were collected, as is their usual practice,
and a portion of Scripture read.
This portion of which sank deep into my mind: "`Oh,
that men would praise the Lord for his goodness,
and for his wonderful works to the children of men.`"
On considering the great deliverances He has wrought for his people in different ages,
and his goodness and mercy towards my own soul,
this language did indeed become the language of my heart,
and my spirit was contrited within me.
