== Chapter III

[.chapter-synopsis]
* Prevalence of Erysipelas Fever
* Death of Her Father
* Exercises in Her Own Meeting, and on Behalf of Individuals About Home
* Starvation in Ireland
* A Religious Visit in Her Own Quarterly Meeting
* The Beginning of the Trouble of Gurneyism

Third Month 10th, 1845.--A wasting disease is in this part of our land.
Many have been called from works to rewards within a short space of time.
Oh, may this awful dispensation teach those who survive to apply their hearts unto wisdom.
This disease is called the "`black tongue or erysipelas fever.`"

Fourth Month 4th.--This has been to me a day of uncommon temptation and trial,
so that I have been forcibly reminded of that which is recorded in
Holy Scripture when the Prophet saw Joshua the high priest,
standing, and Satan on his right hand to resist him.
Strength seemed just afforded today in meeting to cry in secret,
"`The Lord rebuke O Satan.`"
May it please You, oh, gracious God,
never to permit me to cast away my confidence in You, as the enemy is tempting me to do;
but, oh, be pleased to rebuke him,
for You know the desire of my heart is to serve You only and alone.

Sixth Month 31st.--On the 27th of this month, my beloved father departed this life;
a lingering disease had for some time threatened the termination thereof.
He died in great sweetness,
expressing a well grounded hope that through the Lord`'s mercy his end would be peace;
saying that he trusted that He who cared for the sparrows, would care for him.
My spirit deeply feels the stroke, and although it was not unexpected,
it is hard to be bereaved of a tender parent, who in advanced age retained his faculties,
and whose daily concern was that all things might be done decently and in order,
both with respect to spiritual and temporal things.
To part with such a parent,
especially at the present time of great liberty and libertinism in our Society,
is a severe stroke.
Centre down, oh, my soul, into a state of solemn inquiry,
whether you are prepared to render up your accounts with joy.
Oh, You who have taken from me my dearest earthly treasure,
be pleased to prepare me to follow, though it may be through great tribulation.

Tenth Month 31st.--Oh,
You who only can rightly prepare our hearts to offer the tribute of praise,
or to pray acceptably to You, You know my soul is sorely tried and tempted.
Be pleased to enable me to bear the turnings and overturnings of your holy hand upon me,
and enable me to see, and to escape the snares of the wicked one.
Be pleased to deliver me from the "`snare of the fowler, and from the noisome pestilence,
that walks at noonday,`" even the pestilence of darkness and deceit that is
taking captive and slaying so many of this once highly favored society,
oh, slay not all in your wrath, but in wrath remember mercy.

Eleventh Month 2nd.--I sat silent in our meeting today, which is most commonly the case.
Oh, that I may never dare to move in the line of the ministry
without a fresh anointing for the work and service;
for I have seen a snare which the enemy has laid and is laying,
to catch the feet of ministers of our religious Society; insinuating into their minds,
and into the minds of others, that to wait for such a renewed qualification,
and putting forth from time to time of the good Shepherd of his sheep,
in the work of the ministry, is not essentially necessary,
nor to be insisted upon to such a degree, as was upheld and maintained by early Friends.
In the day of my espousals, in hours of extremity, and times never to be forgotten,
the Lord opened my understanding by his own illuminating power and spirit,
to see the nature and worth of true spiritual and living ministry;
and how all who are called and chosen as the ministers of Christ,
must of necessity know a repeated and thorough washing in the river of judgment,
and experience the axe laid to the root of the corrupt tree,
and all that his righteous controversy is with eradicated from the temple of the heart.
Oh, what sweet unity,
sympathy and fellowship did my spirit feel in those days with our early Friends,
who bore the scorn, scoffings,
and persecutions of the highly professing Christians of that day;
and it was then given me clearly to see, that if we in this day of ease to the flesh,
and liberty of conscience, would, and do, maintain,
our principles and testimonies inviolate (as did our first Friends),
we must assuredly come to experience as they did,
a going down into suffering and death with Christ;
that as "`he was raised from the dead by the glory of the Father,
so we also should walk in newness of life.`"
Oh, how was I then given to see in the visions of the eternal light and glory of
the dear Son and Sent of God--the Lord Jesus Christ--into the fallen,
degenerate and dead condition of man by nature; yes, the Lord gave me sensibly to feel,
and powerfully too, that Adam after he ate of the forbidden fruit,
lost all his sight and sense of good spiritually,
and that he had nothing in his nature left, whereby he could seek after,
or desire the presence of his Creator,
from whom he hid himself in the day of his transgression.
And although I had read this account in the Holy Scriptures,
and never did otherwise than assent to the truth thereof,
as far as my natural understanding could embrace it, yet until my Heavenly Father,
in his great and wonderful dealings with me,
gave me to see and feel the state of man in the fall,
as clearly set forth in the writings of early Friends, agreeably to Scripture testimony,
but especially in Barclay`'s Apology, it had remained a mystery to me,
and must have remained a mystery,
had not the Lord revealed it to me by his own power and holy spirit.

Also man`'s restoration and redemption out of the fall
by that one offering of Himself on the cross,
made by our Lord Jesus Christ, in its two-fold nature,
was clearly revealed to me at that time.
Oh, happy day of gospel light and gospel power.
I saw clearly that our justification goes no farther than our sanctification;
that sanctification must and does precede justification,
according to the words of the Apostle, "`But you are washed, but you are sanctified,
but you are justified in the name of the Lord Jesus and by the Spirit of our God.`"

Eleventh Month 5th.--I sat in our meeting today under much exercise
and concern that I might not withhold any thing given me for others.
Some having expressed concern,
and wonder that my mouth is so generally closed in our meetings for worship.
I clearly saw that I might arise under a great weight of exercise,
which this day as well as at many other times, has impressed my mind;
that we as a people, once eminently favored to experience heavenly good,
might more and more seek for ability to worship God in spirit and in truth,
feeling strong desires in my heart that the life
and power of religion might be duly sought after,
believing if this was the case, we would feel our heavenly Father`'s presence among us,
to the comforting and strengthening of our hearts, when thus assembled;
but waiting to hear the word of command on this wise,
"`You give them something to eat,`" I felt that I had
not that command given that would warrant utterance.
May I ever dwell so low and humble as to be preserved from
sinning with my lips in the congregation of the Lord`'s people.
For when ministers begin to lean to their own understanding,
and warm themselves with sparks of their own kindling,
who can tell where the end may be? I do not say or think that I have always
been careful to wait for sufficient clearness as to the subject,
the time when to speak and when to stop.
And I have been deficient with respect to my manner of speaking,
sometimes speaking too loud and too fast,
so as to diminish the weight of that which otherwise might have been more profitable.
Oh! that by increasing attention to the Master`'s voice,
I may become what He would have me to be,
and experience the silence of all flesh in such assemblies.

7th.--Visited a sick friend,
who appears to be near the winding up of her earthly pilgrimage.
I could feelingly sympathize with her when she
complained of a feeling of great destitution,
having felt myself for some time past like a pelican of the wilderness.
But upon the friend`'s saying, "`Oh! that you would get down and feel with me,
and see how poor and destitute I am,`" the
spirit of supplication seemed poured out upon me,
and this language was silently though powerfully breathed forth, "`Lord,
You know how frail and destitute we are,
not able of ourselves to breathe one living desire unto You; Oh! have mercy upon us,
and help us, if it be your holy will.`"
After which, a sensible feeling of consolation was extended,
and towards evening the sick friend remarked, what a comfortable afternoon this has been;
on being asked in what respect, she replied, "`In almost every way.`"
Oh! that it may be my constant concern to keep the word
of his patience who afflicts not willingly,
nor grieves the children of men,
but who in all the fiery trials and baptisms which He permits
to come upon them while the day of their visitation lasts,
has their sanctification in view.

When He withdraws his sensible presence from me
and veils the light of his glorious countenance,
may I never make an image,
but abide in the furnace through these proving conflicts until He is pleased to return,
or again show Himself for my comfort.
I felt this day a song of praise to pervade my heart for the goodness
of the Lord and for his wonderful works to the children of men.

Same date.--I had a visit from two Hicksite cousins.
Before they left I felt it right to tell them,
that I believed there was no other name given under heaven, whereby we can be saved,
but by the name of Jesus Christ of Nazareth;
that it is through and by Him we must experience redemption, if we ever experience it,
etc.
They appeared to receive kindly what I had to say,
and the opportunity ended to satisfaction,
so far that I felt relieved of a burden that rested on my mind on their account.

12th.--Had some conversation with an individual who is under
conviction that it would be right for her to use the plain language,
thee and thou to one person, but is evidently evading the cross,
pleading the excuse that her education has been so different
and her surroundings such that she finds it very hard,
and the cross very great.
She tried to comply with the requisition, but found herself greatly in the mixture.
She is not a member among Friends.
I encouraged her to be faithful,
telling her that He who required the sacrifice
and had given her to see that it was her duty,
would enable her to comply if rightly sought unto and followed.
That although of ourselves we are not able to bring about a resignation of our wills,
or to take up the cross,
yet it is important that we should look for help and strength unto Him who has all power,
etc.
She appeared to receive kindly what I said, and seemed thankful and thoughtful.
When we feel the stirrings and quickening influence on
our minds of Him who opens and no man shuts,
and shuts, and no man opens, to speak a word for his cause, and truth`'s sake, Oh! then,
how unsafe to fear the frowns of man, or the face of man.

Visited the sick friend before alluded to, who is fast sinking,
but expressed a comfortable hope that through the mercy of God through Christ Jesus,
she would be permitted to land safely.
Upon my remarking that I had this hope for her,
that a living hope was better than a dead faith;
and that of ourselves we could do no good thing, being poor, frail unworthy creatures,
etc., she replied, "`Oh! it is the truth; I have long felt it to be so,
but never so particularly as since I was laid on this sick bed.
It is through mercy, unmerited mercy,
that we are enabled to feel any thing that is good.`"
Before leaving, I said to her that if she had any counsel for me,
I hoped she would not withhold it. After a little pause, she said,
"`I have been thinking a great deal about our poor Society.
It seems to me that many of those who stood in the foremost ranks are
gone--Oh! that the things which remain may be strengthened;
Oh! that you may be faithful.
Be faithful, and strengthen the little flock that is left.
You have been greatly favored,
may it continue to be so.`" At this time the Gurneyites in our
Yearly Meeting seemed to bear down everything before them,
which was a great burden to this dear Friend, as well as to many others; yet she said,
that she saw a little living remnant preserved in our midst,
and greatly desired the encouragement of these.
I have felt myself amply rewarded for endeavoring to abide in the patience,
under the proving feelings of poverty and desertion which have been meted
out to me of latter time,--feeling now and then a capacity given me,
to sympathize with the destitute and afflicted in body and in mind,
being able to say my soul knows well what those seasons are,
and that the Lord delights to show forth his marvelous
power in the time of our greatest extremity; therefore,
the language of my heart is, "`Rejoice in the Lord, Oh, you righteous,
for praise is comely for the upright.
Trust in the Lord forever, for in the Lord Jehovah is everlasting strength.`"

23rd.--Heard some passages read from Scott`'s Diary,
which had a consoling effect upon my mind,
having been for some days past under great exercise and travail of soul.
It seemed as if the weight of mountains, comparatively speaking, rested upon me,
and were it not for the ability given to cry secretly unto the Lord for help,
I could scarcely refrain from crying aloud, even in the presence of others,
under the weight that I feel.
But this passage is at times brought before me with life, "`Why are you cast down,
O my soul? and why are you disquieted within me? hope you in God:
for I shall yet praise Him for the help of his countenance.`"
And, blessed be his name, a little ability has been given me to wash and anoint,
rather than appear unto men to fast; and I have been narrowly reviewing my steps.

First Month 17th,
1846.--Spent some time this evening reading in the Journal of Thomas Scattergood;
and it is renewedly sealed upon my mind that the great exercise and travail of soul,
that he passed though in England and America, in his ministerial labors,
were designed as a particular call and warning to those among us in the ministry,
not to trust to, or lean to our own understandings in our religious movements.
Oh! how abased, how shut up, how exceedingly stripped, tried and tempted,
did our Heavenly Father permit him to become, not only for a day or a month,
but for months together.
Oh! how unlike many in the present day, who run without being sent,
and preach without the Lord`'s anointing, or command, saying the Lord says,
albeit He has not spoken by them.
How tried and proven some are now, who nevertheless desire above all things,
even in the midst of suffering, to hold fast their integrity,
and concerning outward trials,
that which afflicts more than anything else is false brethren.

Second Month 4th.--Tempted, tried and proven,
even to a hair`'s breadth--what further plungings
and wadings the Lord may permit me to go through,
I know not; but all that I ask, all that I desire is,
that my spiritual life may be given me for a prey.
Who that passes through these seasons of stripping and proving,
and are again raised up with their faith and hope renewed,
but can with great abasedness of self, acknowledge that there is nothing in our nature,
no, not a vestige or particle that can further our salvation.
It is all the gift of God through Jesus Christ our Lord,
that can keep us in the hour of temptation.
It is his own immediate interposition which has preserved me from utter despair.
Oh! what shall I render unto Him for preserving
me in and through hours of darkness and doubt,
from casting away my confidence, and making shipwreck of faith and hope.
Surely, nothing but mercy, unmerited mercy,
have I to trust to. It is not by works of righteousness that
we have done but according to his mercy He saves us "`through
the washing of regeneration and renewing of the Holy Ghost.`"
Thanks be ascribed unto You, you King of Saints,
for rescuing me from the jaw of the lion, and the paw of the bear.

16th.--Today had a comfortable silent meeting in which my heart was
bowed down in solemn supplication to the Father of mercies,
in the language of David, "`Give ear, O, Shepherd of Israel,
You that lead Joseph like a flock; you that dwell between the cherubim, shine forth.
Before Ephraim, and Benjamin, and Manasseh stir up your strength,
and come and save us.`" Oh,
the disposition there is among us to modify Quaker principles and
make them more agreeable to the spirit of the world,
and the worldly wise.
This disposition is increasing, but thanks be ascribed to our holy Leader,
He has shown the bait to his honest-hearted children, and enabled them to cry--"`A lion,
my Lord, I stand continually upon the watch-tower in the daytime,
and I am set in my ward whole nights.`"
A lion is in his lurking places prepared to catch men as they sit down to rest,
as did the young prophet,
and to become overtaken by the old and professedly experienced ones,
who entreat them to turn aside,
and to eat and to drink with those with whom they have been forbidden to partake.

Sixth Month 13th.--On reading a letter from Ann Crowley to Thomas Scattergood,
a little hope sprang up in my heart,
that as others had been as deeply tried with fears and
doubts respecting a safe landing as myself,
perhaps the day might before long dawn,
when a ray of living hope might dispel the midnight gloom,
and my captive spirit be enabled to take fresh courage
and to trust in the Lord with all my heart,
and not to lean to my own understanding.
"`O the hope of Israel, the Savior thereof in time of trouble;
why should you be as a stranger in the land,
and as a wayfaring man that turns aside to tarry for a night?`"

I have recently obtained a Minute from the Monthly Meeting to visit some
meetings within the limits of Stillwater and Short Creek Quarterly Meetings.
But oh the baptisms necessary to be endured for such a work!
Oh, holy Father strengthen me to perform what you require and nothing less or more,
and whether I suffer or rejoice with the righteous seed, your will be done.

Seventh Month 21st.--My mind is impressed with the
necessity of spending time in reverence and godly fear.
Oh, time, time, how precious--Lord be pleased to enable me to spend it aright.

Eighth Month 10th.--A little living hope now and then springs up in my heart,
that I am not and shall not be forsaken of the Lord, if grace and faith fail not; but oh,
how close the enemy is permitted to come; truly my soul can say from living experience,
and that renewedly even many times from day to day,
I had fainted unless the Lord had by his holy Spirit
lifted up a standard against the floods of the enemy.
How can I enough admire the goodness of the Lord and magnify his name,
under the humbling consideration of the marvelous deliverances
from the pit of despair which he has wrought for my soul.
Last Seventh-day the conflict of my mind was beyond description,
and I plainly felt and saw,
that nothing save an Almighty interposing power could give or command deliverance;
and to think of attending a neighboring meeting the next day under
such feelings! but the requirement seeming to be right I went,
and though I sat silently among the few who attended, yet in the afternoon,
feelings of thanksgiving and praise were raised in my heart
unto Him who is often pleased to hide his face from me,
and permit my soul to go on mournfully;
but as I believe these dispensations are designed to keep me in my proper allotment,
I can thankfully say I bless the Lord for them.

11th.--My heart today, as well as at many other times,
has been engaged in supplication unto the Lord for mercy and preservation.
Blessed be God who gives me a heart susceptible of tender impressions
and ability to crave a continuance of his compassionate regard.
No matter what I suffer, so that I am kept in the way of the Lord`'s requiring.

23rd.--Great have been the tossings of mind which I have experienced of latter time,
with but little intermission;
but today my heavenly Father (blessed be his name forever)
gave the word of command to the winds and waves,
and behold a great calm.
How can I be thankful enough for the favor.
In those moments and days of tossing the prayer of my heart has been,
that if these proving dispensations were occasioned by unfaithfulness,
or anything done or not done by me, with which the Lord was displeased,
I might be permitted to see it and repent thereof; but I have not felt condemnation.
When will I learn to endure tribulation rightly and let patience have her perfect work.

Ninth Month.--Our Yearly Meeting is past.
Oh, who could have thought that our Society would
have ever exhibited the aspect that it now does,
that of having to so great an extent become as Ephraim of old.
It is written, "`Ephraim, he has mixed himself among the people;
strangers have devoured his strength and he knows it not.`"
I have forborne to write much concerning the state of things among us,
but my heart is at times almost overwhelmed with sorrow
on account of the state of many among us,
yes of very many.

The great Head of the Church is hastening the time, yes it is begun;
when judgment shall "`run down as waters;`" and oh hasten you also the time,
when righteousness, pure undefiled righteousness, shall be as "`a mighty stream.`"
In the last sitting of the Select Yearly Meeting,
I felt a great concern to speak of the state of the ministry
among us. The subject had rested with me as a great burden,
and when the time came for me to unburden my mind, I gave up thereto,
and felt a great calm, and holy quiet to pervade my mind all the evening afterwards.
Such a quietude and song of praise filled my heart as
had not often been surpassed in my experience.
I felt it right for me to say in that meeting,
that I believed there was a ministry gotten up in our
religious Society which the Lord would rend;
that He has had, continues to have, and will continue to have,
a controversy therewith--a ministry which is exercised in all the
deceivableness of unrighteousness in the will and wisdom of the creature.
That this ministry claimed, and brought to view past experience;
and in the modulation and modification of the voice, gesture, etc.,
all was calculated to deceive.
That many times no fault could be found with the doctrine advanced,
yet lacking the life and power, it was offensive in the sight of God.
Though it had been a great burden upon my spirit,
yet I had felt a secret rejoicing that there was that which could not be deceived,
even the elect and precious seed, Christ the chosen of God.

Tenth Month 27th.--The heart-rending considerations that often take
hold of my mind concerning the state of our religious Society,
are accompanied with a daily fear that I myself will yet fall a prey to the
wiles of the adversary who is transforming himself into an angel of Light.
That many are taken captive by a specious pretence,
that early Friends in their doctrinal writings are
chargeable with many discrepancies and errors.
Thus are the adversaries of truth, even many, in conspicuous stations;
and in many places trying to lay waste, not only the reputation of early Friends,
but to destroy the foundation of the Christian`'s hope as upheld, believed in,
and promulgated by them.
Alas for the framers of this Babel;
alas for the poor deceived and deluded ones who follow them,
when the vials of the wrath and vengeance of an offended God
is poured out upon a gainsaying and rebellious people.
Those among us who think and say,
that the doctrines of our religious Society are not in
accordance with the pure truths of the Gospel as set forth by
Christ and his Apostles in the Scriptures of truth,
shall be as when a "`hungry man dreams, and behold, he eats; but he awakes,
and his soul is empty.
Or as when a thirsty man dreams, and behold, he drinks; but he awakes, and behold,
he is faint, and his soul has appetite.`"
Alas, when these awake to a sense of their real condition,
they will find themselves to have been strangely
deluded and led away from the flock and fold of Christ.
This is my firm belief concerning all those among us who are
calling in question the doctrines and testimonies of this
Society as upheld and promulgated by our first Friends.

Eleventh Month 8th.--It has been many months past that I have felt no
command to open my mouth in the ministry in our meetings for worship at home.
Some of these meetings have been seasons of inexpressible
exercise of mind and deep conflict of soul;
insomuch that I have almost despaired of life.
But the Lord who raises the dead and quickens whom He will,
has not wholly cast me off at such times, but has kept me alive,
and given me to see that He will have it so.
That his ministers shall be as flaming fire;
and notwithstanding the great efforts made even by many
in high standing in this day of ease to evade the cross;
teaching people so, by endeavoring to please the natural mind; yet,
in his inscrutable wisdom, He will bring to nothing the understanding of the prudent,
and the wisdom of the wise, who are so in their own eyes,
and the eyes of the worldly wise.
"`He will not give his glory to another, nor his praise to graven images.`"
Oh the reduction that the Lord`'s ministers must again, and again, experience.
My soul is exceedingly fearful for the state of many among us,
both ministers and hearers.
May the Lord purge us until the will of the creature is slain,
and the Kingdom received as a little child.

Second Month 13th, 1847.--Accounts from Ireland are increasingly painful and awful.
It is stated that hundreds have already starved to death,
while hundreds and thousands more are in a state of starvation.
Who can but mingle the tear of sympathy and sorrow with these unhappy people,
while every effort in our power should be made to alleviate their suffering condition.
People in this country seem generally awakened to an interest for them,
and much is doing in many places in forwarding supplies of food.
I can hardly take my usual meals;
the thought of their suffering being heart sickening as well as heart rending.
Who knows how soon or when this cup of famine may pass over to other nations.
Are we not deserving such a judgment? And it is only in
mercy that it is not sent for us to drink.
Full fed and ungrateful as we are, who would marvel, if in his righteous indignation,
who rules the nations,
and unto whom belongs every beast of the field and the cattle upon a thousand hills,
that He the Lord should cut off our resources of necessary food and give us
the cup of famine to drink? Even if this cup should pass from us,
other judgments may come, equally alarming and trying to bear;
for we are as a nation high and lifted up,
and the Lord in his own time will bring down and permit the nations of men to be shaken.

The life and labors of my beloved father often come up before the
view of my mind as a sweet memorial of his constancy and firmness,
through good report and evil report.
He was no flatterer,
but with firmness did he resist the doctrinal
innovations of Elias Hicks and his followers;
and also with equal firmness did he resist the innovations which are making
their way in the Society by the introduction and spread of unsound writings.
Often saying to some of his friends,
that his exercise and interest for the welfare of
society increased as his bodily strength declined.
Greatly desiring that a testimony might go forth
against the unsound writings of Joseph John Gurney,
through much bodily weakness and suffering,
he attended a Meeting for Sufferings held at Mount Pleasant,
not more than two weeks before his death,
for the purpose of issuing a testimony against those writings;
and in that meeting he labored in the authority of
Truth for the support of our principles and testimonies.
After this meeting was over he said to a Friend, who inquired of him how he felt,
"`I am weak and a great sufferer, but I am glad I have been here.
I am willing to be trod upon,`" alluding to the opposition to a testimony
being prepared against the unsound writings of Joseph John Gurney.
Oh, that I may be permitted through mercy to receive in the winding up of my time here,
as was doubtless the experience of my beloved father, the answer of well done,
or a "`crown of glory that fades not away.`"
Oh for faith and patience to wade through the remaining conflicts which may
be permitted to attend me through my future pilgrimage in this life.

I feel that in a late and long mental conflict which has been permitted to attend me,
that the powers of the earth have been in some degree shaken;
and it seems to me that the language of the
Apostle Peter is in some degree applicable to,
and descriptive of,
such a state--"`But the day of the Lord will come as a thief in the night;
in the which the heavens shall pass away with a great noise,
and the elements shall melt with fervent heat,
the earth also and the works that are therein shall be burned up.`"

Seeing then that all these things shall be dissolved,
what manner of persons ought you to be in all holy conduct and godliness.
Looking for and hastening the coming of the day of God,
wherein the heavens being on fire shall be dissolved,
and the elements shall melt with fervent heat.
Nevertheless we, according to his promise, look for new heavens and a new earth,
wherein dwells righteousness.
Wherefore, beloved, seeing that you look for such things, be diligent,
that you may be found of Him in peace, without spot, and blameless.

Agreeing with the foregoing is the language of another
Apostle--"`Yet once more I shake not the earth only,
but also heaven.
And this word, yet once more, signifies the removing of those things that are shaken,
as of things that are made; that those things which cannot be shaken may remain.`"

Consonant with the foregoing is the language of the
Prophet Isaiah--"`The earth is utterly broken down.
The earth is clean dissolved.
The earth is moved exceedingly.
The earth shall reel to and fro like a drunkard, and shall be removed like a cottage;
and the transgression thereof shall be heavy upon it;
and shall fall and not rise again.`"
We who are making profession of the Christian religion,
who are holding forth the necessity of being baptized with fire and with the Holy Ghost;
who are recommending and urging the necessity of people experiencing
the new birth--of witnessing the laver of regeneration to wash the
inner temple of the heart--we who are professing to be led and guided
by the Spirit of Truth which leads out of all error into all truth;
what do we know of these things of which the Apostles speak?
What do we know of the day of the Lord burning as an oven;
consuming the chaff, tin and reprobate silver--the chaffy nature in us,
the earthly sensual lusts and appetites which war against the coming of Christ`'s kingdom?

What do we know of the whole heart being given up to the work and service of the Lord;
and consequently a previous preparation for such work and service, namely,
the will of the creature slain;
and the understanding of the natural man brought to naught,
and the Lord alone exalted and his kingdom set up in our hearts? We
who are preaching to the people the necessity of this change of heart;
professing to believe that as we follow the Lord Jesus Christ,
He will work this glorious change in us;
that He will "`create in us a clean heart and renew a right spirit within us.`"
That the new heavens and the new earth wherein dwells righteousness,
shall take the place of the old heavens and the old earth.
What do we know of this blessed, glorious change being wrought in us?

Seeing then that we look for such things, that we hold up the necessity of such a change,
how ought we to demean ourselves; how ought we to guard our conversation;
how diligent should we be, to hasten the coming of that day,
by submitting to the cleansing operation of the Spirit of Christ.
Much might be said on this subject,
but suffice it for me to add--May the Lord perfect the work of sanctification in me,
so that that which is of the earth and earthy, may be thoroughly removed;
and a new heart and a new life be mine; amen and amen.

Third Month 15th.--Everything around me appears solemn.
Time, my time, is very precious.
I can though, in fear and trembling hope, that through the mercy of God in Christ Jesus,
I may be preserved in watchfulness and prayer, and be permitted to make a peaceful close.
Oh! it is a time of great searching of heart.
Last Seventh-day week was the time of our Quarterly Meeting,
in which it appeared right for me to say--"`That although I
believed the Lord`'s mercy was round about to gather us;
and to bring us to repentance;
yet an awful consideration had taken hold of my mind
concerning those who say they are Jews and are not;
but do lie, but are of the synagogue of Satan;
believing that the wrath and indignation of
Almighty God was impending on account thereof.
Those who were willing and desirous to be thought the followers of Christ,
making a profession of being led and guided by the Spirit of Truth;
yet are refusing to submit to the heart-cleansing operation of the holy Spirit,
which would enable them to offer an offering acceptable unto God;
it seemed to me that our Heavenly Father was weary with such,
and that his indignation was impending therefor.
It is an awful thing thus to speak, but the reward is only found by being faithful.

18th.--In reading and tracing the accounts of many
valuable and worthy servants of the Most High,
I find that their lives were tribulated; and some through great tribulations,
were permitted to partake seldom of the bread of the Governor, even as Nehemiah.
Oh, my God! you order all things for your glory,
as there is an entire dependence upon you.
I beg, yes crave, that my heart may be increasingly devoted unto you, and your service;
that whatever tribulations I may have yet to pass through it
may redound to the glory and praise of your excellent name.
Should these lines ever meet the view of any poor tribulated soul;
let me say to such a one, the Lord knows your condition; He hears your groanings,
your sighs, and tears; the anguish and grief of your spirit, are all plain before Him,
though you know it not.
And if you wait in patience, and do not stir up your Beloved before He pleases;
He will in his own time come "`leaping upon the mountains, skipping upon the hills.`"
He will put down all opposition which rises in your mind to
retard the spread and growth of his pure and glorious word,
and power in your heart; and though he tarry, wait you for Him,
and let the prayer of your heart be on this wise:
"`Until the day break and the shadows flee away, turn my beloved; and be like a roe,
or a young deer upon the mountains of Bether.`"
Yes, desire not you that He will satisfy your longing soul until He sees fit,
until He disperse all shadows, all types,
all things which tend to veil your mind from enjoying the substance, the essence,
the marrow, the kernel of religion--Christ in you the hope of glory.

21st.--Attended our meeting at Flushing.
Great was my desire for this little company,
that the Lord would awaken them to a sense of their true state.
Oh, that He would raise the dead,
is often the cry of my spirit without the intervention of words.
Many wonder at my mouth being so generally closed in our meetings for worship.
It seems to me I see a cause; how have we become degenerated,
trusting in the arm of flesh;
and what a flow of words do we often hear which have
but little of the demonstration of the Spirit and power
to recommend them to the attention of the people.
Oh my soul bows before God; and mourning as a garment covers me,
which I desire not to cast off until the Lord`'s appointed time.
Then if He sees fit to give me beauty for ashes, the oil of joy for mourning,
and the garment of praise for the spirit of heaviness, then may my soul rejoice;
and not till then presume to take upon me to praise and magnify with the tongue;
when the command is to mourn in secret, and wash and anoint,
rather than to appear unto men to fast.
The Lord only knows the tribulations of my soul,
and how my spirit craves to serve Him faithfully through all the remainder of my days;
which I sometimes think will not be many.
Oh, that I may be found worthy to enter into everlasting rest,
when time here to me shall be no more.

Fourth Month 2nd.--Appointed a Meeting for Worship last
First-day for the colored inhabitants of this neighborhood,
which was in some degree relieving to my mind.
Having felt a concern for a long time,
respecting appointing a meeting among the Presbyterians,
about four miles distant from my home,
and having obtained liberty of my Monthly Meeting for the
purpose of appointing some meetings from among Friends,
I ventured to mention it to some Friends, and being encouraged thereto,
the subject was laid before some of their leading members, or Elders,
who assented thereto except one; who said,
their minister was absent and they could not grant the liberty until his return,
and not without his approbation.
I feel peaceful and easy in having thus far endeavored to obtain a meeting among them.
If they refuse the liberty of holding such a meeting, I then believe I shall be clear.

Fourth Month 7th.--Attended West Grove Meeting.
It was to me a low and painful time, the life of religion being, I fully believe,
at a very low ebb in that place.
I had to revive this language: "`God sets the solitary in families;
He brings out those which are bound with chains, etc.;`" expressing my belief,
that although it might be only a solitary one, or a solitary few, in a meeting,
or neighborhood, who were desiring to serve the Lord, or did faithfully serve Him;
that in his own time He would make a way for their enlargement and deliverance,
and "`give them beauty for ashes, the oil of joy for mourning,
and the garment of praise for the spirit of heaviness.`"
But with the lukewarm, the careless and indifferent, the casual attender of meetings,
or those who made it a matter of convenience,
preferring the things of this world to their best interest;
with these I believed the Lord was weary, who say they are Jews and are not, but do lie.
Oh, He is jealous of his honor; He will not give his glory to another,
or "`his praise to graven images.`"
I had to warn them of their danger, and left them with a heavy heart.

8th.--Attended Harrisville Meeting.
It is painful to see how some of our members who have given up to go where they please,
and run as they list, have become divested even of common civility,
and good breeding in our Meetings for Worship;
having given up to mix with all the popular associations of the day, such as Abolition,
Temperance, etc.
They despise those who believe it best and right
for Friends to act upon religious ground,
and in a society capacity,
in their petitions and efforts for the extermination of these evils.
Oh how some,
while they are full of argument and run into many notions respecting these subjects,
do at the same time trample upon the principles of the Christian religion;
evincing that they are not what they profess to be, being enemies to the cross of Christ.

They will have their day, so in a time to come,
perhaps when it is too late to make amends;
they will find that their garments are moth-eaten; that they are wells without water;
and having committed two evils, "`forsaken the fountain of living waters,
and hewed them out cisterns, broken cisterns that can hold no water.`"
They will have nothing to depend upon that will afford them consolation in a trying time;
and "`leaning their hand upon the wall of the house to which they have fled for safety,
a serpent shall bite them.`"
I had to warn these of the dangerous situation they were in,
and call their attention to the necessity of turning to the Lord,
who had often shown them the danger of the way which they were pursuing.
I had also a word of encouragement for the honest-hearted among them,
and returned home peaceful,
and thankful for having been strengthened to labor honestly and faithfully among them,
notwithstanding some seemed ready to mock at what was delivered.

Seventh Month 8th.--"`My God, my God,
why have you forsaken me!`" was the language of the blessed Redeemer on the cross,
when suffering for the sins of the whole world.
Oh, the agony of the dear Son of God at that moment.
May a recollection of this incite me to think nothing hard
which He permits to attend me through this pilgrimage.
For "`He, who knew no sin, suffered that ignominious death,`" for poor vile man,
"`the just for the unjust;`" how shall not we,
with the strength and ability which He gives, learn to bear all things patiently;
and so "`fill up the measure of the sufferings
of Christ which are behind for his body`'s sake,
which is the Church.`"

Last Monthly Meeting I returned the Minute granted me in the Third Month to
visit some meetings within the limits of our own Quarterly Meeting,
and to appoint some meetings among those not professing with Friends.

Although this visit was the most exercising one which I ever performed among Friends,
owing to the unsettled state of our religious Society
by the introduction of unsound doctrines among us,
yet I was favored, as I thought, to discharge myself faithfully,
and leave the result to Him who sees the end from the beginning;
and will reward us according to our deeds.
Oh, the cruel censures which are heaped upon the faithful in this day--
Lord enable them to bear all things patiently for your name`'s sake;
and for the cause they have espoused; and for their own soul`'s sake.
I felt like being nailed to the cross in this little visit among our own members;
and in Smithfield Monthly Meeting this language often ran through my mind:
"`It is finished.`"
The cup of suffering drank there mingled with the wormwood and gall,
was bitter in the extreme; and yet I felt thankful on leaving the place,
that strength had been given me to speak what
appeared to me to be the whole counsel of God:
and left them with but little prospect of ever again
sitting in that meeting under its present low,
lifeless--what if I say, libertine condition.
At Short Creek Monthly Meeting the state of the
ministry was alluded to as being unwholesome,
and not edifying.
This seemed trying;
but I came away satisfied with doing what I believed the Master required.
Glorified be his name forever, and let all the earth say, amen.
