== Chapter IV

[.chapter-synopsis]
* Visits Families about Home
* Great Exercises of Mind
* Visit to a Sick Neighbor
* Exercises Continued, and the Spring of the Ministry in Great Measure Closed Up
* A Visit to Miriam Ellis, on Her Death-bed
* The Funeral of Miriam Ellis
* Her Labors and Concern Relative to California Gold-hunting

Tenth Month.--Various have been the exercises of my
mind since I penned a line in this book of memorandums.
Our annual assembly has been passed by for several weeks,
and yet the state of things exhibited amongst us at that time is daily in my remembrance.
When will better days arrive? is often the language of my heart.
When will this people be sufficiently humbled,
so as to "`offer unto the Lord an offering in righteousness,
and true holiness,`" as in days that are past? Oh,
gracious God! you have permitted this people to drink the cup of trembling.
You have poured out your fury upon us, so that we have become a byword, a taunt,
and ridicule to all who behold us. Our enemies scornfully deriding us, say,
where is their God? This have you permitted to
come upon us because of our transgressions,
and our many and grievous back-glidings; and yet we are not humbled in your sight.
Oh, holy and eternal One; my soul most of all craves, with respect to myself,
and with respect to my people; that your "`hand may not spare nor your eye pity`" us,
until you make us what you would have us to be--even to speak the same language,
by minding the same thing, by minding the dictates of your holy Spirit,
which "`leads out of all error into all Truth.`"

Twelfth Month 30th.--It is cause of inexpressible
gratitude to the Author of all our sure mercies that,
although I have of late passed through a severe struggle between hope and despondency;
yet I am at this moment able to lift up my head and with a degree of living
and heart-felt thankfulness to exclaim--"`hitherto has the Lord helped me.`"
In a late visit to some of the meetings in the two northern quarters,
I sometimes felt great peace and quietude of mind;
but most especially in the attendance of one appointed
in a neighborhood where but few members reside.
Such was the sensibly-felt presence, and flow of our heavenly Father's love, in,
and after the meeting, that an anthem of praise,
constantly filled my heart for some hours afterwards;
even that feeling whereunto no sorrow was added.
Blessed be God,
who has this day renewed a little grain of faith and
hope in me. May I be accounted worthy of such a favor,
through the mercy of God in Christ Jesus.

Third Month 28th, 1848.--Those who think they have any natural faculty,
constitutional part, or principle inherent in them,
whereby they are enabled to discover the way of life and salvation; or by such a faculty,
or principle, enabled to walk in this way;
have a different view of the natural mind of man from myself.
I believe, as the Holy Scriptures declare, in relation to man in this natural state,
"`that every imagination of the thoughts of his heart was only evil continually.`"
None who see and feel by the light and power of the gospel,
their condition as it really is by nature, can say, they have any inherent holiness,
constitutional part, or principle in them, to direct them in the way of life,
and salvation.
It is all through the mercy of God in Christ Jesus,
that we are favored to see ourselves as we really are in the fall;
and to obtain victory over our natural corrupt propensities, and desires;
and also the suggestions and temptations of the Adversary of our soul's peace.

Fifth Month 14th.--Today our Public Meeting was large;
many attending who are not in profession with us. Oh,
how my heart was bowed before the Lord in secret, silent prayer and praise.
Earnestly was my spirit enabled to cry unto Him for his protecting power to keep
down and restrain that which would be soaring above his true witness in the heart.
Humble and contrite us, oh Lord! are the breathings of my soul,
while my mouth is closed from vocal utterance.
I felt very thankful at this time in the belief, that the Lord had not forsaken us:
and blessing and thanksgiving are due unto Him,
in that He raised up a people who in the beginning of this Society,
were so eminently favored with his life-giving power and presence.
Surely we should now, as a Society,
be very differently situated if our hearts were more devoted
to the Lord--more loosened from the things of the world,
and set on things above.
Oh, the unspeakable value of being brought into a capacity to worship God
in spirit and in truth--of silently adoring the Almighty One.
What signifies all the noise of words, if that power which is the crown, diadem, beauty,
and excellency of religious assemblies, be lacking.
All without this is vain.
No true enjoyment to hungry souls.
If friends were more alive to the importance of possessing the Truth as it
is in Jesus--of becoming vessels fitted and prepared for the Master's use,
how would He deign to meet with them as in former days;
He would "`beautify his sanctuary, and make the place of his feet glorious.`"

Fifth Month.--I cannot think that my Heavenly Father has entirely forgotten me,
or wholly forsaken me; though I am, or seem to myself to be,
like a "`pelican of the wilderness,
or like an "`owl of the desert,`" or "`alone as a sparrow upon the house-top.`"
Though my mouth is closed in our meetings, and I sit as a wonder to many, yet far,
very far, from apathy of feeling or unconcern is my heart.
The Lord knows, before whom I lie not, that my desire is to serve Him only,
and Him alone; and although He seems to shut up his compassion from me oftentimes;
yet the language of my spirit is--"`My soul longs,
yes even faints for the courts of the Lord.`"
I look back upon the past, when He was pleased to manifest himself to me,
so as to refresh me greatly;
but now the recollection of those seasons adds grief to my sorrow,
fearing as I sometimes fear, that I have, or shall by some misdemeanor,
wholly cut myself off from a return of the beloved of souls.

Oh, how does my spirit crave in our Meetings for Worship, as well as at other times,
that our beloved young people, as also the middle-aged,
may be so wrought upon by the good hand of the Lord,
as not only to give up their names to serve Him, but through the spirit of judgment,
and of burning, become standard-bearers in his Church, that will go no more out;
and yet when every feeling of my heart is prostrated on their behalf,
as it often is in our religious meetings, how presumptuous would it be for me,
either in vocal supplication, exhortation, or ministry, to open my mouth,
unless a Divine command to speak was super-added to my exercise.
Oh, that the Lord would lay his chastening hand upon them,
and make them heirs of his Kingdom.
"`I will make you sick in smiting you,
in making you desolate,`" is a language which I think
some will have to realize in their experience,
before they are prepared to give up their names to serve the Lord.
Oh, hasten the work, you preserver of men!

Eighth Month 9th.--I feel like a prisoner in bonds.
Last Monthly Meeting I obtained liberty to visit some
families belonging to my own Monthly Meeting,
and some who are not members;
also to appoint some meetings amongst those not in membership with us.
I have visited fourteen families and appointed two meetings,
which afforded me some relief and peace, as respected those families and meetings.
But oh, the conflicts of my spirit for some time past;
the Lord only knows the trials to which I am subjected; the temptations, the buffetings,
etc., of the unwearied enemy of my soul.
In most of the families visited, and in the meetings appointed,
a sweet and undoubted evidence was given me,
that it was the Lord's requisition which induced this visit;
and that He verified his promise which He made me when I set out, namely:
"`I will go before you and be your rearward;`" yet since my way seemed to close up,
the enemy has tried in many deep laid plans to shake my faith in that all-
protecting power which has so lately been to me as a sun and a shield,
and who at times, while engaged in this little visit,
enabled me "`out of weakness to become strong,`" to "`dip my foot in oil,
and to tread upon high places,`" but proportionate to this feeling of trust,
confidence and rejoicing in the Lord, has since been my descendings,
temptations and tossings, that I have been led to remember this language of the Psalmist:
"`They that go down to the sea in ships that do business in great waters;
these see the works of the Lord, and his wonders in the deep.
For He commands and raises the stormy wind, which lifts up the waves thereof.
They mount up to the heaven, they go down again to the depths;
their soul is melted because of trouble.
They reel to and fro, and stagger like a drunken man, and are at their wit's end.
Then they cry unto the Lord in their trouble, and He brings them out of their distresses.
Oh, that men would praise the Lord for his goodness,
and for his wonderful works to the children of men.`"

11th.--Very poor and tried in mind, and my bodily strength small.
Oh, when will better days arrive? I who, a short time ago,
thought it my place to go from house to house, and from place to place,
to encourage the people to seek the Lord with their whole heart,
that He might be found of them.
I who felt a holy confidence to declare unto them, not merely in words, but in power,
that none ever yet trusted in the Lord and were confounded or disappointed;
but those who sought Him with the whole heart, who dedicated their all unto Him,
were amply repaid a hundred fold in this world,
and in the world to come life everlasting.
I who felt my soul poured forth in supplication for my people--my neighbors,
and at times for the whole human family.
I, who so lately felt at times the voice of thanksgiving and melody in my heart,
unto which no sorrow was added.
What am I now?--a bruised reed, not capable of measuring or dividing anything aright.
Oh Lord God of hosts;
you only know why you have permitted this fiery trial of faith to come upon me;
give me patience to endure until you arise for my help, for vain is the help of man.
When you hide your face we are troubled; when you unveil yourself,
and show us the light of your countenance, there is no joy comparable thereto,
blessed be your name, I will yet hope in your mercy;
and oh enable me to wait all the days of my appointed time until my change come.

13th.--Paid a religious visit to an individual who professes to believe that
all religious denominations are doing more harm than good;
and insists that a moral life is all that is required of man;
that if people are upright in their dealings one with another,
and do not commit any gross sins, it is all-sufficient for them.
In this opportunity with him and his family,
I had to reason with him concerning righteousness, temperance, and judgment to come.
I had to tell him that my spirit travailed for none more than that
class of persons who thus reasoned away religious feelings,
and religious duties; that I well knew the bitter fruit such a course would produce;
that I had seen the time when I thought a moral life might do for me;
but when death stared me in the face--when affliction's rod was laid
heavy upon me--when the hand of the Lord was laid heavy upon me,
I then felt the need of religion;
I then lacked that peace which the world cannot
give--that peace which can satisfy the soul,
and which cannot be obtained without a surrender of the whole heart unto the Lord;
becoming prostrate before Him; sanctified and purified in his holy sight.
I hope the opportunity will not be wholly forgotten, or of no effect.
For a time he appeared to fortify himself against all that was said;
but before the opportunity ceased, I believe, the power of truth came over him;
his heart smote him, and, in spite of all his resistance, showed conviction.
My spirit craves his return to the Father's house from which he has so widely strayed;
that the Lord may bring him down into the valley of humiliation,
and finally prepare him for death when it comes.

Tenth Month 17th.--Various have been the conflicts and deep
the baptisms and wadings of my spirit of latter time.
I have felt it required of me in the late family visit in which I have been engaged,
not only to go to a number of families who were not members of our religious Society,
but also to some houses, whose inhabitants were entire strangers to me;
and whose names were unknown, except by inquiry at the time;
feeling attracted to the houses as we passed them,
and feeling the woe if I did not give up to go in.
Trying as this service was to flesh and blood,
it is nothing to compare to a wounded conscience;
for when I have shrunk from the fulfilment of my duty herein,
it has brought great distress upon my mind,
so that I have been led to say for the sake of peace, "`here I am Lord,
do what you will with me.`" Previous to a late
engagement in several families of this description,
I was near three days at a Friend's house, shut up without any clear opening whatever;
but the command was to be still.
What will my friends say of me? was a query that often crossed my mind.
But the answer of my Heavenly Father was on this wise--"`Your time, your health,
and your faculties are mine.
I have a right to do with them and with you as seems unto me good.`"
Thus did I remain, until a little opening appeared in a remote neighborhood,
where a few members were scattered.
After we arrived there and had visited most of those who were members,
I felt hedged in on every side;
and began to wonder whether I should ever get away from there alive;
but as I endeavored to turn my mind unto the Lord,
and to seek for strength and ability to do his will,
it came into my mind to inquire of the Friend at whose house we were,
concerning his children, who had married out of Society; where they were settled,
and being informed that several of them were near-by,
I soon saw I must go to their houses, as well as to some others which we had passed,
to whose inhabitants we were entire strangers.
This dedication, though greatly in the cross, yielded peace.

20th.--Oh, gracious Father, my heart is greatly in need of your healing balm.
My spirit is wounded, and a wounded spirit who can bear.
I have not been willing enough to suffer for your precious truth's sake,
for the sake of my dear Redeemer,
who died for me. Oh! enable me to become resigned to your blessed will,
whatever it may cost me, dearest Father give me not over to a reprobate mind;
for you have all power,
and can enable me to drink the remaining bitter draughts which you may dispense,
or permit for me. Dearest Lord, remember mine affliction,
and enable me to say in deed and in truth, "`your kingdom come,
your will be done`" in me, and by me, and through me,
unworthy worm as I am. Oh! "`let not your hand spare, nor your eye pity`" me,
until you cause me to surrender my will in all things unto your holy will.
Dearest Father, look down with an eye of compassion, and behold my distress;
and with the crook of your love, in your own way and time, turn this gloom into sunshine,
and fit, and prepare me;
though it be through great tribulation for a mansion in the heavens.

In my late family visit,
I fear that I have not been willing enough at all times to
bear my burden with Christian patience and resignation.
The language of my heart has often been--you require hard things.
Oh, Lord! if you deal thus with me, take away my life,
for my burden is greater than I know how to endure.
And I have felt the truth of this saying of our blessed Lord--
"`Whosoever he be that forsakes not all that he has,
cannot be my disciple.`"
Yet I know not that I ever had more cause to marvel at the glorious
manifestations of light and strength vouchsafed in times of great need,
than in this visit.
But in times of great proving, the exercise through which I had to pass,
seemed sometimes almost insupportable; so that sleep was often taken from me;
and the desire for food was not known: and now should further provings be necessary,
and a requisition again to go forth, plainly manifested;
I crave to become resigned to his will,
who has a right to dispose of us as seems unto Him good;
though it may lead us to become as spectacles to the world, to angels, and to men.
Oh, may the short space of my existence here be spent to the honor of my God;
and may I count nothing too dear to part with for his blessed name's sake,
that the winding up of my days may be peace.

28th.--I feel it to be a time of great importance to me. The Isaacs are called for,
and if I omit to surrender all up into the hands of the Lord, great will be my loss.
I crave to become resigned to my Heavenly Father's will in all things;
but of myself I cannot become resigned.
Dearest Father, grant me resignation to your will, and enable me to dedicate body,
soul and spirit to you, yours I am, and yours I desire to be, with acceptance,
through your well-beloved Son, who gave himself a ransom for me.

Eleventh Month 3rd.--The enemy is continually endeavoring to
persuade me that I shall never be able to hold out to the end;
that I shall "`one day fall by the hand of Saul.`"
But the exercise of my spirit is, when of ability to crave anything for myself;
that the Lord would not spare me nor forsake me,
but make of me just what He would have me to be. A few moments of sunshine now and then;
and a calm and peaceful mind, which is at times my experience,
convinces me how possible it would be for my
Heavenly Father to change the storm into a calm,
and the midnight gloom into the light of the glorious day.
When the "`Son of righteousness is pleased to arise with healing in
his wings,`" how glorious is his work and appearance in the heart.
Or when He is pleased to hide himself, who then can behold Him;
whether it be done against a nation, or against a man only.
If the deep wadings, tossings, and conflicts of spirit, through which I have passed,
and am passing; and may yet have to endure, only have a tendency to refine and purify me,
and make me a vessel fit to bear the inscription of holiness unto the Lord,
it will be enough.
Oh, my soul rejoice and be exceeding glad because of these dispensations,
if in the winding up of your pilgrimage here,
an admission into the realms of never-ending felicity, and joy, be given you.
"`Count it all joy,`" said an experienced Apostle,
"`when you fall into various temptations,`" knowing that the
trial of your faith is much more precious than gold or silver.

I know not that I have ever felt so broken to pieces before the Lord,
as in the late family visit, in which I have been engaged;
and for wise purposes known only unto Him;
I have been kept from returning the Minute granted me in the Seventh Month last;
though it is greatly in the cross so long to feel under the exercise of a visit,
which I had hoped to get through with in a few weeks after
obtaining liberty to perform it. But when I consider that for
years previous to laying this prospect before my friends,
it had at times dwelt with great weight upon my mind,
I wish not now to draw back from making any visit to any one,
or to any family which the truth requires;
for I have often said in my heart in going from one house to another,
greatly in the cross; surely the dregs of the cup of suffering will be wrung out,
when this visit shall have been accomplished;
and had it not been for the help of Him who lays
nothing upon us but what He will enable us to bear;
if we look unto Him with a single eye--had it not been for his help,
making a way for me where there appeared no way,
I should have utterly fainted and given out.
Blessed be his name, I will yet strive to serve Him more faithfully.
Enable me, holy Father! to wrestle for the blessing until the break of day,
that I may not be one of those who draw back unto the perdition of the ungodly.

18th.--I have felt that it would be best for me
to record my feelings of yesterday evening.
After our Quarterly Meeting, which to me was a very trying one,
having sat under a painful, lifeless, wordy ministry;
a secret breathing was begotten in my heart on this wise--"`Oh,
for the substance of religion,
for the life-giving presence of Him whom we profess to serve.`"
Soon after which a solemnity of feeling and song of praise filled my
heart comparable to this--"`My soul does magnify the Lord;
and my spirit does rejoice in God my Savior.`"
Such seasons of refreshment from the presence of the Lord, how humbling to one,
the language of whose heart often is--"`My way is hid from the Lord,
and my judgment is passed over from my God.`"
I crave that no poor, tried, distressed mortal man,
woman or child may despair of the mercy of God in Christ Jesus;
how have I been brought into sympathy, and my spirit travailed with,
and for the afflicted, the tossed and the tempted;
how have I been as it were in the deeps, where the weeds have been wrapped about my head;
where no hand save that of the Lord's could succor.
Oh, trust in the Lord, whoever you are; and whatever your trials may be,
who are seeking after durable riches and righteousness; "`trust in the Lord forever,
for in the Lord Jehovah is everlasting strength;`" for out of the pit,
and from the pit of despair,
has the Lord raised me up. He has also "`put a new song into my mouth,
even praises to his name;`" rejoice, oh my soul, with trembling; yes,
rejoice and be exceeding glad that your God has not forsaken you, has not forgotten you;
when you were nigh the grave He raised you up;
when you stumbled and fell like a weak young child, he raised you up;
when your near and dear relatives, one after another, were taken from you,
He gave you strength to bear the loss with resignation.
And now, when your way seems through a narrow and thorny path,
He does at seasons show himself marvelous unto you;
tremble you before Him and keep the word of his patience,
that you may be accounted worthy, through the Son of his love, of protection and peace.

Today, when returning from our Meeting for Worship,
which to me was a solemn time in silence;
this language sweetly revived in my mind--"`For a small moment have I forsaken you;
but with great mercies will I gather you.
In a little wrath I hid my face from you for a moment;
but with everlasting kindness will I have mercy on you, says the Lord your Redeemer.`"
Oh, this is choice food of encouragement and consolation, not to be trifled with,
and lavished out to others; but for the sake of some poor, tried,
tossed and tempted ones,
who may think their way the most gloomy and discouraging of any other, do I record this;
believing the Lord is able to change the fruitful field into a barren wilderness,
and the barren wilderness into a fruitful field,
and it seems to me that I can do no less than acknowledge his might, and his power,
who alone is worthy of all praise and thanksgiving.
"`Bless the Lord, oh my soul, and all that is within me, bless his holy name.`"

22nd.--Passed our Monthly Meeting under great exercise of spirit;
not feeling at liberty to return the Minute granted me
in the Seventh Month last to visit families.
Oh, the wormwood and gall; if it be to reduce and humble me, your will, oh God, be done.

Twelfth Month 3rd.--Today sat in our Meeting for Worship,
with my spirit bowed down in supplication for light and
strength to pursue the path of duty myself;
and for the Lord's presence in our assemblies.
Thought I could adopt the language of my dear sister Lydia on her death-bed:
"`Surely I could not seek the Lord so earnestly, if his presence was not near me.`" Oh,
Lord, strengthen me to do your will, that I may be yours here, and yours hereafter.
Your will be done in me, and by me, and through me. Amen and amen.

First Month 9th, 1849.--Surely I have never been so long,
and so much like a prisoner in bonds as of latter times.
It is now nearly six months since I obtained liberty to
visit the families of my own Monthly Meeting,
and some not in membership with us. I have visited about one hundred and forty families;
several of whom were not in membership with us,
and some to whom I was an entire stranger.
But for nearly three months past my way has been closed up,
and no opening to return my Minute to the Monthly Meeting.
Oh, gracious God! you only know the depths of distress into
which my spirit has again and again been plunged;
longing desires have been raised in my heart after you, and to be found your humble,
dependent child.
Oh, look down with an eye of compassion upon me; prosper your own work;
and let it take what strokes it may to purify me,
"`let not your hand spare`" me until you are pleased to say, it is enough.

10th.--On taking my seat today in our Week-day Meeting,
my mind was quickly brought into a solemn consideration of our frailty and unworthiness,
and I could not suppress the rising tear.
A humble hope lives in my heart, that the Lord will not utterly forsake me;
but when He has tried me, I shall come forth the better for all my proving.
Oh, how much better is one moment in his presence than a thousand void thereof;
though they may be spent in the midst of our earthly friends, and those too whom we love;
yet in the absence of the beloved of souls, how can my spirit but mourn? Oh,
that I was more worthy, and willing to suffer for the blessed Truth.
Then shall I not be ashamed when I have respect unto all your commandments.
"`Lord teach me to number my days, that I may know how frail I am,
and apply my heart unto wisdom.`"
My spirit bowed in supplication for myself and friends,
though no vocal utterance was required;
and unless an express command to speak or a gentle intimation
which may be distinguished from the voice of the stranger,
let my lips be sealed in silence,
and I not presume to utter words without that life-giving
sound which renders that which is piped or harped,
acceptable to the anointed ear and profitable to the people.

14th.--I am brought into great extremity.
Oh, Lord! look down with an eye of compassion upon me in my present condition.
You know the distress that I feel,
and how impossible it is for me to do anything towards relief
without your superintending and supervening power.
Look down, I beseech you, and gather my mind into a trustful, quiet, resigned frame.
I ask not for any change in my outward circumstances,
or for a multiplication of outward enjoyments;
but for the continuation of your protecting power and presence,
to an unworthy worm of the dust.
You know the extremity that I feel, and how liable I am, or may be,
to cast away my confidence in you,
and sell that precious inheritance for a mess of
pottage--something for the fleshly part to feed upon.
Oh, forsake me not, neither let your hand spare me, but in wrath remember mercy.

18th.--My mind is more calm and quiet than yesterday.
Scarcely have I known such a plunge into the abyss of sorrow and distress.
Scarcely could I refrain from crying aloud, "`My God, my God,
why have you forsaken me;`" "`why are you so far from helping me?`" Verily,
is there not a cause for my sorrow? When I look around and see the lukewarm ness
and indifference prevailing amongst such a highly professing people as we are,
and the zeal too which is not according to the knowledge of God,
how can I but mourn? But this is not all.
When I consider my own weakness and natural tendency to corruption,
and how far short I have come of filling up my measure
of suffering and exercise for the body's sake,
which is the Church; how can I but mourn? Lord prove me and try me; make me white;
fit and prepare me for a mansion in heaven,
where all sorrow and sighing shall forever flee away.

28th.--The experience of this day is worth recording.
After a night spent in the most indescribable anguish of spirit,
how has the Lord interposed,
and by his Spirit lifted up a standard against the floods of the enemy.
On taking my seat today in our religious meeting;
this language ran through my mind--"`I will bear the
indignation of the Lord until He plead my cause,
and execute judgment for me.`" Which was soon followed by this-
-"`The Lord on high is mightier than the noise of many waters;
yes, than the mighty waves of the sea.`"
Oh, how did the Lord still the tumult of my soul.
He arose, and rebuked the winds and the waves, and behold there was a great calm.
"`Bless the Lord, oh, my soul, and all that is within me, bless his holy name.
Bless the Lord, oh, my soul, and forget not all his benefits;
who forgives all your iniquities; who heals all your diseases;
who redeems your life from destruction;
who crowns you with loving kindness and tender mercies;
who satisfies your mouth with good things;
so that your youth is renewed like the eagle's. The Lord executes
righteousness and judgment for all that are oppressed.`"

Fourth Month 9th.--Gracious God!
You who, in days past, was my "`Urim and my Thummin;`" so that I had no need to ask,
who it was, or what it was; knowing that it was your light, grace, truth and power,
over and above all in me, that enabled me to say in the midst of suffering,
and prospect of severe trials and suffering--"`Not as I will, but as you will.`"
Oh! enable me, gracious Father, once more to bow down before you in humble,
heart-felt resignation and obedience to your holy will; here I am, do with me,
make of me, what seems unto you good.
You who see my condition,
grant light and strength to move and walk in. Dearest Father! forgive mine iniquities,
pass by my transgressions, and remember my sins no more.
Help the helpless; you alone can comfort, help and satisfy my soul.
Lord! deliver me, I beseech you, from mine enemies which war against my soul,
and enable me to say--"`Yours is the power, and the wisdom, and the glory forever.`"

Fifth Month 26th.--Oh, holy Father! look down, I beseech you, upon a poor,
unworthy worm of the dust; enable me to follow you in the regeneration.
You know my frailties and shortcomings; have compassion upon me,
for you know the revilings of the enemy, and his temptations,
and how impossible it is for me to escape his wiles,
without your immediate interposition for my deliverance.
You know the scoffs, sneers and revilings of those who watch for my halting.
Oh interpose, I beseech you,
and "`let not your hand spare nor your eye pity,`" until you execute judgment for me.

Ninth Month 30th.--The troubles of my heart are
enlarged unless the Lord undertake for me;
unless He take care of and preserve me, I shall surely sink below hope.
Oh help, gracious God, and sanctify me, body, soul and spirit;
for I am grievously oppressed.

Tenth Month 25th.--"`I, even I,
am he that blots out your transgressions`' as a
thick cloud and will not remember your sins.`"
This comfortable language,
sprang up in my heart to the brightening of the gloomy prospect before me. The Lord
only knows the extent of the misery and distress which my spirit suffers;
and why it is thus with me. Lord be gracious unto me,
and hear my supplication which I make day and night unto you.

Eleventh Month 3rd.--Surely my Heavenly Father has a special
design concerning me to be accomplished in thus permitting the
floods of unutterable distress to rise higher and higher,
until it seems as if I was verging to that point where all consolation ends.
Surely,
there was wisdom in those words addressed to me a few
years ago by a dear Friend on her death-bed:
"`You have been greatly favored; do not give out, nor give way to discouragement.`"
The enemy is permitted to tempt and try me far more than I
have words to convey an adequate idea of. Surely it is mercy,
everlasting mercy, that has hitherto enabled me to hope against hope,
to cast not away my confidence in the Lord.
I can feel for the miserable, for the tossed, and the tempted; and it seems to me,
that my spirit is in travail, and bound up in sympathy with the afflicted and distressed.
Oh, my soul, struggle on and let not go your hold, but ask for mercy, unutterable,
everlasting mercy.
I remember, when on a sick-bed several years ago,
that the consolations of the Lord were so abundantly poured into my soul;
and so great and wonderful did his might and majesty appear, that I thought, then,
that I could trust in his mercy,
no matter how dark and gloomy the days and years
might be through which I might have to pass.

But alas! the manna gathered yesterday will not answer to live upon today.
A fresh supply of that faith and confidence which enables us to call Jesus Lord,
must be experienced; or where will we land? even in the labyrinth of doubt and dismay.
Despair takes hold of me,
and in vain I recur to any past experience of my life for consolation.
If the Lord help me not, how vain is every sublunary assistance.
A competence of the good things of this life;
the choice blessings of faithful and interested friends fail, utterly fail,
to afford that consolation which the hungry and thirsty soul is needing;
and which if not obtained, all outward enjoyments will be of no avail.
Strengthen me, oh holy Father, to trust in you, the Shepherd and Bishop of souls;
you know that I desire to trust in you, to love and serve you above all.
Oh! "`create in me a clean heart and renew a right spirit within me,`"
that I may yet praise you on the banks of deliverance;
and prepare me to praise you forever, whatever strokes it may take.

Eleventh Month.--It has now been more than a year since
I opened my mouth in our Meetings for Worship at home,
except once.
The Lord's name be praised,
in that He has kept me from offering a vain oblation in words; or like Saul,
to offer before the coming of Samuel.
Our dear friend M. Kite attended our last Yearly Meeting;
and I think was favored to enter into sympathy with the suffering seed.
How was her spirit clothed with exercise in the last sitting of the meeting,
for those whose harps were hung on the willows,
and who could not rejoice while the true seed was in bondage.
My spirit, which had been bowed down with unutterable distress and exercise,
said amen to her communication,
and could rejoice that every "`knee had not bowed to Baal,
nor all kissed his image;`" though it seemed that the floods
of the dragon were poured out upon the true Church,
to destroy, if possible, the true seed of the kingdom.

9th.--My mind has been more tranquil for a few days past than for some weeks previous.
Until the "`Son of righteousness is pleased to arise with
healing in his wings,`" mourning must be my covering.
When and while the Lord is pleased to keep the city, there can no harm befall it;
but when He withdraws his help, where shall we flee for succor,
or when He veils his face who then can behold him? My
spirit has been mingling with the miserable,
but when it feels calm and composed, confiding in the mercy of God in Christ Jesus,
how great is the change.
Shall I ever forget the days of mourning and nights of grief
which I have passed through for twelve months past.
Lord forgive the impatience of my spirit and the lamentations of my soul,
for when the bridegroom is taken away, who can but fast?

14th.--Visited dear cousin Miriam Ellis.
Soon after taking my seat in her room, this language ran through my mind:
"`A holy solemnity,
a holy convocation,`"--accompanied with a belief
that the dear sufferer was preparing for,
and nearly ready to be gathered into, a mansion in heaven.
She expressed herself as being in a comfortable state of mind, saying,
she had heard the language, and she thought that she knew the voice, which said unto her,
"`I will never leave you nor forsake you.`"
Repeating the passage, "`Great and marvelous are your works, Lord God Almighty;
just and true are all your ways, you King of Saints, adding,
"`if any one ever had cause thus to exclaim,
it is I.`" She also dwelt with emphasis upon the mercy of God in Christ Jesus, saying,
it was all mercy--adorable, everlasting mercy, that enabled her to feel calm,
and composed, when it appeared at times that her breath was leaving her,
not feeling the least alarmed thereat.
She also dwelt, at some length, upon the situation of our poor Society;
expressing her belief, that those only who remain faithful unto the Lord,
that experience "`judgment laid to the line,
and righteousness to the plumb line`" in themselves,
would be enabled to stand against the wiles of the devil;
that he was trying to lay waste the whole heritage of God,
but he would not be permitted to do it; that there would be a remnant preserved;
but she believed Friends would have to come out of the mixture,
"`Come out from among them, and be separate,`" had often been the language of her heart,
particularly of latter time.
She wanted Friends to stand plumb for the precious
principles and testimonies given us to bear;
and much more of a similar nature.

19th.--Last Seventh-day, the 17th, was our Quarterly Meeting.
After the shutters were closed, and near the close of the meeting,
I had to speak a word of encouragement to the tribulated, exercised remnant amongst us,
who are concerned above all things to serve the Lord faithfully;
the desire of whose hearts is to be satisfied with
nothing short of the Truth as it is in Jesus;
and though these have to struggle long for the blessing,
hoping at times even against hope; yet I had to express my belief,
and I might have expressed my experience also,
that the Lord would not leave nor forsake such as these;
but keep them in the hollow of the hand.
How has He stretched out his hand for my help,
in that He allows me not to become wholly a prey to the enemy,
but has again rescued me out of the mouth of the lion,
to speak well of his excellent name.
"`Lord, what shall I render unto you for all your mercies.`"
I feel, and have felt,
that I am much behindhand in faithfully occupying the gift entrusted to me.

Twelfth Month 1st.--A few evenings ago, as I sat considering my situation,
suddenly and unexpectedly, my feelings became calm and composed, tranquil and serene;
and a song of praise filled my heart; so that I said, I will trust in the Lord,
and not distrust his mercy, however dark and gloomy the days and the nights.
Surely something will grow out of the year's exercise--
an exercise that cannot be told to the full.
My sorrow has often been so great, that I could scarcely refrain from crying aloud,
"`My God, my God, why have you forsaken me;`" yet now and then a comfortable hope, yes,
a song of praise, fills my heart;
so that I can scarcely refrain (as was the case
a few evenings ago) from praising his name aloud.
As I sat in meeting yesterday, the language revived,
"`What are these which are arrayed in white robes? and from where did
they come? These are they which came out of great tribulation,
and have washed their robes, and made them white in the blood of the Lamb.
And a trembling hope revived that if I struggle on, I might become one of these.

8th.--Today attended the funeral of my dear cousin, Miriam Ellis.
Truly she was to me a precious friend; and we were united in spirit, one to another,
as well as nearly related by consanguinity,
and yet I could not shed a tear or weep for her.
This language was sounding in my ears: "`Weep not for me.`" Her close was a peaceful,
happy one;
and no room is left to doubt that she has joined the heavenly host to
ascribe thanksgiving and praise unto the Lord God and the Lamb forever.

18th.--Went with others of the school committee to the school taught by J. S.,
and had some religious communication to hand forth to the children.
I am almost a wonder to myself, and perhaps to others; so tried, proven and tempted;
and yet I cannot feel peace without, now and then,
encouraging others to seek after and persevere
in the strait and narrow way that leads to life.
Surely there is no other way to the kingdom of heaven than by the way of the cross;
let others try to smooth down and present to the view of the young and rising generation,
any other way or path than that of the cross to the kingdom.
The testimony of my heart and experience is that there
is no way short of becoming crucified to the world,
and the world unto us, that will lead to peace.
For this end came our blessed Savior, even to destroy the works of the devil;
and if judgment is to be laid to-the line, and righteousness to the plumb line,
where is the work to be begun and finished but in the temple of the heart.
My heart sickens at the thought of the modifiers,
that are rising up and are already risen up,
to "`sew pillows to all arm holes,`" to make people
feel easy with that which should be a burden to them;
to make them think they can get to heaven without such a strict
conformity to the will of God as the gospel of Christ enjoins.
Oh! you superficial daubers with untempered mortar--you who sew pillows to all arm holes;
trying to make the way to the kingdom of heaven appear easier than it is;
as far as your ingenuity can devise; that having begun in the Spirit,
we can be made perfect by the flesh; the time will come upon you,
when neither you nor your daubing can stand the storm.
The end will come and try your works and you;
and it will be seen that your "`covering is
narrower than that you can wrap yourselves in it,
and your bed to be shorter,
than that you can stretch yourselves on it.`" You cannot cover
yourselves with the covering that you have devised,
neither can you rest yourselves comfortably upon the resting-
places that you have made or chosen for yourselves;
and as to the pillows that you have sewed to the arm holes of others,
these will be torn away,
and great will be the astonishment and amazement
of those who are deceived with your machinations;
when they see you and your devices brought to naught;
when they behold that nothing but the pure gold, the clean, white linen,
the righteousness of saints will stand them instead in a trying hour.
Then how will they lament that ever they were seduced and drawn aside to believe a lie;
to believe that there is any middle path to the kingdom.
How will they "`be as when hungry man dreams, and behold, he eats; but he awakes,
and his soul is empty; or, as when a thirsty man dreams, and behold, he drinks;
but he awakes, and behold he is faint, and his soul has appetite:
so shall the multitude of all the nations be that fight against Mount Zion.

22nd.--Visited a merchant who has obligated himself to
furnish money to a considerable company of men,
to enable them to undertake the hazardous and
unnecessary journey to California to get gold.
For several weeks my mind has been so arrested and exercised with the subject,
that I was apprehensive something would be required of
me as a testimony against this procedure,
but for a few days past the burden became so great that I
could no longer doubt that I must raise my voice against it,
and that, too, to the chief contributor and encourager of the project.
Accordingly I endeavored to discharge myself faithfully, and have thus far been satisfied.
Oh! the condescension of Israel's Shepherd in making a
way for me where mountains of difficulty appeared;
truly, I have no words to set forth his mercy to me. The fear of man was all taken away,
and I had to speak very plainly to this individual, telling him that I believed the mind,
will and counsel of the Lord was against the procedure,
and that a great weight of responsibility rested and would rest upon his shoulders,
that I thought if he would seek to know the will of the Lord herein, and obey it,
that he would be helped to withdraw his support and encouragement from this measure.
He received kindly what I had to say;
acknowledged that he believed my motives were good in thus advising him,
and he could not say but my sentiments were correct,
but he had not viewed the subject as I viewed it,
or he should not have engaged in it. I thought he felt the burden, in some degree,
resting on his own shoulders, where it properly belongs; and I felt,
in a considerable degree, relieved of a great weight.
Several of the men, who are going, have families of children,
and were in a comfortable way of living as to the outward.
What folly, indeed, to leave a country where plenty reigns,
and where the honest and industrious can procure a comfortable subsistence,
to search for gold.
Alas! alas! what will these poor creatures do
when overtaken with affliction and distress,
far from their friends and homes.
Gold! gold! you can not procure a peaceful mind for them.
