== Chapter V

[.chapter-synopsis]
* Exercises in Her Own Select Meeting and the Quarterly Meeting
* Asa Branson's First Appearance in the Ministry
* A Religious Visit to the Meetings Composing Salem and Springfield Quarters
* A Visit to a Dying Man after Her Return
* Had to Go Back to Salem and Thereaway to Finish the Required Service

First Month 6th, 1850.--Attended meeting at our boarding school,
and was enabled to cast off something of a burden that
rested upon me. After the evening reading of this day,
a quiet and holy serenity covered my mind,
and I believe the same canopy of heavenly love was felt in a degree by others present,
and this language pervaded my heart, "`Lo, the winter is past, the rain is over and gone;
the time of the singing of birds is come,
and the voice of the turtle is heard in our land.`"
And I thought I felt the truth of it in some degree realized.
Oh, how good it is to wait upon the Lord; his hand is not shortened that it cannot save,
neither his ear heavy, that it cannot hear.

Second Month 22nd.--Last Seventh-day, the 16th of this month, was our Quarterly Meeting.
I attended, and found my mind engaged to appear in the ministry; also the day before,
in our select meeting.
What a wonder I am to myself, very often feeling like a dry and withered branch,
neither life nor strength to call upon the name of the Lord for help;
but only in sighs and groanings which cannot be uttered.
Lord, you only know why it is thus with me. I had, in the Quarterly Meeting,
to warn Friends to bow down before the Lord,
to become so prostrated that He might yet be pleased to
look down upon us with an eye of compassion,
beginning with these words: "`No weapon formed against you shall prosper;
and every tongue that shall rise against you in judgment you shall condemn.`"
Expressing my belief that the Lord's faithful will assuredly experience,
(as they have in every age experienced) this precious promise verified,
and also the subsequent portion: "`This is the heritage of the servants of the Lord,
and their righteousness is of me, says the Lord.`"
Staid in the neighborhood of Mt. Pleasant, and on the 18th attended the funeral of E. H.,
a young Friend removed in the bloom of youth from works to rewards.
There my mouth was again opened with these words: "`Daughters of Jerusalem,
weep not for me, but weep for yourselves and your children;`" believing,
we had abundant more need to weep for ourselves and for one another,
than for the dear departed one, having a humble hope, trust and confidence,
that her spirit had been permitted to enter the mansions of rest and peace.
On the 19th, attended Short Creek Monthly Meeting,
where my mouth was again opened in the ministry, in the women's meeting,
beginning with the words: "`Return unto me, oh, backsliding children,
and I will return unto you; I will heal all your backslidings and love you freely,
says the Lord;
telling them that I believed this gracious invitation had long been held out to them,
and still awaited their acceptance;
that the Lord was and had been pleading with them to return
unto Him and bring forth fruits in keeping with repentance,
and not to put off the work.
My heart was enlarged in the love of the Gospel towards them,
and I had to deal very plainly with them, saying, "`You have robbed God, but you say,
wherein have we robbed you? In tithes and offerings.`"
I felt much peace after this meeting, and my strength and confidence renewed in the Lord;
that I should thus open my mouth through the constraining influence of gospel love,
in a solemn warning and exhortation, not to put off the work, but to "`walk in the Light,
while they had the Light;`" for assuredly the time would come when the "`hail would
sweep away the refuge of lies,`" but the Lord's people would never be ashamed.

Eleventh Month 10th.--While reading in the Journal of Thomas Scattergood this evening,
I was strongly reminded of the circumstance recorded in the Holy Scriptures,
where the dead man touching the bones of the prophet Elisha,
revived and stood upon his feet.
It is impossible for me to describe to the full the situation of my poor, tried mind.
I have thought for some time past that my condition resembled the dead or the dying.
Did any one ever pass through what I do,
and yet live? My spiritual life seems almost gone, my faith and hope so low,
my temptations so many, that I am ready, at times, to give over struggling for life;
yet the awful situation of those who faint and give out,
after having put their hand to the plough, is often before me;
accompanied at times with a very strong desire to be enabled to hold out to the end.
Oh, Lord! strengthen me, is often the prayer of my heart, while my many misgivings,
and shortcomings are before me. It seems that I could weep often and much,
but the fountain of my tears is dried up. In our Meetings for Worship I generally sit,
as with my mouth in the dust; while my heart is lifted up in prayer unto God;
that He would be pleased to renovate and quicken us into a
more lively and sensible feeling of our real condition;
into more hungering and thirsting after righteousness,
loosening us from the worldly spirit that is eating up every green thing.
I can truly say,
everything compared with an interest in Christ Jesus--compared
with a blessed assurance of his Divine approbation and favor,
sinks in my view into utter insignificance;
and yet how barren and lifeless He often permits me to feel;
but if this be for some wise purpose, and I verily believe it is, his name be praised.
I will try to bear it with patience.
How did our dear friend Thomas Scattergood pass through indescribable exercises,
tribulation and temptations, both in England and his native land,
and yet the Lord was near him, and preserved him through all.
And shall such a one as I hope in his mercy? Yes, I will, with his holy assistance,
still struggle and strive (and may it be lawfully) for the mastery,
casting every crown at his holy footstool; for this is the only way to sing triumphantly,
and to worship Him who sits upon the throne acceptably.

Twelfth Month 25th, 1851.--Today was our Monthly Meeting,
in the forepart of which my cousin Asa Branson spoke a few words in testimony, saying,
"`There is a path which no fowl knows, and which the vulture's eye has not seen;
the lion's whelps have not trodden it,`" etc., remarking upon the straitness of that way,
and narrowness of that path that leads to life.
I was exceedingly glad, on hearing him open his mouth,
having travailed in spirit for his deliverance from that which
kept him from offering unto the Lord that which I had for some
time felt sensible was required of him,
though I had not named it to him.
And today, as my heart was lifted up in silent supplication on his behalf,
he arose on his feet and uttered a few words which affected me to tears;
fully believing it was the Lord's requiring,
and though at the time rather unexpected to me. And now I can say,
as dear Mildred Ratcliff once said to me, speaking of the ministry:
"`I rejoice with trembling when I see a right beginning.`"
I rejoice, but I tremble also,
knowing the many ways and devices of the enemy to lead
astray from faithfully following the Lord.
May the Lord keep him in the hollow of his holy hand.
May He prune and dig about him, and if need be cast a nauseous substance about him;
even that which is grievous and greatly contrary to the natural will,
so that fruit may be brought forth abundantly to the praise of the great Husbandman.
Amen, says my soul.

31st.--I was instructed and encouraged this
evening in the remembrance of the Savior's words,
"`that men ought always to pray and not to faint.`"
"`Shall not God avenge his own elect, who cry day and night unto Him,
though He bear long with them? I tell you that He will avenge them speedily.`"
The words of Job had been occupying my mind: "`Oh, that I were as in months past;
as in the days when God preserved me. When his candle shined upon my head;
and when by his light I walked through darkness.`"
Lord, deal with me as you see best;
bring upon me anything which may tend to refine and purify me,
that by your light I may walk through darkness.

Third Month 28th, 1852.--Let none of the poor, tribulated followers of the Lamb,
however faint at times they may be permitted to feel,
despair of the mercy and protection of the Shepherd of Israel.
Let none who are sensible of the strivings of the Lord's holy spirit with them;
and who feel the stirrings of life at times in their inner parts, despair of mercy.
Let them wait upon the Lord,
let them watch for the arising of his power to enable them to
pray--let them wait upon Him whom to know is life eternal.
He can make waste mountains and hills and dry up all their herbs.
He can make the rivers islands and dry up the pools.
He can change the face and appearance of things to suit himself,
and make a way for those who are hedged in on every side.
Trust in the Lord, you who are tossed about as with a mighty wind.
Look unto Him; despair not of his mercy; cleave unto Him in the darkest hour.
This is your privilege--avail yourselves of it.
He gives hope--He gives life--He gives strength.
He will give you ability to wait upon Him, even when you feel that you had no hope,
life or strength.
Oh, my soul, wait upon the Lord.
You have experienced many dark and cloudy days.
You have often gone mourning on your way, ready to say,
"`My hope is cut off and perished from before the most high God.`"
Will you not trust in Him who has shown unto you his adorable, unutterable, unmerited,
everlasting mercy, through Christ Jesus, your Lord? Yes,
you may still trust in Him--you may still hope in his mercy, who can redeem, fit,
and prepare you for endless felicity with the saints in Light.
Amen.

Seventh Month 18th.--Left home on a religious visit to some of the
meetings belonging to Salem and Springfield Quarterly Meetings.
Arrived at Salem on the 20th, and attended the Select Quarterly Meeting in the afternoon.
Had nothing to communicate.
Next day at Salem Monthly Meeting I was silent throughout and felt peaceful.
Next day attended New Garden Monthly Meeting; was silent in the fore part.
When the business was gone through, I requested the shutters raised,
which being done I had to be plain and honest amongst them, beginning with these words:
"`What shall be given unto you, you false tongue? Sharp arrows of the mighty,
with coals of juniper, urging the necessity of having our conversation and actions,
such as the Lord approves; not offending Him in thought, word, or deed, etc.
Felt my mind relieved.
Next morning went to Augusta.
Attended the Select Preparative Meeting, which began at eight o'clock,
and the Monthly Meeting at eleven, in both of which I was silent,
except a few words before the close of the women's meeting.
The day following was at Springfield Monthly Meeting.
I was silent in the fore part, but before the close of the women's meeting,
had considerable to communicate, and felt relieved of a burden.
Returned to Salem.
Staid there until after meeting on First-day, was silent and felt satisfied.
Second-day, the 26th,
went to Marlborough and attended the Select Preparative Meeting in the afternoon.
Lodged at Margaret Brantingham's. Next day was their Monthly Meeting.
I was silent in the fore part.
When the Queries were before the women's meeting, I spoke upon plainness of speech,
deportment and apparel,
earnestly desiring that mothers and caretakers might be induced to examine how far
they were concerned to maintain our testimony on these important points.
Also in regard to encouraging the reading of the Holy Scriptures in their families,
and keeping the children from the corrupt conduct of the world,
and from pernicious reading.
After which I felt in some degree relieved,
yet my mind was still loaded with exercise for them, which was hard to be uttered.
From there to Goshen, fifteen miles,
and attended their week-day meeting on the 28th. Was silent therein and felt satisfied;
in the afternoon went to Benjamin Maulsbury's,
whose wife is pretty much deprived of the use of her speech, limbs and faculties;
which makes it trying on the health and patience of those who have the care of her.
I have often craved that such circumstances as this might have a tendency to
induce us to make use of our time and talents to the glory of God,
while we are permitted to enjoy them.
We staid but a little time at this' Friend's house;
but coming away before I felt easy to do so,
I afterwards suffered considerable in my mind.
The Master's time is the best time to move in,
however outward circumstances may seem to urge us forward.
May He see fit to pardon my weakness, and make me more watchful in the future.

29th.--Attended Springfield Meeting and had
considerable to say on the subject of the ministry,
and came away satisfied.
Next morning went back to Salem.
Felt unwell with disease of the stomach, and no liberty to leave.
Was at Meeting there on First-day, and again silent;
which is the fourth time I have attended this meeting since coming amongst them;
not daring to open my mouth in any of them.
I found it needful to watch very closely the pointings of Truth,
and to move only when and where it pointed;
though sometimes entirely contrary to my expectations.
I am often blindfolded and led about by that invisible power,
that knows best what is best for us. A little
opening appeared after meeting on First-day,
to go as far as William Fawcett's on our way to Middleton;
though my mind was in a very low spot; and I was not very well in body;
and I began to think whether my way for further service would not
entirely close up. But I found no liberty to turn my face homeward.
Next morning, with a little renewal of faith, started for Middleton;
having Wm. Fawcett for our pilot.
About noon reached the neighborhood, and put up at Sina Heald's, widow of Abner Heald,
a much beloved minister who died a few years ago,
sound in the faith and hope of the gospel.
William Heald, the father of Abner,
was then at his daughter-in-law's. He is near ninety years old;
and is smart and active on his feet, and his faculties clear.
Soon after we arrived he asked whether we wished a meeting appointed.
I told him if Friends were willing, I wished to see them,
and others of the neighborhood in the capacity of a Meeting for Worship.
He readily assented, and soon started to give notice himself.
It was some encouragement to my tried mind,
to see this valued Friend and Elder in the Church,
evince such an interest in promoting that concern which led me to leave my home;
even the good of others, and the peace of my own mind.
This meeting was well attended, and I thought it a good meeting.
I felt concerned therein to arise upon my feet and say--
that I believed there was a spiritual knocker,
and a spiritual knocking; but very different indeed in its nature,
from that self-styled spiritual knocking in these days;
of which the devil and his agents were the authors.
Unto Christ Jesus,
who is knocking at the door of the heart--unto
Him who is the "`minister of the sanctuary,
which God has pitched, and not man,`" I directed the attention of the people;
and to turn away from, "`Lo here is Christ, and lo He is there,`" etc.
I afterwards felt easy and quiet.

Next day went to Elk Run.
It was a very small meeting, and, I thought, a lifeless one.
We sat a good while in silence; but before the close, I told them,
that although I had seen no one asleep, except a little child,
I thought it right to admonish them, to "`present their bodies a living sacrifice,
holy and acceptable unto God, which is our reasonable service.`"
That a religious meeting was not the place to sleep; not even for children.
That even such, though quite young, should be better instructed.
I had considerable to say, and felt relieved when the meeting ended.
Rode to Carmel that evening.
On our way we passed a road,
at the sight of which I felt that I must enquire to whose house it led.
Our pilot answered, to the house of a Friend whose wife has long been a cripple; adding,
the Friend desires you would come and see them.
I noted this down in my mind, thinking we would call on our way back to Salem.
Lodged that night at N. Armstrong's, and next day attended Carmel Meeting.
And although I had considerable to communicate, I did not feel relieved;
and could hardly tell why.
Dined at Armstrong's, and felt weighed down with exercise.
It rained hard and the clouds were thick; but expecting to leave Carmel that afternoon,
and return to Salem, I felt anxious to be going.
Under these feelings I requested the horses got ready that we might be off;
but as we left the Friend's house and turned towards Salem,
I felt a weight of exercise which I cannot describe.
I thought if the sheriff had come and taken me captive,
I should not have felt more like a prisoner;
while this language ran forcibly through my mind--"`You are still a prisoner.`"
Under these feelings we rode five miles to T. Ws, a Hicksite preacher,
whose wife is an elder amongst Friends.
Next morning I told my companions, I must go back to Carmel.
They were ready and willing to do so. I requested a
private opportunity with T. W. and wife.
I told him, that I believed the Lord required him to be still,
to know what it was to be brought into true silence before Him;
and if this was his experience he would see his way out from amongst the Hicksites.
That I had no unity with their principles, nor gospel fellowship with those who hold them.
I said much more to the old man in the presence of his wife,
which he seemed to take kindly;
his wife uniting with what I said--that a state of stillness was what
he was called to. After this I requested the children called in,
and had an opportunity with them to the relief of my mind.

On our way to Carmel we called on a son of the aforesaid Hicksite,
yet a member amongst Friends.
He had been lately married.
We had a religious opportunity with him and his wife.
I exhorted them to "`seek first the Kingdom of Heaven, and its righteousness,
and all things necessary would be added.`"
I reminded them of the danger of setting their affections on things below,
that the desire after worldly treasure generally and gradually increased in the mind,
as riches increased.
That the natural mind of man could not be satisfied with wealth.
I reminded them of the humble situation that our blessed Savior made in his
appearance in the world--his birthplace a stable--wrapped in swaddling clothes,
and laid in a manger.
He by whom all things were created that are in heaven and in the earth,
condescended thus to humble himself; setting us a pattern of meekness and humility,
which we ought to consider when we are desiring
great things and fine appearances for ourselves.
I had much more to communicate to these young persons, to the relief of my mind.
Went to William Leech's. After dinner had a religious opportunity with the family,
and then rode to Carmel.

Same afternoon went to see an aged Friend, eighty-six years old,
who had been confined at home about six years; suffering much bodily pain.
She seemed overjoyed to see us; often exclaiming, "`Oh, I am so glad to see you;
I am so glad to see the faces of my friends.
I am a poor, unworthy creature, but have much to be thankful for.`"
On looking around her room,
and contrasting her humble cottage with the dwellings of those who
have all the comforts and conveniences of life when thus afflicted;
I was struck with her expressions of gratitude,
and thankfulness for the blessings she enjoyed.
We stayed an hour or two with this aged Friend,
had a religious opportunity with the family, consisting of herself, her son and his wife,
and several children.
I felt thankful for being permitted to make this visit.

Next day visited two aged Friends, who were mostly confined at home with bodily infirmity.
There I relieved my mind in a religious opportunity, and came away satisfied.
But for not giving up to pay a visit to his sons, who lived near by, I felt remorse;
and have since regretted this omission.
Went to Martha Ashton's to dine.
Had a religious opportunity with herself, son and daughter, to the relief of my mind.
I then mentioned to my companions a concern which had
rested with me to appoint a meeting at Carmel,
at four o'clock tomorrow afternoon; which with the consent of the elders, was done.
The meeting gathered at the time appointed and was well attended.
I felt it right to plead with the infidel to forsake his proud and vain course,
and turn unto the Lord while He was pleased to plead with him in judgment,
mingled with mercy.
I had to warn them against indulging.in a spirit of unbelief;
that an awful doom awaited those who gave up to disbelieve in,
and continued to disbelieve in, the Savior of the world;
and in the existence of a Supreme Being.
I admonished the youth to flee from the reasonings of
the sceptic as they would from the bite of a viper.
To shun the company of such as they would shun a venomous beast.
The meeting ended in supplication.
After this meeting,
in which I was largely and weightily engaged in the service appointed me,
I felt ready to leave Carmel with a peaceful mind.
Truly thankful was I for having been enabled to wait the Master's time for my departure.

Rode to Elk Run that afternoon,
and Lodged at the Friend's house whose wife was a cripple,
and where I had proposed stopping on our return to Salem.
We had a religious opportunity in the family (where were several young people),
much to the relief of my mind.
Returned to Salem the 9th of the Eighth Month.
Went to A. H.'s, and had a religious opportunity in his family;
relieving my mind towards his children, and some of their relatives who were present.
I reminded them of the uncertainty of time, and the necessity of spending it rightly.
I told the young people of my father's expressions concerning himself--"`When a lad,
I was left without father or mother, or any one to counsel me;
but as I looked to the Lord He kept me out of bad company, and preserved me from evil.`"
I did not know until afterwards,
that some of the children had been disowned for attending balls, dancing-parties, etc.
This was a very unexpected opportunity to me;
but I felt that I dare not go away without trying to relieve my mind amongst them.
Stayed in town at our old home, M. J. F.; kept close at home next day;
and on the 11th again attended Salem Meeting). I
had to declare the truth amongst them that day;
telling them that I felt bound, poor and unworthy as I was,
to speak of the nature and tendency of gospel ministry.
That I esteemed such a ministry a blessing to the Church;
yet where any spoke from past experience,
without the fresh anointing of the holy Spirit--without the immediate
putting forth of the Shepherd of the sheep--such a ministry,
although esteemed eloquent, and adorned with gifts,
belonging to the natural parts--theoretical,
and head knowledge--could not profit the people,
and was nothing better than sounding brass or a
tinkling cymbal--the bell without the pomegranate.

I exhorted them to get down deeper in their spirits; to wait upon the Lord,
who is the fountain of life, and never-failing source of help to the rightly exercised.
To such as these, a ministry, however calculated to please the itching ear of man,
yet lacking the demonstration of the spirit and power, was a great burden.
When this meeting ended I felt calm and peaceful.
Oh, the superficial daubing which it seems to me is going on. My heart
feels sometimes to sicken under a consideration of these things.

In the afternoon visited Salem school,
and had a religious opportunity with the teacher and scholars.
Next day visited the family of an individual who had died suddenly from home,
with the cholera, while attending a political meeting.
Though I went in fear and trembling (they not being members of our Society),
I felt greatly satisfied in having given up to this intimation of duty.
This family, which consisted of the widow and several children grown up,
were much contrited and humbled on this occasion;
and I trust it will be some inducement to them to consider the uncertainty of time,
and to prepare for a future state.

Next day, attended the Select Quarterly Meeting at Salem, in which I was silent.
The day following, the Quarterly Meeting--silent also in that,
except a few words in the last meeting.
Next day being First-day the 15th of the month, again attended Salem Meeting.
Nathan Hoag and Rebecca Updegraff were there, and had much to communicate.
I spoke a little, near the close of the meeting,
but my mind was so depressed after meeting that I could not forbear retiring to my room,
without partaking of any nourishment,
and tried for a resting place from the commotions that seemed to come in like a flood.
I remembered the language of the Psalmist--"`The Lord sits upon the flood, yes,
the Lord sits King forever.`"
Towards evening, visited a brother of the man who died with cholera, before mentioned.
Had an opportunity of relieving my mind in his family.
Then went to Dr. A. C.'s, and had an opportunity with him and his wife,
to the relief of my mind.

Next day, attended Springfield Select Quarterly Meeting.
After much communication from various individuals, and the business gone through,
I felt it right to tell them, that I had been reminded of the word of the Lord,
through the mouth of his prophet--"`Take away from me the noise of your songs;
for I will not hear the melody of your viols.
But let judgment run down as waters, and righteousness as a mighty stream.`"
I told them that I felt constrained to declare
in their hearing in the love of the gospel,
that breathed for the salvation of every soul present;
that I believed that the deceivableness of unrighteousness was in the camp;
that there was a disposition to cry peace, peace, when there is no peace.
That the Lord required judgment laid to the line,
and righteousness to the plumbline in the hearts
of those who were crying out in his name,
or concerning his works, and goodness, etc.
I felt peaceful and easy after this meeting;
yet under exercise that I might be kept in my proper place.

Next day, at the Quarterly Meeting, I was silent.
After meeting returned to Salem, and that evening visited two families.
Next day being Salem Week-day Meeting, I felt no liberty to leave before,
though I had been looking a little towards it,
but felt that I must not be a Jonah fleeing before the right time.
Paid two family visits and then went to meeting, and sat under great exercise,
which caused some of my limbs to tremble.
It being their Preparative,
I did not feel it my place to say anything in the public meeting,
but requested when the business was gone through, that the shutters might be raised,
which was united with by men and women.
Then, in the fear of the Lord, and, I trust, in the power and strength which He gives,
I felt at liberty to unburden my mind amongst them--telling them that I was
not aware of having omitted any right opening to relieve my mind;
that my spirit had been held captive amongst them as well as my body,
and I had been baptized into a very low place for the living, as well as the dead.
That I believed the spirit of Balaam was amongst them;
that spirit which George Fox said is the most deceiving.
That spirit that could speak from past experience of God and of Christ, yet nevertheless,
had forsaken the right path and gone out into gainsaying.
That spirit was amongst them that could exclaim, "`How goodly are your tents; oh Jacob,
and your tabernacles, oh Israel; let me die the death of the righteous,
and let my last end be like his;`" while, at the same time,
ascending the altars of Balak and following after the wages of unrighteousness.
I told them that I believed the Lord would in his own time arise and deliver his people,
and discover the deceit amongst us;
that the great hail-stones would fall and sweep away the refuge of lies,
and the Balaam-like spirits would be found slain in the enemy's camp.
That the spirit of Saul and of Goliath was also amongst them;
that which hunted the life of the true Israelitish seed.
Also that which defied the Israel of God.
Oh, it was a fearful meeting; but I had to tell them with trembling, and in the fear,
dread and power of the Lord,
that in his own time He would prepare the sling and the stone,
and rescue his chosen from the hunters and defiers of Israel.
I also exhorted those who were alive to get down deeper in their spirits,
that they might be prepared to labor availingly in the vineyard of the Lord.
How good it is to wait all the Lord's appointed time for ability to do his work;
and labor after resignation until He gives the
word of command to step forward in his service.
After meeting paid another family visit and then set out for home,
taking our Quarterly Meeting in the way.
Reached home after Quarterly Meeting,
but felt no liberty to return my Minute at our Monthly Meeting the week following.

Twelfth Month 14th.--My soul is exceedingly sorrowful.
Oh, you preserver of men, you have been with me, in and through many straits.
Once more I ask your all-protecting guardian care;
while my spirit is exceedingly tried and tempted.
Be pleased, I humbly pray you,
to look down with an eye of compassion upon one who feels that there is none in heaven,
or in earth, to look unto for help and strength, but you;
in this hour when my patience is put to such a close trial.
Oh, you who know how far to try me, let me not faint, or give out,
or conclude as Saul did, that the prophet tarried too long;
and so offer an offering before the right time.
Lord,
you know for what you permit me to experience the cloud to rest upon the tabernacle;
while it seems to others,
that I am deferring of my own accord the work appointed me. Grant ability, oh God,
to wait all the days of my appointed time, until my change come;
until the shadows flee away, and there is daylight to walk in, and to work in.

Second Month 4th,
1853.--I think of leaving home tomorrow to finish (as way opens) a religious visit
for which I obtained the concurrence of our Monthly Meeting nearly eight months ago;
and though it remains partly unaccomplished, I know of no other cause,
than that the way has appeared closed up, and no opening in the truth,
either to move forward, or to return my Minute to the Monthly Meeting.
A strange situation to be in some may think;
for any one professing to be a minister of the gospel.
But shall any one undertake to move in such an important work,
without that degree of light and strength requisite to bring peace of
mind? None knows how it has been with me for the past six months,
save the Searcher of hearts.
No tongue can tell or pen describe the extent of the sorrow
and distress which my mind at times has undergone;
so that I have marvelled how the body could sustain the weight of exercise endured.

What shall I say of the works of the Lord,
or how shall I declare the mighty power of God.. I will even "`lay my hand upon my mouth,
for his greatness is unsearchable, and his ways past finding out.`"
"`I fainted in my sighing and found no rest,`" only as you have been
pleased to give it me. The world had no consolation for me,
and as for things delightful, they fled as though they had never been; but now,
He lifts me up a little and causes me to hope in his mercy.
My soul has this testimony--that there are those in these days,
who appear to be full fed, and in need of nothing, who run when they please,
and speak what they please, who shall experience their staff of bread broken,
and they shall lack bread and water, and be astonished one with another,
and consume away if they repent not of their iniquities.

"`Do your duty independent of the whole world,`" said a dying
man to me the other day as he bid me affectionately farewell,
repeating it twice--"`Do your duty independent of the whole world.`"
What an honest hour is the hour of death.
This man, as he expressed himself, had waded in gold, yet he found, as he said,
that it is not worth living for; exhorting his children to be good.
Very plainly had I dealt with this man,
concerning his spiritual condition in the days of his health,
when sickness and disease were far from him;
but now he remembered that nothing but honesty would do,
and a faithful performance of our religious duties.
Oh, may I never fear the face of man, when the Lord bids me speak,
though he may soar above the true witness for God in the secret of his heart;
yet the time will come when he will need pure and undefiled religion.
Great had been my exercise for this individual in his sickness,
as well as in the days of his health;
and ardently did my spirit crave that he might be permitted at the
eleventh hour to enter into the vineyard and labor for the penny.

5th.--Left home as contemplated;
rode seventeen miles to a neighborhood where no Friends reside;
appointed a Meeting for Worship to be held the next day, at three o'clock.
The day was cold and stormy, and the roads difficult to travel,
yet the meeting was well attended,
and I felt thankful that I was there amongst a company of strangers,
whose faces I may never again see; yet, for the welfare of their souls,
my spirit has long felt deeply interested,
and now I feel peaceful and easy in regard to the
dedication of my will to that of my Divine Master.
After this meeting (which ended to satisfaction) rode to Jefferson, five miles;
but did not reach our lodgings until eight o'clock at night.
Here we met with a Methodist minister,
with whom we had some conversation on doctrinal subjects,
and I believe it was not an unprofitable interview;
both he and the innkeeper were very friendly disposed,
and perhaps some things mentioned may be remembered to profit in days to come.
From Jefferson to Harlem Springs, twelve miles.
After dinner had an opportunity with the innkeeper and wife,
whom I considered in a very responsible situation.
It being a place of great resort in summer for all classes of people,
on account of the (supposed) virtue of the water for the cure of diseases, bathing, etc.
I had to deal very plainly with them, exhorting them to keep an orderly house,
free from music, dancing, card-playing, etc.
I warned them of the consequences resulting from a life spent in pride, vanity,
and irreligion.
I have since felt easy in my mind in regard to them,
and hope I shall be clear of their blood.
Rode that afternoon to Mechanics-town, over as bad roads as I ever travelled.
When I think of the cup of suffering which has been meted out to me,
and the strokes it has taken to make me willing,
and to prepare me to set out on this little journey, retracing my former steps;
all that can arise in regard to difficult roads, weather, etc., seem nothing in my view,
compared to that peace which is necessary for us to
know before we can receive an immortal crown of glory.

This morning, the 8th, had a religious opportunity with the family where we lodged,
all of whom were strangers to us. What was offered appeared to be well received.
This day reached the settlement of Friends.
9th, today, attended the Select Preparative Meeting at Middleton.
In the evening went to Samuel Dixon's,
where we unexpectedly met with our friend J. E. and companion.
This evening, during an interval of silent, reverent waiting on the Lord in this family,
my mind was raised above all gloom and discouragement,
and a song of praise filled my heart, so that no sorrow was thereunto added.
I said it is enough, Lord,
you have given me an evidence of your favor and loving kindness of which I am not worthy.

10th.--This day was Middleton Monthly Meeting.
After the business was gone through, I requested the shutters lowered,
and had a relieving opportunity with men and women Friends.
I told them that I believed the Lord had not cast off his people;
that He had preserved a remnant to speak well of his excellent name;
that if we as a people deserted our posts,
others would be called in from the highways and hedges,
to support our principles and testimonies, and our vineyards, and olive-yards,
would be taken from us and given to our neighbors who are
better than we. This and much more I had to tell them.
Dined at J. Heald's;
had an unexpected opportunity with him and his family in the way of caution,
counsel and encouragement; hope it will not prove to their disadvantage.
Lodged at Sina Heald's, widow of Abner Heald, who died a few years ago,
leaving a noble testimony behind him for the Truth, and against Gurneyism, etc.

11th.--Attended Salem Select Quarterly Meeting.
After returning from it my mind became deeply affected,
and I could not refrain from weeping.
I went alone and gave vent to my tears;
I thought of the strokes it had taken to make me willing to return to Salem,
and the turnings, and the overturnings I had endured since I was there.
I remembered the wormwood and the gall,
and my heart was humbled within me. I felt willing to be reputed anything or nothing,
so that I might be found in my place.
I desired not to be in company, but endeavored as much as possible to conceal my feelings.
Next day attended the Quarterly Meeting; in the forepart of which I was silent.
After the shutters were closed and J. E's Minute was read,
I informed women Friends that I was there with the same
Minute that I obtained in the Eighth Month last;
that on returning home, as I apprehended, at the right time;
month after month had passed away,
and still I did not feel fully released from the service,
and yet had felt no liberty to return amongst them until the present time.
That it could not be to our peace, or the advantage of others,
to move in our own will and time;
though we might think it long to be thus held as it were in bonds.
Several Friends expressed satisfaction with the information, and unity with my attendance.

After the business of the meeting was finished, I requested the shutters opened,
that I might see men and women Friends together,
which was fully united with by men and women.
My mouth was opened to commemorate the goodness of the Lord;
that He is able and willing to sustain those who put their trust in Him,
even under the weight of mountains;
reviving the language of the prophet--"`He that
comprehends the dust of the earth in a measure,
and weighs the mountains in scales,
and the hills in a balance;`" He can sustain under every trial
that can befall us. I had to allude to the prophet Ezekiel,
who was commanded to lie upon his left side,
and lay the iniquity of the house of Israel upon it, and then upon his right side,
and bear the iniquity of the house of Judah.
He was not to turn from one side to the other to ease himself,
until the days of the siege were fulfilled.
His bread was nauseous and to be eaten by weight,
and with care from time to time was he to eat it; he was to be a sign to the people.
So the Lord had some in these days who were to be a sign to others;
they could not run at their own will or pleasure.

The Lord had put bands upon them, and they knew that He is Almighty,
and can in his own time release them;
that man as he is obedient to the teachings of the holy Spirit,
that leads out of all error into all truth, will be raised above all earthly-mindedness,
become heavenly-minded,
having his affections weaned from the world and the things of the world.
I had to tell them that I believed,
there were those amongst them who were not willing to
be counted as earthly-minded as they really were.
Who, instead of saying to their children and those around them,
follow us as we follow Christ, by our every-day walk and conversation,
were saying practically, follow us as we follow the world, its spirit, its manners,
its maxims, and its customs; that the day is hastening,
when we shall be called to an account, and every false covering rent off.
Oh, the importance of being ready for such an hour; "`when the dust shall return to dust,
and the spirit shall return unto God who gave it,
to receive a reward according to the deeds done in the body.`"
I felt peaceful and easy when the meeting ended.
Before the close, Joseph Edgerton said, "`This is a day which the Lord has made,
we will rejoice and be glad in his salvation.`"

Next day united with J. E. in appointing a meeting for the youth at Salem;
but the meeting was not so much to my satisfaction as I could have desired, partly,
I believe, on account of my own disobedience,
in not strictly attending to the pointings of the Master; both before going into meeting,
and afterwards.
Those who preach to others must know judgment laid to the line in themselves,
and righteousness to the plumb-line,
or else their preaching will not profit their hearers, nor bring peace to themselves.
May I learn obedience by the things that I suffer.
The dear Master gives an unflattering witness in
our hearts which sticks closer than a brother,
and if we do not stifle its convictions, we will be led plainly to see our misses,
and how to mend them, as well as to feel the answer of well done,
when we have faithfully followed this heavenly monitor.

10th.--Proceeded to Springfield Select Quarterly Meeting;
after which we dined at J. F's. Before leaving there J.
E. had some encouraging language to these young Friends,
and I felt myself called upon to repeat the words of the Apostle,
and apply it to our Society in the present day--"`The Lord has
not cast off his people whom He foreknew;`" with some
encouragement to those who were rightly exercised,
not to give out though trials may abound.
Then went to J. Lynch's, where I felt my mind drawn to caution and encourage them,
not to give out in the day of trial; to remember Lot's wife,
who was turned into a pillar of salt through unfaithfulness;
a warning to others instead of a way-mark.

From there to Simeon Fawcett's in the evening.
His wife proposed that a chapter be read in the Bible, with which we united,
and it proved an opportunity for me to cast off a
burden that rested with me in regard to this family.
I felt peaceful and easy afterwards, blessed be the name of Israel's Shepherd,
for when He opens none can shut, and when He shuts none can open.

Next day, attended Springfield Quarterly Meeting, where I relieved my mind,
particularly in the women's meeting, greatly tending to my own peace;
and I hope some encouragement to the rightly exercised amongst them.
Dined at J. H. Stanley's,
where we had an opportunity with his family and some other Friends,
to the relief of my mind.
I told them I believed the Lord would sift us until we were a people more to his praise;
that all who would live godly in Christ Jesus, must be willing to suffer;
that the integrity of Job's heart kept his head above the waves of affliction;
that everything seemed to combine to render him uncomfortable, and cast him down;
yet he maintained his allegiance firm unto Him who is the Lord of lords,
and King of kings; so may we be able, in and through all trials and besetments,
as we keep the eye single to the Master, to triumph over all opposition,
and become "`more than conquerors through Him who loved us.`" Went to Goshen,
and lodged at Robert Ellyson's.

Next day, in company with J. E. and companion, rode forty miles to Job Warren's;
where J. E. had an appointed meeting to middling good satisfaction.
They being the only family of Friends in that neighborhood, the meeting was held there.

13th.--Left Job Warren's and rode twenty miles to Ravenna,
where Joseph Edgerton felt his mind drawn to appoint a meeting,
to be held at seven o'clock that evening.
The attendance was small in consequence of several
other meetings having been previously appointed;
yet it proved a time of favor.
One individual, a stranger to us, expressed his near unity with what he had heard said.
His views in regard to the necessity of water baptism, and some other doctrinal subjects,
had recently undergone a change.
He hoped to be able to live so as to be united to the true disciples of Christ,
or words to this import.
We left this person in a very tender frame of mind,
and parted under solemn feelings.gospel of our Lord and Savior Jesus Christ;
and I had large and open service amongst them, greatly to the relief of my mind.
The prospect of this meeting had for months past borne with weight on my mind,
and now I was enabled through holy help to cast off a great burden.
Blessed, praised and magnified be the name of Israel's Shepherd.
He brings low and raises up, and is worthy of all glory and honor forever.
I was largely opened in this meeting to declare against infidelity, atheism,
and all unrighteousness; and had to bear my testimony against those works of darkness,
called spiritual rappings, and the workers thereof; stating my belief,
that it was the devil and his agents who carried it on, and were the originators thereof.
A young man, a stranger to us,
expressed his satisfaction with what he had heard delivered.

Next morning we parted with J. E., they going towards Salem, and we to Marlborough;
where we arrived about noon.
The concern to appoint a Meeting for Worship for the inhabitants of that town,
resting with weight upon my mind, it was laid before the elders,
who making no objections,
it was appointed to be held next day at seven o'clock in the evening--being First-day.
The meeting was held in the town hall,
where we found the house about half filled with men, women and children;
and such a scene of confusion on such an occasion, I never before witnessed.
Some were laughing and talking aloud; some whistling and humming in a light,
irreverent manner; and the prospect for a quiet settlement, to all outward appearances,
was discouraging: yet my mind felt in a good degree staid upon Him,
who I believed had required me to come here.
We took our seats, and trusted to his interposing power.
Soon the company began to find seats, and to become more quiet and orderly.
Still some kept whispering.
After the meeting was pretty much gathered, I informed them,
that I was a stranger amongst them,
bad come a considerable distance to be with them in a Meeting for Worship,
and felt desirous that we might settle down into a quiet, waiting frame of mind,
and endeavor to worship God in spirit and in Truth.
After taking my seat, and remaining silent for some time, my mouth was again opened,
to declare the glad tidings of the gospel of our Lord and Savior Jesus Christ;
and I had large and open service amongst them, greatly to the relief of my mind.
The prospect of this meeting had for months past borne with weight on my mind,
and now I was enabled through holy help to cast off a great burden.
Blessed, praised and magnified be the name of Israel's Shepherd.
He brings low and raises up, and is worthy of all glory and honor forever.
I was largely opened in this meeting to declare against infidelity, atheism,
and all unrighteousness; and had to bear my testimony against those works of darkness,
called spiritual rappings, and the workers thereof; stating my belief,
that it was the devil and his agents who carried it on, and were the originators thereof.
A young man, a stranger to us,
expressed his satisfaction with what he had heard delivered.

Next morning proceeded back to Ravenna,
where I felt a concern to have a religious opportunity with the innkeeper and his family,
which was readily acceded to on their part.
and we sat down together to wait upon the Lord.
Here I had to revive the necessity and obligations that rest upon us,
if we would be owned of Christ before his Father and the holy angels;
not to deny Him before men,
not to be ashamed of his cross before a crooked and perverse generation.
It was to me a satisfactory opportunity; his wife appeared in a tender,
sweet frame of mind, and I left them peaceful and easy.
That afternoon rode twenty miles to Goshen; got to R. E's about eight o'clock at night,
and found the parents from home; but the children kind and attentive.
Next morning had a religious opportunity with the children of this family;
and had I delivered the whole counsel of the Lord to some of them,
I should not have come away burdened as I did.
I felt that there were snares cast about the feet of some of them,
in which they would be taken, if a more strict watch was not maintained.
I let in the reasoner, and did not acquit myself faithfully.
A fear rested with me,
that more than one of the young Friends then present was not willing
to support our principles and testimonies in regard to some things.
After hinting to one of the girls a little of my feelings, I came away with a heavy heart.

Went to Aaron Woolman's, an honest, sincere-hearted Friend,
in a declining state of health.
On inquiry, he said that he suffered but little pain of body,
and was favored with peace of mind;
and there was such a quiet serenity to be felt in his company that needed
not words to tell that the Master's calming influence was there.
I proposed the family being collected;
and had some encouragement to hand forth to the young people, four in number.
I exhorted them to arise,
and shake themselves from everything that hindered them from
the service in the Church whereunto they were called;
that as the fathers and mothers were removed, there might he those to take their places.
"`Say not four months and then comes harvest.
Lift up your eyes and look on the fields; for they are white already to harvest.`"
There is now a work and labor to perform, and there is no putting it off with safety;
the Lord will have a people to his praise.
The privileges of the birthright members of our Society if not more appreciated,
will be taken from them, and if there is not a turning and returning unto the Lord,
who has smitten us,
many of the members of our religious Society will experience the
truth of this language--"`Our inheritance is turned to strangers,
our houses to aliens.`"
That evening returned to Salem.

Next day being the 23rd of the month, attended Salem Monthly Meeting;
was silent in the forepart,
but towards the close of the women's meeting the language of Pilate to the Jews,
just before the crucifixion of our Savior, together with their reply,
forcibly presented to the view of my mind, "`Behold your King.`"
The Jews answered, "`we have no king but Caesar.`"
I had to query with them, whom they owned as their king.
Whether in their daily walks and conduct, they were denying the meek and humble Jesus,
and following the world and the spirit of the world,
thus saying in the line of their conduct, we have no king but Caesar.
This testimony was close and searching, but I felt peaceful.
After meeting paid a visit to an afflicted relative,
for whom my mind had for several years been at times deeply exercised;
believing that the offers of salvation through Jesus Christ,
the only and alone way to peace and everlasting happiness, had been slighted by him,
until the eleventh hour was come, or nearly so. I found it my place to tell him,
that I had never felt like saying to any relation,
friend or fellow-creature--"`Stand by yourself,
for I am holier than you,`" but far otherwise;
yet the truth of this declaration was sealed on my mind-
-"`Without holiness no man shall see the Lord.`"
That however we may be surrounded with stumbling-blocks on the right hand,
and on the left, it will afford us no available excuse,
when called upon to give an account of the deeds done in the body.
If our day's work is not done the fault will be our own,
for He whose power is above every other power,
and who has called us to glory and to virtue, is able and willing,
as we look unto and trust in Him,
to make a way for our escape from everything that would hinder
our progress in the strait and narrow way which leads to life.
I exhorted him to turn inward to the gift of grace revealed in his heart,
and let the welfare of his soul have the chief place;
that it was high time to wake up to the importance of
being ready to meet the Bridegroom of souls,
for if the oil was lacking when the midnight cry was heard, no friend, or physician,
or any instrumental help would then prove availing.
After supplicating the throne of grace,
and commending the care and keeping of our souls unto God, I felt peaceful and easy.

Went to W. F's, where we met J. E. and companion, and several other Friends.
After spending some time in cheerful conversation, we dropped into silence,
which continued uninterrupted for a considerable time;
when it appeared right for me to say, that during our silent waiting together,
I had been forcibly reminded of our Savior's language to his disciples,
when describing to them what great distresses and perplexities
they should be witnesses of in their day and generation.
There should be wars and rumors of wars--earthquakes in
various places--men's hearts failing them for fear,
and for looking after those things that were coming upon the earth.
"`Then if any man shall say unto you, Lo, here is Christ, or Lo, He is there;
believe it not.
For as the lightning comes out of the east, and shines even unto the west;
so shall also the coming of the Son of man be.`" I had to
declare that I believed it to be as needful for us in this day,
to wait for the coming of the Son of man as it was for
those to whom this language was then addressed.
That we should not go forth at the sound of the lo, here is Christ; or lo, He is there:
but to get on the watch tower, and keep on it, "`dwelling in the ward whole nights.`"
That our early friends, by the operation of the holy Spirit upon their minds,
by deep baptisms, and waiting upon the Lord in the way of his judgments;
were brought to a clear discernment of the will of God concerning themselves;
and were also able to detect error and wrong in others; being able to say triumphantly,
"`Lo, this is the Lord! we have waited for Him;
we will be glad and rejoice in his salvation.`"
As this was their experience, so as we are willing to bow before Him,
in humiliation and prostration of soul,
in his own time He would give us to experience
that as the "`lightning comes out of the east,
and shines even unto the west,
so shall the coming of the Son of man be.`" That
no disappointment awaits those who truly fear,
and wait upon the Lord, in singleness of heart.
Those who are truly desirous to be his followers, He will lead and guide.
He will be their Urim and Thummim, their light and perfection, their all in all;
and enable them to feed together in heavenly places,
as certainly revealing himself spiritually to them as
He did in the days of his flesh to his disciples,
when He invited them on this wise, "`Children come and dine.`"
And none of the disciples dared ask Him, "`Who are you?`" knowing that it was the Lord.
Paid a visit to C. and S. Moore,
then returned to M. J. Fawcett's and found several
young people had come in to spend the evening.

Before separating, a chapter in the Bible was read;
after which I thought it right to speak of the
necessity of spending our time soberly while here below.
The Christian may be cheerful, but not light, trifling and vain.
Those only who do the will of our Father in heaven, have a right to be cheerful.
Christianity does not lead into gloominess, melancholy and despair:
neither does it lead into vanity, lightness and forgetfulness of God.
As we submit ourselves unto Him,
letting Him "`work in us to will and to do of his own good pleasure;`" every
thing in our nature that is crooked and perverse--every thing rough,
snarlish and selfish, will be brought into order;
all disposition to be preferred one above another, or lord it over one another,
will be brought down, as we experience his gospel power operating in our hearts.
While the day of mercy lasts,
every thing around us proclaims this language--
"`Pass the time of your sojourning here in fear.`"
"`Live soberly, righteously and godly in this present world.`"

Next morning rode to New Garden Monthly Meeting, but was silent throughout.
J. E. had good service.
I appointed a meeting for the inhabitants of this town
to be held at seven o'clock same evening.
It proved a time of laborious exercise, with but little relief of mind,
partly owing to causes, I believe, existing with myself.
I feared my communication was too lengthy,
and too complex to be as profitable to the people as it otherwise might have been.
Ministers must know judgment laid to the line in themselves, and a careful watch set,
that they do not exceed their proper bounds,
when greatly exercised for the welfare of the people;
as well as not to cut short or curtail that which is given them to deliver.
No relief can be obtained by prolonging such communications, when the time comes to stop,
however the burden and exercises for the people may continue.

Lodged that night at Lewis Walker's. Next morning,
my mouth was opened in a religious opportunity
with the family and several Friends present,
to speak of the goodness, mercy and power of God; that He can keep us alive in famine.
When the widow spoken of in the Scriptures, was apprehensive that the time drew near,
when she and her son must die of famine, she did not sit down and despair,
without doing her part towards preparing the last morsel, as she supposed,
for herself and son.
Before the last cake was to be baked, her faith was put to the test,
but not without the promise, that if she would first bake a cake for the prophet,
the meal and oil should not fail.
This account shows the necessity of walking by faith,
and not giving out in the darkest and most gloomy time,
however long the winter may continue; and however bleak the winds;
and however hard and cutting the frosts and cold thereof;
yet the Lord's power is over all.
I had to speak of the necessity of keeping the faith and patience through all.
That the Lord would in his own time arise and scatter
the gloom and hid the winds and waves be still,
and produce a calm, and replenish the souls of those who trust in Him with good things.

The same day, attended Sandy Spring Monthly Meeting.
I was silent in the forepart.
J. E. had a lively testimony; but the Gurneyites being rulers in that meeting,
and having both the clerks, they did not record his attendance as acceptable.
Towards the latter part of the women's meeting,
I found it right to revive the language of Esau,
which had been uppermost with me nearly ever
since taking my seat in the meeting--"`Bless me,
even me, oh, my Father!`"
I told them that I had feared, and greatly feared,
that there were those present whose situation resembled Esau's,
who were crying out for the blessing, but who had not regarded their birthright;
but when that nature which was appointed to die, was in great distress and hunger;
they had for something to satisfy this, sold their birthright,
and were now charging their leanness and distress to
others who were not the cause thereof.
That it would be well for such to recur, and return to first principles,
lest the day come when this would be the language of
their hearts--"`The harvest is passed,
the summer is ended and we are not saved.`"
Dined at Robert Miller's, and after dinner started for home,
and rode nineteen miles to Harlem--nine miles after night.
Next evening, reached home in as good health as when we started,
having been just three weeks out on this visit.
