== Chapter VI

[.chapter-synopsis]
* A Religious Visit to Pennsville Quarter and its Branches, and Many Families
* Her Testimony Against Music
* A Religious Visit to Stillwater Quarter and its Branches, and Some Families, Accompanied by Close Exercises
* Visits Meetings about Home, and Appoints some Meetings Among Non-members
* Visited Families at Guernsey
* Again Visited Stillwater
* And also Performed Religious Service within the Limits of Short-creek Monthly Meeting
* Labor with Laban Mitchell against His Going to the Army
* And a Notice of His Death Soon After
* Labor and Appointment of Meetings at Guernsey

Eleventh Month 13th, 1859.--With a Minute of concurrence from our Monthly Meeting,
I set out on a visit to the meetings of Pennsville Quarterly Meeting;
the weather was very cold and stormy--as much so
as I ever travelled in--and my health being poor,
if faith had not been given me, I should have returned home after reaching Guernsey.
But believing the Master would take care of us (having
Isaac Mitchell and Rebecca Wright for companions),
we pursued our journey, and attended all the meetings in the limits of that quarter;
and appointed a Public Meeting at McConnelsville, a town on the Muskingum River.
It was large and favored.
Oh, the poverty and strippedness that I experienced on going to this meeting,
but such had been my exercises before giving up to appoint it,
that I felt willing to become a fool,
or anything that the Lord might permit for the sake of peace.
And He was to me mouth and wisdom, tongue and utterance,
and a present help in time of need.

The people were quiet, sober and attentive,
and I thought truth triumphed over all opposition, blessed be the name of the Lord.
But to return,
in the Women`'s Quarterly Meeting I was constrained to revive the
language of the prophet Jeremiah contained in the ninth chapter,
beginning with the seventeenth verse and ending with the twenty-fourth.
I thought some wondered that I should thus speak, but believing it required of me,
I endeavored to be faithful.

On the 21st, appointed a Meeting for the young people at Pennsville,
but notice being extended beyond my request, it was very large;
and not keeping close to my Guide, I stopped short in my supplication,
and arose from my knees before the right time, which brought great confusion,
and distress upon me, and the meeting did not end satisfactorily to myself or to others,
as I have cause to believe.
The Lord is a jealous God; jealous of his honor, He will not give his glory to another,
or his praise to graven images,
no matter how much or how highly we may have been favored heretofore,
if we swerve from faithfully following the true Shepherd we
will find nothing but confusion and perplexity.
My sufferings after this meeting were indescribable,
but in the Lord`'s own time He spoke peace to my soul and raised me up
from the low dungeon into which I was for a time permitted to sink.
I waited patiently upon the Lord and He heard my
cry and spoke peace to my greatly troubled soul.
Appointed a meeting at Chesterfield for the young people which I thought a favored one.
The last meeting we attended in this quarter was at Pennsville on our return home,
and I might say Truth reigned over all.
I had been brought very low since being there before,
and now desired that whatever the Lord required of me I might
perform without turning to the right hand or the left.
I told them in this meeting, that they had a covering spread over,
in imitation of the pure white linen--the righteousness of the
saints--but it was nothing better than paper muslin,
nothing that would stand the storm; that the first man is of the earth, earthly,
the second man is the Lord from heaven.

That as we have borne the image of the earthly, we must,
if we would be the followers of the Lamb, bear the image of the heavenly.

I had to allude to deism and universalism, and class them together,
and speak plain truths to those who were tinctured with this doctrine.
I afterwards found there was one young man (and how many more I know not) present,
whose associates when at home were of this class.
I told them that however hard it was for me to speak, or them to listen,
I must be faithful and deliver the whole counsel of the Lord.
After meeting, Friends spoke very kindly to me, and some with tears in their eyes,
who before had been shy and distant.
But I could appeal to the Searcher of hearts, that it was his honor I sought,
and not my own, and so my reward was peace.
In this visit within the limits of this Quarterly Meeting,
I was astonished to behold such wholesale departure from Christian
simplicity as was apparent in the dress of the young people.
Surely the Lord`'s judgments are near to come,
and I had to tell them that the Lord would not be mocked;
that the testimonies for which our worthy predecessors suffered imprisonment and death,
many were now trampling under their feet.
The children of the kingdom,
if they continue to slight the offers of redeeming love to their souls,
will be cast out and others called in to take their places.
Oh, the grievous departures from Christian simplicity!
What will we not have to suffer before we are brought back upon ancient ground.

Started for Stillwater on the 27th and arrived there the 29th,
in time to attend the Select Meeting; and the day following,
Stillwater Quarterly Meeting, but had nothing to communicate.
Next day returned home.

Some things I have omitted to mention in their proper places,
which occurred during this visit, namely: calling at a Friend`'s house in Chesterfield,
I inquired for the children, having been previously invited to come;
and also having my mind impressed with a belief,
that it would be right for me to go. The mother
informed me that some of the children were at school,
some from home, and two at home;
one of whom was busily engaged preparing to leave home the next day to teach school.
Having given them to expect I would be there that afternoon,
I again made some allusion to the children`'s absence.
The mother replied (rather pettishly, I thought) that those who were at home,
one was busily engaged packing her trunk to leave home, and the other was sick in bed.
After a while one came in and sat down;
it occurred to my mind that I should not be clear, without seeing the daughter,
who they said was sick in bed.
So I proposed going to her room, her sister leading the way.
I met her at the head of the stairs, and told her, that however she might hide from man,
she could not hide from God.
I warned her to take heed to her ways, and ponder the paths of her feet.
Not to set light by our Christian principles and testimonies;
to avoid pernicious company and pernicious reading.
Her sister wept much.
I told them in the words of the poet,
"`That with the talents of an angel a man may be a fool.`"
They were talented young women.
I said, I am unacquainted with your course of conduct;
but I felt constrained to admonish them,
and exhort them to walk in the fear and counsel of the Lord,
and not to be stumbling-blocks, and bring a reproach upon the Truth.
Then we went down-stairs, where I had left their parents and my companions.
But now comes another failure of mine in not
delivering the whole counsel to their parents,
though I said considerable by way of counsel and advice,
encouraging them to discharge their duty faithfully towards their children,
yet for hastening away and keeping back a part which belonged to them,
my reward was not that peace which I desired.
The Friend who accompanied us here,
seeming to be uneasy and wishing to go sooner than I felt fully clear,
informed us afterwards that she was afraid the family would
think that she had been telling us how it was with them.
The daughter, who was said to be in bed when we went, was, or had been,
under the care of the overseers, for attending balls and places of diversion,
and very much gone out in her dress and conduct from a consistent walking with Friends;
and others of the children not far, if any, behind her.
Oh the poor parents!
One an overseer, and the other a minister.
The latter, once a promising plant, and bid fair to make a pillar in the Lord`'s house;
the daughter of an eminent minister of the gospel in our Society.
May the Lord turn his hand upon her, and purge away the dross,
and take away the film from her spiritual eyes, says my soul.

On our way from Pennsville to Stillwater, we called at a private house to stay all night.
The family consisted of the father and mother, and two interesting little girls.
After supper, while I was talking with one of the children,
the mother asked me if I would not like to hear
her (the child) play on an instrument of music.
I replied, No!
I had no desire for such a thing.
Then she asked if I would not like to see the instrument itself.
I said, No! telling her at the same time,
that I believed our time was given us for a better purpose than to spend in such an idle,
vain and useless way.
She then asked if I did not like to hear singing.
I replied in the negative, explaining my views upon the subject.
Her husband then coming in, and being apprised of our conversation,
looked at me with some astonishment, and said,
"`We had a Quaker with us a short time ago,
who was very much gratified in hearing our little daughter play on the dulcimer.`"
My companion replied, "`He was not a consistent member of our Society.`"
"`Oh, yes!`" said the man,
"`he was an old gentleman in good standing,`" or to this import.
In the morning, before leaving,
I embraced the opportunity of relieving my mind concerning the
responsibility resting upon them as parents,
to endeavor to train up their children in the nurture and admonition of the Lord,
and not to feed or gratify a vain mind in themselves, or their children.
They heard and received what I said with marked attention and respect,
and we parted with them in a very friendly way.
I then went on my way rejoicing.
Far different were my feelings on reflecting upon this little occurrence,
than if I had shrunk from apprehended duty;
and that day I realized what the Master told me,
when I was doubting and questioning about appointing
two meetings in the limits of Pennsville Quarter,
thinking the weather might turn cold, and the roads become more difficult,
and our time be too limited to reach Stillwater Quarter.
As I was pondering these things in my mind and reasoning thereon,
suddenly the language sounded in the ear of my soul,
"`Are not the winds and weather in my hand,
and the way too? be obedient and all will be well.`"
I was hushed into silence and doubted no more.
And now more beautiful weather, or a more pleasant day,
or better roads than we were then travelling, the 28th of the Eleventh Month,
is not often met with in this section of country, at any season of the year.
So I find it is good to trust in the Lord at all times and in the greatest strait.

Sixth Month 9th,
1860.--I have just returned from a religious visit to the
meetings within the limits of Stillwater Quarterly Meeting,
having been from home about two weeks, during which,
I have had some very close conflicts.
Under the weight thereof it sometimes seemed that I could scarcely live;
but the good Master helped me through.
Stillwater Monthly Meeting was the first attended in which I was silent.
After meeting, I requested the select members to stop.
I spread a concern before them to appoint a meeting next day at the
place for the young people and children belonging to that meeting;
which was fully united with,
and appointed to be held the next afternoon at three o`'clock.
Next day attended Stillwater Meeting in the forenoon and was silent therein.
The afternoon meeting was well attended, and I had considerable service,
in a good degree to the relief of my mind.
Next day, the 28th of Fifth Month, attended Somerset Monthly Meeting, held at the Ridge;
in which my mouth was opened, to speak to a tried state, or states,
who were almost ready to distrust the superintending care and providence of Almighty God;
because of the flood the Dragon is permitted to cast
out of his mouth to destroy the living in Israel.
My heart was enlarged in the love of the Gospel, to speak of the goodness,
greatness and omnipotence of the Lord`'s power, which is over and above every other power,
and will ever remain to be--blessed be his name forever.

29th.--Attended the Select Quarterly Meeting and was silent therein.
After meeting, laid before the Select members a concern that had long rested with me,
to appoint a public meeting in the town of Barnesville, which was united with,
and the subject left with me, and a few Friends, to attend to it when the way opens.

30th.--Attended Stillwater Quarterly Meeting, which was very large,
many from other parts of the Yearly Meeting being present,
it being the first time of holding the Meeting for Sufferings at that place.
Y+++.+++ W. spoke in the public meeting--also my cousin, Asa Branson; I was silent.
When the business was nearly through,
I informed women Friends that I felt a concern to have the shutters opened,
and see men and women Friends together; which was united with by men and women Friends.
But before I yielded to this requisition of duty,
I felt that hard things would be given me to speak, if anything was required;
that I said in my heart: Lord, I cannot yield;
it were better for me to die than to live to be a by-word, a taunt and a ridicule;
a song in the mouth of the vain and licentious;
a derision to those who profess the Truth, but possess it not.
Then came a great cloud of darkness over me,
so that I felt the Lord`'s displeasure had been kindled towards me,
and I knew not what to do. After some time the spirit of supplication was given me,
and I said, "`Lord, here I am. Do with me as seems unto you good; require what you will,
only take not your Holy Spirit from me. I will endeavor
to be obedient and deliver the whole counsel.`"
Then the concern revived, and I spread it before Friends.
After the shutters were opened, I stood up with these words:
"`Are there those present who are saying in their hearts, as some formerly said,
'`Prophesy unto us smooth things,
prophesy deceits;`' I cannot prophesy unto you smooth things,
I cannot prophesy unto you deceits, for I believe there is a terrible day approaching,
when all the false resting-places will and must be broken up;
when the hail will sweep away the refuge of lies
and the waters overflow the hiding-places.
That however any might be making their nest among the stars,
exalting themselves very high, yet if their foundation was not upon the rock,
Christ Jesus, they must come down.`"
I remembered the Word of the Lord, through the mouth of his prophet,
"`I judge between cattle and cattle, between the rams and the he-goats.
Does it seem a small thing unto you to have eaten up the good
pasture? but you must tread down with your feet the residue of
your pastures? and to have drunk of the deep waters,
but you must foul the residue with your feet? And as for my flock,
they eat that which you have trodden with your feet,
and they drink that which you have fouled with your feet.
Because you have thrust with side and with shoulder,
and pushed all the diseased with your horns, till you have scattered them abroad;
therefore will I save my flock, and they shall no more be a prey;
and I will judge between cattle and cattle.
I will feed my flock, and I will cause them to lie down, says the Lord God.
I will seek that which was lost, and bring again that which was driven away,
and will bind up that which was broken, and will strengthen that which was sick;
but I will destroy the fat and the strong; I will feed them with judgment.
As a shepherd seeks out his flock in the day
that he is among his sheep that are scattered;
so will I seek out my sheep,
and will deliver them out of all places where they have
been scattered in the cloudy and dark day.`"
However any might be comparable to Balaam, trying to please God and man,
they would be disappointed.
In vain did Balaam ascend the altars which Balak had reared by his direction and cry out,
"`How goodly are your tents, O Jacob, and your tabernacles, O Israel!`"
Let me die the death of the righteous, and let my last end be like his!
But Balaam having followed the wages of unrighteousness,
being double-eyed and double-minded, trying to please God and man,
he was rejected by both.
"`Flee you to your place,`" said Balak; "`I thought to promote you unto great honor;
but lo,
the Lord has kept you back from honor;`" and as
Balaam was found slain in the enemy`'s camp,
so will it prove with all those who are trying to please God and man:
the Lord will keep them back from honor.
After this meeting, I felt satisfied that I had yielded to apprehended duty,
and my mind was relieved of a burden in some degree.

31st.--Attended Sunsbury Meeting, held by appointment to pretty good satisfaction.

Sixth Month 1st.--Attended Richland Meeting, and was largely engaged therein,
to my own peace, and hope in some degree to the profit of others.
The subject of appointing a meeting at Sailsville,
a little village five miles from Richland, pressing heavily upon me,
I consulted some Friends about it, and having their concurrence and unity,
the meeting was appointed and held in the afternoon the 2nd of this month.
It proved a close, exercising time.
I had to warn the wicked, to turn from his wicked way and live.
The drunkard,
the intemperate and careless professor were solemnly
warned not to linger on the brink of a precipice.
Rode to Stillwater, ten miles, and put up at Robert Smith`'s, and this evening,
while sitting in their parlor with my companion, a song of praise,
accompanied with a holy solemnity, flowed through my heart; so that I could say.
Lord, it is enough, at which time this language of our Savior revived in my mind,
"`With desire I have desired to eat this passover with you before I suffer.`"

3rd.--Attended Stillwater Meeting in the forenoon,
and had some encouragement to the rightly exercised,
and tribulated ones among the youth, and those more advanced;
and felt peaceful as to what I had delivered,
but felt a great weight pressing upon me in regard to
the meeting to be held this afternoon in Barnesville,
which we attended; and it proved, as I expected, a laborious exercising time;
insomuch that it seemed to me that the obstacles thrown in the way,
would almost entirely stop the current, or circulation of life.
It was largely attended, and they generally behaved well.
As ability was afforded, I endeavored to relieve my mind among them;
but felt after meeting very low and depressed in spirit, and weak in body.
Such meetings are often very exercising to me,
perhaps partly owing to the great anxiety I feel,
that the Truth may not suffer by my omission or commission; for truly I have said, Lord,
I have no qualification for such a service.
But the answer has been, If you refuse to warn the people when I bid you,
their blood will I require at your hands;
and on no other ground have I dared to appoint meetings from among Friends,
but from a sense of duty like unto this.
The meeting had been on my mind for several years.
I had to deal plainly with professor and profane,
and must leave the result to Him who I apprehend
required the surrender of my will herein.

4th.--Visited several families in town.

5th.--Visited some families among whom a difficulty
and difference had arisen relative to temporal affairs.
I exhorted them to Christian love and forbearance,
believing where the Spirit of Christ is,
no hard or censorious feelings can rest in our hearts against any one,
much less a feeling of enmity and jealousy against a brother, sister, father or mother.
I had to deal very plainly with these families,
without entering into the subject matter of difficulty,
warning them against hard feelings and hard reflections,
and hope the Truth did not suffer.
All the families treated us respectfully, cast no reflections upon one another,
which was a satisfaction to my mind,
for I had felt very anxious to be preserved from saying
or doing anything to make matters worse among them,
remembering the words of Solomon: "`He that meddles with strife, belonging not to him,
is like one that takes a dog by the ears.`"

6th.--Attended Stillwater Meeting, in which I had a close, searching testimony,
exhorting them to examine their daily walk and conduct, bringing into view,
that the beasts which under the Mosaic law were
considered fit for the children of Israel to eat,
were those that chewed the cud and divided the hoof;
the one was not sufficient without the other.
So, under the Gospel dispensation,
the precept and example of professing Christians must be good,
and such as the Lord approves, or they will not be fit examples to follow;
for while any are drawing near unto the Lord with their mouths,
and their hearts far from Him, their example contradicting their precepts,
this is like chewing the cud without dividing the hoof; the track of the foot,
as well as the operations of the mouth, are to be taken into the account.
A mere nominal profession will not do. The lights of
such as these will be like a candle put under a bushel,
or under a bed.

[verse]
____
A bushel, the emblem of worldly gain,
A bed, where the sluggard delights to remain.
____

I told them that I believed some were buried, as it were, in the earth.
Some were pursuing the pleasures and pastimes of the world;
and others were sleeping in an unconcerned condition,
thinking to have some plausible excuse (when the time of
reckoning comes) for not having occupied their talents aright,
but such will fare no better than the man spoken of in the parable,
who was found among the wedding guests, without the wedding garment.
But what was said to the man who thus intruded?`" Friend,
how did you come in here without a wedding garment?`" And he was speechless.
"`Bind him hand and foot, and cast him into outer darkness;
there shall be weeping and gnashing of teeth.`"
The kingdom of God is preached,
and every man presses into it. How do they press
into it? Some with a false hope and a dead faith,
thinking to be reckoned with the wedding guests,
without the wedding garment--without a change of raiment,
with the old nature which is corrupt, with the filthy rags of their own righteousness;
they presume to number themselves with those who are prepared to
partake of the marriage feast--the signal of Divine and lasting favor
in the presence of the great God and his servants forever.
It seemed to me that there were some there sleeping almost the sleep of death,
who needed to be awakened,
who had the smell of tobacco as well as the smell of
fire upon their garments and round about their houses;
and I doubted if the prophet Ezekiel were there and to stamp with his foot,
whether it would wake them up. The language to such was,
"`Awake to righteousness and sin not, for some have fallen asleep.`"

In the afternoon made a visit to _______ and wife.
In that opportunity I had to tell that I did believe that unless he
humbled himself and came down to the footstool of his Divine Master,
that the time would come, if he pursued the course he is now pursuing,
that he would find himself situated as Absalom,
left without any help from above or beneath.
The mule went away from under Absalom, and left him hanging between earth and heaven,
without any support from either.
I told him that I believed he was giving his strength to the Philistines,
and the consequences would be serious and awful if it continued thus.
I felt reluctant thus to express myself to him,
feeling nothing in my heart towards him but the love of the gospel,
and I would gladly have left him without saying what I did,
could I have felt peace without.
Much plain talk passed between us relative to
the trying condition of our religious Society,
on account of the great departure from our principles and testimonies
on the part of many of our members in the foremost ranks,
in various places.
And I think it may be the last conversation between us on that subject,
as I told him I had not unity with him,
and that it was only from a sense of duty that I felt at liberty to visit him.
But my heart yearns with inexpressible solicitude for his welfare.

7th.--After a religious opportunity in Robert Smith`'s family,
I felt at liberty to return home.

Seventh Month 7th.--My spirit is low and depressed;
I have to wade through much discouragement, being in very poor health as to the body,
and no strength of mind only as the Lord helps me. Oh,
that I was more what He would have me to be. Two weeks
ago I appointed three meetings from among Friends,
and have felt well satisfied in attending to this opening and requirement of duty.
Truly I can say, the Lord strengthened me in a wonderful manner at Tippecanoe;
a place where I had long felt a concern to appoint a meeting.
It was very large, and the Lord gave me strength of body and mind,
to declare the gospel of life and salvation to the people,
to my own relief and admiration, and I trust the truth did not suffer.

10th.--I feel much weighed down in spirit; may the Lord be waited upon.
Oh, Lord, I am unworthy of your help and counsel; be pleased, I pray you,
to order my steps aright, now that I am in a great strait,
having a weight of exercise and concern on my spirit.
Lord help me, for vain is the help of man.
Some trust in chariots and some in horses, but we will trust in the Lord our God.

Eighth Month 31st.--I was induced by what I apprehended my religious
duty to apply to the Presbyterians about four miles from this place
(Flushing) to hold a religious meeting among them.
After granting the liberty, they held another consultation,
and authorized their minister to let the Friends know, who made the application,
that it was contrary to their doctrine and practice for a woman to speak in the church,
and therefore they could not without marring the peace and harmony among themselves,
grant the request.
When I first received this last conclusion,
I felt a kind of secret rejoicing which perhaps the Truth did not own;
for I thought if I could be released from them in this way, it would be a favor;
but this language presently ran through my mind:
Would you rejoice in their wrong judgment and conclusion? So I
have thought there was much self in their release,
and also in my secret rejoicing.

Ninth Month 2nd.--Appointed a meeting in the village of Flushing for
the inhabitants thereof and the neighborhood around.
It was held to pretty good satisfaction.
If the people knew what it cost me to appoint such meetings,
they could not suppose that it was from anything short of preserving my spiritual life;
for though it be against my will, yet, nevertheless,
a dispensation of the gospel is committed unto me, yes,
woe is me if I preach not the gospel.
My cousin Asa Branson was engaged in the ministry at this meeting,
and I believe to good satisfaction.
Oh, that he may be preserved on the right foundation.

How many of the visited and gifted sons and daughters have been turned,
and are turning aside at the cry--Lo here, or lo there is Christ,
seeking an easier way to the kingdom of heaven than by the way of the cross.
Having begun in the spirit they seek to be made perfect by the flesh,
and hence become vessels marred on the wheel, instead of standing with their loins girt,
and their feet in the bottom of Jordan,
with the ark of the testimony resting on their
shoulders until the people be clean passed over;
or in other words, until the expectation of the people is turned away from them.
Oh, the incalculable mischief that has been done in our
Society of latter years by a superficial ministry.
Lord help and preserve those who still remain on the right foundation,
that stones of memorial may be brought up from the bottom of Jordan,
showing your marvelous dealings with your people who serve you in singleness of heart.
Amen, says my soul.

Ninth Month 14th.--Perhaps few, if any, know the hidden conflicts of my spirit.
Oh, that my faith may be renewed and increased a little in the Lord,
in whom only there is strength.
Lord increase my faith in you, the only and alone sure helper,
and guide your people with wisdom.

It is now nearly a year since I obtained a Minute from my Monthly Meeting,
for religious service among Friends and others;
and as my health has permitted and way opened in the Truth,
I have not put off any duty knowingly required of me, yet some may think I am loitering.

Tenth Month 6th.--This day commenced the Select Yearly Meeting for ministers and elders.
Oh, may my Urim and Thummim be with the Holy One.
My spirit is bowed under awful considerations.
Lord assist me, I beseech you, and enable me to do your holy will.
Great indeed is the effort of the Adversary to make us
believe we are in a better situation than we really are.
Oh Lord! undeceive us before it be too late, that we fall not a prey to the cruel Enemy.
My soul is exceedingly sorrowful,
under an apprehension that we shall yet have to be sifted as from sieve to sieve,
notwithstanding all we have heretofore passed through.
Oh, hasten the time when Mystery Babylon shall cease
among us to mimic the true gospel power,
life, light and truth; when the solemnity that prevails shall be the true solemnity,
and not a false representation of the true.
When the words spoken shall have the substance, the life,
melting into tenderness the humble contrite heart, evincing the truth as it is in Jesus.
Oh Lord! you only know the depths of Satan,
and you only can open our eyes and instruct our spiritual
understandings to count the number of the beast;
and his number is limited.
For you surely gave your Apostle John to see that it is the number of a man,
and that his number is limited; so that by your might and your power he may be overcome.
Glory to your name.

25th.--Returned the Minute to the Monthly Meeting, granted me one year ago;
and felt thankful that I had not been permitted, or prevailed upon by human weakness,
to return it sooner.

In the forepart of the meeting today, I felt constrained to revive this language--"`Oh,
that you had hearkened to my commandments! then had your peace been as a river,
and your righteousness as the waves of the sea;`" expressing my belief,
that as we bow to the will of the Lord in all things manifested to be required,
He will fill the soul with good things, giving strength and ability to praise,
glorify and magnify his great and adorable name, who created the heavens and the earth,
the seas and the fountains of waters.
After saying considerable in this way, I felt peaceful and easy.
At this meeting,
I requested liberty to appoint some more meetings
among those not in membership with us,
and to visit the meetings belonging to our own Quarterly Meeting.
Also to visit some families and individuals among Friends and others;
which was united with by the meeting,
and liberty given to perform the service as Truth may open the way.

Eleventh Month 17th.--The Quarterly Meeting endorsed my
Minute for the service above mentioned;
and my prospect then seemed to be to proceed pretty directly to appoint some meetings;
but from some cause the clouds seem gathering and resting on my tabernacle;
and the way closing up for moving immediately in the service.
If it should altogether close up, and the will be taken for the deed,
I trust that I shall be enabled to see and know and do the Master`'s will herein.
I am beginning to think some proving exercise awaits me,
separate and apart from this service.
Lord! enable me, I beseech you, to lay aside my own will in all things,
so that I can say, not as I will but as you will.
You have often been with me to my humble admiration,
and to the filling of my heart with praise.
Now, if you see fit to hide your face from me, and to prove me as in the deeps,
I most ardently pray you to keep my tongue from sinning against you,
and my feet from pursuing any other course than that marked out by you.

Oh, you fountain, light, life, grace and truth; you who did beget me into a lively,
living and glorious hope of eternal salvation, through your dear Son,
the Lord Jesus Christ, when I was without life, light, or truth in my inner parts.
You who saw me and had compassion on me when I was destitute,
and had none in heaven or in earth to look to but you.
You who saw me in my blood,
and spread your skirt of love over me. You who washed me with pure water,
and put bracelets upon my hands, and shoes upon my feet; who said unto me live,
when life and hope were almost extinct.
You who did magnify your power in that you did raise me up,
and gave me spiritual and natural life,
when both seemed alike departing from me. You
who have done for me what none other could do;
forsake me not.
Oh, you Holy One! but enable me to bear whatever you
may permit to come upon me for my own refinement,
or for the sake of others.
I think you have a deep baptism, or baptisms,
for me to pass through before entering on this service; therefore I pray you,
so to order it, that I may keep the faith and the patience,
and not cast away my shield as though it had not been anointed with holy oil,
for I have seen your wonders in the deep, and known that you can do all things well.
Amen and amen.
Twelfth Month 28th.--I am now at Guernsey, where I have been more than a week;
most of the time as a close prisoner; but I feel content and resigned to my allotment,
greatly craving that I may be kept in my right place.
Oh, Lord! all that I ask is, that you will keep me in the place you designs for me,
even if it be to walk through fire, or water.
I have visited a few families,
appointed a meeting for the young and youngish people and children in this neighborhood;
had also a religious opportunity with a young man, greatly to the relief of my mind.
I warned him in an especial manner not to listen to the doctrine of infidelity, atheism,
or universalism.
I had to use language which was very trying to utter,
but I told him as I knew nothing about his company or
course of conduct (his home being in Iowa),
I wanted him to receive what I said in the way it was intended--in gospel love.
He afterwards acknowledged that most of his associates when at home, were universalists:
that what I felt and said on that subject was right.
And I think he parted with us under a feeling of conviction and tenderness.
May it never be forgotten, says my soul.
I have had to deliver some plain truths to individuals,
without using any kind of a plaster to make them set more easy than the Master chooses;
but feel that the hardest is yet to come.

When all has to be given up for the blessed Truth`'s sake,
then we sometimes feel what it is to be separated from those,
who before had been very friendly,
and even fawning towards us. Job`'s integrity was put to the test more ways than one.
When Satan determined to overthrow his faith in God,
he left no stone unturned that he could possibly move to upset Job; but God kept him.

Oh, you fountain of all our sure mercies! will you keep me when nothing but trouble,
disappointment, and affliction, both within and without,
are the things permitted to come upon me? Do you be
graciously pleased to bear me up until my change come,
and my cup of suffering be drank, that I may praise you on the banks of deliverance.

First Month 2nd, 1861.--Yesterday,
visited several families not members of our religious Society,
wherein I had close and searching work, to the relief of my mind;
also felt it required of me to go into a merchant`'s store-room,
where a number of men were gathered,
and declare the gospel of life and salvation among them.
After which, I felt the reward of sweet peace in a good degree;
but because of the bonds and afflictions that await me,
my rejoicing is of short duration.
Nevertheless I have felt, and particularly yesterday, after yielding to apprehended duty,
the force of this language and the truth thereof--"`They who minister about holy things,
live of the things of the temple;
and they who wait at the altar are partakers with the altar,
even so has the Lord ordained that they who
preach the gospel should live of the gospel.`"
Under the Mosaic dispensation the priests were allowed their portion,
or what was left of the meat, after offering a burnt offering,
and were to eat with unleavened bread before the altar.
Oh, the beauty, the dignity, the excellency of the gospel dispensation,
as typified under the law of Moses.
How my soul admires, and my heart adores,
that power that broke through that long night of apostacy
after the ushering in of the gospel dispensation,
and gave our worthy predecessors to see in the
glorious light of the Son of righteousness,
the transcendent beauty, excellency and dignity of the gospel dispensation,
when compared with the types, shadows and ceremonies of the law,
and how we are required to rally to the standard of primitive Christianity;
for ancient Quakerism is nothing more nor less than primitive Christianity revived.
Oh, Lord!
I am exceedingly distressed, undertake for me,
for I have none to look unto but you for help.
I pray you ease my burden,
by giving me light and strength to obey your Divine requirements;
even if it be again to go among the gainsaying
and rebellious--the mockers and scoffers;
and those that pluck off the hair and spit in the face.

Have visited several families not members among Friends,
in which I had to declare the day of the Lord`'s
power upon all that is high and lifted up;
upon all the oaks of Bashan, upon all the cedars of Lebanon.
Oh, how gracious has my heavenly Father been in leading me about and instructing me.

Sixth-day, the 4th, visited a district school.
I had to address a young man, in a close, warning manner, to return from his wicked way,
and live.
I afterwards learned he was a profligate character.
I left the school-house with a heavy heart,
under a sense that there were those in that district, or section of country,
who were the agents of Satan to lead others astray.
I soon found I must appoint a Meeting for Worship in this place;
which was held on the 5th, at three o`'clock in the afternoon, in the same school-house.
The meeting was small, but I have no doubt such were there as I was required to see;
for truly, I have rarely, if ever,
met with so many open and barefaced gainsayers in so small a company;
and mostly young people.
But I had to deal plainly with them; warning them of the evil of their ways,
and the consequences which must result therefrom,
if they continued in their downward and pernicious course;
telling them that the day would come if they did not turn unto the Lord,
that He would laugh at their calamity, and mock when their fear comes.
Sometimes their countenances would fall in spite
of all their striving against conviction,
showing that the heart was smitten; then they would rally,
and muster all their force to put it from them.
I cleared my conscience towards them,
and encouraged the few sober ones to walk in the right path,
without turning in with the gay, licentious scoffers of this day.
After addressing the throne of Grace on behalf of both classes,
I felt clear and easy to leave them,
and truly thankful that I had given up to appoint this meeting.

9th.--Attended Guernsey Meeting;
several strangers were present who do not commonly attend.
Again I had to sound the warning voice to some of them, who,
notwithstanding they have again and again been invited to
enter into the vineyard of their own hearts and labor,
are putting off the work of their soul`'s salvation, until wisdom,
to use the words of the poet, is pushed out of life, or nearly so;
telling them not to dally and linger,
lest the door of mercy be forever closed against them.
Though I spoke under much bodily weakness, yet I believe the Truth required,
and owned my service, and I felt peaceful and easy after meeting.
Lord be pleased to keep me in my right place.
I feel that snares surround me, and that bonds and afflictions abide me,
from which none but your holy hand can rescue me.

23rd.--Returned from Guernsey, where I remained five weeks, visiting families,
individuals, schools, etc., as way opened and my health admitted;
also attended that meeting regularly as it came in course.
Had not the Lord been on my side I should have fainted;
such repulses in a meeting of Friends I never before remember to have felt,
for nothing openly occurred to show what was the cause;
but I felt those smitings that were harder to bear than open opposition or persecution.
But I was favored to relieve my mind among them, at least in a considerable degree.
I made forty-nine family visits in that neighborhood,
including several families among those who have separated
from us. Before leaving this account of my visit to Guernsey,
I think is right to say, that on one occasion,
after making a family visit where I had delivered what appeared required of me,
both to parents and children, and had left the house;
this language ran through my mind--"`You must go back
to _____;`" it filled me with fear and trembling,
and I queried why? I have said all that I
thought was required of me. But the language was,
"`you must go back; you did not get to the root of the matter;
you did not get to the bottom.`"
Then I felt that there were some hard feelings
crept into the hearts of some of the family.
But what great fear possessed my heart, lest I should be mistaken.
So after trying the fleece both wet and dry, before mentioning my feelings to any one;
and finding I could not return home with peace of mind without going back;
in the little faith and hope which is ever safe to follow,
I mentioned to my companions my concern to return to this family, which we did;
requesting none but the parents and a young woman who lived with them to be present.
I then plainly told them how it had been with me, since being there before;
telling them if I was mistaken in my feelings, I hoped they would pass it by,
and I would try to be more careful in future, at the same time remarking,
that there was a secret language in my heart which said, you have not got to the root,
there is a secret hardness against some which is not rooted out;
but it was in great fear and trembling, lest I should be mistaken;
but after fully clearing myself, I felt easy to leave; and when about to bid farewell,
the individual (where it seemed to me the testimony belonged), with tears,
and in much brokenness of spirit, said to me--"`I am glad you came.`"
I said in my heart it is enough;
Lord take away from me that fearful spirit which had
nearly prevented me from doing your blessed will.
For, truly,
I felt it a great matter to go and charge any with
having feelings against a friend or neighbor.

Second Month 9th.--It has presented to the view of my mind,
to leave a short account of what I saw and felt on a sick bed,
the 26th of the Tenth Month, 1833. On the morning of this day,
I felt a great cloud of darkness come over the land.
It was so great, that it was plainly to be felt, like Egyptian darkness;
such a feeling as I never before experienced.
It was a sore exercise to my mind, and I saw that Friends had need to turn unto the Lord,
for this language sounded in the ear of my soul: "`Friends everywhere turn unto the Lord;
revive the ancient testimonies.`"
Then I requested a pen and paper, that I might write it down, which I did;
and I requested that if I did not recover from that illness, that this short exhortation,
above given, might be inserted in The Friend,
for I saw that our Society was in a low condition,
and had need to repair the broken down walls; or, in other words,
to revive the ancient testimonies.
Then I exhorted Friends to stand faithful to our principles and testimonies,
and like Nehemiah, to labor to remove the stones out of the rubbish.
Little did I then think that I should live to see such a great departure
from the principles and testimonies of our religious Society,
by those professing the name of Friends, as I have seen of latter years.
But I fully believe the Most High God will raise up others to take the places of
those among us who are the backsliding and backslidden sons and daughters,
and who will be willing to suffer; yes,
they will rejoice that they are accounted worthy to
suffer for the very principles and testimonies,
that many under our name are trampling under foot.
Yes, the time will come, though I do not expect to live to see it,
that from the highways and hedges,
there will be living monuments and living witnesses brought into the garden enclosed,
taking the places and the crowns and diadems of beauty
from those who have forsaken their first love.
I believe, as dear Mildred Ratcliffe said to me, not long before her death,
"`If there is one more vial of wrath to be poured out
upon any one religious Society more than another,
it will be upon the Society of Friends,
or those who forsake the principles and testimonies thereof.`"

Oh, Lord, I beseech you, whatever you may permit me to suffer,
or pass through for your name`'s sake, preserve me from casting away my confidence in you,
or becoming a prey to the wiles of Satan.
Amen.

11th.--My soul is exceedingly sorrowful.
Lord, have mercy upon me.

Fourth Month 12th.--Returned from a little visit within
the limits of Stillwater Quarterly Meeting.
Appointed two meetings among those not in membership with us,
and visited several families; also attended Ridge Meeting yesterday,
but for not minding my steps on the way home, I have had to suffer much.
While out on this visit, on passing through a little village near Sunsbury,
coming opposite a blacksmith`'s shop, this language ran through my mind:
"`Stop at the proper point,`" and it seemed required of
me to stop and go in. It was snowing fast,
and I gave way to reasoning, and suffered myself to go on,
without mentioning the subject to my companions; but before we got far,
my burden increased so much, that I told my companions how it was with me,
and that I had a great load upon my spirit.
They proposed that we should go back, which we did in the evening.
After dining at J. L`'s we had a religious opportunity with the family.
Oh, the sorrow and distress that came over my spirit on account of some of the children,
but I endeavored to clear myself, and leave all to the Master.
We then went to the blacksmith`'s shop, where we stopped and went in; saw the proprietor,
with a number of others, who collected in when they heard the sound of my voice;
for I had to declare unto them the Gospel of life and salvation,
exhorting them not to spend their time in lightness,
irreverence and forgetfulness of God.
I had considerable to communicate to the owner of the shop and those assembled,
both male and female.
Then left them with a peaceful mind,
very different compared with my feelings when I passed by this place.
Oh! what can be compared to a wounded spirit; but being blindfolded,
and required to trust wholly to the leadings of my good Master,
how J have had to rejoice when I have yielded perfect obedience thereto.
But not always being willing enough to walk by faith,
my heart is pained on account thereof,
and I fear I shall never become that obedient servant that the Lord would have me
to be. Were it not that I can now lift up my eyes upon the brazen serpent,
like unto the children of Israel in the wilderness, when they were bitten by serpents,
I should sink and despair; or, in other words,
hoping on the mercy of God through Christ Jesus, who takes away the sin of the world,
I am kept from sinking below hope;
for the enemy has injected his poison and induced me by his
subtlety to return home before the Master fully liberated me,
thus spoiling my peace, and causing great distress of mind.
And I can say, Lord, have mercy upon me, a sinner; encamp round about me,
and keep me from the sin of omission and commission.

30th.--My mind is greatly oppressed.
Oh Lord, undertake for me, and show me if it be your will the cause of my great distress.

Fifth Month 5th.--Left home to meet with the boarding school committee;
also with a prospect of visiting the meetings and some
families within the limits of Short Creek Monthly Meeting.

6th.--Met with the school committee at Mt. Pleasant;
then back to N. Hall`'s at Harrisville, and feel no liberty to return home.

7th.--Visited two innkeepers and their families, in the town of Harrisville;
also had considerable to say by way of counsel, warning and encouragement,
in the bar-rooms at both places, several being present,
warning them to spend their time more to the
glory of God--to forsake the foolish practices,
pastimes and sinful pleasures in which many were engaged, and turn unto the Lord.
Great plainness of speech was given me to utter, at which they did not appear to mock.
Visited one other family (not members with us) of some note in the town,
but the cup is very bitter.
Lord, assist me, or I shall utterly fail of strength.

10th.--Still at Harrisville.
Oh, Lord! be pleased to look down upon me with compassionate regard,
for my soul is troubled.
Keep me, I beseech you, in the hollow of your holy hand,
for my sorrows are stirred within me. May I be kept faithful,
is all that I ask of my God, and not do, or leave undone,
anything contrary to his Divine will.
Yesterday had to attend their week-day meeting at this place with my apron on,
and such other attire as the Master required; without fixing, fashion or finery.
I said in my heart, Lord, if you deal thus with me,
it were better for me to die than to live;
but I had to wash and anoint rather than appear unto men to fast.
I feel that bonds and afflictions abide with me,
and am almost constantly reminded of the bread which Ezekiel was commended to bake,
and partake of it. That which is loathsome to myself and others I must
partake of. That which my soul refuses to touch has become my sorrowful meat.
Oh, that I may so dwell that nothing may hinder me from a faithful
fulfilment of all required of me. I must become a sign to others,
and some may have to remember it, when my head is laid in the grave;
had I known what would have been required of me before I came here,
I know not that I should have had strength to come;
but my bodily health is better than when I left home.

14th.--Yesterday my mind was much solemnized in
the little Select Preparative Meeting here,
which consists of only three members, two having recently moved away.
I said in my heart, Lord, you have all power, and can break the bonds and fetters,
and can cause the two-leaved gates to open whenever you will;
be pleased to keep me in my proper allotment,
and my soul was filled with a song of praise, but with this precaution:
"`Serve the Lord with fear and rejoice with trembling.`"
Last First-day, the 12th, and also in the mid-week meeting (at this place),
I had some service in the ministry, in some degree to the relief of my mind;
yet I feel that the watch must be strictly kept, to accomplish the remainder of service,
which may be allotted me here, to the honor of Truth.

25th.--If any one should ever see these lines, let me encourage such to trust in the Lord.
Great have been the conflicts of my spirit, insomuch that I have almost despaired of life.
But God, who quickens the dead,
has kept my head above the waves and billows hitherto--at
least so far as not to permit me to be totally overwhelmed.
I am still at Harrisville,
but think the way will before long open for removing to another place.
I have to pitch my tent first in one place and then in another, as the Master appoints.
May I never become a prey to the wiles of the devil.

Sixth Month 4th.--I am now at Concord.
Have been here more than a week, and have attended two meetings as they came in course.
How much longer I may have to stay I cannot tell.
Feel today exercised in mind more than since I came.
I have to appear as a fool in my dress.
The children are looking for something fine and fixed,
but I must set an example of great simplicity.
It costs me much conflict of mind to be for a sign unto others;
more than I could bear if the Lord did not support me in it.

22nd.--I have now been at Concord nearly four weeks,
shut up a close prisoner most of the time,
not knowing when the Master will give me the word of command to depart hence.
I appointed a meeting here for the young people and children, which was well attended,
and I thought a solid meeting.
Also attended Short Creek Monthly Meeting on the 17th,
and was favored with Divine strength to declare the greatness and
goodness of our Savior`'s love to those who serve Him faithfully,
and how He causes them to triumph over all their spiritual enemies,
and to become more than conquerors through Him who loved them.
I trust I am learning the lesson of patience somewhat,
for I have felt more cheerful and composed in this imprisonment than I once thought
it possible for me to be. People may think that as I have no family to care for,
I might perhaps be the more willing to pitch my
tent first in one place and then in another.
But how little do they know the strokes it has taken, to make me able to say,
"`Not as I will, but as you will.`"
Oh, the hurry of spirit which I naturally possess to get from under the cross;
it has to be with me that of dying daily;
but I believe we may attain to that state wherein every thought can centre in this:
"`Not as I will, O Lord,
but as you will,`" and this is a work of the greatest importance,
and essentially necessary that we may become heirs of the kingdom of heaven.

Harrisville,
Seventh Month 19th.--The Lord has been graciously pleased to
help me through many straits since I left home,
which has been more than ten weeks.
Little did I suppose,
when I attended to that small opening which led me first into this neighborhood,
that I should have been kept so long in the verge of this Monthly Meeting.
How marvelous are the ways of the Almighty.
Man cannot find them out or fathom them by all his boasted wisdom.
Lord, be pleased to be with me,
and make me willing to give up and surrender my life and my all into your hands,
if I become a by-word,
a hissing and a reproach all the day long in the mouth of gainsayers,
I feel that you have many things to say unto me which I am not yet able to bear.
Oh, guide and guard my footsteps in this critical time--Yes, this critical time.

Seventh Month 31st.--Oh, God!
My God!
You have brought me very low.
Cause me not to stumble upon the dark mountains, which rise up to oppose my pathway;
Lord, assist, or I perish.
My hope is in you, the Fountain of light and life.

Eighth Month 1st.--It is now more than twelve weeks since I
first came into this neighborhood (Harrisville). Have spent
five weeks at Concord and two at the boarding school;
visiting meetings as they came in course at Concord;
the school at Smithfield and Harrisville;
also visited all the families of Friends at Smithfield and some at Harrisville.
None but the Lord knows what I have had to pass through during this time.
Today had to go as one who regarded not the outward appearance,
and have had to go into families and meetings in
such attire as to be a gazing stock to others.
I have said, Lord, if you deal thus with me, take away my life;
and He has answered me on this wise:
"`Have I not as yet allowed you decent clothing? You
must be a sign against the pride of this day and age,
and against the pride of this people.`"
If the Lord had not sustained me, I must have sunk under this burden.

Eighth Month 14th.--Attended the funeral of Mary Thomas at West Grove,
who died suddenly of apoplexy.
It was a very large gathering;
and in fear and trembling I had to sound the warning voice: "`You also be ready,
for at such a time as you think not, the Son of man comes.`"
I had to warn the proud and thoughtless not to
put off their day`'s work until it was too late.
The same day returned to Flushing, after an absence of fourteen weeks,
with the feeling of an unprofitable servant;
but with the belief that I could not have returned sooner without a guilty conscience,
which I have not felt in the retrospect.

15th.--Attended our Quarterly Meeting held at Flushing, which was larger than usual.
In the forepart of this meeting,
I had to revive the language of the Most High through the mouth of his prophet:
"`Blow you the trumpet in the land.
Cry, gather together and say, Assemble yourselves, and let us go into the defenced cities.
Set up the standard toward Zion; retire, stay not, for I will bring evil from the north,
and a great destruction.
The lion is come up from his thicket, and the destroyer of the Gentiles is on his way.`"
Believing,
and having to declare that the Lord would mar the pride of this people and this nation,
even as He marred the pride of Judah and Jerusalem in the days of old,
which was signified and foretold by the prophet Jeremiah,
when he was commanded of the Lord to hide the linen girdle by the river Euphrates, which,
when he took again, behold it was marred;
so will the Lord mar the pride of this people and this nation,
and the language to many is in this day, Return, stay not upon the ground you occupy,
which is a false resting-place; lift up the standard towards Zion, retire there;
there wait upon the Lord,
that you may experience your "`place of defence to be the munitions of rocks,
your bread to be given you and your water to be sure.`"

18th.--First-day morning, I felt my mind greatly oppressed and distressed.
When I went to meeting, the burden increased;
and I had to proclaim the gospel of life and peace to the people,
declaring against the unlawfulness of war under the Christian dispensation,
feeling that there were some in imminent danger of being drawn away and
taken captive by the delusive baits of the enemy on the subject of war;
and warning them in an impressive manner to flee from the snares of the adversary.
In the afternoon of this day,
I could feel no peace of mind without going to see a young man in the neighborhood,
who I believed was one cause of my distress, he being a member of our religious Society.
I had to deal very plainly with him, telling him,
I knew not why I should feel thus exercised on his account, but perhaps he could tell:
I told him that I believed if he pursued the course he was designing,
that the cup of trembling would be taken out of the hands of
those who were afflicted for him and given to him to drink,
and he would have to drink the very dregs thereof.
He seemed much brought down and contrited for the present, weeping freely;
but I had little hope of his amendment, but felt that I must be clear of his blood,
let him take what course he might.
Next morning I learned that he had the evening before
my visit enlisted as a soldier in the army;
or given his word that he would serve if called on.
After this he was in great conflict of mind at times,
rather giving his parents and friends to hope that he
would decline his intentions to serve as a soldier,
having the liberty to do so;
but alas! the thirst for honor and military fame
overcame his better feelings and judgment.

Twelfth Month 12th.--None can comprehend the dealings of the Lord with my soul,
but those who may pass through or experience similar exercises.
Oh, the openings and shuttings which are my attendants,
the heights and depths through which He leads me, the tossings, the calmings.
Truly I can say as Job, "`You hunt me as a fierce lion; and again,
you show yourself marvelous upon me.`" Sometimes I am tempted to despair,
and again I see his matchless, marvelous love and mercy; so that I can say with his help,
deal with me as seems unto you good.
Oh, that I may not make shipwreck of faith and a good conscience,
is the earnest travail of my soul.

First Month 8th, 1862.--At Guernsey, today, heard of the death of L. M.,
the young man before alluded to. He had joined the army
and gone into Kentucky with other soldiers,
where he remained some weeks,
anxiously looking towards the time when he would be engaged in actual fighting,
as he signified in a letter which he wrote home to his friends, before his death.
But He who holds our lives in his hand, saw fit before he was called into action,
or permitted to shed the blood of his fellow-man, to cut him off with typhoid fever,
far from home, and it is to be feared without a sympathizing friend near him.
A day or two before I heard of his death, and as I was sitting alone in a thoughtful,
serious frame of mind, this language sounded in my mental ears:
"`L. M. is dead;`" and it then presented to my mind to go and write it down;
but as I was about to do so, a reasoning took hold of my mind,
and I thought it might only be imagination.
Oh, how I have been exercised for this young man; but now the conflict is over,
his sentence sealed,
and an awful warning left to others not to sin out their day of Grace.
Far, very far, am I from limiting the Holy One of Israel,
or saying that it is impossible that this young man should
have experienced repentance before he was taken hence;
but very certain I am that he had some,
yes many loud calls and warnings before he finally gave
up to go counter to all his friends`' advice,
and stifle the convictions of Truth in his own mind;
so as to join in with the unchristian practice
of taking the life of our fellow creatures.

12th.--Appointed a meeting this afternoon at Belmont.
It was held in the Methodist Meeting-house, but the day being very rainy, it was small.
I had to bring things close home to the few in attendance,
but what I had to say appeared to be well received, and it was a solid meeting.

14th.--Had a meeting at Londonderry, a village four miles from Guernsey.
It was well attended, and considering the number of light and frothy spirits present,
I thought it a quiet meeting.
Oh, the vanity apparent in this age:
surely the Lord will bring judgment home to the hearts,
and upon the heads of many who are now soaring in pride and wantonness.
It may be too late to lay these things to heart, when the stroke of death comes.

15th.--My soul is very sorrowful; the judgments of the Lord are in the land,
but the inhabitants do not learn righteousness.
Oh Lord! you are greatly to be feared: but who does love, fear,
and serve you as they ought.
My spirit bows and craves that your all-sustaining power may
continue to be my protection in this time of deep proving,
when all terrestrial things fail to afford support to the mind of a poor pilgrim,
where so much wickedness abounds.

Help me, Oh Lord, for vain is the help of man.
Assist me, or I sink where there is no standing.
Prove me, and let not the enemy triumph over me. Teach me, and let not my candle go out,
or my candle-stick be removed out of its place.
Gather my wandering thoughts and centre them upon you.
Stay the rolling billows, and hush the furious storm;
and speak peace to the raging waves of this troubled sea,
upon which this bark is now sailing.
Amen and amen.
I eat but little pleasant bread, and am often ready to faint by the way,
being much bowed down on account of the great distress in the land.
And to see people in the midst of war and bloodshed, so lighthearted and vain,
as many are, is distressing in the extreme.
I am often ready to say, I will speak no more in the name of the Lord.
But then his word is as a fire shut up in my bones, and I am weary with withholding.
Then the language of my heart is, Lord, give me strength to perform your will;
then I will not regard what man may say or do. Oh,
the lovingkindness of the Lord to a gainsaying, rebellious,
backsliding and backslidden people.
My soul can testify to his goodness, even in the depths of distress,
for out of the low dungeon has He heard my cry.
When shut up and enclosed in darkness, the Lord showed me his marvelous light,
for none other could have done for me what the Lord has done, blessed be his name.
Whether I continue faithful,
I can testify that the Lord is faithful and gracious
towards all who look to Him with a single eye for help.
Oh, my soul, trust in Him, come what may, life or death, sickness or health,
and never cast away your confidence in his arm of power.

24th.--Today was held our Monthly Meeting,
and I still feel no liberty to return the Minute granted me more than a year ago.
This is a very humiliating path to walk in;
very little active service seems required of me,
but passive obedience and submission to the will of the Lord.
Often, of late,
has this language ran through my mind--"`The things concerning me have an end.`"
Oh, if I should strive against the will of the Almighty,
it would indeed bring spiritual death and perhaps the death of the body also.
None but the Lord knows the secret travail of my soul,
at times it seems as if it would waste the flesh from my bones,
and nothing can give me ease but the ability to say--"`Not as I will but as you will,
oh Lord.`"
In the forepart of the meeting, today, my spirit was much prostrated in fervent,
silent supplication before the Lord,
at which time my cousin Asa Branson knelt in vocal supplication,
and I thought it a season of some favor,
as the Lord gave us a little evidence that we were not forsaken.

Second Month 15th.--Visited a sick man and his family,
with whom I had a religious opportunity, both in counsel and encouragement to the sick,
and those in health;
and also felt it right to address the Father of
mercies in vocal supplication on their behalf;
but for not vocally interceding on behalf of the
aged grandfather of the family then present,
I have felt very sorrowful in letting this opportunity
pass away without faithfully doing my duty.
When shall I learn perfect obedience to the will of God.

19th.--This is the week of our Monthly Meeting,
and my mind is again brought into exercise about returning my Minute.
Oh, you fountain and source of all good, look upon me, I beseech you,
and order all things concerning me to your glory; then will I not be afraid,
whatever man may say or do. Amen.

Father of light, life, grace and truth, you who see and know the hearts of all,
have compassion upon me, try me and prove me,
and let not my gray hairs come to the grave in sorrow
on account of unfaithfulness to your commands,
however hard to flesh and blood it may be to obey.
Give me strength, I beseech you, then will I not be afraid, or fear the face of man,
though they scorn or scoff at the words which you give me to declare unto them.
Have compassion upon them, oh God, who scoff, mock and deride;
that they may come to know and understand what it is to live
in your fear and obey your counsel before it be too late.
Plead with them in judgment, mingled with mercy;
that the vial of your wrath may never be poured out upon them unmingled with mercy.
