== Chapter VII

[.chapter-synopsis]
* Appointment of a Meeting at Georgetown, and other Service in that Vicinity
* A Pointed Testimony at Micajah Johnson`'s
* Beginning of the Civil War, and Her Exercises Concerning it
* Exercises and Service about Harrisville and Mt. Pleasant
* A Visit to Two Despondent Persons at Stillwater
* Again Visits Salem and Springfield Meetings
* Neglects an Apprehended Duty at the Town of Barnesville
* An Acknowledgment and Regret Over other Omissions
* Death of Micajah Johnson
* Frequent Sufferings of Spirit on Account of the War
* Again Visits Salem and Springfield Quarters and their Branches

Third Month 22nd.--I have just returned from Guernsey,
where I have been again spending some weeks
attending meetings there as they came in course.
Oh, the bitterness of that portion meted out to me. I have said in my heart,
when will I learn passive obedience and submission to the Lord`'s will,
and glory in nothing save in the cross of our Lord Jesus Christ.
Though I have been tempted and tried in a manner I never anticipated,
yet the streams of Divine consolation have been such,
that I have no language to set forth the mercy of God to my soul in this little visit.

The Lord laid it upon me to attend the funeral of a man,
who about a year ago refused me a religious opportunity in his family;
though I could not see for what; but when the interment was over,
and before the people left the ground, I was moved to step forward near the grave,
and proclaim this language--The strong men shall bow themselves--exhorting,
warning and inviting those present to prepare for such a solemn event.
I had not much to say, but in a short testimony for the Truth I felt sweet peace.
Several opportunities I had with individuals, greatly to the relief of my mind;
besides opportunities in meetings at this place to the acknowledgment of the power,
wisdom and goodness of God to those who do indeed love and serve Him.

28th.--I desire nothing so much as a preparation to serve the Lord.
I feel that I have no time to do my own will.
I believe bonds and afflictions abide me if I continue
faithful in the further prosecution of this visit.
Oh, that I may not be permitted to shrink from any suffering needful for me to endure,
in filling up in my flesh the "`afflictions of
Christ which are behind for his body`'s sake,
which is his Church.`"

Fifth Month 15th.--Attended our Quarterly Meeting, in which I had considerable to say,
by way of encouragement, to the low, desponding little ones, and felt peace afterwards.

17th.--Went to Harrisville in company with J. and R. Hobson,
in order to attend a prospect which has for some time rested with weight on my mind;
that of appointing a meeting at Georgetown,
a small village about three miles from Harrisville.
John W. Smith and Joseph Hobson went over the same
evening and made arrangements for the meeting,
which was held next day at three o`'clock p. M. It was well attended,
and proved a relieving time to my mind.
I had to speak plain truths to professors and profane,
beginning with these words--"`There is no peace to the wicked, says my God.`"

Many were there of various descriptions, and I trust the Truth did not suffer.
Stayed all night with cousin Abraham Branson,
who with his family have joined with the Separatists (or Gurneyites),
from our Yearly Meeting in 1854. They were very kind.
In the morning, after a religious opportunity,
he and his wife expressed satisfaction with the visit;
cousin A. saying he could wish I might oftener visit them.
After this we went to Micajah Johnson`'s. But what shall I say concerning this visit.
The cup given me to drink, both before and after going to this house,
was indeed the cup of trembling.
The Master gave the word of command, and bade me not to turn to the right hand,
or the left.
He bade me loose the strings of my shoes and take them off my feet;
and take the covering off my head,
and to tell Micajah Johnson in the presence of his wife,
that so the Lord would rend every covering that was not of his Holy Spirit;
and take away the false resting places; and deal with us according to our deserts;
that there was no biding from Him.
I was not deranged, or out of my right mind, but was commanded to be a sign unto him.
The door of mercy was still open,
and the hand of the Lord still stretched out for his recovery from all that
had let and hindered him from coming into the obedience required.
There was no time to dally or put off the work of repentance, and amendment of life.
Great plainness of speech and Christian boldness was given me
to declare the whole counsel of the Lord to this individual;
whether he will hear or forbear.

I then addressed his wife,
entreating her to endeavor to come into a situation
comparable to that of the Shunamite of old;
a situation in which she could intercede, not only for her own spiritual life,
but that of her husband and children.
Having previously addressed their two daughters,
and requested them to withdraw before I said anything to the parents,
I now found I must make some efforts to see their two sons.
The eldest refused to give us his company, and the younger being from home, was sent for,
and came presently; to whom the language of warning, encouragement, and entreaty,
to live soberly, righteously and godly,
while the Lord was pleased to continue his mercy towards him.
My mind was greatly relieved of a heavy burden.
On taking leave of this family the father requested Joseph Hobson to inform
me (I being very dull of hearing) that he was glad of the visit.

In the afternoon of the same day I went to see Nathan Smith,
who had requested his son-in-law to let me know
that he would be glad to see me. Some years ago,
as this Friend was about to engage in marriage with an
individual not in membership with Friends,
I used great plainness of speech to him,
concerning the impropriety and sin of such an engagement.
He was then a member of the Meeting for Sufferings; had a large family of children;
his former wife having been deceased some years.
Oh, what a delusion came over him;
and notwithstanding many Friends warned and counselled him against the procedure,
yet he persisted therein; but now he seems to realize in some measure his situation;
and seemed willing to receive whatever might be in
store for him in the way of counsel or admonition.
I had to remind him of the brazen serpent which Moses lifted up in the wilderness;
when those who were bitten by serpents, looked upon it, they were healed;
which was a type of the Messiah.
Christ Jesus is He who can heal all the bites and wounds of the old serpent the devil,
which He inflicts upon us poor, frail, finite creatures.
I had to encourage him to look to this source for help,
even unto Him who is the healer of breaches,
and the restorer of paths to walk in. Poor man, he seemed very glad of our visit,
expressing his thankfulness several times for the favor granted.
His wife, stepdaughter and granddaughter were present.

20th.--Attended Short Creek Monthly Meeting;
was silent in the forepart but had a word of encouragement to
the destitute and afflicted in the latter part;
returned home the same evening.

21st.--Attended the funeral of Maria Hosier; a single woman who lived alone;
and as she lived, so she died, without anyone being present,
though a Friend was in an adjoining room.
Maria being desirous to be left alone until a certain hour,
when the Friend went in she found the last struggle was over.
Great silence prevailed while we were sitting beside the corpse, indicative,
as I thought, of a happy release from the shackles of mortality.
After the corpse was interred, I had a short testimony to deliver to the vain,
profligate and wondering sons and daughters;
warning them to prepare for such a solemn event, when dust returns to dust,
and the spirit to God who gave it.

28th.--I had an appointed meeting at Wrightstown, or Belmont,
among those not of our Society.
Many attended, more than the house could hold.
It was held in the town hall, and I thought it a favored meeting in a good degree;
but how changed am I now; so empty, so distressed, so forsaken,
and yet hoping against hope, nothing to trust to but the mercy of God.
Oh, the war and bloodshed which is prevailing in this land;
it is so grievous to my feelings,
that I can hardly retire to bed when the hour for rest comes;
or eat my meals with any comfort; but I must leave it with the Lord who will do right.

Eighth Month 3rd.--Appointed a meeting for the
young people and children in our neighborhood.
It was well attended,
and the Lord gave me a plain testimony to deliver concerning
the unlawfulness of war under the gospel dispensation.
Many members in various parts of our religious
Society in this country are joining the army.
Oh Lord, cause the sword to be sheathed, if consistent with your will, "`says my soul.

Eighth Month 13th.--Visited William Kirk,
who is making up a company of volunteers for the army, himself to be their captain.
I was strengthened to cast off a great weight and burden,
which had rested on my mind concerning this individual,
and another whom I requested to give us his company.
William being a member of the Baptist society, and the other a leading Methodist.
I sought to deliver the whole counsel of God to these individuals,
and kept nothing back which He gave me to utter.
I used great plainness of speech in regard to the
inconsistency of war with the gospel dispensation;
yet no offence was taken.
I told them that I knew there was a law recently made to imprison any one,
who by word or action should discourage any from volunteering;
yet I regarded the law of the Lord more than the law of man;
and paramount to the laws of the land.
I requested and warned William not to violate his conscientious scruples,
nor press others to do so: that he would be held accountable,
as those concerning whom it was said, "`Woe unto him who strives with his Maker!
Let the potsherd strive with the potsherds of the earth.`"
After supplicating the throne of Grace on their behalf,
I left them with a thankful heart for having given up
to this requirement of our Lord and Savior Jesus Christ,
who said, "`my kingdom is not of this world, else would my servants light.`"
On bidding William Kirk farewell, he expressed his thankfulness for the visit, saying,
it was well timed.

14th.--Greatly bowed down and oppressed day after day Lord have mercy upon me,
and keep me from the wiles of the devil who is trying to upset my faith and hope in you,
the sovereign Ruler of the universe.

10th.--Yesterday was our Quarterly Meeting.
In the women`'s meeting I had to deal plainly with those
who were indulging in the vain fashions of the world.
That the Lord`'s judgments were not slumbering;
but would come upon us for our manifold sins and transgressions.
That it would be well for those who experience judgment laid to the
line and righteousness to the plumbline in the temple of their hearts,
to break down their stubborn wills;
for when judgment comes without mercy then it will be too late
for repentance and amendment of our ways and doings.
I had, also,
at this time to tell Friends that there was a specific
and certain remedy for sleeping in meeting,
and those who wrestled aright for the blessing would be favored to overcome,
and be made more than conquerors through Jesus Christ our Lord and Savior.

21st.--Today was our Monthly Meeting held at Guernsey.
We went down and returned the same day.
Shall I ever forget our morning ride.
It was the day appointed for a company of volunteers to meet at Belmont Ridge,
and from there proceed south to the martial field.
Oh, that men were wise with that wisdom which they so highly profess,
even the Christian religion, which would, if people were really in possession thereof,
put an end to all war and fighting with carnal weapons.
The Lord`'s name be praised that there are still left in Christendom
those who cannot fight for any earthly consideration.
Many young men, not yet arrived to the age of twenty-one, were in this company;
some with downcast and sorrowful countenances;
weeping mothers accompanying their sons--wives their husbands,
and sisters their brothers, to some parting spot, never again, perhaps,
to meet in mutability.
After witnessing this sight, I felt the testimony very precious,
that was given Friends to bear against all war and military performances;
and I felt it right to encourage Friends to maintain this testimony faithfully,
even if it be to imprisonment, and death.

31st.--Attended the funeral of S. C, who died of a short illness,
leaving a wife and three small children.
It was very large, being on First-day afternoon.
I was exercised at the graveyard, in warning the people to work while it is day;
to "`walk in the light, while they have the light.`"
I was much concerned, and exercised for those who are lukewarm and careless,
putting off their day`'s work till a more convenient season.
I had been quite ill several days previous; and felt scarcely able to attend,
but the Lord strengthened me both in body and mind,
to deliver a warning and exhortation to the people on this occasion.

Ninth Month 14th.--Oh, the war!
When will it please the Almighty to cause this grievous calamity to cease? I
often feel (comparatively speaking) as if I were on the battle-field,
witnessing the great perils to which the poor soldiers are subjected,
and the sufferings of the wounded and dying.
It seems to me,
that I could not have endured the agony of mind this war has occasioned me,
especially at times, when great slaughter has been going on (having a sense of it),
if the Lord did not sustain me in and under it. On the
day of the first great struggle at Bull Run,
as I was riding along the road with some Friends;
I felt an intimation that the great slaughter was going on;
and might have mentioned it to the Friends, but forbore; so also at other times.
Wonderful it is what has been permitted to befall us, and still we are not humbled.

Tenth Month 20th.--Lord, you know the depths of distress that have come upon me,
for the further trial of my faith, and the purification of my heart;
I beseech you to preserve me in patience, or I sink below hope.
The fiery trials which are to try me are in your hands,
and into your hands I commit body, soul and spirit.
Amen.

On the 19th, appointed a Meeting for Worship, about five miles from home,
among the Presbyterians.
It was a laborious time, because of a feeling of opposition to the doctrines advanced,
but the people were generally sober and well behaved.

Eleventh Month 27th.--At Harrisville.
The exercises of my mind are greater than I well know how to bear.
Oh, Lord! strengthen me to endure, for my soul is sore broken within me:
my soul lies prostrate before you, and my spirit craves that you will not permit me,
like Esau, to sell my birthright for a mess of pottage.
Oh! how have you dealt with me, causing me to become a spectacle to the world, to angels,
and to men.
All that I now ask, all that I now crave, is,
that you will not let me become a prey to the Adversary,
whatever else comes upon me. This day two weeks ago,
being the time of our Quarterly Meeting held at this place,
I believed it right to remain, and here I have been most of the time since,
at W. H`'s. When it may please the Lord to change this dispensation I know not;
but I do pray for strength to continue steadfast unto the end.

29th.--I have said in my heart, surely I shall be swallowed up in my distress;
greater trials and distress may yet come upon me.
The Lord only knows the end from the beginning.

Twelfth Month 9th.--Oh, you God of my life, preserve me, I beseech you,
that I may do no harm on the right hand or the left.
You have laid a great work upon me, permit me not, I entreat you,
to fall a prey to the Adversary of my soul`'s peace.

17th.--It has been five weeks today since I came into this neighborhood,
most of the time a close prisoner; except attending meetings as they come in course.
The Lord knows the exercise of faith and patience it requires thus to be shut up,
not seeing the ground thereof,
save to know that it is from Him who makes the morning
darkness and treads upon the high places of the earth,
and declares unto man what is his thought.
The Lord of hosts is his name.
I have visited six families in this neighborhood; three at Mount Pleasant,
and a school taught by George K. Jenkins; besides, I have had very close exercise,
and labor with some individuals.
I have sometimes of late thought that I was learning this lesson by the hardest way:
that of being content in the situation the Lord appoints for me. But pretty
soon I find some root of discontent and dislike springing up in me,
which causes me to remember the language of the Apostle--
"`If any man think that he knows anything,
he knows nothing yet as he ought to know.`"
I have thought too, of latter time,
that I knew what it was in some degree to rejoice in
tribulation,`" knowing that tribulation works patience,
and patience experience, and experience hope.
And hope makes not ashamed;
because the love of God is shed abroad in our hearts by the Holy Ghost which is
given unto us.`" May I learn perfect obedience by the things that I suffer.

19th.--Yesterday, in the Preparative Meeting at this place,
I had close things to communicate to some present, hard to be uttered.
Several times since being here at this time, I have had very close work in this meeting;
also with several individuals; so much so,
that if the Lord had not sustained me and held me up,
I had not had strength to have gone on, but must have fainted by the way.
You know, oh Lord, the integrity of my heart, and my desire to serve you only and alone;
be pleased to be with me the remainder of my days, and then lead where you will,
only strengthen me to follow in the regeneration.

21st.--Oh, Lord! you have been very gracious unto my soul.
I will praise you with my whole heart, for you have given me the gates of mine enemies.
I cried unto you with my whole heart, and you looked upon my affliction.
May I never distrust your power, for you make darkness your pavilion,
and tread upon the high places of the earth:
whichever way I turn you meet me with your flaming sword to
slay that within me that your righteous controversy is with.
Blessed, praised and magnified be your name forever, and let all the world say amen.

22nd.--"`He took me, He drew me out of many waters.`"
This language, with a song of praise, so filled my heart last evening,
that I thought the Lord was very near me with his goodness and mercy.
He has wrought deliverance for me when the waves of affliction were ready to engulf,
and the artifices of the deceiver of mankind
strong and very subtle to lay waste my faith;
so that, had I not cried with my whole heart unto the Lord,
I should surely have been swallowed up.

23rd.--When I said I shall be swallowed up, then, oh Lord, you did strengthen my soul;
when the gates of brass, and the bars of iron, were round about me,
seeming immovable forever; then you bade me trust in you,
so that a bow of steel has been broken by my arm.
Blessed and praised be your name forever and forever more.

This day attended Short Creek Monthly Meeting,
in which very hard things were given me to deliver;
but strength was given for the emergency,
and very peaceful has been the retrospect concerning
the testimony delivered in that meeting:
I had to revive the words of the prophet Ezekiel contained in the twelfth chapter,
when he was set for a sign to the rebellious house of Israel.
He was commanded to prepare his stuff for removing, and remove by day in their sight,
carrying his burden upon his own shoulders,
and covering his face that he should not see the ground.
He was also to dig through with his hand, and carry out his stuff thereby;
as those who go into captivity; and he did as the Lord commanded him.
In the morning the word of the Lord came unto him, showing him what these things meant,
and bidding him declare it unto the rebellious house.

I told Friends that I had been held captive among them week after week,
while my face had been covered, that I had not seen the ground, or cause of my tarriance,
or exercises; that I had to bear my own burdens,
and dig through a wall of opposition in order to walk in the obedience of faith;
but now I believed it right for me to tell them,
that it had appeared to me that I was set for a sign among them.
Many no doubt querying,
What do you? Why do you tarry so long among us? What good can such a
strange and unaccountable act as that of keeping your Minute so long,
do? But now it was for me to tell them,
that unless there was a deepening in the root of life and speedily turning unto the Lord,
they would go into captivity, even the princes of the people, and die there,
though they should see it,
or know it. That this vision concerns the princes of Jerusalem,
and all the house of Israel that are with them.
Sampson was a strong man, a judge in Israel, but through the importunity of Delilah,
he was shorn of his strength,
and those who were in any way compromising our precious testimony
against war were in danger of being shorn of their strength,
and those who could pay a bounty tax to induce volunteers to join the army,
had already some of their seven locks taken off.
I knew of none in that meeting that had done so, but if there were any,
they were in a dangerous situation.
Much more I had to say in the way of warning, counsel and encouragement,
to turn with the whole heart unto the Lord.

24th.--Received a few lines this morning from a leading Friend of this meeting, saying,
that he believed my communication yesterday towards the close of their Monthly Meeting,
was in the authority of Truth, and partly, if not altogether for himself.
That he had been drawn into a snare to pay the bounty tax, not only for himself,
but for several of his friends; that no act of his life had given him so much uneasiness,
though it was altogether unintentional, when he went to pay his common tax,
to pay the bounty; yet for lack of making proper investigation into the matter,
and not properly keeping the watch, he had been drawn into the snare,
and balked that precious testimony, which he ought to have been the first,
or among the first, to have supported.
Friends have now in the limits of that Monthly Meeting, with one exception,
paid the bounty tax upon whom it was levied;
several not living in that county (Jefferson) of course not included in the number,
or implicated in this breach of our Christian testimony; but some, and I believe most,
consider it better to pay, than suffer, or contend.
Oh, what a breach!
Though several Friends, for whom the tax had been paid, as before stated,
were very much tried and distressed therewith.
May the Lord heal the wounds that have through un watchfulness been made.

28th.--Again attended Harrisville Meeting.
It is now nearly seven weeks since I came to this place,
and still I find no liberty as yet to leave it. My mind was exercised in meeting today;
and a prayer begotten to the Lord,
though not vocally uttered--that if any of the dear children had a testimony for Him,
that He would bring them forth.
While my mind was thus exercised, a dear lamb (for so I may call her,
though she is the mother of a family), stood up and expressed this passage of Scripture:
"`If the righteous scarcely be saved, where shall the ungodly and sinner appear?`"

Last First-day also, my mind was much exercised in this meeting, believing,
that a youngish Friend had something on her mind to deliver.
I wrestled for her deliverance in secret prayer to God;
at last these words were required of me to utter,
without any addition--"`There is that scatters and yet increases;
and there is that withholds more than is fitting, but it tends to poverty.`"
After which the Friend arose and repeated this passage from
Job--"`How often is the candle of the wicked put out,
and how oft destruction comes suddenly upon them.`"
After this my mind felt easy and a song of praise filled my heart.
getting there, I was informed of two individuals,
members of Stillwater Quarterly Meeting, who were in a desponding state of mind.
Immediately a great exercise came upon me, and such a weight of concern,
and sympathy for them, that I could neither eat nor sleep with any comfort,
until I gave up to go and see them.
And in company with N. H. and E. B., on the morning of the 7th,
I got up at two o`'clock (the weather being very cold), rode ten miles before day;
then took the cars, and arrived at Barnesville about eight o`'clock.
Went to their Week-day Meeting; and after meeting, went to see B. H.,
a desponding young man.
Had a religious opportunity with him, and the rest of the family.
I told him my Master had sent me to tell him that he had no need to despair;
he had committed no unpardonable sin;
that the Lord in his mercy was round about him to do him good,
willing to remove the weight and pressure which so mightily weighed him down;
and much more of an encouraging nature.
After vocal supplication on his behalf, I left his room.

The Lord only knows how my heart is exercised before Him daily and hourly,
that I may in no wise balk any of the precious testimonies given us as a people to bear,
nor stumble any of the children in my tarriance here.
Dearest Father! you know my prayers by day and by night.
Oh! let me not faint, nor give out,
nor stay one hour longer here than it is your holy will I should.

31st.--Yesterday visited a district school,
and the day previous had very close things to deal out to a dear Friend.
It was like parting with my right hand,
to clear myself towards this Friend in the way of caution, warning and some censure,
for having, as I believed, departed in some degree from the pure Truth.
It is for peace of mind, I feel constrained to labor for and with others.
When will I know an overcoming of the enemies of my own household.

First Month 1st, 1863.--The cup given me to drink has been very bitter,
and the burden heavy upon my shoulders, which I have had to bear alone,
that is almost without human help, or consolation.
I have feared I shall get into a murmuring disposition.
Oh Lord, help me, for you only and alone can ease me of my burden,
and enable me patiently to bear it all the days of my appointed time.

3rd.--Last evening my mind was so impressed with the horrors of war,
that I felt almost constrained to request a Friend,
who was reading aloud (though in an interesting and instructive book), to forbear.
It seemed to me that all the distress and agony of the battle-field was before me.
When will the remainder of wrath be restrained? When will the sword be sheathed?

Since writing the above, a Friend informed me, that according to my request,
a Meeting for Worship has been appointed, about two miles off, among the Presbyterians,
to be held tomorrow at eleven o`'clock.
I am exercised almost to trembling,
but I fear I think more about the poor creature who has requested this meeting appointed,
than the glory of the Creator.
When will I learn perfect resignation to the will of the Lord?
The same Friend gave me a word of encouragement,
unexpectedly to myself, but not unnecessarily.
Oh Lord, help me, or I shall faint by the way;
give me strength to do or to suffer according to your holy will;
so shall your name and praise be exalted.
Amen.

4th.--Went at the.time appointed to the meeting.
It was well attended, and ended solidly.
The Lord`'s name be praised for the help afforded.
May faithfulness be the girdle of my reins, and righteousness the girdle of my loins,
says my soul.

5th.--Left Harrisville, where I have spent at this time nearly eight weeks;
making my home at William Hall`'s;
where I have been kindly treated both by parents and children.
The dear little children!
May the Lord bless them, together with their parents,
has been the prayer of my heart for them.
But what strokes it takes to bring our wills into subjection to the will of the Lord.
May his hand not spare, nor his eye pity, until this be accomplished in us all,
says my soul.

The same day went to the Boarding School to meet with
the committee having charge of this Institution;
having also a prospect of visiting some families in the limits of Mount Pleasant Meeting.
But on my way there, felt that something crossed my path, and turned me another way.
After getting there, I was informed of two individuals,
members of Stillwater Quarterly Meeting, who were in a desponding state of mind.
Immediately a great exercise came upon me, and such a weight of concern,
and sympathy for them, that I could neither eat nor sleep with any comfort,
until I gave up to go and see them.
And in company with N. H. and E. S., on the morning of the 7th,
I got up at two o`'clock (the weather being very cold), rode ten miles before day;
then took the cars, and arrived at Barnesville about eight o`'clock.
Went to their Week-day Meeting; and after meeting, went to see B. H.,
a desponding young man.
Had a religious opportunity with him, and the rest of the family.
I told him my Master had sent me to tell him that he had no need to despair;
he had committed no unpardonable sin;
that the Lord in his mercy was round about him to do him good,
willing to remove the weight and pressure which so mightily weighed him down;
and much more of an encouraging nature.
After vocal supplication on his behalf, I left his room.

Before we left, he requested his mother to ask me into his room again.
He then asked several questions, such as these:
If I was ever tempted to believe that I had committed an
unpardonable sin? Whether I thought it right to take medicine,
when nothing was the matter with the body? Thought his trust ought to be in the Lord;
that it was his mind only that was affected.
He further said that he thought he had treated my advice some years before with contempt.
I assured him that I did not remember his having treated my advice in that way.
He then asked me if I had received a letter from him a
few days previous to my visit? I told him no!
I had received none.
At which his countenance brightened up, and he replied,
"`That is the greatest word of comfort I have had;
that you came to see me because you felt as if you must.`"

We went to see the other individual, a female Friend;
who had passed the most of that day in extreme agony of mind;
bewailing her condition in a deplorable manner.
On being told that some Friends were there who would like to see her;
she at first thought she could not see us;
but after a little while she concluded we must come into her room.
My mind was led into great sympathy for her;
and a word of encouragement and counsel was put into my mouth for her;
and vocal supplication to the throne of Grace offered on her behalf.
She sat perfectly composed all the time we were in her room; and after we left,
said to the Friend who attended her,
in allusion to this visit--"`This may be as bread cast on the waters,
found after many days.`"

After this I returned to the Boarding School, where I spent six weeks;
most of the time under much exercise of mind.
Left the Boarding School and returned to Flushing, after an absence of three months.
The same day attended our Select Quarterly Meeting, and on the day following,
the Quarterly Meeting,
in the forepart of which I had to allude to the circumstance recorded in Scripture,
of a man who was felling a beam, and the axe-head fell into the water,
and he cried and said, "`Alas, master! for it was borrowed.`"
It seemed to me there was instruction in this for those who felt that they had lost
the little capacity they once had to labor for themselves and others;
and not only so, but were responsible for that over which, they now felt,
that they had no control;
but seeing a miracle was wrought for this poor man by the prophet,
in making the axe to swim,
and bade him put out his hand and take it. And the great and good Prophet,
the Lord Jesus Christ, is near unto all who cry unto Him out of a pure heart;
and it is an unspeakable blessing that this cry and petition is put into the heart--Alas,
Master! as if to say, if I receive no help from you, I am undone.
Oh, He will work for all those whose hearts are turned unto Him for help in the right way,
and cause them to sing for joy,
and the praise and honor will be given unto Him to whom it is due.

Fourth Month 23rd.--Returned the Minute to the Monthly
Meeting which was granted me more than two years ago,
during which time I have been engaged in visiting families, meetings and individuals,
as way opened, to the relief of my mind.
The same day obtained a Minute to attend Salem and Springfield Quarterly Meetings,
and the meetings constituting them, and some families, as way may open.

Fifth Month 3rd.--Set out on my visit to the northern quarters,
having the company of my brother Jacob Branson, and cousin Abigail Sears.
Rode to Jefferson, twenty-three miles; next evening got to Salem.

5th.--Rode to Springfield, and dined at Nathan Warrington`'s. After dinner,
had a religious opportunity with the family, to good satisfaction;
Nathan`'s father-in-law and mother-in-law being present.
I had to revive the language of our Savior--"`I am come that you might have life,
and that you might have it more abundantly.`"
And again, "`I am come to set a man at variance against his father,
and the daughter against her mother, and the daughter-in-law against her mother-in-law.`"
"`And a man`'s foes shall be they of his own household.`"
Commenting upon these passages as Truth gave me utterance, saying that however a father,
a mother or daughter might miss his or her way,
those who follow Christ will feel themselves
bound to maintain their allegiance to the Truth,
and stand against error,
even if it is found in the nearest and dearest friend upon earth.
Then went to the Select Quarterly Meeting held at three o`'clock; was silent therein,
and felt satisfied.

6th.--Attended Springfield Quarterly Meeting.
In the forepart of which I had to declare my belief that there was an
individual present who had been tempted to take his own life.
I had a short testimony in the way of caution, warning,
and encouragement to such a state, and felt peaceful and easy afterward.
I have since been informed that a man who left the meeting when the shutters were closed,
acknowledged that he had been under that temptation.
After meeting, rode seven miles to New Garden,
and lodged at Joseph Stratton`'s. In the evening, before retiring,
had a comfortable religious opportunity with this Friend and his wife,
a brother and sister-in-law also being present;
and I felt my faith and hope renewed in Him who
never said to the wrestling seed of Jacob,
seek you my face in vain.

7th.--Attended New Garden Meeting.
After J. E. had spoken considerable therein, I had to come forth with a sharp,
close testimony, beginning with these words, "`I have heard it said, forewarned,
forearmed,`" but I had not thought of meeting with what I have met with here.
I have seen the serpentine spirit at work in the galleries and on the facing seats,
like Ishmael of old, who came from the land of strangers,
among the little remnant of the children of
Israel which had been left in their own land,
after the greater part had been carried away to Babylon.
Now Ishmael got into favor with Gedaliah and treacherously slew him, and many more,
and those who remained were greatly affrighted, and proposed to go into Egypt,
where they concluded they should not suffer hunger of bread, nor see the sword,
nor hear the alarm of war.
But Jeremiah plainly told them if they did go into Egypt,
and refused to continue where they were,
they would die of those very things they were trying to escape;
but go they would and did,
contrary to the express command of the Lord by the mouth of his prophet.
I had to express my belief, that a wrong spirit, comparable to that of Ishmael,
had been at work among them, and slain some of them,
and others being alarmed were flying for their lives.
I warned Friends to take no dark steps like going into Egypt,
but to maintain their standing where they were, and the Lord would bless them.
Though this serpentine spirit had been,
and was destroying the spiritual lives of many among us,
yet the Lord`'s power was over it,
and would deliver from it if faith and patience were abode in. I
encouraged and warned them not to forsake the fountain of light,
life and Truth for any false light, etc.
Lodged at Lewis Walker`'s. Next morning,
had a religious opportunity with the parents and children,
bringing matters close home to them;
encouraging and warning them to labor for the promotion of Truth in their own hearts.

Rode to Barclay Stratton`'s, and had a religious opportunity with him and his family.
After dinner, rode eight miles to Salem,
and attended the Select Quarterly Meeting held at three o`'clock, in which I was silent.
That evening, paid a visit to Daniel Koll and family.
Daniel had just published a pamphlet,
setting forth his convincement of the principles professed by Friends,
and his reception into membership:
also his conclusion to leave that body of Friends with which he is now connected,
and his reasons for doing so. I had heard of this pamphlet,
but had not seen or read it. I told Daniel that I fully
believed that he was under a great delusion,
that it was a dark move with which I had no unity whatever.
Much plain talk passed between us, in which I let him know my mind fully,
as to the impropriety of the steps he was taking,
and so leaving the matter with him for his consideration, I proposed going;
but when about to start, I felt a stop in my mind,
and thought it right to request that the children, such as were at home,
might be called in; which being done, I had a favored opportunity with them,
encouraging them to turn unto and obey Him who
could and would keep them in the right way,
as they were concerned above all things to look to Him for help,
and wait upon Him in the way of his requirings.
Oh, how my heart is led to sympathize with the children in this day,
who are saying in their hearts,
"`Who shall show us any good?`" I had to set forth the great
responsibility resting upon parents as well as others,
not to cast a stumbling-block before the dear children.
I was made truly thankful on leaving this family,
that I had been faithful and delivered the whole counsel to parents and children.
Returned to Mary J. Fawcett`'s, and lodged.

9th.--Attended Salem Quarterly Meeting, which was large.
I had not been here before since the separation in 1854;
and this meeting was not so much reduced in size as I had expected.
J+++.+++ Edgerton spoke at length; after which, I thought it right to revive this language:
"`Fear you not the reproach of men, neither be afraid of their revilings,
for the moth shall eat them up like a garment, and the worm shall eat them like wool;
but my salvation shall be forever,
and my righteousness shall not be abolished`"--commenting thereon in a short,
impressive testimony, and felt peace afterwards.
In the afternoon, several Friends came to our lodgings,
and I had to open my mouth among them, though I greatly preferred keeping silence.
Beginning with, "`Seek the Lord and you shall live: but seek not Bethel,
nor enter into Gilgal, and pass not to Beer-sheba;
for Gilgal shall surely go into captivity,
and Bethel shall come to nought;`" giving it as my
belief that nothing was so much needed among us,
as that of knowing in our own individual experience the Lord`'s
circumcising knife in the temple of our hearts--the Lord`'s axe--
the Lord`'s plough--the Lord`'s harrow--his fire and harrow,
reducing and bringing into conformity with his
holy will all that his controversy is with.
This was a memorable opportunity to me,
in which the great God was pleased to strengthen a poor worm to plead with those present,
to give up unreservedly to his holy will concerning them,
and to bear the turnings and overturnings of his holy hand upon them,
in order that they might find a place of safety amidst the storm and
tempest now beating vehemently against the buildings of many,
and trying their foundations, and which storm and tempest we shall not be able to escape.
It was a solemn time, the language of warning, counsel, and encouragement flowed freely,
at which my soul did marvel.

10th.--On awaking, this language presented to my mind:
"`Be not dismayed at the signs of heaven,
for the heathen are dismayed at them;`" accompanied with a belief that it
would be right for me to go to a Friend`'s house and strengthen the mind of
one of the family by reviving the above passage.
I accordingly went, and had a religious opportunity in the family,
and delivered what I apprehended was called for; then attended Salem Meeting,
held at eleven o`'clock.
It being First-day, the meeting was large,
and I had to plead with those who were putting off their day`'s work,
and warn them of the awful consequences of so doing,
if they persisted therein until the door of mercy should be closed against them.
In the afternoon went to see two aged Friends,
and had to revive the language of the apostle: "`leaving the things that are behind,
I press towards the mark for the prize, etc.`"
This, I think, is encouraging not to dwell improperly upon our past failings,
but to put on strength in the name of the Lord,
and follow his bidding in order to obtain the prize.
My heart was enlarged towards them in the love of the gospel,
and I had good service in this family.
After this went to see a sick young man, who appeared near his close with consumption.
After a religious opportunity with him and his parents and sisters,
I had another with several young people who had come in to see their sick friend,
which was to the peace and relief of my mind.
The same evening took tea at Z. F`'s. There I had to deal very plainly,
encouraging his wife not to give out in a dark and cloudy day,
but to trust in the Lord and mind his pointings,
and way would be made where there appeared no way.
I told him to be aware of an endeavoring to promote a
separation in society as he was trying to do;
but to mind the counsel of the Lord in his own heart,
that nothing was so much needed with him as the
operation of the fire and hammer of the Lord.
The Lord gave me sharp words to use to this man, and strength to do it,
blessed be his name forever.
Returned to Mary J. Fawcetts`'s, where we made our home and lodged.
I may add that the first religious opportunity I had in this visit was in her family,
where I had to warn the young people to be aware of slighting
the visitations of heavenly good to their souls,
lest those visitations be withdrawn, and the heart become hardened,
and incapable of receiving good impressions,
than which I know not of a more deplorable condition,
save that of being in the midst of tribulation and anguish, "`where the worm dies not,
and the fire is not quenched.`"

11th.--Early this morning left Salem for New Garden,
with a prospect of reaching our own Quarterly Meeting, to be held the 14th of this month.
At New Garden,
I had a concern to visit a few families who had withdrawn from that meeting,
alleging as a reason for so doing,
that all is gone like life and hope from their meetings,
and if they save their spiritual lives,
they must make their escape from those who they
consider have lost the vitality of religion,
by favoring the disowning of the Gurneyites,
according to the late act of our Yearly Meeting.
I could not favor this act of our Yearly Meeting in 1862;
yet I had to use great plainness of speech in regard to this
separation now going on in different parts of our Yearly Meeting,
fully believing it was a dark move, and I told these individuals so very plainly.
Went to see a widow, who appears to be in a declining state of health.
Had a comfortable opportunity with her and her children.
Lodged at Henry Lupton`'s. In the evening, before retiring,
had a religious opportunity in this family,
which closed my services for the present in these parts.

12th.--Rode forty-seven miles to Cadiz, where we lodged.
Next day, about ten, got to David Binns`', at Harrisville.
Had an opportunity with David and his wife;
they having separated from the meeting to which they belonged.
His wife was an overseer of Harrisville Preparative Meeting, and has been a concerned,
consistent Friend;
but has stumbled at the late act of the Yearly Meeting in
regard to disowning those who separated from us in 1854. Oh,
what a great pity that the leaders of the people should cause them to err.
My soul deeply mourns on account of the sad state of things among us,
and I am often reminded of the language of Ezekiel concerning those
who took horns and pushed the diseased of the flock from them;
yet I cannot believe that this separation now going on
in our Yearly Meeting will land those engaged in it,
either in the land of peace or plenty.
I have endeavored to deal plainly with those who
have put a stumbling-block in the way of others,
as well as those who are stumbled thereat.
After a free conversation with these Friends,
I left them with mournful feelings on their account,
also on account of their large and interesting family.
At three o`'clock, attended our Select Quarterly Meeting.
It was indeed, a very low time.
The life of religion, I thought, almost at as low an ebb as it well could be.

14th.--Attended our Quarterly Meeting,
which was a very exercising time to me. I informed Friends that I had returned to
the Monthly Meeting the Minute granted me more than two years ago,
which was endorsed by the Quarterly Meeting,
that I had attended to the service for which I was liberated, as way opened,
in good degree, to the relief of my mind, except, in a few instances;
and one in particular, for the neglect of which I have suffered deeply.
And now it may be best for me to record it for a warning to others.
Several months before the war broke out, in the spring of 1861,
I had felt an impression that it would be required of me to go to Barnesville and
deliver a public warning in the main street of that town to the inhabitants thereof;
and the spot I was to go to, to deliver this message from the Lord,
was pointed out to me. The language contained in the ninth chapter of Jeremiah,
from verse 17th to verse 25th, had been sounding in my ears, month after month,
with a belief that some, if not all,
of that remarkable declaration would be required
of me to deliver in the street of Barnesville.
And being in that neighborhood on religious service in the spring of 1861,
and about to return home, a deep and weighty exercise came over me,
with an intimation to settle down and wait upon the Lord,
to see and know what He required at my hands,
so that I scarcely knew what to do with myself.
But I plead the necessity of returning immediately home,
having given my companions and their families to expect our return at that time,
I plead excuse, and thought when I got a little more strength I would yield,
or comply with whatever more might be called for at my hands in that place.
But alas! the day after I returned home,
news came to Barnesville that Fort Sumter had been bombarded,
and now all the town was in an uproar,
and everything out of order to hear a message
like unto the one I had upon my mind to deliver;
and indeed, the requisition has never since been made,
nor even a presentation of it. I now saw,
that a dream which I had some time before was fulfilled.
I thought in my dream that I was sick, and in a low, damp place,
and it was required of me to arise with the help of two Friends,
and go to a certain place a short distance from me, among some people, men,
women and children; whom I saw sitting quietly on raised forms,
and other places considerably higher than the ground I was occupying.
They appeared to be all busily engaged doing something, but I knew not what.
With the help of those Friends, I arose and went where these people were sitting.
When I came to them I perceived they were picking over wild plums,
which they had gathered in abundance,
and I thought in my dream that there had been an abundant crop of wild plums that year.
As I stood looking at the people,
it came into my mind to warn them to repent and turn unto the Lord;
but I plead excuse that I was too weak, and the motion to speak was not strong enough.
But while I was thus reasoning in my mind, and waiting for more strength,
they all arose suddenly as with one accord and dispersed,
running some in one direction and some in another, in great hurry and confusion.
Then I saw in my dream that I had missed the right time to deliver the message,
and that it never would return, and I was brought into great distress,
feeling satisfied that I should never again have the like opportunity,
for everything seemed to be in utter confusion; whereas a little before all was quiet,
and a suitable opportunity was given me to say what the Lord required of me.
I felt that the blood of those people would be required at my hands.
I saw in my dream the same Friends with me who were with me afterwards at Barnesville.
I thought in my dream that I followed some and tried to
engage their attention to hear what I had to say,
but they were quick and hasty in their steps, and appeared to heed nothing I had to say.

Then I thought all was over, and I must bear my burden alone,
and that I should never be able to get over the
sorrowful feelings this omission occasioned.
And so it has very much proved with respect to my omission of duty in the case related.
I have felt that the blood of many of the
citizens of Barnesville was required at my hands,
because I did not faithfully warn them to return, repent and live.
Many have gone from that town to the war, and have been since slain in battle.
My dream was fulfilled in a remarkable manner, for I had been sick,
or in very poor health,
and had been strengthened to get up and go to
Barnesville to attend to some religious services,
but lo, the time came when I must be proven whether I would give up all for his sake,
who died for me. I was disobedient to the heavenly vision,
and justly have I suffered for it. Amen.
The foregoing account of my omission of duty at Barnesville,
and the dream here related I have never before related to any one

Now, I think it right to leave in writing one or two more circumstances,
which may be a warning to others not to put off what
they believe the Lord is requiring at their hands.
It was, I believe, in the year 1837,
that the Lord required me to visit an innkeeper in the village of Flushing,
who was in the habit of selling spirituous liquors, and taking it to excess himself.
I had for some years felt at times a great weight on my mind concerning this man,
during which time he was brought very low with delirium tremens.
I then felt very fearful that if he should be
taken away by death in that awful condition,
that I should not be clear of his blood; yet the thought of visiting him,
and delivering the whole counsel of God unto him, was like giving up my natural life.
The latter would have been preferred, could it have been taken in place of the former.
But the Lord in mercy raised him up from this bed of affliction,
and he for some time entirely refrained from the poisonous draught.
Now it came before me that the time for visiting this man was about come,
and as I was expecting to go with a committee of the Yearly Meeting
to visit some Meetings belonging to Salem and Springfield Quarters,
the Lord showed me clearly that He required me
to go to see this innkeeper before I left home,
and moreover, he said to me, If you go not, a judgment will overtake you.
This was as clear to the ear of my soul as any
voice could be to my outward or natural ear,
and such were my feelings on this memorable occasion, that I said in my heart,
good is the word of the Lord,
and thankfully bowed in a feeling of acquiescence to his holy will.
But alas! the frailty of human nature.

The same evening my father and I were sitting alone in the house,
it came strongly and very impressively before me to mention the subject to him,
for his consideration and judgment, but I put it off until he left the room.
Then a dear aged aunt came in;
again I was impressed with the belief that I ought to mention the subject to her,
but I had weakened my hands already by letting my
father pass away without unburdening my mind to him,
and I said nothing to my aunt about it. The next
morning was the time pointed out for me to go,
and I concluded that when morning came I might feel stronger,
and would wait till I did before I said anything about it. When morning came,
I was weaker than ever, and had no strength to say anything about it,
so the concern died on my hands, and, strange to say, I thought but little, if anything,
more about it until the Lord awoke my feelings again to consider what I had done,
or rather, left undone,
by bringing the judgment upon me which He had promised
He would do if I did not obey his command.
I had started on my journey to Salem,
and when within a short distance of a Friend`'s house, and near our journey`'s end,
our carriage upset, and my right arm was broken, and the elbow joint dislocated,
or partly so. For a few minutes I was almost unconscious of what had happened,
but when recovered a little, I then remembered what the Lord had said to me:
"`If you go not to see this man, before you leaves home for Salem,
a judgment will overtake you.`"
And while some were censuring the driver for carelessness,
I was considering that it was only what I had justly brought on myself by disobedience;
and now I have ever since, a lame,
or rather a stiff arm to carry about me as a memento of that act of unfaithfulness.
I was not, of course, permitted to accompany my friends in this visit any further,
but was favored to get home in a short time, and as soon as my arm was well enough,
was glad to obey the call which was renewed, to visit this man,
which I did at three different times.
He received me respectfully and heard what I had to say,
except on one occasion he excused himself, professing other business to attend to,
which I thought was occasioned by the woman Friend who was with me. Poor man,
he died a few years after with delirium tremens,
so the warnings given were unavailing respecting him.

One more circumstance I will mention in this place:
Several years after this I was made uneasy with a certain article of my clothing,
which appeared to me of a texture I was required
to change for something more coarse and uncommon.
This, though a little thing, was like parting with a right eye or a right hand.
Long did I struggle, long did I reason;
sometimes appearing in the garb that I apprehended I was required to put on,
and again changing back.
In this way I went on for several years,
and I fully believe it was the pride of my heart that kept me from surrendering sooner.
I was often afraid, when I left home,
that a judgment would overtake me when I ventured to
wear that which had given me so much uneasiness.
In this situation of mind I met at one time with the Boarding School committee.
It was there, above other places, this cross was hardest to bear.

I was intending to visit a relation before returning home,
and begged for indulgence this once in wearing my favorite article of dress.
When about to leave the school for my visit,
having attired myself as I was accustomed to do, this language sounded in my ears:
"`You know not what those horses may be permitted to do,
before you reaches your nephew`'s;`" accompanied with a feeling of uneasiness,
for my halting, wayward course.
But these feelings passed off, and we went along cheerfully,
until we had nearly reached my nephew`'s, when suddenly one of the horses took fright,
ran a short distance with fury, turned out of the road,
and seemed like tearing all to pieces.
I said, as the horses left the road, We are gone!
I hope not, said my nephew.
The horses were suddenly stopped,
but not until I fully expected we should be upset and perhaps killed.
My nephew admired at the circumstance.
I think he said that he never knew this creature to do so before.
He saw nothing to scare the horse, but it seemed so affrighted,
that it trembled very much.
This put an end to my wearing that precious piece of clothing,
which I had so many checks and calls to give up;
for I fully believed it was the Lord who showed me how
easily and suddenly my life might then have been taken;
but in mercy He spared me. Oh,
the compassionate regard of my Heavenly Father towards the erring mortal;
what shall I render to Him for all his benefits?

Seventh Month 18th.--Heard of the death of M. J.,
an individual I visited about a year ago,
and was constrained to deliver a solemn and singular
warning to him to prepare to meet his God,
believing he had no time to put off the call.
Poor man, how thankful I feel that I am clear of his blood.
The cup of trembling was given me to partake of in his presence, and for his sake.
Astonishment seemed to take hold of him at the message I had to deliver.
I understand that strong drink was thought to be one cause of his death;
he was not an old man, but was past the meridian of life.

Eleventh Month 20th.--Returned home after an absence of more than five weeks,
having finished a religious visit within the limits of
Salem and Springfield Quarterly Meetings,
for which I was liberated in Fourth Month last.
I attended all the Monthly Meetings,
and nearly all the Particular Meetings of those two quarters,
and visited more than eighty families.
Also, again attended these two quarters.
The exercise of my spirit in this engagement none knows but the Lord.
I had very often to bring things so close home in families and meetings,
that it seemed almost more than some could bear.
May the Lord take away every stroke that was laid on the shoulders of any too heavy,
and give it to me to bear.

After an appointed meeting at New Garden for the young and youngish people,
and being about to go to Salem to engage in a family
visit within the limits of that Monthly Meeting;
this language very forcibly came before the view of my mind:
"`When the time was come that he should be received up,
he steadfastly set his face to go to Jerusalem.`"
And again,
"`The cup which my Father has given me shall I not
drink it?`" And this was the clothing of my spirit.
The way appeared clearly pointed out to me and I
was bidden to turn neither to the right hand,
nor to the left.
It was shown me where I should begin the visit, and the message I should deliver.
It was almost more than I knew how to bear,
and more than the individuals visited seemed able to bear in a Christian spirit.
I had to tell the head of the family that he was
clothed with a garment mixed with linen and wool,
over which was a coat of mail; and had to revive the language--"`Oh,
that you had hearkened to my commandments! then had your peace been as a river,
and your righteousness as the waves of the sea.`"
I believed it was the will of the Almighty that the filthy rags of
our own righteousness should be parted with and the pure white linen,
the righteousness of saints, be given us in place thereof.

Very close work I had in many families,
and the cup was indeed the cup of trembling which I had to drink.
At one place, having stayed all night and been treated kindly by the family,
after going from there to meeting,
I had to return in the evening and tell the woman Friend that
a fretting leprosy had got into her garments,
as well as a high, lofty spirit.
The Lord was willing and able to heal her,
though it might require the fire to work it out.
This was a hard stroke for her, but I dared not turn to the right hand or the left.
I had also considerable to say to her husband,
and he expressed satisfaction with our visit.
One place after another in the plain way I was required to go,
as the Lord strengthened me, and this He did in a marvelous manner,
both in body and mind.

Among those who have recently separated from their respective meetings,
I had to deal in a very plain way,
because I could not in the fear and counsel of the Most High,
according as it was sealed on my mind, do otherwise than condemn their course of action.
In the Monthly and Quarterly Meetings I had to tell Friends in a. very plain way,
how things appeared to me among them; and in our religious Society;
and that the Lord would sift us until we were a
people more to his praise than we now are.
I had to revive the testimony of Francis Howgill concerning our religious Society,
and express my full belief that his remarkable testimony would stand good.
I alluded to what he says concerning the covenant,
which the Lord made with this people in the rise of the Society when
persecution raged like a storm against the wall to destroy them.
(See Sewel`'s History, Vol.
ii, page 14.)

My dear friends Isaac Mitchell and Abigail Sears, were my companions in this visit,
the exercise of whose spirits I often felt to be helpful to me,
and comparable to Aaron and Hur, who held up the hands of Moses.
At one place, having dealt in a very plain way with the head of the family,
and being about to leave, as I took hold of the hand of this man to bid him farewell,
this language came very forcibly before the view of my mind,
with a belief that it might be right to express it: "`My son, hide it not.`"
We may remember that this was the language of Joshua to Achan;
but I shrank from apprehended duty and passed away;
but the distress which came over my mind, none but the Lord knows.
So, for the sake of peace I gladly went back again to his house,
and endeavored to deal out the whole counsel of God to him and his family.
As far as was given to see and know, gross darkness was there.
At another place, after delivering a very close testimony to the man and his wife,
I told them there was something hidden about that house, for darkness was there.

At another place, after sitting a considerable time in silence,
and feeling something to arise to communicate, and being about to do it,
I felt a sudden stop; and asked if all the family were present.
The father replied, all except one son, and he was not willing to give us his company.
I told them that under this circumstance I
should feel best satisfied to leave at present,
and if the Master required me to come again,
I would endeavor to do so. We went on another day,
but again the son refused to come into the house.
I asked the mother if she would be willing to go with me where he was at work.
She readily assented.
We found him husking corn in a field not far from the house.
He appeared very angry because of our coming, talked very unbecoming to his mother,
and looked so wicked, that I feared he would strike her.
I reasoned with him of righteousness and the judgment to come.
He told me he wanted to hear nothing I had to say, and cared nothing about these things.
I endeavored to engage his attention and followed him from one shock of corn to another,
but all appeared to be in vain.
If I had supplicated the throne of Grace on his behalf before leaving the field,
on the bended knee, I believe that I should have felt clear of him.
Such a hardened state in one so young I have rarely met with.
I did not suppose him to be more than eighteen or nineteen years old.

A few days after this I was at a funeral in another neighborhood,
where I had a close warning to give to some in the younger walks of life.
I afterwards learned that this young man was present, at which my heart rejoiced,
having had an opportunity to relieve my mind in a very
close warning without knowing of his presence.

While engaged in this visit we attended Sandy Spring Monthly Meeting; after which,
on passing a Friend`'s house in that neighborhood, it forcibly presented to my mind,
that I must visit the family residing there before returning home,
and I concluded to do so; but said nothing about it to any one,
and the concern and remembrance of it passed from me. On our way home,
when we came to the road which led to this house,
I felt a strong presentation to take that road and lodge at a Friend`'s house
some miles short of the place we were intending to reach that night.
But this family visit had so gone from me that I did not remember it
until after we had left the road leading to the house.
Then my burden greatly increased, and I knew not what to do. It was raining fast,
the road very hilly and slippery, night near at hand, our horses very tired,
and we some miles from the road where we should have turned in;
and had it not been for the encouragement of my kind companions,
who were by this time acquainted with the burden resting upon me, I should have gone on.

We now turned back,
and made the best of our way through the rain and over the
hills till we reached the Friend`'s house just at night,
where we should have stopped had I attended strictly to
the pointings of the Master at the road leading here.
I felt greatly humbled and unworthy of the least regard of my Heavenly Father;
conscious of my waywardness and lack of faith in his pointings to duty.
Next morning, very early, I informed the Friend and his wife where we lodged,
of my concern to visit the family before alluded to,
but as the man`'s wife was not a member among Friends (being a Hicksite,
of which I was not aware),
it was thought improbable that such a visit would be
acceptable (a Friend having recently been denied such a visit),
but application being made the request was granted,
and we had a more satisfactory opportunity than was anticipated.

The father, mother and daughter were tendered, especially the daughter, who wept freely;
being a gay young woman and not a member among Friends.
I could but rejoice greatly, yet not without trembling;
and a feeling of deep humiliation that way was made for me to relieve my burdened mind,
after having so nearly put myself out of the
reach of complying with my Master`'s requisition;
and consequently must have carried a great burden home with me. The Friend and his wife,
at whose house we lodged, went with us to this family.

Not long after this visit the wife of the Friend where we lodged, and the one visited,
were laid in the silent tomb; also the daughter then present.
I was exercised in that opportunity that all might be prepared for the hour of death,
that it often comes at an unexpected time, and in an unexpected way.
When in this neighborhood on a religious visit ten years before,
I hastened home and left some duties neglected, for which I suffered much,
and now I had nearly done the same again.
May I learn obedience by the things I suffer.
Surely the Lord has had patience with me more than I can possibly describe.

Seventh Month 24th, 1864.--What shall I render unto the Lord for all his mercies.
I have now partially recovered from a severe attack of erysipelas in my head and eyes.
At one time during my illness the stroke of death seemed near at hand.
So great was the heat in my head, that it seemed as if I was holding it over a hot fire.
While the rest of my body was so cold as to require warm
mustard baths necessary to keep up the circulation,
cold applications were constantly applied to my head.
Great was the suffering, not of pain but of heat and inflammation of the brain,
but through all I was permitted to retain my senses, which I esteemed a great favor.
May I number my days and be prepared for a sudden summons from
works to rewards which may be my experience,
that is, a sudden removal.

On the 7th of the Seventh Month,
1865,I returned home from a visit within the limits of Philadelphia Yearly Meeting.
Great were the exercises of my spirit while engaged in this visit,
and many sore trials I had to pass through.

Previous to laying the subject of this visit before my friends,
I had been confined to my room and bed nearly seven months with a severe illness;
the disease appeared mainly to be dropsy of the chest and an affection of the heart.
The subject of visiting some meetings within the limits of that Yearly Meeting,
particularly the meetings belonging to Cain, Concord and Philadelphia Quarterly Meetings,
and some families within their limits; also to attend the Yearly Meeting,
had for several years at times weighed heavily on my mind.
But during the greater part of this illness it looked
altogether improbable that I should ever accomplish the visit.
I remarked to two Friends who were waiting on me,
that I had expected it would have been required of me to go to Philadelphia,
but now it does not look likely I shall ever perform the visit.

But in the First Month of the year 1865,
although not able to sit up out of bed but a little while at a time,
yet on First-day previous to our Monthly Meeting,
I felt that it was required of me to go to meeting,
and though it was judged very unsuitable weather for an invalid to ride out,
yet I attended to the Master`'s bidding, and went;
and had to deliver a testimony for the Truth and felt none the worse for going.
The next Fifth-day was Monthly Meeting, the weather very cold,
and everything as to the outward forbidding me to turn out;
but the Lord gave me an assurance that He required the sacrifice at my hands,
which left me no room to doubt.

On the evening previous to the Monthly Meeting (the weather still being very cold),
while considering the prospect before me,
and being desirous above all things to do the will of the Lord herein,
in addition to that grain of living faith, which can remove mountains,
this Scripture was brought forcibly to my remembrance,
"`Ask you a sign,`" while I was ruminating on this language so
impressively brought before the view of my mind,
it was sounded in the ear of my soul,
I will give you a sign--"`The weather shall be three
degrees warmer in the morning than it is this evening.`"
Then I called M. W., the young woman who was waiting on me,
and requested her to look at the thermometer and bring me word concerning the weather,
which she did.
In the morning early I made the same request without letting her or any one know
why I did so. And found by her reports the Lord had verified his promise,
which was a confirmation to my mind,
and produced a feeling of deep humiliation in
view of the condescension of the great I Am,
towards a worm of the dust.
With that grain of living faith which can remove mountains I went to meeting,
having to be carried to the carriage, and also out of the meeting-house,
when the meeting was over.
When I laid the subject before Friends they were greatly surprised,
and considering my great bodily weakness,
and the improbability that I could ever perform the visit, a long silence prevailed.
Then one after another was moved by the influence of
Truth in their hearts to unite with the concern,
until full and free unity was expressed therewith,
and I felt now satisfied to leave it with the Master.

During the interval between this meeting and the Quarterly Meeting,
I had a very severe turn of disease,
and some of my friends thought the will would surely be taken for the deed,
and I would be released by death.
The day previous to our Quarterly Meeting,
having the company of our friends Joseph Edgerton and wife,
I alluded to the weighty service in prospect, and remarked,
that considering my great bodily weakness the will might yet be taken for the deed;
to which Joseph replied with emphasis, "`Rest satisfied,
you will be strengthened in body and mind to perform this visit.`"

Next day I was strengthened in body and mind to attend
meeting and lay the subject before Friends.
The Quarterly Meeting fully united with the concern, and liberated me to attend thereto.
Elizabeth Smith, a minister, remarked in the meeting, "`This is the Lord`'s doings,
and marvelous in our eyes.`"
After this I was repeatedly quite ill,
so that the prospect of performing the visit according
to human calculation appeared impossible:
but it may well be asked,
is anything too hard for the Almighty? For He who required the service,
strengthened me with might in the inner man,
and also gave me bodily strength to perform that which
to the human understanding appeared impossible.
