== Chapter IX

[.chapter-synopsis]
* Protracted Illness
* Private Spiritual Exercises
* Interview with Daniel Koll
* And Opportunities with other Individuals
* A Religious Visit to Indiana
* Iowa
* And the Western Parts of Ohio; And the Peculiar Exercises and Trials Connected Therewith
* Death of Her Brother, Jacob Branson, and Her Accompanying Feelings

After my return from this visit,
I was able to get out to meeting quite regularly
until about the middle of the Second Month,
1866, when my health again gave way,
and I was pretty closely confined to my bed for about eight months,
being unable during that time, and even some longer,
to walk a step without suffering in consequence,
and often had turns of great prostration of bodily strength,
which seemed to threaten at times, immediate dissolution.
But He who holds our lives in his hand, saw fit to order it otherwise,
and He again raised me up, to enjoy tolerable health and strength:
when I first began to attend our religious meetings, after this indisposition,
I had for some weeks to be carried in and out of the meeting-house, being unable to walk.

Third Mouth 3rd, 1866.--I feel like recording my feelings on the evening of the 28th ult.
After spending the afternoon of that day in earnest desires that I might be searched,
tried and proven, that if anything remained in my heart contrary to the will of God,
that I might be enabled to bear the cleansing,
purifying operations necessary to remove it, whatever it might be:
that nothing might stand in my way of acceptance with the Beloved of Souls.
After the Lord had begotten this exercise in my heart, He did condescend,
in a marvelous manner, to break through all weakness,
and the feeling of unworthiness which for some time had been the clothing of my spirit,
so that I had felt afraid to take his name in my mouth,
and He did pour into my soul the song of thanksgiving,
praise and high renown to his own worthy name.
He did clothe my spirit with praise, as with a garment.
He sent his angel and rolled away the stone from the door of the sepulchre.
He removed every restraint, and gave me to see and feel that He is the same today,
yesterday and forever--that nothing is too hard for Him to do--
that He has all power in the visible and spiritual creation.
And when I had remained under this feeling for some time He gradually
withdrew the overflowing fulness from my heart and left me in the
enjoyment of peaceful acquiescence to his holy will,
trusting that as He cares for the sparrows, so He would care for me. I said,
I will praise you, O God, with my whole heart--I will utter the song of thanksgiving,
glory, honor and high renown unto my God: Praise Him, O my soul, in heights,
and praise Him in depths--when He hides his face from you,
praise Him by keeping hold of that little grain of living faith mercifully vouchsafed,
which will keep you from despair, in the most dark and gloomy hour:
and when He arises for your deliverance, and shows you the light of his countenance,
keep your heart with all diligence,
lest after having sung his praise as on the banks of deliverance, like Israel of old,
you forget his works and cause his hand to be turned against you.
My spirit had at times for months previous to this, been in the deeps, in travail,
exercise and sympathy for and with some, who had widely strayed from the path of peace,
whose dwelling seemed to be where there was no ray of light.
I felt, as it were, the weight of mountains pressing upon me,
and as the floods of deep discouragement and despair,
presented and awfully threatened to overwhelm, my prayer day and night was, Lord,
be graciously pleased to have mercy,
and in your great and wonderful mercy be pleased to prevent the awful
calamity of hopeless despair from overwhelming those who feel that
they have greviously revolted from your law and commandments;
and bring them to see and feel, that though their sins be as scarlet,
you can make them white as snow, and though red like crimson, you can make them as wool,
though their sins be many and grievous, you,
in your compassionate mercy are ready to forgive
and blot out as there is a bowing before you.
Oh, that I could write my feelings in a book,
that I could persuade the sons and daughters of men,
to whom the arms of everlasting mercy are stretched out for their help and recovery,
to lay hold of the hope set before them.
Oh, that I could persuade those who are still in the
bonds of iniquity and resting under a false hope,
to turn unto the Lord, who will have mercy, and to our God, who will abundantly pardon.

The foregoing has been written on a sick bed,
to which I have been mostly confined for some weeks past.

Eighth Month 23rd.--Received a visit today from Daniel Koll and David Conrow.
Daniel has been one of the leaders in the late separation in our Yearly Meeting,
and David has followed their footsteps.
All the family having gone to Monthly Meeting except the colored woman,
I had no idea who was about to enter my room
until they came in. When I shook hands with them,
Daniel remarked that hearing I was confined to my room by indisposition,
and being in the neighborhood, he felt like coming to see me; to which I made no reply,
but asked them to sit down.
The prayer of my heart then was: "`Lord,
preserve me from uttering a word uncalled for by you;`"
and the desire was that if consistent with his will,
I might be permitted to spend the time in silence.

After a few brief inquiries and answers respecting my health, we dropped into silence,
which remained undisturbed for a considerable time,
during which I felt this precious invitation awaiting
the acceptance of those to whom it was applicable,
and very sweet and precious did the mercy of God feel to my soul: "`Return,
you backsliding children, and I will heal your backslidings.`"
But still I felt in hopes I might be permitted to pass the time in silence.
After this the language of the prophet came before me:
"`Take away from me the noise of your songs;
for I will not hear the melody of your violins;`" and I
felt that I should not be clear without reviving it,
and so I did.
I told Daniel that he had been visited of the Lord,
his understanding had been opened to see the beauty of holiness,
but for the lack of keeping his eye single to the Lord and following the true light,
he had become as a vessel marred on the wheel,
so that this language appeared applicable unto his situation:
"`Take away from me the noise of your songs;
for I will not hear the melody of your viols.
But let judgment run down as waters,
and righteousness as a mighty stream,`" in the temple of your heart: and again,
"`O that you had hearkened to my commandments! then had your peace been as a river,
and your righteousness as the waves of the sea.`"
I told them that the foundation they were resting on could not stand;
that nothing pleased the enemy better than to
get people into a false rest and false peace.
They knew I had never given countenance or encouragement to the steps they had taken,
that is, withdrawing from their respective meetings and setting up separate ones;
and because I had dealt plainly and honestly with those
who had thus departed from the right way,
I had been accounted their enemy.
But of one thing we are all aware,
that we must independently of any arm of flesh to lean upon,
separately and singly stand before the judgment seat of Christ,
and receive a reward according to the deeds done in the body;
and the ardent prayer of my heart for them, as well as for myself, is,
that we might be able in sincerity of heart to adopt this language: "`Search me, O God,
and know my heart, try me and know my thoughts, and if there be any wicked way in me,
do you it away.`"

I told Daniel he well knew that I had dealt plainly and
honestly with him some years ago when at his house,
letting him know that I had no unity with the course he was pursuing He said he knew it,
but his desire was to do right.
I told him I fully believed he was in an error and deceived, and you too [David]
who had joined with him in this separation.
That he was amongst the first at Salem who took this step,
and a great weight and responsibility rested upon him.
I said, do not be going about strengthening the wrong and weakening the right.
I said to David, oh,
that you were still a member of our meeting deepened in the root of life,
so that you could dig with the staff of faith for the arising
of the well-spring of life in yourself and others.
He replied, that his desire had been to do right.
I answered, but you are, I believe, deceived.
They both gave me to understand that they did not look upon me as their enemy.
I said, I must be clear.
I pray God that you may do that which is right, though we be accounted as reprobates.
But I trust you shall come to know that we are not reprobates.
Daniel said, he had no counsel for me;
he left the Yearly Meeting because it had left the right foundation.
I told him I believed in the view of Lydia Ann Barclay, namely:
That separation brought about in the will and wisdom of the
creature was like one worldly spirit separating from another,
and great reproach will be entailed on the blessed cause.

Twelfth Month 23rd, 1867.--Yesterday I entered my sixtieth year;
how solemn the consideration that I have lived so long on this earth
and done so little to promote the Redeemer`'s kingdom amongst mankind,
yet the prayer of my heart has been ever since I was young in years,
that the Lord would so deal with me, as to fit me for my latter end,
no matter what strokes it might take.
And I can say in looking over my past life,
the Lord has dealt marvelously and very graciously with me: Blessed,
praised and magnified be his holy and adorable name forever;
and let all the world say amen.
For He has preserved my life both naturally and spiritually,
through many sore conflicts of flesh and spirit.
"`When I said my flesh and my heart fails, your mercy, O God, held me up.

30th.--My spirit has long been and still continues to
be greatly exercised on behalf of my nephew L. B.,
whose welfare I have earnestly sought, not only by giving counsel,
admonition and encouragement to pursue the right path, the path that leads to peace,
but the fervent petitions of my heart have often been
raised to the Father of mercies on his behalf.
Oh, that his heart might be turned to seek after durable riches and righteousness,
before the day of his merciful visitation passes over.

First Month 14th, 1868.--I have just been conversing with an individual,
who some years ago was a serious, sober-minded young man,
apparently much concerned for the welfare of his own soul, and that of others;
but who by giving way to a wrong spirit, stumbling at the faults of others,
and forsaking the Truth, has become a poor, wandering outcast,
and literally a vagabond upon the earth.
The show of his countenance does witness against him,
having the look of a hardened sinner; and yet mercy, unspeakable mercy,
seems still to follow him,
and he appears to be aware in some measure of his wretched and forlorn condition.
Oh, you who gathers souls as from the pit of corruption,
have mercy upon this man as you had upon the one that met you out of the tombs,
exceeding fierce, who was afterwards found sitting clothed, and in his right mind.

Third Month 18th.--Attended the close of the winter session of our Boarding School.
Went under considerable discouragement and some difficulty,
the roads being very bad and tedious to travel over,
but I was favored to return home with an easy mind,
which more than compensated for all difficulty.

On my way home, attended Harrisville Meeting, and there, as well as at school,
had something to communicate in the way of the ministry,
which was relieving to my feelings.
On our way from this meeting to the Friend`'s house where we dined,
I noticed an aged man in a field by the roadside.
When I saw him my heart was moved to address a few words to him in the love of the gospel.
I halted a little and then proceeded onward,
but finding I should have a burden resting upon me if I did not yield,
I requested the Friend with me to invite the stranger to the carriage.
He came without hesitation, and received what I had to say with respectful attention,
saying he was thankful for the opportunity.

After dinner, went to the house of a Friend, and found him and his wife at home,
his wife`'s father being there also.
I laid before them the concern that rested with me on account of the lack of true love,
Christian patience and forbearance apparent in the heads of that family,
relieving my mind in a very plain way to the father in particular,
and also to the others.
I felt thankful for the opportunity afforded for clearing myself on this occasion,
and when I had done so, proceeded towards home.

As we entered the town of Harrisville,
I noticed two men near the roadside conversing together.
As soon as I saw the countenance of one of these men,
this language ran forcibly through my mind--"`Repent before it be too late.`"
After passing them, I found I should carry a burden with me,
if I did not stop and leave a message and warning with them.
I therefore requested the Friend who was driving the carriage, to halt.
After waiting a few minutes in silence,
I requested that those two men might be invited to the carriage.
They came and heard respectfully what I had to say.
After which I felt relieved and humbled, going on my way with a thankful heart.

On the 26th of Fifth Month, 1868,I left home,
accompanied by my cousins Asa Branson and Abigail Sears,
to perform a religious visit amongst those professing with Friends and others,
in some parts of a few States west of our own, and also in some parts of Ohio.

Attended Stillwater Quarterly Meeting on the 27th,
and on the 28th we took the cars at Barnesville for Indiana,
and about six o`'clock that evening arrived at my brother Isaiah`'s,
four miles north of Richmond, in Wayne County.
I was very much fatigued with the day`'s ride, but a night`'s rest recruited me finely.

On the 29th,
we went to Earlham College (a high school under the care of Indiana Yearly Meeting),
in pursuance of that which I believed my religious duty.
I informed the Principal, Barnabas C. Hobbs,
that our business there was to request a Meeting for Worship
with the students and inmates of that institution.
We gave him our certificates, which he read aloud to his wife.
They both expressed a willingness that we should have a meeting,
but said it was the time of review,
examination was coming on and it would be difficult to spare the time, etc.
Barnabas said he would consult other officers on the subject as he
had no right to grant the request without the consent of others.
After consulting with those he selected,
he informed us that they had concluded they could spare about one hour for the meeting.
I asked him if it was to be understood, that the time was limited to an hour.
He replied that that was what he was instructed to say--one hour, or at the furthest,
an hour and a quarter.
I told him I could not appoint a meeting on such terms.
It was not for us to say, just how long a Meeting for Worship should hold.
It was the prerogative of the Head of the Church
to open the way for a religious meeting to close;
such a limitation act was not in accordance with the principles of Friends.
His wife owned that it was not right ground to take,
regretted we could not be there on meeting-day, etc.

Barnabas said,
we have a system for the management of our school--clock-work for all
the recitations--and there were many students that were not members,
their interest and feelings had to be taken into the account.
But the main thing in all their excuses was, I have no doubt,
that they had not unity with us in our religious engagement.
I told Barnabas that the Lord in his own way and time would sweep away from
our midst this compromising spirit which was laying waste the Society,
and preserve a remnant,
and add to that remnant those who would stand for the
principles and testimonies of the Society,
as promulgated and upheld by Friends in the beginning.
I said considerable to him in the presence of some of the male teachers,
who I was willing should hear.
I told him,
that the time would come when all worldly honor and popularity
would burst as a bubble upon the mighty ocean,
not affording a ray of comfort or consolation.
This was only a small part of what I had to say.
I had been acquainted with Barnabas while he was teacher in Ohio Boarding School,
and did not then consider him a Friend in principle,
and he appeared not to have gained anything in that way since he left our school,
though he is an acknowledged minister in Indiana.
After a pretty full expression relative to their innovations touching Society matters,
we left them with feelings of sadness.

Went to Richmond,
to ask for an appointed meeting amongst those
professing the name of Friends in that city.
We laid the subject before an elder,
who agreed to call a consultation of ministers and elders,
and let us know the result of the conference.
We received information next day,
that they thought it would be a violation of
their Discipline to appoint a meeting for us,
but they were very free that we should attend their meeting on First-day,
and if we had anything for them in the way of the ministry,
they desired we might feel all freedom,
as they granted this privilege to ministers of other religious denominations.
But we declined to accept their invitation.

We next applied for a meeting at Chester, but the same results followed.
They wished us to attend their meetings,
but we told them we felt no more freedom to go into their meetings,
than the meetings of other denominations.
We staid at my brother`'s one week; during which I was under great exercise of mind,
as much so as I ever remember to have been.
I felt that I could do anything for the sake of that peace which the world cannot give.
Although thus exercised,
I did not feel any condemnation in relation to setting out on this visit,
neither as regards my movements since leaving home,
but my sorrows were stirred within me on seeing and feeling the sad and benumbed
condition of those professing the high and holy profession of Friends.
But when my heavenly Father had let me feel this depth of sorrow,
and the low and suffering state of the true seed, He opened our way to move forward,
and we left Wayne County on the 4th of the Sixth Month, and proceeded to Spiceland,
in Henry County, a distance of about fifty miles.

We stopped with Jason Williams, who married my cousin Abigail Holloway.
I asked Abigail (her husband having gone to Richmond to attend a
Meeting for Sufferings) if she thought the elders and heads of their
meeting would be willing to appoint a meeting for us next day,
at some suitable hour.
She thought they would, and said she would go and see some of them, which she did.
Presently two elders came in to see us, and asked what our wishes were.
I told them they were perhaps aware that we were from that
Body in Ohio which Indiana had designated as Separatists;
nevertheless, we believed we were from the legitimate Yearly Meeting of Friends in Ohio;
and had come among them in gospel love,
desiring a meeting the next day if there was a freedom amongst them to appoint one.
They asked whether we would appoint meetings for
one of their ministers? Cousin Asa replied,
that he expected we would not.
They thought the rule ought to work both ways; we were not willing, they said,
to do as we would be done by. Asa replied, the rule ought to work both ways,
provided things were equal.
They then asked if we considered them unsound.
Asa replied, that we had not charged them with unsoundness,
but the Yearly Meeting had given support to unsoundness.
These elders said we might attend their meetings, and feel a freedom in them,
as they admitted ministers from the Methodists, Presbyterians, etc., into their meetings;
and asked what we would do if such ministers were to
come to our meetings and preach amongst us. Asa replied,
they would be civilly requested not to disturb the meeting.
One of these elders said George Fox would not have made such a request--that is,
to silence such in our meetings.
Asa said, I think he would.
Then those men left us, and collecting several more of the heads of the meeting,
held a consultation, and concluded to allow an appointed meeting next day,
at three o`'clock.

The meeting was held, but was quite small, and I apprehend but little notice was given;
besides,
such was and is the prejudice against our Yearly Meeting that many
are afraid to be seen or known as showing us any countenance.
A woman belonging to that meeting appeared in supplication,
and I and my companions kept our seats the while.
I had some encouragement to offer to those present,
the language of whose hearts was on this wise: "`Oh,
that the salvation of Israel were come out of Zion!
when the Lord brings back the captivity of his people,
Jacob shall rejoice, and Israel shall be glad.`"
I referred to the faith and faithfulness of Noah and Job,
how they were preserved amidst surrounding influences of the most
trying nature by keeping hold of that which showed them the right way,
not turning to the right hand or left.
This exhortation flowed freely towards those who were sorely tried
and knew not what to do. Another state was spoken to. I said,
those who were trampling upon those principles and testimonies
for the maintenance of which our early Friends suffered so
much would fare no better than Belshazzar if they repented not;
who having made a great feast and while drinking wine out of the
golden vessels which had been taken out of the house of the Lord,
and carried to Babylon,
was suddenly brought to confusion and trembling by seeing the
fingers of a man`'s handwriting upon the wall of his palace,
and neither he nor any of his wise men could read or interpret the writing;
yet one was found in his dominions who was made to understand it. Yet it was not
until the prophet Daniel had clearly set the sins of this wicked prince before him,
that he proceeded to read and interpret the writing.
"`God has numbered your kingdom and finished it. You are weighed in the balances,
and are found lacking.`"
Thus I had to warn some present of the evil of their ways,
and counsel them to turn unto the Lord before it be too late.
Lodged that night at our cousin,
David Holloway`'s. There we had very plain talk with
some who came in to spend the evening with us,
concerning the inconsistent practices which had gotten in amongst
those professing to be Friends in those parts and elsewhere.
Alas,
alas! will not the Lord break the fetters in some way with which this people are bound.

Sixth of the month.--David Holloway took us to Duck Creek, six miles from Spiceland,
where a meeting had been appointed to be held at three o`'clock that afternoon.
It was small, yet way opened to relieve my mind amongst them in a plain close testimony,
and also in supplication.
Cousin Asa had a short communication with these, and also at Spiceland.

Dined at John Spencer`'s. Before leaving his house,
I had a few words to speak to him in the way of warning and counsel,
to use all diligence to make his calling and election sure,
while time and opportunity were afforded.
Jabez Henley, a minister belonging to Duck Creek Meeting,
took us that afternoon to Cadiz, a distance of five or six miles.
There was considerable conversation on the way concerning Society matters.
We thought Jabez was a pretty thorough Gurneyite.

Next day being First-day, we were strongly solicited to attend their meeting at Cadiz;
saying we might feel all freedom to do so,
and exercise ourselves in the ministry if anything was required.
This solicitation we declined there, as well as elsewhere,
and requested a meeting amongst them at three o`'clock p.m. It was appointed,
and well attended, and proved an open and satisfactory meeting.
"`One of the principal elders expressed his full unity with us,
desired our encouragement, hoped the Master would be with us.

Went the same evening to see cousin R. Holloway, son of Uncle Robert Holloway.
After a religious opportunity with Robert and wife, his brother-in-law and wife,
we left them under much exercise of mind.
How sorrowful it is when children, who have had the care and counsel of godly parents,
turn a deaf ear to the voice of instruction and choose
the path that leads down to the chambers of death.
May the son yet see and feel the path he is pursuing to be as it really is,
the way to destruction, and become as a brand plucked from the burning,
is and has been the prayer of my heart for him.
I might have left that house with a clear conscience had I
relieved my mind fully towards an invalid woman present;
but my omission herein paved the way for further delinquency.
As we proceeded towards the Friend`'s house where we lodged,
it came forcibly before me to halt at a house we were about to pass,
but feeling very weary, I allowed myself to pass by it before inquiring who lived there.
I then found it was the elder who had spoken to us at the meeting house,
and he and his wife had kindly invited us to call with them.
I now saw I ought to have halted and made them a call,
feeling something in the way of encouragement and counsel for them.
But I proposed to return next morning and do my evening work,
and so with respect to another house I passed the same evening;
but the Lord`'s time is not our time.
In the morning no way opened for me to return to those houses,
and I had to carry my burden with me. That evening came
a young man and his wife to our lodgings.
After a chapter had been read this young man went down on his knees
and had quite a lengthy communication in the form of a prayer.
During his exercise, I felt my mind solemnly impressed with this Scripture passage:
"`Let every one that names the name of Christ depart from iniquity.`"
I had to speak very plainly relative to the ministry,
how the apostles were called thereto, that it was of necessity they spoke,
and their speech and preaching was not of the enticing words of man`'s wisdom,
but in demonstration of the spirit and of power.

That such should be and must be the call and
qualification of gospel ministers in the present day.
No man takes this honor unto himself but he that is called of God as was Aaron.
The poor young people are exampled and encouraged to
set about preaching by the older ones,
and by the example one of another,
many of them having no call to the work from the right source.

Next morning we had much conversation with this young man in
the presence of his wife and brother-in-law`'s family,
in regard to the principles of Friends,
showing him wherein many professing to be Friends were leaving the true ground.
He seemed to think we should always be ready to explain and expound the Holy Scriptures.
I told him there was but one key to the Scriptures,
and that was the spirit by which holy men of old wrote them,
and those who went about explaining them in their own
will and according to the wisdom of man,
would only wrest and pervert their true meaning.
On taking leave of this young man,
he expressed his satisfaction in being with us and hearing what we had to say;
hoped he would improve by it. Left John Bufkin`'s
that afternoon and went back to Spiceland.

Sixth Month 9th.--We obtained leave to visit the large school at Spiceland,
Clarkson Davis, Superintendent.
We had a religious opportunity with the scholars
and teachers to pretty good satisfaction,
but I felt all were not present whom I desired to see;
and found afterwards that some of the older scholars were in another apartment.
Returned to J. W`'s and had a religious opportunity with him and his family.
I had to use great plainness of speech,
which was hard for me and hard for some of the family to bear; but before we left,
his wife said to me and my companion,
"`I expect there is cause for your remarks and exercise;
I expect we have not been as faithful as we ought to have been.`"
Surrounded as they were and had been with wrong doings,
and those who were going too fast, leaving the principles and testimonies,
she thought it was likely they had not stood their ground as faithfully as they ought.
She further said, "`When our son lay on his death-bed,
he had several Friends called in--heads of our
meeting--and gave them much counsel and advice,
warning them against the fast doings and wrong doings which
are amongst us.`" This she told us (or words to this import as
near as I can remember) in an honest and respectful manner.
And I could but believe that if her husband would but let the
witness for Truth speak out plainly in the temple of his heart,
that he could not say he saw no cause for my close dealings with him.
The same day we hired a conveyance to take us to Walter Edgerton`'s,
brother of Joseph Edgerton.
He had an invalid daughter, with whom I became quite interested,
believing she was a pious young woman, but appeared to be fast declining.
While there I felt a concern to see his son and family, who lived near by,
but found he was working some distance from home;
and it being a busy time with the farmers,
I had well nigh reasoned away my concern and made work for repentance,
but having felt the burden of putting by duties to be great,
I requested the man invited to give us his company, which he did,
and had a religious opportunity with him and his wife, somewhat to the relief of my mind.
The husband expressed his thankfulness for the visit.

We left Spiceland for Kaysville; stopped with Samuel Pritchard, an elder.
In the evening, after a chapter had been read in the Bible,
I had unexpectedly to myself something to communicate
in the way of encouragement to faithfulness,
no matter what surrounding influences we might have to contend with,
citing them to Job and Noah as examples.
After this little opportunity,
Samuel showed more openness and kindness towards us. The same evening,
I laid a concern before them that rested with me
to appoint a meeting in that neighborhood.

The next day, being their meeting-day in course, they desired we would attend,
but for reasons already spoken of, we could not comply.
We made them acquainted with our objections as well as we could,
but could not satisfy them of the propriety of our refusal.
Samuel`'s wife said, by refusing to attend our meeting and requesting one appointed,
you are throwing yourselves into the hands of those who
do not know their right hand from their left.
She thought the heads of the meeting would not allow it.
But after consulting with other members,
it was concluded we might have a meeting at two o`'clock that afternoon.
It was held, but very small, nearly all being afraid to give us their company,
fearing the rulers, and that they would lose their good name.
The meeting was silent, except a few words at the close,
which were these--"`When the Lord shuts none should attempt to open, and when He opens,
none should attempt to shut.`"
It was a very suffering season,
as much so as I remember to have passed through in a religious meeting.

Samuel Pritchard took us that evening to Carthage, five or six miles from Raysville.
We had considerable conversation on the road relative to the
state of Society in that Yearly Meeting and elsewhere,
which I hope will be some advantage to Samuel.

At Carthage we put up at Henry Henley`'s, an elder.
We proposed to Henry and his wife,
the appointment of a meeting on the afternoon of the next day.
It being their meeting day in course, they urged us to attend;
but we felt constrained to bear a faithful testimony against the
doings of Indiana Yearly Meeting and its subordinate branches,
in uniting with and owning the Binns`' Yearly Meeting of Ohio,
and also to bear a faithful testimony against the unsound doctrines
and practices which are sweeping Quakerism from their midst.

Henry laid our request before other members of their meeting, and after the consultation,
we were informed that there was not a freedom on the part of those consulted,
to grant the request.
I asked Henry (in the presence of some others)
what objections they had to our having a meeting.
He replied,
that one objection was that they understood that I was
opposed to the doctrines of Joseph John Gurney,
and that their Yearly Meeting (Indiana) had officially
acknowledged all his doctrines to be sound,
etc.
William Johnson, a member present,
said that my objections to Joseph John Gurney`'s writings was
not the only reason they objected to our having a meeting.
Henry replied, it was the first objection brought forward.
Henry then informed us that Indiana had,
through a document introduced into the Meeting for Sufferings by Elijah Coffin,
and approved and sanctioned by that meeting, and forwarded to the Yearly Meeting,
and fully approved and endorsed by the latter,
owned and acknowledged all the writings of Joseph John Gurney to be sound and scriptural.
I told them that those unsound writings of Joseph John
Gurney were doing just what Thomas Shillitoe,
on his death-bed, said they would do, were they not suppressed.
They have spread a mixed garment of wool and linen over the Society,
and the Society was gradually going down,
as that devoted servant of the Lord said it would, if they were circulated,
and allowed to pass uncondemned by Friends.

I further said, they are sweeping Quakerism from your midst.
Wilson Hobbs, a doctor in the village, coming in,
and being as I apprehended from his conversation one of the fast ones,
we had much conversation with him and others present in a very plain way.
It seemed laid upon myself and the Friends with me, to speak out boldly for the Truth,
without the fear of man.
One present (I think William Johnson) remarked: We let Methodists, Presbyterians,
Universalists, etc, attend our meetings, and preach amongst us. I said,
what can you expect from the young people? Friends have
a testimony against a hireling ministry,
war, formal preaching and praying, etc.
You admit ministers of other denominations amongst you who
have no testimony against these anti-Christian practices;
they captivate your young people by their eloquence and oratory,
and many are drawn away from the testimonies and principles of Friends;
while at the same time you are holding out the view
that the principles of Friends are spreading.

Although not many meetings could be obtained amongst them,
yet I thought our work was going on by talking with and
plainly setting forth to those in the foremost ranks,
the anti-Quaker sentiments and practices prevalent amongst them.
In looking towards appointing meetings with those not professing with Friends in Indiana,
this language would immediately spring up--
"`Into any city of the Samaritans enter you not.
But go rather to the lost sheep of the house of Israel.`"

Henry Henley and William Johnson took us to Walnut Ridge,
and we put up at Thomas Hill`'s. There again we requested a meeting,
but it could not be obtained.
Thomas Hill confirmed the statement of Henry Henley concerning
the official acknowledgment by Indiana Yearly Meeting,
of the doctrines and writings of Joseph John Gurney.
Thomas and wife appeared to be much distressed on
account of the sad state of things in this meeting,
but seemed to see no way to help it.

On the 12th, we took the cars for Indianapolis,
and arrived at Asa Hunt`'s on the evening of the same day.
We found Asa from home,
but proposed to his wife the appointment of a meeting next day at ten o`'clock.
She said she would see one of her neighbors,
and know what he thought of it. Her neighbor, William Hadley came in,
and said he could not speak for others,
but as for himself he should not favor the appointment.
He said there was to be a meeting next day at Plainfield,
of the Quarterly Meeting`'s committee having charge of Sabbath schools,
and most of their members would be leaving.town on the morning train.

I felt like seeing some others of their head members,
and learning that Enos Prey lived in town,
William Hadley went with cousin Asa to his house.
Pretty soon, Enos (who is a minister) and a woman preacher by the name of Trueblood,
came to our lodgings.
The way opened for conversation with Enos Prey, which tended to the relief of my feelings.
Enos said he had read considerable of the writings of Joseph John Gurney,
and was also familiar with the doctrinal views of Fox and Barclay,
and he could unite with all; he saw no discordance in their doctrinal views.
I told him that was strange; I thought there was a great difference.
He desired me to cite him to something in particular.
I cited him to this text--"`We have also a more sure word of prophecy, etc.,`" saying,
Joseph John Gurney calls this more sure word the Scriptures;
you know this is not the doctrine of Fox and Barclay.

He said there was a difference of opinion amongst
people concerning the meaning of that text.
I told him there was no difference of opinion amongst those who were Friends in principle.
He then requested me to mention something else,
wherein this author differed from Fox and Barclay.
I cited him to this declaration of Gurney--"`It
is only through the religion of the Bible,
that we can obtain an adequate notion of sin.`"
Enos then adverted to the benighted state of the heathen,
before they became acquainted with the Scriptures.
I replied, do you not believe in the universality and efficacy of Divine Grace?

He seemed to see where it would lead him to defend fully this author`'s views,
and waived the subject, saying, Ann,
I would caution you not to speak against the writings of Joseph John Gurney;
it will close up your way amongst us. I let him know that if I felt myself called
upon to allude to or speak against those unsound and anti-Quaker doctrines,
I should not withhold through the fear of man.
I asked Enos if he thought ministers of the gospel were
at liberty to cut and carve for themselves,
to preach what they choose.
I said, the Lord`'s prophets of old did not do so to please the people.
After much plain talk with Enos we parted;
he said he should have no objection to our having a meeting if it were a suitable time.
The woman minister present kept silent.

In the evening, Asa Hunt came home, and with him also,
we had very plain talk concerning the unsound doctrines and
anti-Quaker practices which were destroying the Society.

Asa thought, by admitting ministers of other denominations into their meetings,
and giving them liberty to preach,
the doctrines and testimonies of Friends were advanced.
It was astonishing to hear the sentiments of old men and heads of meetings,
on this and other subjects relative to the welfare of our Society;
and I said in my heart, great indeed is the mystery of iniquity, as well as of godliness.
For it seemed that the very things which were destroying the Society and laying it waste,
were looked upon by many as calculated to build it up. Alas!
how my heart was pained within me on account of these things;
and I found it necessary for myself and companions, to keep closely on the watch tower,
not fearing with the fear of man,
lest we should be confounded before them and desert the field of battle
before a clear acquittal was given us by the Captain of salvation.

On Seventh-day morning the 13th, we left Indianapolis for Plainfield, in Hendricks Co.,
the place of holding the Western Yearly Meeting.
We arrived there the same day, and put up at my uncle Asa Holloway`'s,
where we were very kindly and hospitably entertained.
Finding that Jane Plummer resided in the village,
and believing it would be best to pay her a visit,
her sister Hannah Wright being then with her,
we accordingly did so. Jane Plummer was for several
years Clerk of Ohio Yearly Meeting of women Friends,
previous to the separation of 1854; but when the separation occurred,
Jane went with the Gurneyites,
having given her strength and influence to that party for several years,
and acted for them on all occasions, greatly to the burden and grief of sound Friends.
I felt no personal grudge, or enmity in my heart towards Jane Plummer,
neither had I anything whatsoever premeditated relative to this visit.
However, during our stay, mention was made in some way of the Hicksites,
and their doctrine, and I told Jane that when I was in Wilmington,
in the limits of Philadelphia Yearly Meeting, we were visited by a Hicksite preacher,
to whom I said that Hicksism on the one hand, and Gurneyism on the other,
were neither of them Quakerism, but entirely the opposite,
and would lead away from the principles and testimonies of Friends.
Jane appeared to be disconcerted at my reference to Gurneyism,
and asserted that Joseph John Gurney`'s writings
had done a great deal of good in the world.
I told her that Benjamin W. Ladd said in the Meeting for Sufferings
that he considered the writings of this author very unsound,
he had kept some of them locked up in his desk as unfit for his family to read.
Jane remarked that the only objectionable publication put out by
Joseph John Gurney was the first edition of his peculiarities;
that contained a few sentiments that were somewhat objectionable,
but the author was then young, and after that work was revised, and republished,
it was considered sound and unobjectionable.
The first edition of Gurney`'s Peculiarities, as I understand it,
was the least objectionable of all his numerous publications,
and when it was revised and enlarged,
and the name of the book changed to Distinguishing Views,
it contains more that is not in accord with Friends`' views.
I told Jane,
Thomas Shillitoe`'s views of Joseph John Gurney`'s writings were correct,--
they had spread a mixed garment of wool and linen over the Society,
and it was going down in consequence of their adoption in various places.
Cousin Asa referred Jane to the "`Appeal for the Ancient Doctrines.`"
She replied that the extracts in that, from Joseph John`'s writings were garbled.
Cousin Asa asked her if she thought Enoch Lewis (who
was a prominent member of the Meeting for Sufferings,
and an advocate for Joseph John) would allow garbled extracts to go
out before the world? She still persisted that they were garbled.
After this visit to Jane Plummer,
I requested that the elders and others concerned might be
consulted in reference to a meeting on First-day afternoon,
for the inhabitants of Plainfield and neighborhood.
There were several collected, elders and ministers,
and I and my companions being requested to join them,
we did so. Jane Plummer being an elder,
was the first to object to a meeting being appointed, others followed her example,
and the question was soon decided in the negative.
They then proposed we should attend their meeting on First-day morning;
were very willing to hear anything we might have for them;
but on that subject we were settled.
Cousin Asa told them there was principle involved, and we could not attend their meetings.
Next morning, one of their ministers came to our lodgings.
He said he was come to give us a kind and hearty
invitation to attend their meeting that morning.
The invitation appeared to be on behalf of those
who had been consulted the evening before.
But we were not to be taken in their trap, and so declined.

On Second-day, the 15th, we left Plainfield for Chicago,
where we arrived next morning about six o`'clock,
and went to my nephew William Sharp`'s. Staid there until the 17th,
and then took the cars for Cedar Co., Iowa,
and next day reached our kind friends and relatives, John and Miriam Thomas,
at Hickory Grove, where a large settlement of Friends reside,
members of Ohio Yearly Meeting.
We attended their meeting on First-day, the 21st, which was quite large.
I felt my mind impressed with the belief that there were some present
in great danger of being drawn away from the Truth as it is in Jesus,
by listening to the insinuations and reasonings of those who profess to
believe that the Almighty is too kind and gracious towards his creature man,
to condemn any to everlasting punishment after death,
no matter what their sins may have been,
or how impenitent they may continue to the very last.
I had to warn the people against this sin-pleasing doctrine,
as being one of the subtle baits of the grand adversary
of man`'s peace and happiness here and hereafter.
I dwelt somewhat upon the subject, and afterwards felt peaceful and easy.
A young woman after this meeting,
acknowledged that her strongholds were broken up. She had been
pleading in defense of this universalism doctrine,
but now she saw her error, and appeared very much contrited.
May it last, has been my desire for her.
At this meeting, a woman sitting in the second gallery appeared in the ministry.
While she was speaking, although I could not hear a word she said,
I felt my mind impressed with the belief that she had come from the Gurney meeting,
I was looking for some one to request her not to disturb the meeting,
but it was not done.
I asked a Friend who this woman was, and where from.
She said that she had been going to the Gurney Meeting for eleven years,
but had become dissatisfied and recently attended Friend`'s meetings,
and nearly always spoke when she came.
I felt much distressed,
and could not get rid of the uneasiness which her appearance produced on my mind,
but I kept my thoughts closely to myself.

We staid until after their Monthly Meeting,
which was held on the 24th. Previously I was impressed with a belief that this woman,
at the Monthly Meeting, would appear in supplication,
and great were my exercises that I might be kept from hurting the precious Truth,
and it was made plain to me by my heavenly Father,
that I must keep my seat when she thus appeared.
And to meeting I went under great exercise,
knowing the woman had gained the sympathies of many in the meeting,
and had been promoted to a high seat contrary to gospel order,
she not being known as a member amongst Friends.
I mentioned my thoughts to no one, but at the Monthly Meeting,
when she knelt in supplication, I and my companions kept our seats,
and one other Friend in the gallery followed our example.
After meeting, several Friends came to our lodgings,
to whom I expressed my concern relative to this woman,
whom they had recognized by their actions as a minister in unity with them.
We laid the subject fairly before them,
showing what the Discipline says in regard to those coming amongst us,
appearing as members without producing certificates,
for this individual had neither produced a certificate,
nor been in any way received into membership amongst them.
I saw there was a restless spirit in the woman,
and that she had to a considerable extent, deceived many Friends of that meeting,
as well as some elsewhere,
so that they had promoted her contrary to Discipline and true gospel order.

Left Cedar County on the 25th, accompanied by John Thomas, who took us to Coal Creek,
in Keokuk Co., a distance of seventy miles,
where there is a large Monthly Meeting belonging to Ohio Yearly Meeting.
At Iowa City we dined at John Lee`'s;
his wife was a cousin of mine and a daughter of Isaac and Sarah Branson.
Her mother was a precious Friend, and died before her children were fully grown.
She was much concerned that they might be brought up right and be consistent Friends.
This eldest daughter has left Friends and joined the Methodists.
I had a religious opportunity with her and son and father,
but my feelings were painful and sad,
to see such who had had so many favors conferred upon them in
the way of admonition and advice by a beloved parent,
leaving the footsteps of the flock,
and going into outward forms and ceremonies which can
never make the comers thereunto perfect.
The evening of this day we reached Joseph Holloway`'s, son of my uncle Robert Holloway.
Had an appointed meeting next day in this neighborhood.
It being harvest time, the meeting was not large,
but we were favored to relieve our minds to the strangers present,
and I felt thankful that I gave up to the requisition.
The weather being very warm and the road dusty, I was well nigh spent,
and unable to travel that afternoon;
having been so smothered and filled with dust the day
before that I felt like being really sick,
but next day we ventured onward and were favored
to reach Coal Creek on the evening of the 27th,
and stopped with our relatives John and Lydia Hoge,
where we were very kindly received and entertained.

On First-day, the 28th of Sixth Month, attended Coal Creek Meeting, which was very large.
After meeting, dined with Lemuel and Mary Brackin,
also spent some time with Richard Brackin and family, and several of their relatives,
and had a religious opportunity with them.
The same afternoon, visited Amy Clendenon, who was suffering with a cancer,
and had a religious opportunity with her and the family.
My mind was greatly exercised on behalf of the children present,
that they might be in earnest above all things, to make their calling and election sure,
and I felt such a weight of concern for them,
that it was hard for me to leave them or to get relief.
Since that visit, a married daughter then present, and in good health at that time,
has changed this state of existence for a never-ending eternity.
On her death-bed she remarked that she had been too much unconcerned about her
latter end (or words to this import) and now her body was so racked with pain,
that she had scarcely a moment for reflection or any time to prepare for death,
desiring others to take warning by her.
Oh, the necessity for every moment to be rightly spent;
may my spirit deeply ponder the worth of time--precious time of more value than gold,
or all earthly grandeur, riches or honor--precious time,
how it is murdered by the sons and daughters of men.

On the 29th and 30th we visited several families in this neighborhood,
and had religious opportunities in them all.

Seventh Month 1st.--Attended Coal Creek Preparative Meeting,
and had considerable to communicate therein.
On the 2nd, we started for Warren County,
but a sudden swell of the waters occasioned by a heavy rain the night previous,
had carried away the bridge across a creek we had to cross, so we could not proceed.
Returned and called at Abraham Bonsalfs.
After dinner requested a religious opportunity with the family;
but the son would not give us his company.
When we were about to leave, I addressed a few words to him.
He said he had nothing against us, but Friends had disowned him for going to the war,
which he believed to be his duty, and thus he had taken offense.
Poor young man, my heart yearned for him, and towards him,
for he seemed to be in the gall of bitterness, if not in the bond of iniquity.
Went to the creek again, trying another road, but could not cross.
Returned and called at T. P`'s, and staid till after tea;
had a religious opportunity with the parents and daughter, the only child at home.
In this sitting I was singularly led to encourage to a
faithful confession one to another of our misses,
whenever, and wherever the Truth required, keeping nothing back,
nor counting nothing too hard to do, or to bear for the sake of true peace of mind.
It was hard for me to get relief,
having to recount some of my own experiences in regard to acknowledging my faults,
which had brought true peace, when nothing short thereof could afford relief.
When we were about to leave,
the father of this family said that this had been to him a very acceptable visit,
and desired we would call again if way opened for it.
This was an unexpected word of encouragement to me,
not knowing why I was thus led.
The same evening called at Evan Smith`'s, whose son was sick;
they had a small house and a family of ten children all at home.
After a religious opportunity, returned to John Hoge`'s.

In all the families we visited in this neighborhood,
I felt the necessity laid upon me to request a religious opportunity before leaving them,
and felt peace in so doing.

On the 3rd we again started for Warren County.
The following circumstance occurred on this day.
A young man being desirous to cross a river near the town in which he had been working,
in order to spend the 4th of this month as is the manner of very many in our country,
in a vain and irreligious way, resolved at the hazard of his life to venture across.
He was warned by a man returning from the river, that it was not safe to venture.
The young man replied, he was bound to cross if he had to swim.
And leaving his buggy and one horse by the river side, and mounting the other,
he ventured in, and next day his body was found in the river.
The horse he attempted to cross the river on,
was found on the opposite side from the one left with the buggy,
the life of the poor animal was saved,
while that of his presumptuous rider was permitted to go. Poor young man,
resolved to have, and permitted to take his own course, where did it land him? Oh,
that the young and rising generation would take warning, while life,
health and opportunity are given, to make their calling and election sure.

On the evening of the 4th we arrived at the house of my relative, Elisha Smith,
a distance of sixty-five or seventy miles from Coal Creek.

Next day being First-day,
we proposed the appointment of a meeting at three o`'clock in
the afternoon for those professing with Friends,
and others in the neighborhood (Three Rivers.) The meeting was held,
though very irregular in gathering in consequence of some
being dipped in the river near by. When that was over,
many came to our meeting, more than the house could hold;
and finally settled down into more quietude and
stillness than appeared for a time would be the case;
and opportunity was afforded to relieve my mind amongst them in a good degree.

Next day had an appointed meeting at Hartford,
a little village three miles from Three Rivers.
It was held in the evening, although not large, was to the relief of my mind.
After meeting, we were kindly invited by a Presbyterian and his wife to lodge with them.
We went to their house, but a woman followed us,
earnestly desiring that part of our company at least would lodge with her;
which I and my companion, Abigail Sears, concluded to do. Before leaving,
I asked the man (the Presbyterian),
if he thought it was contrary to Scripture for a woman to preach.
He replied, "`No; I know some people do, but I have considered this passage of Scripture:
'`Male and female all one in Christ;`' and I do not consider it
contrary to Scripture for a woman to preach.`"
He was a sober, serious countenanced man,
and I had some interesting conversation with him and his wife before leaving.
Where Abigail and I lodged, we found them very kind, and glad of our company.
Next morning we started on our way back to Coal Creek, and got to Job Briggs`',
near Oskaloosa, about sundown.

Next morning, the 8th of the month,
I queried with Job and his wife if there would be a willingness on their part that
we should have an appointed meeting that afternoon in their neighborhood.
He very quickly replied in the negative.
I asked him if he would be willing to consult some of his neighbors.
He said he would, and went to his neighbor, Clark Terrell,
but soon returned with the same decision as he first gave.
I was not at all disappointed at their refusal,
being well acquainted with their sentiments and doings
in Society matters when they lived in Ohio,
and knew them both to be Gurneyites.

We then left Oskaloosa and returned to Coal Creek.
Great is and has been the mercy and kindness of
our Heavenly Father in preserving us through,
and in extremities both outwardly and inwardly;
I believe it was the warmest weather that I remember ever to have experienced;
and yet we and our horses sustained no injury in travelling,
though the thermometer was generally over a hundred for days together.

On the 11th attended Coal Creek Monthly Meeting of Friends, and on the 12th,
being First-day, had an appointed meeting in the afternoon for the young people.
It was large and afforded some relief to my exercised mind,
my cousin also having service therein.

We had religious opportunities in several families before leaving the neighborhood,
to the relief of my mind in a good degree.
There are many young and middle aged Friends belonging to our
Yearly Meeting settled in this section of country.
Oh, how my spirit yearns for their eternal welfare,
that they may grow in grace and in the knowledge of the Truth as it is in Jesus.

On the 14th, in company with our friend, Nathan Warrington,
who was our pilot and coachman, we set out for Springville, in Linn County.
The first day we rode about forty miles, and got to the house of Thomas and Mary Emmons,
in Benton County, where a few families of Friends are settled.

On the next evening we had an appointed meeting,
held at a school house not far from Thomas Emmons`'. It being harvest time,
and the people appearing to be more concerned about getting
their luxuriant crops harvested than attending meetings,
but few gave us their company.
However, there were several young people and children present, and a few older ones,
to whom the word of exhortation and counsel was extended in the love of the gospel.
On the evening of this day, some friends coming in,
we had a religious opportunity with them and the family where we put up,
which was relieving to my feelings in some measure.

Next morning, the 16th, we again set out for Linn County, and arrived at Lindley Hoyle`'s,
at Springville, a little after night.
His wife, with whom we were previously acquainted,
appeared very glad to see us. She is a well-concerned young woman,
and if attentive to the Savior`'s voice,
will be helpful to her husband and those she associates with, in the best things.
We paid a few visits on the 17th, and on the 18th attended Springville Monthly Meeting,
held at Hopewell.
After meeting went to see William Hampton, who with his family, and one other family,
meet together separate from Friends, holding what they called a Friends`' Meeting.
We endeavored to set before William the inconsistency of his course,
but he had evidently got into his strong holds,
and nothing we could say would induce him to relinquish the ground.
However, we felt satisfied in having cleared ourselves to him, and of him.
Lodged that night at Aquila Crew`'s, and had an interesting visit with their large family.

Next morning went to see James Doudna and family.
They are one of the two which make up the separate meeting.
James being from home, we had no opportunity with the family.

Attended Hopewell Meeting, and was silent therein.
In the afternoon, attended a meeting at Springville,
appointed at my request for the young and youngish
people in the neighborhoods of Springville and Hopewell.
The meeting was very large, and I trust to some degree of edification.
My cousin Asa, as well as myself, had considerable service therein.

On Second-day, the 20th, accompanied by William Bedell and wife,
we made a visit to Caleb Gregg and wife.
Caleb was one who several years ago assisted in setting up a meeting in Iowa,
which was not in the ordering of best wisdom, and a blast and mildew attended.
Caleb is now a Member of no meeting,
and although he attends Friends`' meeting at
Springville and wishes to be a member thereof,
yet he is not willing to condemn to the satisfaction of Friends,
his previous course of conduct, hence Friends are not free to receive him.
I and my cousin Asa had much plain talk with him in the presence of his wife,
and before the Friends who accompanied us, and also in the presence of two other Friends.
I told Caleb I did not see how he could feel satisfied without publicly
condemning the course he had pursued in the setting up of that meeting,
as he acknowledged their planning and contriving the matter out of doors was wrong.
So, if the first step was wrong, that which followed must have been wrong also.
I thought he appeared too self-whole to be in a
suitable disposition to see or condemn his errors.
We left them under feelings of painful solicitude for their recovery
from that which stands in their way of obtaining true peace of mind,
and becoming united to their friends in the bond of gospel fellowship.

While there, I saw a young woman passing about, who I thought might be their daughter;
and when we were about to leave, I went into the dining-room to bid her farewell,
and found her and a young man sitting at the supper table.
I enquired if they were Caleb`'s children, and found they were.
I felt my mind drawn to address them in the love
of the gospel in the presence of their mother,
and felt true peace in doing so; but felt that the young man was on dangerous ground.
Their father came in before I closed my communication,
and I think the parents were not dissatisfied with what I said.
Oh, how my heart yearns for the children, and my prayer was and is,
that the Lord may have mercy on them.

Lodged at Joseph Embree`'s, and started next morning early to Cedar County,
and got to our cousin John Thomas`' the evening of the same day,
about forty miles from Springville.

23rd.--Attended Hickory Grove Monthly Meeting,
and in pursuance of a concern which had attended my
mind since being at that Monthly Meeting before,
of visiting the families thereof as way might open, also some families not members.
I laid the subject before the meeting, and had its full concurrence.
Great were my exercises during this family visit,
but I felt that we must not desert the field until the
word of release was sounded by the Captain of salvation.

It was harvest time, their crops very abundant, and help scarce; so,
that going from house to house,
and calling the men from their harvest-fields to sit down with us to wait upon the Lord,
appeared to some, no doubt, as a strange thing, and hardly warrantable in the Truth;
but such was the pressure upon my spirit that I dare not omit to do
so. Generally there appeared a willingness to receive the visit.
At one house where we called, the woman being a member, and her husband not,
the Friend with us asked if we would have a choice in having the husband called;
I replied that I would.
The Friend went where the man was working, and invited him; after awhile he came,
and as soon as I saw him I thought to myself, you have a hard countenance,
though I had never seen the man before,
neither did I then know that I had ever heard of him.
When we sat down together,
the subject of preparing for our latter end while we
had time and opportunity afforded was brought before me,
and the necessity of using all diligence to make our calling and election sure,
which I expressed,
and also said that some people did not believe in a place of
punishment hereafter for the wicked and guilty soul,
that there were some who called themselves Universalists, of this class I did not know,
I added, that anyone present was of this belief.
He replied, "`I am one,`" and he several times proposed leaving;
but his wife telling him I could not hear anything he said,
prevailed upon him to keep his seat.
Oh, what a dark man; the darkness was to be felt, as well as seen in his countenance.
When I bid him farewell he said to me, Ann, you is ignorant, you lack information.
I told him that I desired for myself, and for him,
that we might attend to the teachings of the holy Spirit to enlighten our hearts, etc.
He replied, that was his guide, or words similar.
Poor man! my heart did ache for him,
and I felt the spirit of supplication given me on his behalf,
and had vocally to utter a prayer for him.

The same evening, paid a religious visit to my cousin William Branson and family,
and called to see another cousin who was ill;
both opportunities to the relief of my mind.
This closed the family visit in that Monthly Meeting,
and I felt at liberty to look towards home; and we made some arrangements for starting.
But the Lord saw fit to disappoint us, and suddenly prostrated me by a severe illness,
which for a time appeared like taking my life.
But He who had often brought me low and raised me up,
saw fit to relieve my extreme suffering, and in two weeks I was able to ride out.

Hickory Grove Quarterly Meeting being near at hand,
I felt that I must not look towards returning home before it occurred.
We waited until after another Monthly Meeting at Hickory Grove,
in which I had singular service; then started for Linn County,
where the Quarterly Meeting was held.
I stood the ride pretty well, though quite weak in body.

On the 21st of the Eighth Month,
attended the Select Preparative and Select Quarterly Meetings, both held the same day;
and had some service, but weakness is prevalent.

On the 22nd, the Quarterly Meeting was held; it was a very large gathering,
being the first Quarterly Meeting held there.
Many not members at the first meeting.

Next day being First-day, the meeting at Springville was very large,
and I felt that I must open my mouth in warning and counsel to the people,
which I did to the relief of my mind.
While at Springville we put up at the house of our friend Parker Askew,
who with his wife and children,
were very kind to us. Parker is pow about eighty years old;
he moved to Iowa three years ago; appears very cheerful, innocent and happy,
as does also his wife.

We left Springville on the evening of the 24th, and took the cars for Ohio;
had a dangerous passage across Rock River in a boat; the bridge having been burnt;
but were favored to cross without accident;
several hundred passengers and all their baggage
to be taken across in small skiffs and boats.

Reached Chicago on the evening of the 25th, very much fatigued.
Stopped with my nephew William Henry Sharp,
and was not able to be out of bed much for two or three days.
Feeling a concern to appoint a meeting in
Chicago for those professing the name of Friends,
and others who might incline to attend, I proposed the same to my companions,
and to my nephew and niece.
Those appointed to the station of elders in the city were consulted, or some of them,
but gave no countenance to it. I knew the chief speaker in Ohio,
and did not expect his consent would be obtained, he being of the New School,
and a bankrupt in his temporal business.

Left Chicago on the 31st, and took the cars for home.
Great had been the exercises of my mind while we tarried in that city,
for the wickedness of the inhabitants appeared to me to be very great,
but no way opened for my relief.
When we arrived at Columbus, and before getting there,
it had rested upon my mind to visit an inmate of the Lunatic Asylum, a relative of mine,
who had been conveyed there since we left home, but I suffered discouragement,
and reasoning with flesh and blood to prevail, and did not attend to my duty,
which brought trouble upon me. The dear,
desponding one lived but a short time afterwards, and I had keenly to feel my miss:
I wanted to tell this woman that the Lord had not forsaken her,
but that mercy was still round about her, which I hope she realized in her last moments.
Oh, how sorrowful that any should despair to whom the offers of mercy are still held out.
Oh, my soul, trust you in the Lord your God, who has done marvelous things for you,
and despair not when clouds and darkness intervene, and rest upon you;
even thick darkness.

We arrived home on the 2nd of Ninth Month, and found my dear brother Jacob Branson,
very ill of dysentery, and very anxious to see.us. He lived until the 13th,
and then gave up the ghost.
Oh, the struggles of nature in that hour of death:
but we believe a preparation was experienced for the solemn change;
some account has been preserved of his illness and death.

I think it right here to say, that while we were at my brother Isaiah`'s,
a great concern came upon me on account of the inhabitants of Richmond.
My exercises seemed almost unsupportable,
and for a time it appeared that I might have to go through the
streets of the city and warn them to humble themselves before
the "`Great I Am,`" the fear and dread of nations;
and on the morning we left for the west, as we came to the city to take the cars,
it seemed as if I could scarcely leave the carriage without
requesting the driver and my companions to take me to Main Street and
let me have the opportunity to deliver what was on my mind;
but I forbore.
Oh Lord, forgive, I entreat you, if in this thing I have offended; for it was not wilful,
but through fear that the call was not strong and powerful enough.
Oh, for more childlike obedience to the will of my heavenly Father.
