== Chapter X

[.chapter-synopsis]
* Death of Her Cousin, William Wright; and Further Remarks on the Last Days of Her Brother Jacob
* Appointment of Meetings from Among Friends
* Home Exercises, and Labors in that Vicinity
* A Visit to Springfield Quarter on a Yearly Meeting Appointment
* Further Exercises, and Labor about Home
* A Testimony Against Attending at Fairs
* Religious Service at Concord
* Death of Joseph Hobson, and Remarks Thereon
* Death of Joseph Wilson, and Her Feelings Concerning Him

After the death of my brother, I had a turn of dysentery,
so as to preclude the prospect of attending our approaching Yearly Meeting,
held in the Tenth Month; but when the time came for starting,
through a grain of faith and the encouragement of my cousin, E. Wilson,
I set out for Mount Pleasant.
But several times while riding along I felt so weak and faint
that it appeared almost impossible for me to reach my lodgings,
and after getting there, and a return of the disorder, and the lack of faith,
made me think I had been presumptuous in leaving home in my weak, debilitated condition,
and the probability seemed that I should be prevented from attending Yearly Meeting,
and perhaps end my days where I was.
But after the Physician of value had tried and proved me as to a hair`'s breadth,
He quieted both mind and body,
and strengthened me to attend all the sittings of the Yearly Meeting,
and comforted my spirit therein,
so that I could say as I have often said from some sense of
the healing power of his holy hand who created me,
nothing is too hard for the Almighty.

In the Eleventh Month, accompanied by my cousins, Asa Branson and Abigail Sears,
I attended Salem and Springfield Quarterly Meetings,
and returned in time to attend our own, which occurred in the same month.

Twelfth Month 17th.--Today heard of the death of my cousin, William Wright,
aged nearly eighty years.
He had been quite ill for some days, but appeared to be mending,
and thought he should soon be well enough to need but little attention;
but while sitting in his chair, his attendant perceived a change,
and he passed away in a few minutes.

On hearing of cousin`'s death--his disease being an affection of the heart--I
am solemnly reminded that I too who labor under the same disease,
may pass away suddenly.
Oh, I do earnestly crave that the Lord`'s hand may be so turned upon me,
that nothing may stand in my way of acceptance when the solemn summons shall come.
You know O Lord! that the earnest breathings of my spirit, day and night are,
that this may be my happy experience; be pleased, I earnestly pray you,
not to let your hand spare me, nor your eye pity me, until I am fitted for your kingdom.
Oh, Lord! look down with an eye of compassionate regard upon my brother`'s family,
whom you have lately stripped of their father,
and turn the hearts of the sons and daughters to you,
and enable the mother to see and feel more and more the necessity of taking the
children and sitting down with them daily in solemn silent introversion of soul,
waiting upon you for counsel, for strength and help to pursue the right path,
the path that leads to true peace.
It is now a little more than three months since the death of my dear brother,
whose decease at that time was a very unexpected event in our neighborhood,
but we have the consolation in believing that his affliction was sanctified to him,
that he has been permitted through the mercy of God in
Christ Jesus to join the church triumphant in heaven.
Oh, gracious Father! you have dealt marvelously with me;
you have been more gracious towards my soul than I can possibly set forth;
I will therefore magnify your name;
I will call others to come taste and see that you are good,
as you command and give me ability.
You have I fully believe, answered the fervent petition of my heart and soul,
and the fervent petition of my dear departed brother Jacob,
that he might find acceptance and remission of sins through Jesus Christ our Lord.
Yes you did give me such a joyful feeling the evening after he was taken away, and did,
I believe, put this language in my heart as an evidence of his acceptance,
namely "`Joy unspeakable and full of glory.`"
And you did give me to feel my spirit united to
his in a song of praise to you you Holy One.
You did often put a prayer in my heart on behalf
of this my beloved brother when he was in health,
by day and by night.
You did enable me to raise a cry unto you for the
preservation and sanctification of this brother,
as well as for the rest of my brothers who are still living.
And now Oh gracious Father,
deal with the rest of my father`'s family as you have with those taken hence,
and leave us not; set judgment to the line,
and righteousness to the plumb line in the temple of our hearts,
and bring all things into a conformity with your holy will.
Amen.

19th.--Attended the funeral of my cousin, Wm. Wright.
It was a large gathering,
and I was called upon by my Heavenly Father to warn the people
assembled at the house of the deceased to set their spiritual
accounts in order to meet the summons of death.
It was under much bodily weakness that I spoke, yet I was strengthened to relieve my mind.
Joseph Hobson spoke a few words at the grave,
which appeared to have a solemnizing effect upon the people.

24th.--Attended our Monthly Meeting, held at Guernsey.
The weather being very cold,
my health seemed hardly sufficient for a ride often miles over rough roads,
but knowing the Lord could strengthen me,
and enable me to perform all that He required at my hands,
I set out and got to the meeting pretty well.
After Monthly Meeting, I thought it right to remain at Guernsey,
having a prospect of appointing a meeting or two a few miles
from that place among those not in membership with Friends.
The weather becoming increasingly cold, and my health poor,
everything as to the outward appeared very discouraging,
and had it not been for that grain of living faith which removes mountains,
I should have given up the prospect.
But about noon on the 25th, I queried with my cousin Joseph Wilson,
at whose house I then was,
if it was too cold for him to turn out and appoint two meetings,
one on the 26th and the other on the 27th. I saw his faith was at a low ebb,
as he afterwards confessed it was, but he made no objection, and turned out in the cold,
and a stranger pretty much to the inhabitants of both
towns where the meetings were to be appointed.
After he started, the enemy was permitted to buffet me sorely for a little time;
but the Lord,
who knew that the desire of my heart was to serve Him only and alone in this matter,
lifted up a standard against him, and spoke peace to my mind, and bade me trust in Him.
He promised to still the piercing winds, and moderate the weather,
and to strengthen me in body and mind, to perform the service, which promise He verified.
Next morning the weather was much milder, and in the afternoon we went to Sewelsville,
a distance of five miles, and attended the meeting to good satisfaction.

On the 27th we went to Hendrysburgh, a distance of nine miles,
and attended the appointed meeting in that town, which was large and satisfactory.
Many spoke to us after meeting in a very affectionate manner,
showing that their hearts had been reached,
and that they were thankful for the opportunity.
As for myself, my mind was kept low,
and humbly confiding in Him who had so graciously cared for and favored a poor worm,
to preach the unsearchable riches of Christ Jesus to the people,
and enabling me out of weakness to become strong,
so that I can say He does all things well.

Fourth Month 30th, 1869.--The exercises of my mind have of late been so great,
that I have feared I should not be enabled to endure them.
Sleep has departed from mine eyes.
Tears have been my meat day and night.
The weakness and wickedness prevalent in the land,
and my own weakness and shortcomings staring me in the face,
are almost overwhelming to my soul.
In a national capacity we have been scourged and afflicted, but we are not humbled.
Pride and wickedness appear more prevalent than before the late bloody war,
and that this should be the case, who can marvel, since war,
to use the words of Robert Hall, "`is a temporary repeal of every Christian virtue.`"
Yet, when we reflect that thousands and tens of thousands of our countrymen,
have in the late struggle been sacrificed on the field of slaughter, and other ways,
contrary to the benign religion of Jesus, which teaches us to love our enemies,
to do good to them that hate us, etc.,
and reflecting upon the destitute condition of widows and orphans,
now suffering poverty in consequence of this awful scourge,
would it not seem reasonable to suppose, in view of these things,
that more humility would be apparent than is to be found anywhere,
where our eyes or footsteps turn?

Fifth Month 7th.--I long to be among the number who
love the Lord their God with all their heart,
with all their soul, and with all their might, and their neighbor as themselves;
and to feel that I really come up to this Divine requisition.
Lord, have mercy upon me,
and hasten the day when everything like the mountains and hills of opposition in my
heart to the coming and setting up of the Redeemer`'s kingdom therein,
may be laid low, and cast as it were, into the sea.
I am a wonder to myself, so poor, so blind, so naked,
so destitute of that which my soul desires,
and yet having more than I deserve--having a little
grain of living faith--a little living hope,
which keeps me from sinking into hopeless despondency.

10th.--Oh Lord! be graciously pleased to keep me from falling a prey to the destroyer.
You know he is daily and hourly seeking to take me captive at his will.
I will trust in you, O my God! hear my prayer and deliver me from sin and from Satan.

11th.--O Lord! keep me faithful to known duty,
and patient when you are pleased to hide your face,
as at the present time--yet you give me ability to
plead with you for the continuation of your mercy,
which I acknowledge as a great favor.
Amen and amen.

19th.--Heavenly Father! be pleased to show me
the way I should take in this critical time;
yes, this time of great conflict between flesh and Spirit, between hope and fear.
Be pleased to give me ability to say in sincerity of heart, Your will, O God,
be done in earth as it is in heaven,
so I may be preserved from falling into the
snares of the enemy on the right hand or left.

20th.--Attended the funeral of M. K., a large and mixed assembly met on the occasion,
and my God who hides his face from me at times, so that my faith seems nearly gone,
was pleased to raise me up out of a low place,
and caused me to proclaim the gospel of life and salvation to the people,
both at the house and at the grave of the deceased.
My mind has been under much exercise of latter time,
partly owing to the length of time which I have been holding a Minute from the
Monthly and Quarterly Meeting for religious service in the West and in my own State;
and since my return from the West, but little active service has appeared to be required.
Only now and then the appointment of a meeting among others opens
before me. Had a meeting about two weeks ago in the town of Cadiz,
twelve miles from Flushing.
This meeting was large and quiet, and quite satisfactory.
Out of great weakness I was made strong by the Lord, my God.
For some days previous to the holding of this meeting,
the exercises of my mind and my great weakness were altogether indescribable,
insomuch that the language of my heart often was--"`How shall I be
able to bear the great weight and load of exercise resting upon me?

Sixth Month 23rd.--Dearest Father! you see and know the great
extremity I am in with regard to returning my Minute.
O, be pleased to undertake for me, for you know the depth,
length and breadth of the enemy`'s baits.
Oh, preserve me, I entreat you, from falling into his snares, which are laid to take me.

28th.--The Lord is a sun and a shield to those who put their trust in Him.
He helped his servants of old, and forsakes them not, even from generation to generation.
When I said, my flesh and my heart fails, your mercy, O God, held me up. When I said,
my foot slips, help Oh Lord, or I go down quickly into the perdition of the ungodly,
and cast away, as did Saul, my shield, as though it had not been anointed with oil;
then you did hear my cry and interpose your arm of power.
You did lift up the light of your countenance, and gave me to hope and trust in you.
I will extol you, my God!
O King, for you do for me great things, and that my soul knows right well.

Yesterday I had an appointed meeting at St. Clairsville,
the county seat of Belmont County.
It was held in the Presbyterian meetinghouse,
and pretty well attended by the inhabitants of the town.
Out of weakness I was made strong in body and mind to
declare the gospel of life and salvation to the people.
Oh, what a dread had been on my mind with reference to this place,
in the appointment of this meeting; but the Lord opened my eyes among the people,
and opened my mouth to declare the whole counsel to them.
After sitting silently for some time, this Scripture passage presented to revive:
"`It is not in man that walks to direct his steps.`"
Then added, there is nothing in man as pertaining to his fallen nature,
that can lead and guide him in the path of peace.
Then what is it under the gospel dispensation that the
Lord has given to be a guide and leader to the people.
Is it not that which was promised by the Most High through the mouth of his Holy Prophet,
quoting Jeremiah, chapter 31st, verses 31, 32, 33. This law written in the heart,
the law of the Spirit of life in Christ Jesus,
which makes free from the law of sin and death,
is given to be a guide and leader to the sons and daughters of men,
under the gospel dispensation;
even the Spirit of Truth which our Savior promised to his disciples,
should lead into all Truth.
I adverted to the testimony of Judge Hale relative to
the leadings and teachings of the Holy Spirit,
and recommended all present to take heed thereto;
that it never led any to deny the Holy Scriptures,
nor the propitiatory sacrifice of Christ Jesus on the cross.
I had to enlarge somewhat on this subject, and then to address the infidels,
or speak to and of that class who deny a place of
punishment hereafter for those who die in their sins,
as declared and described by our Savior, and recorded in the Holy Scriptures.
I had to set forth the nature of the one true and saving baptism,
the baptism of fire and the Holy Ghost;
how it cleanses the heart and is the only essential baptism,
and that which John the Baptist declared must increase,
while his watery and typical baptism must decrease.
It was a very relieving opportunity to me. The people were quiet and attentive,
and the meeting ended to satisfaction.
Oh, may I learn to trust more and more in Him who has all power in Heaven and in the earth.

Seventh Month 2nd.--Gave way improperly to reflect upon others in thought and word,
which left me weak and wounded.
I find my greatest enemies to be those of my own household.
If these gain the ascendency,
then weakness and every hurtful passion may take possession of the mind.

Oh Lord! preserve me from the baits of the destroyer,
whom you know is more busily engaged to overcome my faith,
and weaken my strength by the way, than almost at any former period of my life.
Have mercy upon me, O God, I beseech you, or my faith and hope will utterly fail.
Be pleased to undertake for me,
that I be not wholly overcome with those things that should be kept under foot.

Eighth Month 1st.--What a stupid and benumbed condition
we appear to be in relative to the soul`'s best interest.
Oh Lord! be pleased to awaken us in some way to a sense of our spiritual condition;
enable us to cry mightily to you for help and strength
to come up out of our graves of ease and unconcern.

Eleventh Month.--Had an appointed meeting for the colored people of our neighborhood.
It was well attended, and afforded relief to my mind.
After this meeting I returned the Minute to the Monthly Meeting,
granted me about eighteen months ago for religious service in the west,
and in our own State.
I felt that it was the right time, and ease and peace of mind attended me,
which is more precious than all the treasures of the world.
Friends have been kind and tender towards me in and under my exercises,
which I esteemed a favor.

First Month 14th, 1870. Is now on a bed of languishing, and probably near his end.
My mind has been so exercised for him for some time past,
that I cannot pursue my accustomed portion of daily labor.
Oh Lord! if it seem good unto you, have mercy on this afflicted man,
who when time and opportunity were afforded to make his calling and election sure,
has so far neglected this momentous concern, as to be unprepared for the final summons.
Oh, forsake him not,
but be pleased to prolong his life until his sins shall
have been washed away in the blood of the Lamb,
if consistent with your will to show him mercy.

18th.--Visited the sick man above alluded to, and delivered the message given me for him.
Oh, how nature shrinks from disturbing the false
rest of those who are so weak in body as _______,
and yet, unprepared for their latter end.
I had to tell this suffering man that this language had for several days rested on
my mind concerning him--"`He that covers his sins shall not prosper;
but whoever confesses and forsakes them shall have mercy.`"
Oh, how fearful I was to visit him lest I should say, or leave unsaid,
that which I ought not; but I trust I did not.
After bowing in vocal supplication by his bedside,
and then desiring him to pray the Lord to preserve him from a false hope,
and a false rest, I bid him farewell.

24th.--How painful have been the exercises and conflicts attending my mind for some
days past on account of the spiritual condition of some of my near relatives,
and on account of the sins and iniquities abounding in the land.
Surely, my concern for the dear children in our neighborhood,
and in the family where I reside,
could not exceed my present exercises and feelings of
prayerful solicitude on behalf of the young people in general.
Lord, have mercy upon them! is the daily breathing of my spirit,
while I am often bowed down as in the dust on account of the things
that are transpiring--things which the Truth does not own.
I will go softly all my days in the bitterness of my soul.

28th. ________ lingers, contrary to the expectation of his physicians and friends.
What a mercy!
Will the vital spark continue until he bows in reverent humility before the Great I Am;
or will he refuse to let go of that which
hinders his acceptance with the Beloved of souls,
until the strivings of the Holy Spirit be withdrawn.
Oh Lord! your power is above all and over all,
break in pieces the will of the creature and give
strength and ability to say in the depths of humility,
your kingdom come, your will be done in earth as it is in heaven.
Amen, and amen.

Second Month 1st.--My sorrows are stirred within me. I have but little respite from
affliction of mind on account of the sad state of things in Church and State.
By revolting from the commands and precepts of Christ, and taking our own course,
what a sorrowful state of things is presented to our
view among those professing the name of Friends,
and in the nation; murder, drunkenness and lying,
and almost every other immorality seems to be on the increase;
and my own weakness and apparently benumbed condition, adds to my affliction;
yet amidst all,
my Heavenly Father gives me some ability to cry unto Him for preservation.
Will not a better and brighter day come?--not perhaps
before more judgments are poured out upon us.

18th.--Yesterday was our Quarterly Meeting, held at Flushing.
Silent in the forepart, except a few words from a youngish Friend.
I am greatly satisfied with silent meetings.
When the presence of the Lord is felt to gather the mind into stillness,
what can be more strengthening?

Third Month 7th.--In company with two other Friends,
I paid a visit to the jail of Belmont County, and had an opportunity,
by permission of the sheriff, with three individuals who had been convicted of murder.
The first, whose name is Carr, is sentenced to be hung on the 25th of this month.
He appeared in some degree to feel sensible of the great crime he had committed,
but it seemed to me that a species of insanity attended him.
My feelings were such, on being with this poor wretched criminal,
as cannot well be described.
He has certainly been a very wicked young man; he still looks young,
and carries the marks of alienation from the path of peace in his countenance.
He expressed a hope of forgiveness through the mercy of the Savior.
Under the feelings that pervaded my mind while in his room,
I had vocally to supplicate the Father of mercies on his behalf,
that He would be pleased to break in pieces the strong heart,
and bring into a state of deep contrition, if mercy still remained in store for him.
Carr made some sensible remarks; said he had made a full confession of his crimes,
knowing that unless he did so he could not find forgiveness of his God.
But whether his penitence is sincere or not,
we must leave with Him who knows the hearts of all.

On my saying to him that had He attended to the teachings of the holy Spirit,
which had often striven with him, showing him the evil and the good,
and pleading with him to choose the good and forsake the evil,
he would not have committed this great crime, he assented,
and said he had felt this striving with him to which I had alluded,
and that had he attended thereto he would not have been there, or words to this import.

We next visited Enoch Thomas,
who had also been found guilty of murder in the first degree,
but sentence of punishment has not yet been passed upon him.
He appeared almost frantic with grief and anguish,
but whether this grief was occasioned by a due sense of, and penitence for,
the great crime he had committed,
or whether through fear of the punishment that might be inflicted,
the Searcher of hearts knows.
The spirit of supplication was given me on behalf of the prisoner,
which was vocally uttered.
So also with the third, who had been sentenced to the penitentiary.

We next went to a room where five lads were confined;
the youngest about fourteen years of age.
He had shot a man intending to kill him, but missed his aim, yet severely wounding him.
These boys, when we first entered the room, were very light and irreverent,
but before we left, the one whose countenance was at first most defiant,
appeared to change very much, and when I bid him farewell,
he shook my hand for some time, giving evident tokens that his heart had been reached.
I asked him pretty soon after entering the room, if he did not sometimes think of death,
and what would become of him if the Lord should take him hence.
He replied, that he did not think much about it. This he said in a very light manner.
I told him he had known better days; he had been visited in mercy,
and plead with by the good Spirit to forsake the evil of his ways,
and had he yielded obedience thereto, he would not have been there.
I exhorted him to repentance and amendment of life.
He appeared to me to be the ringleader of the band in folly and irreverence,
but his countenance fell, and so did his companions somewhat, and we parted with them,
hoping that the exercise and concern on their account would not all be lost.

Before going into the prison,
we had some conversation with the sheriff relative to capital punishment,
letting him know that the Society of Friends did not believe such a
mode of punishment compatible with the gospel dispensation.
He said he would be glad if that law was done away, but while it was a law,
somebody must execute it. We brought the matter close home to his feelings,
and desired him seriously to consider the subject,
and not to do that which was contrary to his conscience for any earthly consideration.
I told him that the advice of Louis IX, King of France, to his daughter Isabella,
Queen of Navarre, was on this wise--"`In that which is contrary to the will of God,
you give obedience to none.`"
I said it would be far better to resign the office than wound the conscience, etc.
He was respectful, and heard us patiently.

8th.--Visited the Almshouse;
had a religious opportunity with a considerable number of the inmates,
including the Superintendent, Matron and daughter, to the relief of my mind,
and the satisfaction of the visited as far as appeared.
Before leaving, the attending physician came in,
to whom the Lord gave me some counsel to impart, which he received respectfully, saying,
when I bid him farewell, "`I fully appreciate every word you have said.`"

28th.--All alone;
the family having gone to attend the sale of a farm
belonging to the estate of my departed brother Jacob.
This is, or appears to me to be,
the beginning of the scattering of this family and the property.
I have been trying for some time to be brought into a state of quietude,
relative to things over which I have no control,
and the earnest breathings of my spirit for the spiritual welfare of the dear children,
have been many and fervent, amidst the turnings and overturnings of things around.
How necessary to take heed to the injunction--"`In your
patience possess you your souls;`" but I have not on all
occasions been watchful enough over my thoughts and words,
when things have given me uneasiness,
but have sometimes given way to express what had better have been left unsaid,
which has been the means of wounding myself and injuring the good cause.
I have not been careful enough on all occasions to mind this injunction:
"`Let your adorning be that of a meek and quiet spirit, etc.`"
I have remembered too, how the blessed Savior demeaned himself--"`When He was reviled,
He reviled not again; when He suffered, He threatened not.`"
How different from this have I sometimes acted;
have given way to reflect on others when I should have kept quiet and calm.
Oh, heavenly Father! take hold of shield and buckler and stand up for my help,
for you alone can preserve me from falling;
take not cognizance of my evil to punish me in wrath, but remember mercy also.

Fifth Month 28th.--A committee having been appointed by the Yearly
Meeting to visit Springfield Quarterly Meeting and its branches,
in order to judge of the propriety of laying down or continuing that Quarterly Meeting,
I being one of that committee, attended that meeting on the 11th instant.
There was a difference of sentiment in the committee on the subject;
some being for attaching the members of that Quarter to Salem Quarter,
and some for adding New Garden Monthly Meeting (a
branch of Salem Quarter) to Springfield Quarter,
and so keep up two Quarterly Meetings.
The latter was my view of the subject,
but some whose judgment I highly esteemed did not unite
with it. Notwithstanding the difference of opinion,
all appeared willing to weigh the matter,
and wait until we could more fully unite as to what would be best to do. I felt
rejoiced that none appeared disposed to push their sentiments upon those in
opposition to them beyond the bounds of propriety and Christian condescension.
Though there was decided opposition in judgment,
yet no harsh words or bitter feelings were in the least manifest.
May the great Judge rule and overrule in the matter,
and cause the result to redound to the honor of Truth, let it be in what way it may,
has been the fervent and chief desire of my heart.

Sixth Month 14th.--This is a day of great trial,
wherein faith and patience seem to be very closely proven.
All that I seem able to ask for is, that my faith may not wholly fail,
and that I may not become a castaway.
And for my beloved relatives and friends,
that they as well as myself may be so dealt with as to deepen in religious experience.

Oh, the lukewarmness and indifference that prevails with regard to our soul`'s best interest.
It seems to me that judgments, the judgments of the Lord, will not slumber much longer.
But if some who have been remarkably visited,
warned and invited to come taste and see that the Lord is good, do not yield obedience,
they will have to taste of that which will be very
bitter and hard for flesh and spirit to endure.
My soul is often plunged into deep mourning,
while it seems most proper and profitable to wear the sackcloth inward;
yet I could cry aloud with anguish and sorrow of heart,
for our undone and sunken condition as a people in general;
at least it appears thus to me. Lord! hasten the day when,
through the washing of regeneration and renewing of the Holy Ghost,
we may as a religious Society and as individual members experience
more of the incomes of your Divine presence in our religious meetings,
as well as on other occasions.

27th.--What shall I say? The Lord has permitted distress to come upon me like a flood,
on account of the evil doings of those for whom I have prayed often; yes,
mourned and wept for them for years past.
Is all over? Has mercy failed towards them because of
their long and willful rebellion against the light,
grace and Truth, with which they have been visited? Oh, my soul, wait you upon God,
that you be not swallowed up of overmuch sorrow.
My hands hang down, and my knees smite together with weakness and distress.
Lord help me, I beseech you, and cause your mercy, mingled with judgments,
to awaken the transgressors, that so your name may yet be praised by them.

Seventh Month 8th.--I feel the necessity of letting my words be few and savory.
Oh Lord! enable me to watch and pray, that I may not enter into temptation.
I have been engaged for a few days past in transcribing
an account prepared by my beloved cousin,
Miriam Ellis, concerning her worthy mother, Abigail Branson,
both the mother and daughter having been worthy ministers,
belonging to Flushing Monthly and Particular Meetings.
Oh, that others may be raised up in our little meeting worthy to fill their places.

23rd.--The account above referred to was read in our last Monthly Meeting.
I trust it will prove of some advantage to young and old.
Previous to our Monthly Meeting I was from home about a week,
during which I attended Short Creek Monthly Meeting.
My communication in the forepart of the meeting was on the subject of sleeping.
I alluded to this practice as being a weakness which might be and would be overcome
were we daily concerned for the welfare and salvation of our immortal souls,
and when I called it a weakness I felt a stop,
and the language ran through my mind--Is it not a wicked thing also to give up to
go to sleep when we come to meeting to worship Almighty God? But I felt that some
might think it too strong language to use in reference to this practice,
to call it wickedness.
I hesitated,
but found I could not go on without thus expressing it--
"`What if I shall call it wickedness,
as well as weakness,`" or words to this import.
I felt that some were hurt, but I trust that the oil and the wine were not.

Eighth Month 23rd.--What shall I write? The call this morning
seemed to be to pen a few lines in this little book,
but nothing presented to write.
On opening it I found just one month had passed
since I made any memorandum of my thoughts,
words or actions in this way.
Oh time, time, how precious; how exceedingly precious you feel to me;
and yet I seem altogether unable to employ you, or appreciate you aright.
I feel so benumbed,
so stupefied in regard to the best things
compared with that which my soul desires to feel,
that I fear I am farther and farther from the kingdom.
While writing this I am forcibly reminded of the
expressions of a travelling minister to my dear mother,
a few days before the death of the latter.

This female minister from England, being an entire stranger in our parts,
after attending our Monthly Meeting visited my father`'s family;
and in the religious opportunity she had with us, thus addressed my beloved mother:
"`You are not far from the kingdom of heaven, though the thought of your heart is,
that you are farther and farther from it.`" My mother was then in usual health,
but on the 30th of that month she died suddenly, greatly to our surprise and grief;
but not a shadow of doubt remained that she was safely landed.

It is nearly thirty-six years since that beloved mother died,
and still this frail tenement of clay, then apparently near the grave,
still lingers here under infirmities.
Lord, be graciously pleased to prepare me for a sudden exit, or otherwise,
for my latter end by a more lingering illness, as it may seem good to you.

24th.--Visited several invalids in the village of Flushing,
some of whom I had been to see before.
One who appears to be near the grave, and yet awful to consider,
seems in no way prepared for the change.
His countenance bespoke in some degree the situation of his mind.
A settled gloom appeared in his looks, and what if I say (for so it seemed to me),
that his very looks indicated a settled determination to ward off and
reject everything like religious impressions or religious counsel.
Oh, how my heart has yearned for this individual, but his case,
both as respects body and soul, seems to be almost if not quite, a hopeless one.

25th.--Today, our Monthly Meeting was held at Guernsey.
We went and returned the same day.
After the business of the meeting was through, I requested the shutters opened,
which was done.
I endeavored to relieve my mind in regard to Friends attending fairs,
and felt that I must discourage the practice,
fully believing there is more harm than good resulting from them.
Several Friends united with what I had to say,
and I felt relieved of a burden after discharging my duty as faithfully as I could.
The Lord only knows the exercise of my spirit for my
own safety and preservation and for that of others.

Tenth Month 13th.--The individual before mentioned was buried some weeks ago.
He appeared to die as he had determined to live, without the fear of God before his face;
cursing and swearing a short time before his death.
Oh, awful situation.
What language can set forth "`the dreadful condition hereafter awaiting such a one.
On being told by a physician that he could not live,
and exhorted him to set his accounts in order, he used profane language,
calling the physician a fool, etc.

Oh, vain man, how just is the language of the prophet,
when applied to the unregenerate and hardened condition of
fallen man--"`The heart is deceitful above all things,
and desperately wicked;
who can know it?`" What tender visitations of mercy are extended
towards us. How kindly and graciously we are dealt with.
How we are followed from day to day, and from year to year,
with this inviting language--"`Return you backsliding children,
and I will heal your backslidings.
Turn you, turn you, why will you die, etc.
But if we will turn our backs and harden our hearts against such calls of mercy,
our houses will be left desolate,
for the Lord has declared that his spirit shall not always strive with man,
because He also is flesh.`"
Though we are encompassed with weakness,
having no power of ourselves to do any good thing,
yet He who calls us to glory and to virtue has all power and wisdom,
and such as close in with the light of Christ and follow it,
these become strong in the Lord and in the power of his might,
and enabled through this holy help to resist the temptations
of the devil in all his various transformations;
and are made more than conquerors over their spiritual foes through Him that loved them.

21st.--My spirit is very sad and sorrowful.
Be pleased, O Lord, to interpose your arm of power for my deliverance from temptation.
Our late Yearly Meeting afforded at times,
comfortable and refreshing evidence that He who gathered us to be a people,
had not forsaken us, blessed be his holy name.
In the public meeting on Fourth-day,
I felt it required of me to stand up and utter this language of the prophet Isaiah:
"`Since the beginning of the world men have not heard, nor perceived by the ear,
neither has the eye seen, O God, besides you,
what He has prepared for him that waits for Him.`"

After quoting this, I said,
that the same inspired penman tells us in what way he
waited for the Lord--"`In the way of your judgments,
O Lord, have we waited for you; the desire of our soul is to your name,
and the remembrance of you.
We also must wait upon the Lord in the way of his judgments,
knowing the temple of our hearts cleansed and purified
by the spirit of judgment and the spirit of burning,
if we would be partakers of that joy which is unspeakable and full of glory.
The path to the kingdom of heaven is not a flowery path, it is by the way of the cross;
it is through deep tribulations, through fiery baptisms,
that we come to inherit the crown of life everlasting.
Jesus Christ suffered not the ignominious and painful
death of the cross to save us in our sins,
but from our sins.

I had considerable to say in this meeting, but was not very lengthy,
the subject and substance being briefly given in the above;
after which I felt peaceful and easy.
It is seldom I have felt it required of me to open my mouth in those
large public meetings during the time of our annual gatherings,
being rather baptized in spirit for the arising of the life-giving
power and presence of Israel`'s unslumbering Shepherd.
Under this exercise, I have often been led, fervently,
though silently to petition the Father of mercies to bring us into that situation,
both ministers and others among us,
in which we might experience what true and living silence is,
being afraid to open our mouths (such as are called to the work of the
ministry) without the fresh anointing of the holy One for the service.
As this is the living and fervent engagement of ministers, they will not be restless in,
or ashamed of silent meetings;
but being willing to be in the eyes of the worldly-wise as fools for Christ`'s sake,
they will lift up the standard towards Zion,
promoting the Redeemer`'s kingdom among men,
setting an example of true and living worship,
that worship which is in the Spirit and in the Truth,
for the Father seeks such to worship Him.
I thought we were favored at times in our late annual assembly to feel
something of that true and living silence that is not at our command,
in and under which, my heart did praise the Lord,
and beg that He would still everything rising up, that would tend to mar,
or disturb this holy solemnity that He was pleased to spread over us.
Oh how my heart yearns for an increase of that pure and vital
religion which characterized Friends in the rise of the Society.
In the last sitting of the Select Meeting a singular testimony
was given me to deliver which I deferred a little too long,
but was enabled to relieve my mind, and felt peaceful and easy afterwards.

Eleventh Month 5th.--My God! my God! be pleased to enable me
to bear with Christian patience and forbearance towards others
the trials under which I am now pressed down,
on account of the conduct of those, for whose welfare my heart greatly yearns.
Oh, you who have been merciful to my soul for years past--yes,
through my whole life--continue, I beseech you, to be near in this time of great need,
when the mountains press sore upon me,
and be with and round about those who take not counsel of you,
but follow their own understanding in regard to important matters, and forsake them not,
but follow them in mercy that they may not become cast off.
Dearest Father, you who only know the distress of my spirit and heart,
bore me up in days that are past under similar trials,
and have let me see that that which then weighed me down,
and pressed me even out of measure, so that I almost despaired of life,
came to be a burdensome stone to those who caused my distress,
and when the dark valley of the shadow of death was to be passed through,
the world and all that was therein could afford them no ray of comfort,
and had it not been through your adorable mercy extended in that critical, awful hour,
they had died without hope.
O God! sanctify through your adorable wisdom and goodness our hearts; body,
soul and spirit are yours, and into your hands they are committed.

First Month Ninth,
1871.--Another year has passed away and I still an inhabitant of this state of existence.
What shall I render to the Lord for all his benefits? I have
been spending five weeks at Concord with my nephew and niece,
Israel and Rebecca Steer, and their interesting family.
While there I was often reminded of the Apostle`'s advice--"`Whether you eat or drink,
or whatever you do, do all to the glory of God.`"
I strove to make this my aim and object in this visit,
though it was not professedly a religious one;
yet some opportunities for religious communication were afforded,
in which the word of counsel,
warning and encouragement were administered to
those to whom it seemed my place to give it.

While in that neighborhood, I felt a concern to see an individual,
who was almost an entire stranger to me;
yet a strong desire for his everlasting welfare pressed upon me;
and I was favored earnestly to petition the Father of mercies,
to make a way for my relief,
if anything was required of me towards this
individual in the way of religious communication.
I felt no liberty to mention my concern to any one.
The time was drawing near when I expected to return home,
and the concern to see this individual still pressed upon me;
when to my surprise he came to my nephew`'s and
dined with us. On sitting down at the table,
a weighty concern took hold of my mind that I might be faithful to manifested duty,
accompanied with a passage of Scripture forcibly and livingly presented.
I could eat but little, but before we arose from the table,
I expressed what appeared given me to say,
without any particular allusion to the stranger present,
yet felt measurably relieved of the burden,
and rejoiced that this opportunity was afforded; and could but marvel at the wisdom,
and wonder-working power of the Almighty,
who made a way for me when there appeared no way.
Blessed be his holy name forever.

At one place where I visited while at Concord, near the time for leaving,
a passage of Scripture forcibly and weightily presented to my mind,
with an intimation to revive it in the presence
of the family and friends with me. I hesitated,
and reasoned,
fearing it might look like implicating those present in
a way and manner that did not fit them.
But I found that if I left the house with a peaceful mind,
I must be faithful to apprehended duty.
I therefore expressed with fear and trembling what was before me,
and felt peaceful and easy afterwards, without any anxiety to know why I was thus led;
but was afterwards informed that the woman Friend who belonged to the house,
and who was affected to tears by what was said,
desired I would not feel uneasy because of my communication, that there was cause for it.

Third Month 9th.--Today attended the funeral of our beloved Friend, Joseph Hobson,
who peacefully departed this life on the 7th. I
several times visited him during his illness,
and found him mostly engaged in earnest wrestling for the blessing of sanctification,
and a preparation for the solemn close.
Great were his conflicts of spirit while the enemy was
assiduously endeavoring to cast him down below hope;
but He who puts to flight the armies of the aliens,
and who arises for the oppression of the poor, and the sighing of the needy,
was pleased to calm every troubled emotion,
speaking peace to the weary and heavy laden soul.
Oh that men would praise the Lord for his goodness,
and for his wonderful works to the children of men.
This dear Friend had long been an elder in our meeting,
faithfully sounding the alarm when the enemy made his approaches,
by introducing unsound doctrines and practices in the Society;
and great were his exercises and grief on account of
false brethren on the right hand and on the left;
but the Lord has taken him to everlasting rest, where the wicked cease from troubling,
and the weary are at rest.
My soul has been deeply instructed, and impressed, while sitting in the room,
and by the bedside of this dear Friend in his last illness.
It plainly appeared to me that his deep exercises,
baptisms and temptations were permitted and dispensed,
not only for his good and enlargement and purification;
but more especially to drive us home, who were surrounding him--that is,
to look at our own spiritual condition,
and search narrowly for that which hinders our acceptance with the beloved of souls.
O how these words came home to my heart when he said to me,
"`I fear I am not deep enough.`"
It seemed to me that this very fear that impressed his mind on his own account,
was surely for others, more than for himself.
My spirit was then poured forth in vocal supplication,
that the Lord would deepen us in the root of life,
and raise up standard-bearers in our poor backsliding Society;
to take the places of those who had been and were being removed from
among us. Several times during the illness of this dear Friend,
I felt constrained to appear in vocal supplication and thanksgiving by his bedside;
which seemed rather remarkable to me,
as I have long been shut up as to any vocal service in our meetings for worship.
May I never presume to strive for an opening, when the Lord has shut, or to shut,
when He opens the spring of religious communication.

Fourth Month 3rd.--Had considerable conversation on religious
subjects with a member of the Methodist Society,
touching ministry, worship and prayer.
He plead the propriety of ministers receiving
some compensation for their labors in the Church;
but, was opposed to great salaries, such as some demand and receive.
I told him, the little or the much received in the way of pay for preaching,
involved the same principle, and was contrary to the gospel of our Lord Jesus Christ,
who said to his disciples--"`Freely you have received,
freely give;`" and instanced the example of the Apostle Paul,
who labored for his own support, and that of others.

I told him, it was the prerogative of the Head of the Church, and belonged not to man,
to choose and qualify for the work of the ministry,
and no one has a right to choose or refuse for himself.
The gospel ministry is free, and is exercised in demonstration of the spirit and of power.
The apostle said, "`That the gospel which was preached of me, is not after man.
For I neither received of man, neither was I taught it,
but by the revelation of Jesus Christ.`"
We had some plain and interesting conversation,
which I trust did not tend to the dishonor of Truth.

20th.--Today, had a short communication in our Monthly Meeting,
both before and after the shutters were closed.
In the forepart of the meeting, after my cousin Asa Branson had spoken,
I arose and said--"`It is not for the dead that have died in the Lord that I mourn;
it is not for the living that are preparing for
a happy and glorious immortality that I grieve;
but it is for those whose spiritual buildings are going up on a sandy foundation,
which the storm beating vehemently against, must bring down.
It is for these, and those who are in their false resting-places,
that my spirit deeply laments before the Lord God of Hosts.`"

After a short exhortation to all classes to examine their spiritual accounts,
not forgetting or leaving myself out of the number, I closed,
and felt in hopes that I had not hurt the good cause.
Month after month my mouth has been closed in our Meetings for Worship,
and deep have been the travail and exercise of my spirit on my own account,
and that of my brethren and sisters in religious profession with myself.
Oh, that I may be preserved by the power of God from
taking my flight in this wintry season is,
and has been, the feeble and earnest petition of my soul.

23rd.--Attended Guernsey Meeting,
where my mouth was opened in a little testimony for the Truth.
I was reminded, and to speak of it,
that the apostles of our Lord and Savior Jesus Christ rejoiced that
they were counted worthy to suffer for his blessed name`'s sake,
who died for us--who bore the scoffing, scourging, spitting upon,
and nailing to the cross, for poor fallen, finite and rebellious man;
and rose again to save us, not in our sins, but from our sins.
Are we willing to suffer,
and to walk in the way pointed out by this blessed Savior? Are we concerned,
young and old,
to follow Him in the way of his requirings? Obedience must be yielded thereto,
if we would be owned and received of Him who is Lord of lords and King of kings.

I have trodden the slippery paths of youth; I have been surrounded with many temptations,
incident to that period of life, possessed of a light, airy and proud heart naturally,
I deeply feel for and sympathize with the young;
but I can offer them no excuse for continuing in that state and condition in which,
if called from works to rewards,
they would be unprepared to hear the welcome
language--"`Enter you into the joy of your Lord.`"

Sixth Month 19th.--Attended the funeral of my beloved cousin, Joseph Wilson,
who departed this life in great tranquillity and peace of mind, on the 17th inst.,
about half-past six o`'clock a.m. His bodily sufferings were
very great for a few days before his death,
and for several hours before the close they were agonizing.
But not a complaint escaped his lips, and his countenance was calm and serene.
"`Blessed are the dead which die in the Lord.`"

This dear Friend had long filled the station of
overseer and elder in our Monthly Meeting,
and we feel that we have lost a father in the Church.
His example and precept had long been such as to render him a
bright and shining light to those acquainted with him;
and the following language quoted at his grave-side by my cousin, Asa Branson,
was no doubt entirely applicable to his situation,
and doubtless was responded to in the heart of almost every one present who knew him:
"`Mark the perfect man and behold the upright, for the end of that man is peace.`"

Seventh Month 17th.--The exercises of my spirit are very great on account of
the lukewarmness and indifference which prevails among us as a people,
and individually in my own neighborhood and meeting, as well as other places.
Oh, what will be the consequence? Parents and children joined
together in lowering the precious standard of Truth.
The former indulging the latter in great departures from that simplicity in dress, etc.,
which the Truth leads into; and any remarks now made specially against our members,
young Friends joining in with the fashions of the day, and recommending the plain dress,
etc., appears to be treated by some plain parents, with feelings of resentment;
and by the children of such parents, with utter contempt.

My soul has been and is bowed down under an inexpressible weight,
while I behold the gradual departure from the testimonies which cost
our forefathers all that was near and dear to them in this world;
not counting their life dear unto themselves,
that they might finish their course with joy.
While under this weight of exercise,
the consideration and query often comes up before me on this wise:
How or what shall I do to be clear, and to promote the Redeemer`'s kingdom among men,
according to the will of my Heavenly Father? There
appears but little opening to labor in the ministry,
or in counsel and exhortation in families, or in meetings.
Keep me, oh Lord,
in my right sphere! prevent my lips from uttering unsavory and uncalled for expressions,
in this day of great trial; plunge me in the river of judgment,
take away all the leprous spots from me, continue your judgments,
until a clean heart is created in me, and a right spirit renewed,
then will I teach transgressors your law, and sinners shall be converted unto you.

Tenth Month 31st.--Oh Lord, my God! have mercy on me, for my heart is sore troubled,
you only know how it is with me,
and into your hands I desire to be able to commit the keeping of my soul,
as unto a faithful Creator, who will do all things well.
Oh, cast not off, I pray you, my prodigal brother; but turn your hand upon him,
I humbly pray you, oh you almighty and holy One, and bring him back,
if consistent with your holy will, into a state of true repentance.
Oh, have mercy upon my poor wandering nephew,
for whom my soul has been poured out by day and by night before you.
Amen, and amen.
