== Preface

Believing that the account of the life, exercises, and religious labors,
of my beloved cousin, Ann Branson, as set forth in the following pages,
is the best memorial that could be prepared concerning her;
yet I thought I might say in reference to myself,
that she never daubed me with "`untempered mortar,`"--she never cried "`Peace, peace,
when there is no peace.`"
She never "`sewed pillows to my arm holes,`" to make me rest more easy in my sins.
There was no compromising the Truth with her.
When it was required of her, she could say, as Nathan said to David, "`Thou art the man.`"
The encouragement given me, was of this peculiar order, viz:
"`Do no more nor less than the Master requires.`"
Thus showing the Fountain whence she received her own supplies.
An upright pillar has been removed from the Church; and I, in particular,
have lost an endeared and choice counsellor.
And my feeble petition has been and is, Help O Lord,
that I may be prepared for the like happy end, which I believe she experienced.
Some of the language of Thomas Ellwood concerning George Fox, seems so applicable to her,
that I will close this short testimony with some quotations.--"`[She]
was valiant for the Truth, bold in asserting it, unwearied in laboring in it,
steady in her testimony to it, she was richly endued with heavenly wisdom,
quick in discerning, sound in judgment, a lover of righteousness,
an encourager of virtue, justice, temperance, meekness, purity, chastity, modesty,
humility, charity and self-denial in all, both by word and example.
She was courteous in conversation, weighty in communication, instructive in discourse,
free from affectation in speech or carriage.
A severe reprover of hard and obstinate sinners,
a mild and gentle admonisher of such as were tender and sensible of their failings:
not apt to resent personal wrongs, easy to forgive injuries; but zealously earnest,
where the honor of God, the prosperity of Truth,
and the peace of the Church were concerned.
She lived and died the servant of the Lord.`"

[.signed-section-signature]
Asa Branson
