== Chapter I

[.chapter-synopsis]
* Her Birth and Childhood
* Some Account of Her Parents and Other Members of the Family
* Apostasy of Elisha Bates, and Her Exercise Concerning It
* Thomas Shillitoe`'s Testimony Concerning Joseph John Gurney`'s Doctrines
* The Philadelphia Appeal
* Events of Her Early Womanhood
* Her Disobedience, and Repentance, and Forgiveness Therefor
* Her Bed of Sickness, and First Sermon
* Her Subsequent Recovery

I have long believed it would be required of me to leave in writing
some account of the Lord`'s gracious dealings with me from early years,
in connection with some other accounts bearing thereupon.
And now in the fifty-sixth year of my age, I have made the commencement,
having nothing in view that I know of but to be found in the way of my duty.

I was born the twenty-second of the Twelfth Month, 1808. My parents,
Jacob and Rebecca Branson, removed from Virginia in 1805, and settled at Flushing,
in Belmont Co., Ohio, which was the place of my birth.
They had nine children--four sons and five daughters.
I was the fifth daughter and the sixth child.
I was naturally of a hasty, fretful temper,
which was perhaps increased by an erysipelas humor, particularly in my face and arms,
to which I was subject from my infancy.
It often occasioned me much suffering,
and as I grew in years was no small mortification to my pride,
which I esteem not the least of the favors bestowed upon me;
and can remember sometimes wishing that I had never been born.

Being given to fretfulness,
I often became the subject of animadversion by the other children,
who thus added to my affliction by upbraiding me with my fiery, hasty temper.
Children of the same family are often very differently constituted,
as respects their natural tempers as well as their bodily health,
and require judicious treatment for their present and future comfort and welfare,
as they advance in life.
My father was a minister, and my mother an elder, of the religious Society of Friends;
and they were concerned to train up their children in
the nurture and admonition of the Lord.
I was twenty-five years old when my mother died;
and I have no recollection of ever seeing her out of humor,
or of hearing her speak an unadvised, unbecoming word to my father, or to her children.
From her children she required prompt obedience,
and though she seldom resorted to the rod, yet she did not wholly discard it;
but when it was necessary to wield it she did it with a portion of that
wisdom which is wanting in those who spare the rod and spoil the child.
My father was naturally of a hasty temper,
and had much more to contend with in this respect than my mother;
but he was of a generous, free and forgiving spirit:
keeping in view the best welfare of all around him.
Having experienced the axe laid to the root of the corrupt tree in himself,
he was firm and undeviating in the maintenance of those Christian principles
and testimonies given to our religious Society to uphold to the world.
He was not betrayed into that weakness and folly which characterize
many parents in our Society at the present day--that of giving undue
liberty and indulgence to their children in respect to dress,
company, etc.; encouraging them by their example to follow the vain fashions,
manners and maxims of the world.
But when my father drew near his close he could, with calm and Christian composure,
say--whilst his children were gathered around his dying
bed--"`I am clear of the blood of my children.`"

The house and heart of my parents were always
open for the reception of friends and strangers,
and it was with true and genuine hospitality that the
best it could afford was freely offered them;
many of whom it was our privilege to entertain.
During the Hicksite controversy and separation, my father had much to bear;
many hard things were said of him, and many reflections cast upon him,
and I being young and not fully understanding the cause of all that was said and done,
became very much concerned and troubled, not knowing what might be the result.
Whilst in this situation of mind,
I one night dreamed that I was standing in the path that led to our spring,
thinking about my father, when suddenly darkness overspread the earth;
then I looked above my head, and saw a light,
and heard a voice which said--"`When I make up
my jewels I will gather him amongst them.`"
This dream was a great comfort to me,
for I believed it was intended to convince me that my father was on the right ground,
notwithstanding all that was said and done against him.
And I have lived to see him leave the world as a shock of corn gathered in its season,
whilst many who opposed him have come to nothing, or dwindled in the best things.

I have already said that my mother was an Elder.
She was of a sound judgment, and exercised that judgment for the encouragement of right,
and the discouragement of wrong things in her family and neighborhood,
and in society at large, where her lot was cast.
She was careful neither to overrate nor underrate the gifts and services of ministers,
and when she felt an uneasiness with any,
where duty called for an expression of that uneasiness, she would go to the individual,
or individuals, and relieve her feelings in a Christian spirit,
and in such an honest way as left no doubt of her heartfelt concern
for the best welfare of those to whom she administered caution,
reproof or whatsoever might be given her in this way to communicate.

A minister belonging to our Monthly Meeting had, in his ministerial communication,
given some uneasiness to my mother; he was apprised of this,
and subsequently preaching a sermon, he said to my mother--"`Well, Rebecca,
what hast thou heard today,
that thou didst not approve?`" My mother replied--"`I have heard the bell,
but where was the pomegranate?`" This minister afterwards went with the Hicksites,
but was finally disowned by them, and came to nothing; having at one time three wives,
all living, though not in the same neighborhood.
Some years after this a minister from another Quarterly Meeting,
travelling with a minute for religious service, came to my father`'s;
he had a religious opportunity in our family,
where two individuals not members of the family were present; to one of these,
this minister spoke in a way that gave great uneasiness to my parents.
After the opportunity was over my mother took this
minister aside and told him that he well knew,
that he had not spoken to the condition of this individual,
and warned him not to be deceived, and conclude his situation better than it really was.
My parents advised this minister to return home, which he did.

This minister, in the Separation of 1854, went with the Gurneyites,
though he had at one time clearly seen and condemned
the unsound writings of Joseph John Gurney.
When Elisha Bates apostatized from the doctrines and
testimonies of the religious Society of Friends,
it caused great excitement particularly in the minds of many
of the young people who were strongly attached to him.
It was at our meeting at Flushing,
that he made his first public avowal of the unsound doctrine which he had embraced,
touching the resurrection of the dead, viz:
That these material bodies of ours will rise from the dead, etc.

Friends were generally surprised and startled at
this unscriptural and anti-Quaker doctrine.
They were also bowed down under an exceeding weight, and exercise;
and some took an early opportunity with him on account thereof;
but he gave them no satisfaction.
I was at that time from home, teaching school at Barnesville.
The news soon came to that neighborhood that Friends at Flushing were greatly
dissatisfied with Elisha Bates on account of the doctrine which he had preached,
and had let him know it. I soon fell to judging Friends for
calling in question so great and good a man as E. Bates.
Soon after this Elisha, and some of his friends who went with him in his new views,
attended Stillwater Quarterly Meeting;
he and they were high and flourishing in their words and manners.

My father followed Elisha to this meeting with a heavy heart and downcast look.
I soon found an opportunity to let my father know what I thought of
Friends calling in question such a man as Elisha Bates,
and that I thought Friends ought to be very careful how they censured,
or judged down anything he said; thus giving my father a gentle,
and as I then thought a necessary admonition;
being supported in my views at this time by some whose judgment I highly esteemed.

My father made but little, if any, reply to what I said,
but his countenance and his whole deportment on
that occasion has lived in my remembrance.
He appeared to be weighed down with inexpressible exercise of mind,
and I have since had just cause to believe,
that his prayers for my preservation from the baits and allurements
of Satan ascended at that time to the throne of Grace,
and were regarded by Him who heareth the petitions of the righteous,
and answereth them out of his holy habitation.
Soon after this I returned home and found my sister Lydia,
who was some years older than myself, and a thoughtful, religious young woman,
greatly exercised, and distressed concerning the events then transpiring.
She had been greatly attached to Elisha Bates,
believing him to have been a Gospel minister, and a father in the Church;
but his recent movements, and anti-Quaker doctrine she was not prepared to unite with.
We searched and read the Scriptures,
and reasoned and meditated thereon (too much in our own will and wisdom),
to find out whether Elisha`'s views were right or wrong;
but this did not bring the reward of peace, or satisfy the soul.
My parents, both by example and precept, advised quietude and stillness,
which we found tended to our settlement in the Truth as it is in Jesus.
They believed that time would make manifest what
spirit Elisha and his supporters were of;
or rather that, in the Lord`'s time and by his Spirit,
they would be seen in their true colors.

Previous to his giving uneasiness to his friends by the promulgation of unsound doctrine,
Elisha Bates had obtained liberty from his Monthly, Quarterly,
and Select Yearly Meetings, to make a religious visit to Friends, and others, in England,
Ireland, etc.
In London Yearly Meeting he met with a cordial
reception from many of their leading members,
who were not only prepared to receive him with his new views,
but also to advocate and advance other sentiments and practices
greatly at variance with the doctrines and testimonies of Friends.
E+++.+++ Bates, Isaac, and Anna Braithwaite, united together in holding public meetings,
particularly for the young people,
and thus sowed broadcast their unscriptural and anti-Quaker views.
But they and others were too fast in their movements to take
along with them any considerable number of followers.
Soon after E. Bates returned from this visit he made a second
one to England without the consent of the Society;
and while there, was baptized with water,
which set the minds of many Friends at rest concerning
him who before were disposed to advocate his cause;
but now he was taken under dealing and disowned.

He wrote and published much against early Friends, particularly against George Fox,
endeavoring to render their principles and
religious views odious in the eyes of the world,
but he had but few followers,
though he sought honor and popularity amongst men by forsaking and
writing against the Society of which he had been a useful member,
and an anointed minister while he abode in the Truth;
but when he forsook the Truth and went after his own
devices the Lord dealt with him as He did with Balaam.
For the society with whom he joined in religious
profession after he was disowned by Friends,
never promoted him to honor,
so that it might be said of him as it was said to
Balaam--"`The Lord hath kept thee back from honor.`"

Previous to sailing for Europe the second time Elisha
Bates again visited our meeting at Flushing,
where he preached his own funeral sermon (In a
spiritual sense) in a very impressive manner,
as the sequel proved.
He quoted from the fifteenth chapter of Ezekiel,
comparing those who forsook the principles and testimonies of
Friends to the rejected vine there spoken of;
they became as outcasts, meet for no good work whatever, etc., etc.
I seem to behold him at this very moment, as I then beheld him--grave,
and commanding in look and gesture, and with all the fervor and eloquence,
for which he was remarkable,
portraying the sad and sorrowful condition of those who
thus make shipwreck of faith and a good conscience.
I seem even now to hear this plaintive language as it fell
from the lips of one just ready to realize in his own
experience the mournful truth thereof--"`Not meet for any work.
Not fit for a pin to hang any vessel thereon.`"
And I see and feel in connection with this the indispensable
necessity of taking heed to our Saviour`'s injunction--"`Let
him that thinketh he standeth take heed lest he fall.`"

Soon after E. Bates was disowned,
Joseph John Gurney came to America on a religious visit, and Thomas Shillitoe declared,
in his dying testimony, unequivocally against the generality of his writings,
as being "`non-Quaker principles, not sound Quaker principles, but Episcopalian ones;
and they have done great mischief in our Society; and the Society will go gradually down,
if it yields to the further circulation of that part of his works
which they have in their power to suppress--this is my firm belief.`"
And time has verified to a great extent the truth of his testimony.

Jonathan Evans, in a letter to John Wilbur, says:
"`I have perused a great deal of his (Joseph John Gurney`'s)
writings and have been sorely distressed at the darkness and
confusion which are almost inseparable from their contents.`"

Abner Heald, a sound Gospel minister belonging to Ohio Yearly Meeting,
on his deathbed bore this testimony in the presence of substantial witnesses, viz:
"`Those who say that the writings of Joseph John Gurney
are in accordance with the writings of early Friends,
will be found liars before God--his writings
darken the atmosphere of the Lord`'s firmament.`"
This is also the testimony of my heart concerning the writings of Joseph J. Gurney.

In 1846 and 1847 the subject of unsound doctrines,
written and published by members of London Yearly Meeting,
took such hold of the Meeting for Sufferings of Philadelphia that a document
was prepared by that Body and subsequently adopted by the Yearly Meeting.
It was entitled an "`Appeal for the Ancient Doctrines of the Society of
Friends,`" and contrasted portions of the writings of Joseph J. Gurney and
Dr. Edward Ash with the early standard writers in the Society,
on the same subjects,
and the discrepancies were thus brought more fully and generally before the public eye.

In 1846 Ohio Yearly Meeting sent to London Yearly Meeting as follows, viz:
"`The peace and harmony of this Yearly Meeting,
in its several branches as also in its collective capacity,
at the present season have been greatly disturbed on account of the doctrinal
writings of a member or members of your Yearly Meeting in circulation amongst us,
which are not deemed by us to be in accordance with those on the same subjects,
of our ancient approved authors.`"

Ohio Yearly Meeting subsequently adopted the "`Appeal for the Ancient
Doctrines,`" as published by Philadelphia Yearly Meeting.
Notwithstanding the brotherly appeals which had been issued
from time to time by Philadelphia and Ohio Yearly Meetings,
to London Yearly Meeting, on the subject of the unsound writings alluded to,
London Yearly Meeting in 1847 issued a memorial,
or testimony concerning Joseph John Gurney,
in which it is said--"`resigning himself in the simplicity of
a little child to the unerring guidance of the holy Spirit,
he was enabled, though surrounded by adverse circumstances, to make a full surrender;
and he maintained with holy boldness,
the principles and testimonies of the Society through the remainder of his life.`"
And again--"`It will not be expected that we
should here advert at any length to his writings,
but it is right for us to express our belief,
that in these undertakings as in every other,
he was actuated by a sincere desire to promote the glory of God,
and the welfare of his fellow-men,
and at the same time to maintain with unflinching integrity,
the Truth as it is in Jesus.`"
It would then appear that Joseph J. Gurney`'s attacks on
the doctrines and integrity of the early,
and standard authors in the Society are "`believed by London Yearly
Meeting to have been called for to promote the glory of God,
and the welfare of his fellow-men,`" and needed to "`maintain with unflinching integrity,
the Truth as it is in Jesus.`"
What I have written respecting the apostasy of Elisha Bates,
I have written under a belief that it was right so to do;
I have also believed it right for me to give forth an unequivocal
testimony against the unsound writings of Joseph John Gurney,
being satisfied from my heart with the doctrinal writings of early Friends,
and have greatly admired the wisdom and goodness of God in enabling and qualifying
Robert Barclay to give forth such a clear and scriptural exposition of the
doctrines of our religious Society as is contained in the [.book-title]#Apology.#
And I have often said in my heart, it is the Lord`'s doing, and marvellous in mine eyes.

But to return to my early life--I was naturally of a volatile disposition,
and took great delight in childish play;
though I can remember having very serious thoughts and impressions when quite young.
On one occasion having told an untruth when a child, it gave me great uneasiness,
so that I could not sleep when I went to bed; but prayed that I might be forgiven;
and I remember going into the orchard alone and praying
to my heavenly Father to keep me from evil,
and make me a better child.
I am satisfied that the minds of children are often seriously
impressed with good desires and feelings when quite young.

At one time having committed a mischievous act which I knew would occasion
my father to enquire of his children who was the author of the mischief,
I had great reasonings in my mind whether to own or deny the act;
but finally resolved to speak the truth,
though it might subject me to the discipline of the rod:
so when my father called upon us to know who had committed the depredation,
I unhesitatingly answered that I did it,
and I felt great joy that I had been preserved from equivocation,
or willfully departing from the truth, through the fear of punishment;
and it was a strength and encouragement to me afterwards to adhere to the truth.
I remember on one occasion when I was a child, returning from school,
it being meeting day, I was met by my father, who enquired where I was going; I answered,
I was going home,
as I did not want to go to meeting that day--the rest of the scholars having gone.
My father took me by the hand and led me to the meetinghouse,
greatly in the cross to my will.
As we walked along, anxious to find an excuse for absenting myself from meeting,
I told my father that the carpenter he had employed in his service, calling him by name,
did not always go to meeting on Fourth-days.
This little incident of my father`'s faithfulness,
and my own childish flimsy excuse for absenting myself from meeting
on that occasion by referring to the example of the carpenter,
has often since been brought to my remembrance.

Children take great notice of the example of those who are older than themselves,
and are apt to lay hold of anything that they see in others,
that they think will be an excuse for their own faults.

The carpenter I mentioned, in his eagerness to grasp the things of the world,
often neglected the attendance of our religious meetings: and after a while,
for the sake of accumulating,
he moved where there was no meeting of Friends within his reach;
but the judgments of the Lord overtook him,
for he was soon visited with a fever which afflicted his limbs
and made him a cripple through the rest of his life.
As soon as he was able he moved back into our neighborhood,
and became for a time more thoughtful of his spiritual welfare;
he attended meetings pretty regularly, but being again able to work at his trade,
he relapsed into his former careless habits, and finally forsook meetings altogether.
Before he left our neighborhood the last time and moved west,
the Lord gave me a close testimony to deliver to him,
warning him that the day of final reckoning would come, and if his talent, or talents,
were not occupied to the glory of God, awful would be the consequence, etc.
But he did not take the message well,
which he showed in his conduct towards me afterwards;
but I felt satisfied with having done my duty.
His last days were said to have been spent in apparent forgetfulness of his God,
who had dealt thus mercifully with him.

The foregoing account of this carpenter I have recorded as a warning,
not to trifle with the offer of God`'s mercy through Jesus Christ to the immortal soul,
lest He withdraw his lovingkindness,
and leave the heart desolate--awful state for
any to be found in--Lord preserve me therefrom,
saith my soul.

When I was going to school I was amongst the number who, when taken to meeting,
often fell into a dull, sleepy condition.
I felt that this was wrong,
and it became my daily concern that I might be enabled
to overcome this sleepy feeling in meeting,
seeing no use in people going to meeting to sleep.

One Fourth-day morning I came to this conclusion, viz: "`I will go to meeting today,
and if I am overcome with sleep as I have been,
I will in future stay at home`"--not thinking whether my parents would allow it or not.

I went to meeting under exercise that I might be preserved from this shameful practice,
and the Lord condescended to show forth his power even to a child as I was,
for He took sleep from my eyes at that time,
and for several years afterwards I never knew what it
was to feel sleepy in our religious meetings,
though before this I had been so given to it that I
have sometimes come near falling off the bench.
I write this to encourage children, and others,
to strive lawfully for the blessing of preservation from this practice,
and in the Lord`'s time He will deliver them from it.

When I was in my fourteenth year my sister Deborah died.
She was next older than myself.
After her death I thought I could never again indulge in idle conversation,
laughing and jesting, to which I was naturally very much prone;
but the impressions made by her death on my
feelings were too much like the morning cloud,
and early dew, that soon pass away.
Her last words on bidding her sisters farewell,
were--"`May the Lord hold you in his hand`"--which prayer has been answered,
with respect to those who have since been taken from works to rewards.
My sisters, four in number,
were all taken away by death before they reached meridian age;
and all left a comfortable assurance to their
relatives and friends that their end was peace.

When I was about sixteen years of age my eldest brother engaged in
the mercantile business in a little village about four miles from my
father`'s. As my brother was not then married,
my parents consented for me to go and keep house for him for a while,
that I might be company for him, assist some in his business, etc.,
there being no Friends in the place.
When I was settled in my new situation I found I was surrounded with
temptations to which I had before been a stranger.
I was soon invited to a party and had an inclination to go,
but my parents had kept me from indulging in the fashions of the world,
and I knew that I had no clothes that would correspond
with the dress of those I was to mingle with.
I concluded that I should be a speckled bird amongst them,
and therefore did not go. Thus I found the care
of my parents to have been as a hedge about me,
preserving at that time from running into unprofitable company.

After this party was over,
it was reported there were some young Quakers present who were said to have
been the wildest and most unbecoming in their conduct of any that attended.
I then felt truly thankful that I was not one of the guests.
These young people, Quakers as they were called, had run out in their dress,
language and manners,
so as to have no claim to the name of Friends except a right of membership;
and here let me remark,
it would have been justice to these young people and a credit to society,
had they before this been treated with, and if they could not have been reclaimed,
disowned.

I now began to consider how I should appear amongst my new associates,
being so very different in my dress, language and manners from those who surrounded me,
for I had frequently to be in the store when my brother was absent,
as well as at other times.
I thought of trying to fashion myself a little
more in accordance with those I mingled with,
and resolved at least to wear my hair in a different
style from that to which I had been accustomed;
but as I was walking the floor one day reasoning upon the subject,
I opened the Bible which was lying upon the table,
and the first words that presented to my view were
these--"`When pride cometh then cometh shame,
but with the lowly is wisdom.`"
I felt this to be the reproof that I needed, and gave up my plans.
I saw that it was pride,
and pride alone that made me ashamed of that plainness
and simplicity which becomes a Christian,
and I was humbled under a sense of the goodness of my heavenly
Father in thus condescending to strengthen that in me which
had been wrestling with me to prevent me from doing wrong.
My brother,
who had been a wild young man and had deviated in dress and
address from the testimonies of Friends--though at that time
somewhat more thoughtful--observing my exercises,
said to me on one occasion,
"`I do not want thee ever to do as I have done`"--
meaning in regard to keeping unprofitable company,
departing from the plain dress, language, etc.
This I perceived he spoke under some exercise on
account of his own deviations and for a warning to me,
which proved a word in season.
In this town and neighborhood Quakerism was very much scoffed at. On one occasion,
my brother being absent, a man of some rank and fortune in the neighborhood,
came into the store and thus accosted me--"`How does
thee do?`"--emphasizing every word as he spoke it,
no doubt to let me know that it was in derision of the plain language and
little Quaker girl that he thus addressed me. This did not tempt me to
depart from the plain Scripture language which I strictly adhered to,
but it raised in my young mind a feeling of surprise and indignation,
that a man of his age, sense and learning, should stoop so low as thus to address me.

I did not stay long with my brother in this village,
but long enough to come to this conclusion, and that too, as I thought, on good ground,
viz: That members of our religious Society, whether young or old,
must be in possession of the truth as it is in Jesus,
or they will not and cannot consistently support
the principles and testimonies of Friends.
Whilst living here I met with a remarkable preservation from fire,
which I think proper to mention.
My brother not being well,
laid down early one evening in the same room where I was sitting, and soon fell asleep.
I continued sewing and reading for some time after,
and then laid my sewing and head upon the table
by which I was sitting and fell asleep also;
how long I slept I cannot tell, but I was aroused by a loud crackling noise,
like that produced by pouring water on a stick of burning wood.
I had left the candle burning upon the table; it had fallen out of the candlestick;
the table had been on fire and a considerable hole burnt in it;
but the fire was gone out as if extinguished by water,
and the crackling noise which awakened me was still to be heard.
A large dictionary and Bible were considerably burned, but they too had ceased to burn,
but what was most remarkable,
a piece of white muslin upon which I had been sewing was partly burned up;
this too had ceased to burn, as if the flame had been extinguished by the hand of man.
This preservation from fire made a deep impression on my mind,
and I have ever considered it a special interposition of Divine Providence.
My head lying near the burning materials must have been subjected to the greatest peril.

My brother as well as myself was struck with wonder and surprise at what had taken
place--and I record this special deliverance from fire even at this time with
feelings of gratitude and wonder--gratitude to Him who extinguished the flames,
and wonder at the compassionate regard of my Saviour towards one so unworthy his notice.

In this village was an Inn, just opposite our dwelling, where the people sometimes had balls,
and parties of pleasure, so-called.
The awful feelings produced, and the impressions made upon my youthful mind,
by the noise of the fiddle and the sound of the feet of these time murderers,
I have no language fully to set forth.
No doubt they often felt the convictions of the Holy Spirit for such conduct,
but by striving against its reproofs they became hardened in sin and transgression.

A religious young woman of the Methodist Society gave
me an account of her experience in regard to dancing,
etc., which, as near as I can now remember, was on this wise:
It had been the practice in her father`'s house to have dances, etc., frequently,
in which she had participated;
but her mind became impressed with the sinfulness of such amusements,
and she sought to shun them.
By so doing she soon became the subject of derision and persecution.
On one occasion, having hid herself in order to avoid the dance, she was sought after,
found, and taken into the dancing room and compelled to take the floor.
After taking a few steps in the dance, such horror of mind seized her,
that she resolved to dance no more, let the consequence be what it might.
In vain did her relations and associates use
every endeavor to upset her good resolutions;
but she gained upon them by her faithfulness,
and I think she said--when conversing with me--that the practice had
been discontinued in her father`'s family for some years.
She also observed,
that as her mind became impressed with the sin of dancing and its accompaniments,
she felt it required of her to lay aside her gay dress, her superfluous ribbons,
and gaudy trimmings,
and when compared with the generality of that society in the present day,
she was a plain woman.
It is due to my parents to say, that it was not their choice, nor by their encouragement,
that my brother engaged in business in this town.

A few years after his marriage he left the place,
narrowly escaping therefrom with his right of membership.
Several young men--members of our Society--one after another
were placed in the same store in order for worldly gain,
all of whom lost their rights of membership before they left.

The following advice contained in our book of Discipline is worthy the
serious consideration and observance of Friends both young and old:

"`It is the affectionate desire of the Yearly Meeting,
that Friends may wait for Divine counsel in all their engagements,
and not suffer their minds to be carried away by an inordinate desire of worldly riches;
remembering the observation of the Apostle in his day,
and so often sorrowfully verified in ours--They who
will be rich fall into temptation and a snare,
and erring from the faith pierce themselves through with many sorrows.`"

In the eighteenth or nineteenth year of my age I attended a Meeting for Worship,
about eight miles from my father`'s, appointed for Elizabeth Robson,
a minister from England, in which she had large and laborious service,
it being but a short time previous to the Hicksite separation.
On my way home from this meeting some weighty and serious
considerations took hold of my mind on the subject of the ministry,
particularly relative to women`'s preaching,
and this language of the Apostle was impressively brought to
my remembrance--"`We are made as the filth of the world,
and are the offscouring of all things unto this day.`"
These words were accompanied with such feelings as made me exclaim in
the secret of my heart--"`Make of me anything else in the Church,
but a minister I can never be.`"

Sometime after this, whilst sitting in our meeting at Flushing under religious exercise,
a solemn feeling covered my mind,
attended with an impression that it was required of me to appear in vocal supplication,
and felt as if I could scarcely resist the gentle,
powerful and persuasive influence of that holy life-giving power and spirit,
by which my heart was solemnized and my spirit tendered, and I seemed a wonder to myself,
thinking it scarcely possible that such an one as I should be
called upon to address the Throne of Grace publicly.
So I put it from me,
at the same time saying in my heart--"`If Mary Jones (a beloved minister
then belonging to our meeting) will speak to my condition today,
I will believe this impression which I have felt to be a real requirement.`"
I asked a certain sign, which was granted.
This Friend presently arose and said that she believed there
were those in that meeting amongst the youth who were,
or would be, called to the work of the ministry,
with more that seemed pointed and encouraging; but I put it away from me as a dream,
or vision of the night.
Soon after this, on taking my seat in our meeting, this concern again revived;
but I again endeavored to put it from me, saying, after so long a time, etc.,
I will yield.
But God is not to be mocked,
and I presently heard this language which was addressed to a rebellious people formerly,
addressed to the ear of my soul, viz:
"`Ye shall not see me henceforth until ye say blessed
is he that cometh in the name of the Lord.`"
All concern thus to appear in our meetings was now taken from me,
and I had almost forgotten that such a thing had been required until
awakened by the judgments of Him who can bring all things to our remembrance.

In the winter of 1832 and 1833, whilst teaching school from home, I took a heavy cold,
which affected my lungs, and was followed by a hard cough, some fever,
and general debility.
But on my return home, hoping and expecting soon to regain my usual health,
I engaged with my cousin, Asa Branson, as a teacher in Friends`' school at Flushing.
We commenced with forty scholars, and I was deeply interested,
but my health soon obliged me to quit the schoolroom.
This was a great cross to my natural will and inclination.
In vain did I hope and desire.
In vain did I strive and struggle, week after week and month after month,
to become liberated from this unexpected and grievous dispensation of affliction.
But my heavenly Father saw meet to continue the
stroke until my friends thought I must die,
and my physicians gave me no hope of recovery.
My cough was very oppressive and my breathing difficult,
and my pulsations 120 in a minute.
My beloved sister who waited upon me, and watched over me with anxious solicitude,
that I might be fully aware of my critical situation,
informed me of the opinion of my physician,
expressing a heartfelt desire that I might be prepared for
the solemn summons which appeared to be near at hand.
But it was all dark to me, whether I would live or die;
or what would become of me were I to be soon launched into the confines of eternity.
But I had a lingering hope that the Lord would not cast me off on the left hand.
When able to ride out I often desired to attend our religious meetings,
when my friends thought it imprudent, and I yielded to their judgment.
On one occasion I felt much depressed, and was almost ready to murmur;
when this language was addressed to my mental ear, viz:
"`What dost thou want to go to meeting for? Is it above all things to worship God
in spirit and in truth?`" I could not say that this was the leading motive;
but originated more from a desire to gratify my own
will and inclination than to glorify the Lord my God.
Then I remembered the language of our Saviour to the Syro-phenician woman--"`It is
not meet to take the children`'s bread and cast it to dogs`"--and I was greatly
humbled under a feeling sense of my unworthiness of the least of the Lord`'s mercies.
My spiritual conflicts were at times great,
the depths of which were only known by the Searcher of hearts.
I was favored to see by and through the light of Christ in my heart,
the corruption of my fallen nature, that had never passed under the flaming sword,
that turns every way to keep the way of the tree of life.
I had a strong will which had not been slain,
and a proud heart which had not been fully humbled.
I could not truthfully adopt the language, "`Thy kingdom come,
thy will be done in earth as it is in heaven.`"
I did not feel willing to be counted a fool for Christ`'s sake,
and I did not see how it was possible that I could be brought into that state of mind.

A minister from another neighborhood having paid me a visit, after her return home,
wrote me a few lines expressing her belief that my
spiritual condition was comparable to that of the young
man who had kept all the commandments from his youth up,
but lacked the one thing,
that of selling all and following the Lord Jesus in the way of his requiring, etc.
When I received these few lines I said in my heart, this is the truth,
the very truth--the Lord hath put it into thy heart thus to address me,
for I had said nothing to her in regard to my spiritual conflicts;
but I felt that I had no might or power of my
own to take one step in the right direction,
and I seemed to be hastening towards the end of my
pilgrimage without a preparation for the final summons.
Thus the Lord let me see and feel,
that man of himself can do no good thing--he cannot soften his own heart,
he cannot repent when he pleases and become resigned to
the will of the Lord in his own will and time.
I had chosen my own way and disobeyed his command,
when a clear manifestation of religious duty had
been given me and strength to comply therewith,
and now I was reaping the reward of disobedience.
This was the condition of my mind when, one day after a severe spell of coughing,
I sank for a few moments into a state of unconsciousness; as I recovered from this,
I said in my heart,
am I dying without any evidence of Divine acceptance? Then this
language was addressed to my spiritual ear--"`Art thou now willing to
become a little preacher?`" I answered on this wise--"`Lord,
thou hast all power.
I have no might or strength of my own, make of me what seemeth unto thee good.`"
But at that time I had no idea what would be required of me,
or that anything but the subjugation of my will was called for.
Through the judgments of the Lord mingled with mercy,
the deaf and dumb spirit was now being cast out;
that spirit that had turned a deaf ear to the calls of the Lord and disobeyed his
commandments--the oaks of Bashan and cedars of Lebanon were brought down,
and my spiritual condition resembled in no slight degree that of Nebuchadnezzar,
whom seven times had passed over him before he was humbled.
I now felt that resignation to the will of the Lord which I once thought impossible.
Under these feelings of humiliation and abasedness of self,
this language was addressed to the ear of my soul--"`Fear not, for I am with thee;
be not dismayed, for I am thy God.`"
No tongue could tell, or pen portray, the joy of my heart at that time.
I felt that all my sins were forgiven through the mercy of God in Christ Jesus,
and a foretaste of that joy which is unspeakable and full of
glory was given me--a foretaste of the joys of heaven where
ransomed souls and holy angels surround the throne of God,
ascribing thanksgiving, glory and honor unto the Lord God and the Lamb forever.
At this time I was entirely confined to my bed,
and apparently near the end of my earthly pilgrimage;
and my experience at this eventful period of my life very forcibly
reminded me of the account recorded by the Apostle Paul,
of a man (doubtless himself) who was caught up into the third heaven,
and heard things which were not lawful to be uttered;
and the truth of this declaration of the same Apostle
was most impressively sealed upon my mind,
viz: "`Eye hath not seen, nor ear heard,
neither hath entered into the heart of man the things
which God hath prepared for them that love him.`"
But "`God hath revealed them unto us by his Spirit; for the Spirit searcheth all things,
yea, the deep things of God.`"
"`But the natural man receiveth not the things of the Spirit of God:
for they are foolishness unto him; neither can he know them,
because they are spiritually discerned.`"

I was now commanded of the Lord to send for the
inhabitants of the village near which we resided,
that I might proclaim unto them the unsearchable riches of Christ.
My dear father entered fully and feelingly into
the concern and extended the desired information.
Many came to whom the gospel of life and salvation was
preached in demonstration of the Spirit and of power.
They were invited to come,
taste and see that the Lord is good and that his mercy endureth forever;
that it is extended unto all, that He is no respecter of persons,
that in every nation they that fear Him and work righteousness are accepted with Him.
"`The Spirit and the bride say come.
And let him that heareth say, come.
And let him that is athirst come.
And whosoever will, let him take of the water of life freely.`"

But we must come in the obedience of faith--we must
follow the leadings and teachings of the Holy Spirit,
whilst favored with the visitation of Divine mercy,
the mercy of God in Christ Jesus our Lord and Saviour,
if we become heirs of eternal salvation.
Christ Jesus came not into the world to suffer and to die for us, to save us in our sins,
but from our sins.
We must experience the refining,
cleansing operation of his baptism--the baptism of fire and the Holy Ghost,
purging the temple of our hearts from all that his righteous controversy is with,
before He will deign to own us before his Father and the holy angels.
The Lord strengthened me in a remarkable manner on this
memorable occasion to proclaim the gospel unto the people.
All were attentive and serious, and it may be said, truth reigned and triumphed over all,
to the praise and honor of his great and glorious name.
This was in the Tenth Month of 1833. From this time I began slowly to recover;
but was closely confined all the ensuing winter to my room,
and most of the time to my bed.
A large abscess formed in my left side,
the contents of which were thrown off by expectoration.
This was some relief in the way of breathing, but I was very weak and prostrated.
My father sent for another physician, who gave him no encouragement as to my recovery,
but I heard a voice which said, "`Talitha-cumi,
maid arise;`" and I then thought I should recover.
When spring came and the weather became sufficiently warm and settled,
they placed me on a sled and took me out in the fresh air,
as I was able to bear it. I soon got so I could sit
meeting by having at first an easy chair to sit in;
and I found that I must be faithful to what the Lord required of me in meeting,
and out of meeting, if true peace was obtained.
