== Chapter VIII

[.chapter-synopsis]
* A Religious Visit to Philadelphia Yearly Meeting, and Many of its Branches
* Her Remarkable Testimony in the Men`'s Yearly Meeting, and Much Plain Dealing in other Places, During the Fulfillment of Required Services There

I set out on this journey the 10th of the Fourth Month, 1865,
and was from home three months lacking three days.
Isaac Mitchell and cousin Rebecca S. Branson were my companions,
the former being an elder in good esteem.
They were both very kind to me in this journey.
We rode twenty miles in the carriage, then took the cars for Philadelphia.
When I got to the city, it was with difficulty I could walk, even with help,
but a night`'s rest recruited me so that next day I attended Arch Street
Meeting (it being their Weekday Meeting). Contrary to my expectation,
I had to open my mouth and declare,
that the same Jesus who kept Peter from sinking in the midst of the sea,
was still able and willing to preserve and succor those who cry unto Him for help,
and put their trust in Him--the same today, yesterday and forever, etc.

After meeting, several Friends spoke to me,
and some said they were glad to see me. Seventh-day following was Select Yearly Meeting.
I informed Friends that I had a Minute of unity and concurrence from
the Monthly and Quarterly Meeting of which I was a member,
liberating me for religious service within their limits.
(But having been advised by one of their principal
elders not to offer my Minute to the meeting,
they having come to the conclusion some years previous to read no Minutes
for ministers travelling amongst them from any meeting whatever,
I did not lay it on the table, and no one called for it,
though it was from branches of Ohio Yearly Meeting with which
Philadelphia had corresponded since the separation in 1854,
and owned as the legitimate Yearly Meeting of Ohio.) Several Friends
expressed their satisfaction with the information given,
and desired I would not feel embarrassed on account of my Minute not being read,
but be encouraged to do what I might find to do amongst them.

16th.--Attended the Public Meeting at Arch Street, both in the morning and afternoon,
but had nothing to communicate.

17th.--The Yearly Meeting for business commenced.
I informed women Friends how I was amongst them,
but as my Minute had not been read in the Select Yearly Meeting,
the regular channel through which such Minutes were to come before the Yearly Meeting,
I did not think it proper to offer it there.
Women Friends expressed satisfaction with this information,
and desired I would feel my way open to perform
any service amongst them required at my hands.

On taking my seat in that meeting, and casting my eyes over that large assembly,
nearly all of whom were strangers to me,
I could not suppress the rising tears which flowed for a time unrestrained.
I remembered that it had been several years since I first felt a concern to
visit some of the meetings constituting that Yearly Meeting,
etc., that the concern had again and again revived and been put by;
at one time the prospect seemed so nearly ripened for public avowal,
that I expected to lay it before the next Monthly Meeting, but lo!
He who gathereth the winds in his fists, who scattereth the hoar frost,
and causeth the hail, rain and floods to descend upon the earth,
He who dealeth marvellously with the children of men,
both in the visible and spiritual creation, brought a blight upon the prospect,
and showed me that it was not required of me to make the concern public at that time.

The subject rested with me for several years, with no opening to move therein,
till the fall of 1863, whilst engaged in a visit to one of our northern quarters,
I again felt that the time was drawing near when it
would be required of me to lay it before my friends;
and I said to a Friend who accompanied me on this visit--"`What if thou shouldst
have to go with me to Philadelphia Yearly Meeting?`" But I did not then know what
great affliction I should have to pass through before it was made public.
I had to tell Friends in the women`'s Yearly Meeting,
that I had long felt a concern to visit Friends in those parts, but never till recently,
and that too, on a bed of languishing,
had I felt the word of command given to lay the subject before my friends at home, etc.

I had on the first day of the meeting for business considerable to communicate,
which appeared satisfactory to Friends; and once again during the week,
on the subject of dress and address,
and the necessity of keeping to plainness in these respects,
and out of the vain customs and fashions of the world.

At the Friend`'s house where we lodged during the week of Yearly Meeting,
many Friends often came in, in the evening,
and although I would have greatly preferred being out of sight,
and unheard as to the ministry,
yet it was often laid upon me to speak in these companies,
and I think some of those opportunities will not
soon be forgotten by some of those in attendance.

The Yearly Meeting closed on Fifth-day, the 20th of the Fourth Month.
I had felt it right to request the liberty of visiting men`'s meeting before it closed,
which was granted on Fifth-day afternoon.
After taking my seat and sitting awhile, this language arose in my mind,
with a belief that it was right to express it, viz: "`Be silent O all flesh,
before the Lord, for He is raised up out of his holy habitation.`"
I said, that on taking my seat in that meeting,
I felt that I might be permitted to spend the time in
silence and return without uttering anything;
that my heart rejoiced under that feeling, and as I was settling down here,
the language quoted sprang up in my mind,
and I felt it right to revive it. I remembered that it was a
complaint made against the priests in Israel in the days of Ezekiel,
that they put no difference between the holy and profane,
and did not show difference between the unclean and the clean.
Under the law of Moses the beasts which were to be eaten were those that chewed the
cud and parted the hoof--the one without the other was not sufficient.
The operations of the mouth, and the track of the foot must be taken into the account,
and correspond.
This points to the example and precept of those under the gospel dispensation,
who were true followers of Jesus,
the precept and example of these would be such as was worthy to be followed.
But those who made a profession of the Truth without giving a corresponding example,
no matter what their standing or station in society might be,
they were nothing better than the unclean beasts under the law,
not to be partaken of. I believed there were those in that meeting who had been,
and were influential members, whose example was not wholesome to set before the people,
and there were those whose duty it was to show difference between these and
those who maintained the doctrines and testimonies of the Society inviolate,
but who had neglected their duty until a great mixture had taken place.
I said, I believed there were those in high stations, who were comparable to Adoni-bezek,
spoken of in Judges,
when Judah and Simeon went up to drive out the Canaanites and Perrizz`'ites,
and take possession of their lots, they found Adoni-bezek in Bezek,
and they fought against him, but he fled, and they pursued after him and caught him,
and when they had cut off his thumbs and great toes,
he was brought to this remarkable confession, viz:
"`Three score and ten kings having their thumbs and their great toes cut off,
gathered their meat under my table; as I have done,
so God hath requited me.`" And they brought him to Jerusalem, and there he died.
I believed there were those in that meeting who had been occupying
lots which the Lord never designed they should occupy,
and had been busily engaged, maiming and crippling all who could not come up to,
or follow the line of demarcation laid down by them.
They were actuated by human wisdom and human policy,
in the management of the affairs of the church,
and all who were not disposed to succumb to their wishes and
follow out their line of demarcation were put under,
maimed, lamed and crippled.
That the Lord in his own time would deliver his people out of their hands,
and they would die conspicuous cripples if they did not repent and return unto the Lord,
as did Adoni-bezek,
and the language of their hearts would be similar to his "`Three
score and ten kings having their thumbs and great toes cut off,
gathered their meat under my table, as I have done, so hath the Lord requited me.`"

I said, moreover,
there were those who were snugly quartered in their winter houses like king Jehoiachin,
who had also a fire of coals on the hearth before them,
and sharp penknives in their pockets,
ready to cut to pieces and burn the roll that was delivered to them,
so that a trace of it should not be left; but the Lord would send another roll,
and they would have to hear and realize his words fulfilled.
I said the Lord would have a people to his praise.
He would confound the wisdom of the wise and bring to
nothing the understanding of the prudent;
He would sift us until we were a people more to his praise.
I had felt a sympathy and unity with a remnant in that meeting.
I desired the encouragement of those whose hearts trusted in the living God.
He never said to the wrestling seed of Jacob, Seek ye my face in vain,
that as these kept to the Master,
they would experience this language verified in their own particular,
"`Though ye have lain among the pots,
yet shall ye be as the wings of a dove covered with silver,
and her feathers with yellow gold; and again the young lions do lack and suffer hunger,
but they who wait upon the Lord shall renew their strength,
they shall mount up with wings as eagles; they shall run and not be weary,
they shall walk and not faint.`"
Much encouragement flowed to the honest-hearted, and a warning to backsliders to return,
repent and live.

After I had fully and faithfully relieved my mind in that meeting, I left them,
but before leaving I told them the Lord had not raised me from a bed
of languishing and given me strength of body to come amongst them,
to speak my own words or mark out my own path.
I felt that I must be faithful, no matter how hard it was for them to hear,
or for me to deliver, the whole counsel.
After leaving this meeting,
I felt that I had incurred the displeasure and disunity of some, who before,
had shown me much favor; but my mind was stayed on the Shepherd of Israel.
After reaching my lodgings, I met with ample proof that my feelings were correct,
and I said to my companion "`He that eateth with me hath lifted up his heel against
me.`" This I said in reference to some who before had shown me much kindness,
and with whom we had had some favored opportunities.
Next morning, I felt it right to call some Friends together,
and ask their advice with respect to proceeding further in the prosecution of the visit,
or returning home.

As the Yearly Meeting had taken no cognizance of my Minute,
I had strong thoughts that it might be best for me to return immediately home.
The principal speaker in this opportunity being an elder of much influence in the city,
and in the Yearly Meeting,
advised me to return home without attempting to prosecute my visit further,
saying the last eighteen hours had been to him a time of unspeakable distress.
That my way had been remarkably made and opened in the city amongst Friends,
until my visit to the men`'s meeting, and now it was closed up,
and I could have no liberty to appoint any meetings amongst them.
No one else advised me to return home, but several Friends coming in afterwards,
desired I would not be hasty, but wait for Divine direction,
believing way would be made for me, where now there appeared no way.
I felt quiet,
and my mind lifted up to the Helper of his
people for direction and strength to do his will.
My companions were deeply tried, and I pitied them much,
but could do nothing but pray for myself and for them.
I told the Friend who advised me to go home, that I felt this language verified:
"`He that eateth with me hath lifted up his heel against me.`" After
this I asked him if he had any particular time set for us to start.
He said, no!
I then told him I thought we might wait a few days.
He thought so, too.

The next week was the time their Monthly Meetings occurred in the city.
I asked this elder if he was willing we should attend them.
He said yes.
After these meetings were over, and the Quarterly Meeting of Philadelphia,
(which we attended) I asked him if he was willing we should go within the
limits of Caln Quarter and attend the Monthly Meetings? He said "`Yes,
perfectly.`"
So we made arrangements and attended all the Monthly Meetings in that Quarter.

Next we attended Concord Quarterly Meeting.
In the meeting for ministers and elders, I had a trying service.
I told them I saw amongst them those who were maimed and lamed; men and women cripples;
those who could not take a straightforward, free,
firm and steady step in the path of duty,
who had become cripples for the want of keeping the eye to the Master,
instead of leaning on the arm of flesh.
Though they were at a loss to know what was meant by cutting off thumbs and great toes,
yet they had their thumbs and great toes cut off, figuratively speaking.
They could not give the whole right hand of fellowship to the true Israelitish seed,
and they were cripples in both hands.
The fear of man bringeth a snare, and they were taken in this snare.

I said, I remembered how it was with Peter when our Saviour came to him to wash his feet.
He was not disposed to submit to such a humiliating baptism,
supposing himself capable of knowing when, and knowing how to wash his own feet;
and no doubt thinking also, that it was lowering to the dignity of his Master,
for Him thus to stoop to wash his disciples`'s feet,
or for his disciples to subject their Lord to this necessity.
But when he was told, "`If I wash thee not,
thou hast no part with me,`" he was all submission.
After the washing was over, Jesus said unto them,
"`Know ye what I have done to you? Ye call me Master, and Lord; and ye say well;
for so I am. If I, then, your Lord and Master, have washed your feet,
ye also ought to wash one another`'s feet.`"
Jesus did not choose two or three of his disciples to wash the feet of the rest,
but they were to wash one another`'s feet.
The disciples of Christ will feel not only a willingness,
but a necessity of taking and receiving advice from his fellow disciples;
he will not feel himself too clean or too whole to be counselled,
or reproved even by the least babe in Christ.
"`He that receiveth whomsoever I send, receiveth me, and He that receiveth me,
receiveth Him that sent me.`" Male and female are all one in Christ Jesus.

After this meeting, a minister said to me, "`Thou hast had a hard meeting,
but there is cause for thy exercises and thy remarks.
Oh, the bitter draughts my soul was made partaker of in many places,
so that I can say with David, "`Unless the Lord had been my help,
my soul had almost dwelt in silence.`"

Next day the Quarterly Meeting occurred.
It was a very large gathering.
Here, again I had close things to deliver, and hard to be uttered;
yet there was more openness than in the Select Meeting.
Where there is not a willingness to hear the Truth spoken,
it makes hard work for those to whom it is given to declare the whole counsel of God,
whether the people will hear or whether they will forbear.
I told them that some, no doubt, were desirous we should have a good meeting,
the language of whose hearts often was, Oh,
that we could have such precious heart tendering
opportunities as Friends had in the rise of the Society.
But we should remember that we are a backslidden people; the love of the world,
the wisdom, policy, riches, pleasures, pastimes, manners,
maxims and customs of the world, have gained ascendency and great place amongst us;
many were following those things with avidity,
which our worthy predecessors were led to renounce; and were trampling under '`foot,
or esteeming lightly those principles and testimonies for which,
and the support of which, our early Friends suffered persecution, imprisonment and death.
Will not the Lord judge for these things;
will not my soul be avenged on such a people or nation as this?`" The
judgments of the Lord are in the nation and in the Church,
and yet we are not humbled.
But this impressive, gracious and inviting language is still held out to us,
awaiting our acceptance: "`Return, ye backsliding children,
and I will heal your backslidings.`"
And again: "`Bring ye all the tithes into the storehouse,
that there may be meat in mine house, and prove me now herewith, saith the Lord of hosts,
if I will not open you the windows of heaven, and pour you out a blessing,
that there shall not be room enough to receive it.`"

I had to declare that it was my full belief there were
those in that meeting who occupied high stations,
to whom this language was applicable: "`Take away from me the noise of thy songs;
for I will not hear the melody of thy violin, But let judgment run down as waters,
and righteousness as a mighty stream.`"
That the leprosy had got into the head,
and was of such a nature as to require those affected therewith, to cover the upper lip,
and cry, Unclean! unclean.
The foregoing is only a small part of what I had to communicate in that meeting.

In the women`'s meeting I had a short testimony on the subject of dress,
recommending plainness and consistency in this respect.
After meeting, Elizabeth Scattergood, an elder, said to me,
I have good unity with thy services in our meeting today,
and should have felt better satisfied if I had expressed it publicly, but, said she,
"`that is the way we get along;
in a crippled way`"--meaning for the want of being faithful.
On the day following, we visited dear Hannah Gibbons, who was in her ninety-fifth year.
Truly it was a strengthening, encouraging visit to my mind.
She was lively and green in old age, remembered her visit to Ohio,
made in her eightieth year;
could recollect much that was said and done in our Yearly Meeting at that time.
One thing I think right to mention,
it being a time of great disturbance and commotion on account of the spread
of unsound doctrines,--the doctrines of Joseph John Gurney and his abettors,
and there being some Friends in attendance of Ohio Yearly Meeting at that time,
from the Smaller Body (so called) of New England.
The Clerks of the women`'s meeting seemed determined to close
the Yearly Meeting without transacting the business thereof,
being encouraged by those of their way of thinking.
When the Clerk was about to read the concluding Minute, Hannah Gibbons arose and said,
that although she could not hear what was before the meeting, she felt it right to say,
she desired Friends would be faithful,
and if the Clerks did conclude the meeting without transacting the business,
she hoped faithful Friends would keep their seats,
and attend to the business of the meeting.
This honest, timely remonstrance, put a stop to their proceeding to conclude the meeting,
and the regular business was transacted.
The Friends from New England were men.

Fifth Month 11th.--Attended the Select Quarterly Meeting of
ministers and elders for Caln Quarterly Meeting.
Towards the close of this meeting I had to warn Friends
to be aware of the Joabs--to remember Abner and Amasa,
how they lost their lives by his treacherous dealings.
"`Died Abner, as a fool dieth? his hands were not bound nor his feet fettered.`"
Joab did not want any one to supersede him in the king`'s business,
and determined to put all out of the way, who should be appointed to go before him;
hence, with feigned pretences towards the one, and feigned love towards the other,
he slew both Abner and Amasa.
But his gray hairs were not permitted to go down to the grave in peace,
though he arrayed himself conspicuously on the side of king David,
yet the king gave a charge to his son and successor concerning Joab,
because of his treachery and wickedness.
And when Solomon commanded Benaiah to smite him, he took hold of the horns of the altar,
still desiring to be considered a true worshipper in the house of God; nevertheless,
he was smitten there, and there he died.

How similar to the conduct of Joab is the conduct of some in the present day,
who are professing to be on the King`'s side, and actuated by a zeal,
but not of or from the Lord; desirous of self-exaltation or promotion,
who would allure from the path of duty by feigned words and fair speeches,
those who are on the King`'s business; and when they have got them,
to turn aside from the highway of holiness, behold their dagger is felt,
the precious life is smitten,
and they have no more strength to run on the Lord`'s errands, or do the King`'s business.
Though these over-zealous pretenders to religion care
nothing for the spiritual lives of those they slay,
yet their aim is to make a great show of love and good will,
as if the health of the souls of their fellow creatures was their chief concern.
"`Art thou in health my brother,`" said Joab to Amasa,
and took him by the beard to kiss him, and then slew him,
leaving him in the highway for all to gaze upon him.

12th.--Attended the Quarterly Meeting for business.
In the forepart thereof, I had a testimony to bear on the subject of forgiveness,
and felt easy and satisfied.
In the women`'s meeting I had to revive the language:
"`Because the daughters of Zion are haughty,
and walk with stretched-forth necks and wanton eyes, walking and mincing as they go,
and making a tinkling with their feet.
Therefore the Lord will smite with a scab the crown of the head of the daughters of Zion,
and the Lord will discover their secret parts.
I admonished those who were high and lifted up in pride,
to remember what had come upon many daughters in our land,
how they had been brought down from their height and reduced to penury
within the past four years in consequence of the ravages of civil war,
and although we had in many places been basking as in the sunshine of prosperity,
whilst thousands and tens of thousands have been undergoing the keenest reverse;
yet we must remember the Lord is no respecter of persons,
and while we may not be obliged to drink the cup of affliction and
judgment in the same way that others have been partaking of;
the time will come,
that all who continue indulging in the vain gratification of a worldly spirit,
will experience the judgments of the Lord to come upon them, yea,
the time must and will come upon all such, wherein their secret parts,
or the secret of their hearts, will be discovered, and mourning,
lamentation and woe will be their portion.
The Lord will take away from the daughters of Zion the
bravery of their tinkling ornaments and their cauls,
and their round tires like the moon, etc.
(see Isaiah, chapter third.
As this language has been verified in the experience of many professing
Christians of latter time in a remarkable manner in our beloved country,
it should have a tendency to humble us as in dust and ashes before the Most High God,
lest the cup of his indignation be handed to us unmingled with
mercy and we have to drink the very dregs thereof.
But the inviting language is still held out: "`Return, ye backsliding children,
and I will heal your backslidings.`"

13th.--Attended the funeral of Isaac Phillips,
an esteemed elder of Bradford Monthly and Particular Meeting.
At the house of the deceased, before the interment,
I expressed to the widow of this Friend, my belief that all was well with her husband,
and encouraged her to keep the faith and patience,
that she might follow him to his home in heaven.
After the corpse was laid in the tomb, Friends held a meeting, which was very large,
I had nothing to communicate; Samuel Cope and Phebe Roberts spoke therein.
The same evening we went to West Chester and lodged with Elizabeth,
widow of the late William Scattergood.
The latter was a minister in the Society who stood much
opposed to the modern innovations in doctrine and practice,
which have made their way in the Society.
Elizabeth is a worthy elder, and treated us with much kindness and motherly regard.

14th.--Attended West Chester Meeting (it being Firstday). In this
meeting I found it right to revive the language of the Apostle Peter,
viz: "`But the day of the Lord will come as a thief in the night;
in the which the heavens shall pass away with a great noise,
and the elements shall melt with fervent heat; the earth also,
and the works that are therein,
shall be burnt up. Seeing then that all these things shall be dissolved,
what manner of persons ought ye to be in all holy conversation and godliness.
Looking for and hasting unto the coming of the day of God, wherein the heavens,
being on fire, shall be dissolved,
and the elements shall melt with fervent heat? Nevertheless we, according to his promise,
look for new heavens and a new earth, wherein dwelleth righteousness.`"
I said, does any one here suppose that the Apostle Peter had an allusion to a day,
in which this terraqueous globe on which we live should be destroyed
by fire? I cannot suppose that he had any such meaning.
The heavens and the earth here alluded to is no doubt the old fallen nature of man,
against which the fire of the Lord`'s jealousy is kindled,
and the people of the world before the flood,
having been striven with by the Spirit of the Lord to bring them out of that fallen,
degenerate condition, yet they persisting therein,
God gave them over to a rebrobate mind, and brought destruction upon them.
So all, in every age of the world,
who withstand the tender visitations of God`'s mercy to their souls,
and continue in sin and transgression until his mercy is withdrawn,
will experience the outpouring of his indignation upon them, without respect of persons.
For, by the same word, the heavens and the earth which now are,
the first and fallen nature is reserved in chains,
subject to the fiery ordeal and indignation of the Lord,
but those who submit to the baptism of the fire and Holy Ghost, until all the chaff,
tin and rebrobate silver is destroyed--until all the old nature is purged out,
these experience new heavens and a new earth; new desires, new affections,
all old things done away, and behold, all things become new, and all things of God.

By thus bearing the ministration of condemnation for sin and transgression
by knowing the Master to sit as a refiner and purifier of gold and silver,
and as a fuller with soap in the temple of the heart,
becoming as passive clay in the hands of the potter, we hasten the corning of that day,
wherein the heavens being on fire shall be dissolved,
and the elements of our old nature melt with fervent heat,
the earth also and the works thereof shall be destroyed.
Seeing we look for such things,
what manner of persons ought we to be in all holy conversation and godliness.

In the afternoon of this day my companions attended Westtown Meeting;
but I feeling no draft that way, stayed in the neighborhood of West Chester,
at the house of our kind young friends Joseph and Elizabeth Scattergood:
Joseph is a descendant of Thomas Scattergood,
that devoted servant and minister of the Lord.
At this house I was sick for two days, and was very kindly treated.

On Fourth-day following we went to London Grove,
in order to attend the Western Quarterly Meeting.

On Fifth-day attended the Select Quarterly Meeting, in which I was silent.
Next day the Quarterly Meeting for business; silent also in that; but a woman Friend,
from a neighboring Quarterly Meeting, was very lengthy, both in preaching and praying.
Towards the close of the women`'s meeting something arose on my mind to deliver,
but the same woman again arose and had considerable to say,
which put a stop to my communication before it commenced.
This same Friend being at another meeting which I attended,
again took up most of the time in preaching and praying;
also in the Yearly Meeting was several times quite lengthy in her communications,
particularly towards the close of that large assembly.
My spirit was grieved thereat, believing she was going quite beyond her gift,
if she had a gift, which I was not prepared to question, or deny;
but she being young in the ministry, my soul did mourn over her, and I felt willing,
should the Lord require me so to do, to speak to her privately on account thereof,
but no way opened for my relief.

I give this as a warning to others,
believing the good Master will keep those clear-sighted, careful and watchful,
who put their trust in Him--who keep a single eye to his glory,
and if at any time they through unwatchfulness step aside,
He will chasten them with his rod of correction, causing them,
when they warm themselves with sparks of their own kindling, to lie down in sorrow,
feeling uncomfortable for having transgressed his righteous law.
They will be induced, as their chief aim and object is to promote his glory,
to bear the rod of his correction, and profit thereby.
"`My greatest concern (says William Penn) is for public brethren.`"
Oh, that I myself may watch unto prayer, and that continually,
that this language may not apply unto me,
in regard to what I have said on the subject of the
ministry--"`Out of thine own mouth will I judge thee.`"

After this Quarterly Meeting was over I informed the Select members of that meeting,
that I felt a concern to attend the meetings belonging to that Quarter,
to which they readily assented,
also to appoint one meeting within their limits amongst those not in membership with us,
which was also united with.

Seventh-day, the 20th.--Morris Cope took us to London Britain,
to attend that meeting on First-day.
I had service therein, both in silent exercise and vocal communication,
and felt satisfied.
After a religious opportunity in the family where we lodged, we went to West Grove,
where a meeting had been appointed to be held the next day, which we attended.
In this, as in all the other meetings within the limits of this quarter,
I had close things to deliver.
A worldly spirit having got in,
and taken possession of the uppermost room in the temple of the hearts of many, yea,
most of our poor, scattered and peeled Society; and many seem not to know it;
but when close things are preached amongst them, it seems hard for some to bear,
particularly when the leprosy is in the head, as well as in the other parts of the body.
Oh, what a resisting there is of that kind of medicine most needed,
so that the language of my heart often was, both in and out of meeting,
"`My soul is exceeding sorrowful even unto death;`"
for I found to suffer with and for the Truth,
we must dwell very low, even in places where few in these days are willing to dwell,
and withal,
feeling my own weaknesses and insufficiency for
so great a work as that of preaching to others,
being a dwarf in religious experience compared with those who have
faithfully followed the footsteps of the flock of Christ`'s companions.
I was often brought very low in consideration of these things,
and yet I felt the necessity laid upon me to do my part even in these troublous times,
towards repairing the broken-down walls of our Jerusalem.

I was many times whilst engaged in this visit,
pressed as under the weight of hills and mountains.
But magnified and adored forever be his name,
who never left me to become a prey to the dragon, but when He had tried and proven me,
He did always show himself to be the same Almighty Helper,
who can and will deliver all those who put their trust in Him,
out of all their distresses.

The last meeting we attended within the limits of the Western Quarter,
was at Fallowfield--a very small meeting.
I was favored to relieve my mind in this meeting to the few present, and felt clear.
After meeting, we went to the house of a Friend belonging to that meeting.
On my way thither my mind was greatly exercised,
so that I could scarcely refrain from exclaiming aloud--"`My soul is exceeding sorrowful,
even unto death.`"
The Friends where we were going being entire strangers to me,
I knew not why I should be thus exercised, but upon entering their house,
and even before entering their dwelling, the mystery began to be unfolded.
I found they were wealthy and lived in a style which showed plainly
they were not the self-denying followers of the meek and lowly Jesus,
as becomes our profession.
They treated us respectfully,
and whilst dinner was preparing I felt greatly exercised in spirit,
that the Lord would keep me faithful to his requirements,
permitting me neither to go beyond, nor lag behind my guide.

After dinner I requested the family collected, which was done;
two of the older children were from home.
All the wealth and grandeur which I saw there displayed felt to me as nothing, yea,
lighter than vanity;
and I could not feel easy without alluding to the birth-place of our Saviour.
Surely it was in his power to have presented himself to the world in
that prepared body in which he came to do his Father`'s will,
in a very different situation than that of a stable and a manger.
The birth-place of the Son of God a stable!
He by whom all things were made, condescended to set us this example of humility.
He who could have commanded empires and kingdoms,
in whose sight all nations are as the drop of a bucket.
He is Lord of lords and King of kings.
He regardeth the heart.
He requireth us to take his yoke upon us and learn of Him,
who is meek and lowly in heart, that we may find rest to our souls.
And He hath declared that, "`Whoever shall be ashamed of me and of my words,
of him shall the Son of man be ashamed, when He shall come in his own glory,
and in his Father`'s, and of the holy angels.`"
We must be willing to bear the cross, if we would wear the crown of life everlasting.
I felt strengthened to declare the whole counsel to parents and children,
and after a short and fervent supplication on their behalf, my own,
and those who were with me, I felt clear of them, which was indeed a great favor.

Then visited the family of a brother-in-law of these Friends,
and was favored to relieve my mind there also; but did not see the father of this family,
he being sick.
We then left the town of Coatesville,
and on our way to Benjamin Maule`'s (the Friend who took us to Fallowfield),
we stopped and took tea with a widow, who with her daughter received us kindly.
After tea,
had a religious opportunity to our mutual comfort and consolation in a degree
sufficient to call forth this acknowledgment,`" Hitherto hath the Lord helped us.`"

On our way we passed the house of Solomon Lukens,
who with some others in his neighborhood and elsewhere,
have recently left their respective meetings,
and set up others in which they profess they can worship the Father
of Spirits more in accordance with their own sense of duty,
than in the meetings they have left.
I felt a great weight upon my spirit as I passed this house, and have since thought,
if I had given up to call there at that time, I might have felt more easy;
but we passed by, I concluding if the matter rested with me, I would return,
but the time never came that I had an opportunity to do so.

Lodged at B. M`'s,
with a prospect of appointing a meeting at a little village called Unionville,
four or five miles from London Grove.
But on Seventh-day morning, the prospect closed up. I could not account for it,
but felt it safe to be still,
and told Friends I did not see my way clear to appoint that meeting.
On examining the time of holding the Quarterly Meetings, I found Burlington Quarter,
which I was expecting to attend, came two days earlier than we expected;
then I saw why my way closed up to appoint the meeting,
for we had to take the cars for Philadelphia that afternoon in
order to reach Burlington in time for the Quarterly Meeting--
our friend B. M. taking us to the station.
With him and his family we parted in the love of the gospel.
He has six daughters, all grown, and in the bloom of youth.
I thought them interesting young women.
His wife, and aged mother-in-law were also very kind,
and we parted in near affection with these dear Friends.

On First-day we attended the Meeting for the
Northern District in the morning and afternoon.
In forenoon, after Deborah Brooks (a young Friend) had spoken,
not a word of which I could hear, my mouth was opened to speak of silent worship,
and express my belief that those who worship the Father in spirit and in truth,
often find these meetings to be the most strengthening and encouraging of any other;
for the minister of the sanctuary and true tabernacle, who is the Lord Jesus Christ,
knows all our wants, and is acquainted with our several situations,
and where there is a looking unto Him in the way of his judgments,
bearing the baptism of the Holy Ghost and fire, He will cleanse the temple of the heart,
and come in and sup with us, and we with Him.
And He will at times and seasons break in amongst these thus waiting upon Him,
with this inviting language--"`Children come and dine`"--
that there will be left no doubt who it is,
knowing that it is the Lord himself,
thus inviting and feeding his disciples with the food He hath prepared for them,
comforting and strengthening their hearts together, with his holy,
life-giving power and presence.
Instrumental ministry which is of his begetting and ordering, is not to be despised,
but appreciated according to its worth; that is as instrumental help,
and not to be withheld when He gives the command to speak, for He still, as in days past,
makes use of clay to anoint and open the blind eyes,
yet this is not to be compared to his own immediate
presence and inspeaking word nigh in the heart.
I said blessed be his name forever, and let all the world say amen.
holy prophets of the Lord concerning the coming of the Son of God in the flesh,
but when He came, were the ones to mock, deride and scoff, and finally put Him to death.
We as a religious Society profess,
not only to believe He has come in the flesh and suffered for us,
the just for the unjust,
but we profess to believe according to his promise in his
second appearance--his spiritual appearance in the heart,
and that too as a reprover for sin and transgression,
as well as a Comforter to all those who follow Him.
A light enlightening our dark hearts, offering salvation unto all,
and to those who follow him He becomes the salvation of God to their souls,
but to those who turn from the light, with which He enlightens them,
and follow their own carnal wills and inclinations,
He will be the witness against them as in the parable of the sheep and the goats.
And although these may give a summary answer as represented in the parable,
pleading ignorance of having slighted the Lord of life and glory,
saying Lord (for they also called Lord), when saw we thee ahungered, or athirst,
or a stranger, or naked, or sick, or in prison,
and did not minister unto thee? Then shall He answer them, saying,
"`Verily I say unto you, inasmuch as ye did it not to one of the least of these,
ye did it not to me. And these shall go away into everlasting punishment:
but the righteous into life eternal.`"

After this meeting, several Friends spoke very kindly and affectionately to me,
expressing they were glad to see me there again,
and one minister said he was glad to hear my voice amongst them again.
In the afternoon,
I spoke of the children of Israel who were left in the land
after the generality of them had been carried to Babylon,
and how Ishmael got amongst them and slew Gedaliah and some of the rulers and chief men,
and the rest that were left determined to go into Egypt
where they might not have hunger of bread,
hear the alarm of war, nor see the sword;
but Jeremiah faithfully warned them against this step, but go they would and did,
and became greater idolaters than the nations around,
pouring out their meat offerings and drink offerings to the queen of heaven.
And the things they thought to escape came upon them.

The same evening, took tea at G. E`'s. Some Friends coming in,
I had an opportunity to lay some things before them, to the relief of my mind.
The Hicksite separation was adverted to. I told them that
Gurneyism was a more specious snare to lay waste Quakerism,
than ever Hicksism was.
Hicksism is open infidelity,
but Gurneyism is calculated to slide us off the foundation so
imperceptibly that we shall not know it. The first snare is
more easily detected and had not many advocates;
the last is working the downfall of the Society.
Thomas Shillitoe said,
if Friends suffered those doctrines to be circulated
(which they have it in their power to suppress),
the Society would go gradually down; and it is going down;
a linsey garment is spread over us, but we seem paralyzed,
and do not see and feel things as they really are.
I said, we are looking abroad at England, at the departures there,
but we are following close in their footsteps:
Gurneyites in principle being in our midst and no testimony against them;
ministers travelling amongst us of that description and no strength to touch them.
Will not the Lord judge for these things? I had a few
words in supplication and the opportunity ended,
to the relief of my mind, for I felt that the Lord owned this service at my hands,
and it found a place in the minds of some of those present.

Next day, went to Burlington, accompanied by Charles Williams, an elder in the city,
who showed us much kindness--the Lord reward him for it. Got to
Burlington in time to attend the Select Meeting at eleven clock;
all strangers to me. The meeting was pretty much gathered when
we went in. I took my seat below the ministers`' gallery,
but the man Friend, an elder, at whose house we put up, invited me up;
I thought best to go. There were two communications,
one of considerable length from a woman, in the forepart of the meeting.

After the business of the meeting was through,
I felt that I should not be clear without reviving this language,
"`Take away from me the noise of thy songs; for I will not hear the melody of thy viols.
But let judgment run down as waters, and righteousness as a mighty stream.`"
I told them I knew not the name of a minister in that meeting, but such were my feelings,
that I believed this language applicable to some present; with some more plain truths,
the fear of man was taken away, and my only desire was to serve the Lord.
Hence the slightings and smitings were comparatively easy to bear,
for I was often led to remember how it fared with the Son of God,
when in that prepared body in which He came to do his Father`'s will: He was reviled,
spit upon, and finally crucified for our sakes.

The Jews professed to believe in the prophecies of the holy prophets
of the Lord concerning the coming of the Son of God in the flesh,
but when He came, were the ones to mock, deride and scoff, and finally put Him to death.
We as a religious Society profess,
not only to believe He has come in the flesh and suffered for us,
the just for the unjust,
but we profess to believe according to his promise in his
second appearance his spiritual appearance in the heart,
and that too as a reprover for sin and transgression,
as well as a Comforter to all those who follow Him.
A light enlightening our dark hearts, offering salvation unto all,
and to those who follow him He becomes the salvation of God to their souls,
but to those who turn from the light, with which He enlightens them,
and follow their own carnal wills and inclinations,
He will be the witness against them as in the parable of the sheep and the goats.
And although these may give a summary answer as represented in the parable,
pleading ignorance of having slighted the Lord of life and glory,
saying Lord (for they also called Lord), when saw we thee ahungered, or athirst,
or a stranger, or naked, or sick, or in prison,
and did not minister unto thee? Then shall He answer them, saying,
"`Verily I say unto you, inasmuch as ye did it not to one of the least of these,
ye did it not to me. And these shall go away into everlasting punishment:
but the righteous into life eternal.`"

But how many are there amongst our highly professing Society, who,
instead of living up to our high and holy profession,
are mockers and scoffers (as really as were the Jews in the days of
his flesh) of the spiritual appearance of Christ in the heart.
Oh, saith my soul, that there might be a turning unto the Lord,
whilst the day of mercy lasts, that we be not swept with the bosom of destruction,
and be like the Jews, scattered to the four winds,
because of our rebellion against the light of the Lord.

In the Quarterly Meeting for business I had a
short testimony before the shutters were closed,
exhorting to prostration and humiliation before the Lord,
whose judgments are and have been in the land.
After the shutters were closed, I informed women`'s meeting,
that I was there with a Minute of unity and concurrence from
the Monthly and Quarterly Meeting of which I am a member,
branches of Ohio Yearly Meeting, that Philadelphia had been in correspondence with,
but as my Minute had not been read in the Yearly Meeting,
I thought it not right to offer it to Subordinate Meetings unless called for.
This information seemed satisfactory to all except one member,
and her daughter made quite a speech,
in which she asserted that Philadelphia had never corresponded
with the Yearly Meeting of which I was a member,
and threw out some very harsh and bitter words.
Some of her friends, however, were not prepared to join in with her railing,
and quieted her down.

Philadelphia has twice since the separation in 1854 addressed epistles to Ohio,
but it appears evident that in order to satisfy a class
in that Yearly Meeting who are Gurneyites,
and who never intend to own the legitimate Yearly Meeting of Ohio,
that correspondence was dropped.
May the Lord take the cause into his own hands, whose cause it is,
and plead with those who fear man more than the Creator.
I had considerable service for Truth in this meeting,
after which some Friends spoke very kindly to us,
and desired our company at their houses;
but we were not at liberty to tarry at that time.

Before leaving our place of lodging, I enquired of some elders present,
if they would be willing I should appoint some
meetings within the limits of that quarter,
provided I felt it right to return for that purpose.
They answered, they would have no objection, and one of them said,
he hoped if I felt like visiting their meetings, I would not neglect to do so,
or words to this import.
The evening after the close of this Quarterly Meeting we returned to Philadelphia,
in order to attend the Monthly Meetings composing Concord Quarter.

Fifth Month.--Went from Philadelphia to West Chester, and attended Birmingham Meeting,
held at that place.
In this meeting I had close, hard work,
believing there was a want of faithfulness on the part of some of the heads
of the meeting in the support of our Christian principles and testimonies.
I had to compare them to a broken tooth, and a foot out of joint,
who were not only become unfit for service themselves,
but hindered others from a right performance of their respective offices.
This touched some of them to the quick, the smitings of whose spirits was hard to bear.
After the shutters were closed, I requested the liberty of visiting men`'s meeting,
which was readily agreed to. Therein I had to deal plainly
with those who had turned aside from the right path,
expressing my belief that the Lord would yet have a people to his praise,
repeating part of the declaration of Francis Howgill, viz:
"`The sun shall leave its shining brightness, and cease to give light to the world;
and the moon shall be altogether darkness, and give no light unto the night;
the stars shall cease to know their office or place.
My covenant with day, night,
times and seasons shall sooner come to an end
than the covenant I have made with this people,
into which they are entered with me, shall be broken.`"
After this meeting, I had another precious interview with dear old Hannah Gibbons.

Sixth Month 1st.--Attended Goshen Monthly Meeting.
Had some service before the shutters were closed.
In the meeting my heart was enlarged, and my mouth opened in the love of the gospel,
to encourage a faithful endurance of the baptisms necessary for our
refinement and preparation for the work and service of the Lord;
believing there were those present who were designed to become as mothers in our Israel.
I had to revive the language, "`Neither let the eunuch say, Behold, I am a dry tree.
For thus saith the Lord unto the eunuchs that keep my Sabbaths,
and choose the things that please me, and take hold of my covenant;
even unto them will I give in mine house and within my walls,
a place and a name better than of sons and daughters.`"
I said, it is good to feel our nothingness,
our entire inability to do the least good thing of ourselves, to be emptied,
so that we shall appear in our own natural view robbed and
spoiled--divested of all the natural beauty and comeliness,
lying prostrate before the Lord and apparently useless.
Then, when He tries and proves us until seven times pass over us,
we shall know in the Lord`'s own time and by the might of his power,
all old things done away and behold all things made new.
"`Then shall the lame man leap as a hart, and the tongue of the dumb sing:
for in the wilderness shall waters break out, and streams in the desert.
And the parched ground shall become a pool, and the thirsty land springs of water.`"
My heart was enlarged in the love and liberty of the gospel,
and I may say in demonstration of the spirit, to speak the truth amongst them,
greatly to the peace of my soul, and to the refreshment and encouragement of others.
Next day attended Concord Monthly Meeting.
The same evening rode to Birmingham to the house of our Friends,
Aaron and Susan Sharpless.

Next day, the 3rd of the month, rode to Wilmington,
and attended their meeting on the 4th, it being First-day.
I was engaged in this meeting in testimony and supplication,
to the relief and peace of my mind, and I believe, to the satisfaction of those visited.
My way was unexpectedly opened amongst them, and the Truth chained down opposing spirits.
Oh, how necessary for ministers to cast all their care and burdens on the Lord;
truly He doth great things for them who serve and fear Him,
and this my soul knoweth right well.
After this meeting a Hicksite preacher by the name of Bancroft,
came to our lodgings to talk with us, and offer us some pamphlets,
which had been recently published by some of their members,
designing and desiring to bring about a re-union of Friends and Hicksites.
I told the man that they, the Hicksites,
must disown the doctrines of Elias Hicks before we could own them as Friends.
I had heard Elias Hicks preach, and had read his sermons, and considered him a deist.
That I heard Elias say in our meeting at Flushing, that if it were not for revelation,
we could not distinguish a man from a horse, or a horse from a tree.
I told him I had conversed with some of their members,
who said they were not in unity with the Hicksites,
but being queried and questioned with relative to the Son of God, the Lord Jesus Christ,
would not own Him to be anything more than a good man, as any other man might be;
also denying that there was any evil agent distinct from man as a tempter,
the devil--Satan--as termed in the Holy Scriptures.
I found I must come to points with this man,
showing the why and wherefore we could not own them,
till they renounced the deistical doctrines which caused the separation.
We parted on friendly terms, after a very free, and pretty full discourse on the subject.
Aaron Sharpless, the Friend who took us to Wilmington,
expressed his entire satisfaction with the interview.
Language and utterance were given me to clear myself of any compromise,
which seems to be the desire of the Hicksites to make with Friends, that is,
that all who profess to be Friends should meet together as one Society,
irrespective of the principles they may hold.
This will never do, for the Lord will not accept such a mixture.

From Wilmington we went back to Birmingham,
where we attended an appointed meeting on the 5th. In this meeting, as elsewhere,
I had close things to deliver to those who had forsaken the right path,
and those who were refusing to listen to the voice of instruction.
I said, the eleventh hour call does not always come late in life.
Peter Yarnall experienced the very last call of mercy in his youthful years,
and he was shown if he did not then yield, the day of his visitation would be over.
So it seemed to me some then present were very near their last visitation;
it was time for them to look around them,
and close in with the offers of mercy before it was too late.
The meeting ended in supplication to the Father of
mercies for the continuation of his pardoning grace.

Dined at David Garret`'s with a considerable number of Friends, young,
as well as those more advanced in years.
Soon after entering this house, my mind became very much exercised,
and some considerations took hold of my feelings, which I was not able to put from me,
without requesting a religious opportunity with all present, some being about to leave.
Soon after dinner, we accordingly sat down together.
I felt that I must neither turn to the right hand nor left.
I must not do anything to make my communication more agreeable and acceptable to
the natural mind than the Lord would have it to be. So it came before me to say,
"`Friends, if there are any here,
who undertake to keep fair sides with all the hickory Quakers they meet,
it will keep them busy, and besides,
they will be in danger of losing their spiritual life by such a course.
I said, the pathway of some is thickly strewed with temptations.
There is need of keeping the eye single to the Lord.
There are those who would draw us into their snare.
Gurneyism is in our midst; we had need to take heed.
This caution may be as needful for myself as any present,
yet I durst not withhold it. I had considerable to say in a close,
warning manner with respect to the situation of society.
I said, I had felt the smitings of some spirits which was harder to bear than open rebuke.
After this opportunity, I felt that I had incurred the displeasure, or disunity of some,
who before had shown me much kindness,
and I subsequently found I was not mistaken in my apprehensions.

Next day attended an appointed meeting at Concord,
it being the Third of the week and 6th of the month; on Fourth,
Fifth and Sixth-days of this week was at Middletown, Chester and Chichester Meetings.
On Seventh-day rode from Chichester to Whiteland, eighteen miles,
and put up with our friends, Isaac and Abigail Hall.
Attended their meeting on First-day, which was small,
and had some service to the relief of my mind.
In the afternoon of this day we visited some families.
The first was a Friend who had left Whiteland Meeting, and sits down at home alone;
alleging,
that Philadelphia Yearly Meeting has lost its standing as a Yearly Meeting of Friends,
and that he can have no fellowship with meetings subordinate thereto.
I cleared my mind towards him and his family, and left them with a sorrowful heart,
believing him to be under a mistake as to the thing required; whilst,
at the same time we are bound to admit that many
stumblings are by the leaders of that Yearly Meeting,
cast in the way, both of the honest, sincere seekers,
as well as those who are seeking occasion of stumbling.
I told this individual I believed he was mistaken,
and not following the path of duty in leaving his meeting.

Next we visited three aged Friends; had a religious opportunity with them,
and went to see George Malin, a Friend nearly ninety years old,
he being on his death-bed, and could neither see nor speak; though he appeared sensible.
I said to him that I trusted his sufferings would soon be over,
and was led to supplicate for his happy release, and for those in health around his bed,
that we might be prepared for the final summons.
After an opportunity with his nephew, who was left with a little family to care for,
I felt peaceful and easy to leave,
and returned to Isaac Hall`'s. A Friend and her husband
coming in. we had a silent sitting for a time together,
when something arose for communication, to which I yielded,
and felt peaceful and easy afterwards.

A song of praise did indeed fill my heart,
and I was encouraged to press onwards towards the mark for the
prize of the high calling of God in Christ Jesus.
The substance of my communication was this--that Mary Magdalene, and the other women,
that followed Jesus afar off, when He was taken to be crucified;
after his death still lingered around and near the sepulchre.
Jesus arose from the dead, showed himself first to Mary Magdalene,
out of whom He had cast seven devils,
bade her go and tell his disciples that He was risen from the dead--joyful news.
In this dark and cloudy day,
when Jesus is spiritually put to open shame--when the leadings and guidings
of his Spirit are neglected and slighted--when his true disciples have to
mourn and weep--when everything like comfort and consolation is withdrawn,
and the enemies of Truth are permitted to rejoice,
it is meet we should keep the faith and patience of the saints.
It is necessary if we would experience our joy and consolation to abound in Christ Jesus,
to cleave to that little measure and manifestation of the Spirit still vouchsafed,
even in the most dark and gloomy hour: "`For the oppression of the poor,
for the sighing of the needy, now will I arise, saith the Lord.`"
If these his disciples had not kept near Him--had not waited for the
consolations of his Spirit--had not mourned as true mourners,
do we believe they would have ever been permitted to
become living witnesses of his glorious resurrection,
or preachers thereof? Blessed be God!
He will not leave any comfortless who put their trust in Him.
He will more than compensate them for all their sorrow and grief on account
of the sad state of things in the Church and State as they cleave to Him;
though it may seem for a time, that the hour and power of darkness is so great,
that no hope is left; that things will change for the better.
Yet He who burst the bonds of death,
because it was not possible he should be holden of them:
He is Lord of lords and King of kings;
He can and will do great and wonderful things for those who put their trust in Him.
Blessed, praised and magnified be his adorable name, saith my soul,
forever and forever.ling to receive counsel from the very least child,
willing to take advice as well as give.

Second-day,
the 12th of the Month--I felt my mind drawn to visit the
families within the limits of Goshen Monthly Meeting,
who had recently withdrawn from their respective meetings,
and joined in fellowship with those who have elsewhere come to
the conclusion that Philadelphia and Ohio Yearly Meetings are
no longer bodies rightly claiming the name of Friends.
The first family we visited was that of R. E. He and
his wife and children appeared satisfied with the visit.
I laid before them the danger of setting up our
individual judgments respecting whole bodies of Friends;
that we ought to be able to give substantial reasons for so
manifestly disclaiming any unity therewith before leaving.
I had not been able to see the propriety of this step,
and believed it would lead farther and farther into the wilderness.
I exhorted them to reconsider their movements, to turn unto the Lord,
look for help from Him, and I believed they would see their mistake.
That it was for want of abiding in the everlasting faith and patience of the saints,
that they had taken this step.
The mother of this family expressed her thankfulness for the visit,
and I was well satisfied in having performed it.

We next went to Jonathan Cope`'s, who did not incline to accept such a visit,
so we did not get out of the carriage.
Thence to Aaron Garrett`'s; he also refused us admittance on the ground proposed, that is,
a religious visit, so we left them, but felt satisfied that I had made the attempt.

Dined and lodged at the house of our friends Jacob and Phebe Roberts.
They seemed to bid us welcome with the whole heart.
Phebe is a minister, and Jacob an elder.
Oh, that the Lord may keep the little ones in the hollow of his holy hand,
from being betrayed by fair words and smooth speeches.

On the morning of the 13th, left the house of our kind friends Jacob and Phebe Roberts,
in order to attend the Quarterly Meeting of Haddonfield.
During the evening previous to leaving,
I had an interesting and satisfactory opportunity with this family.
My mind was drawn into living exercise for the dear children,
and my heart enlarged to speak many gospel truths in their hearing.
Phebe expressed her thankfulness for the visit,
and I believe she felt it as she expressed it. In the
afternoon went from Philadelphia to Moorestown,
N+++.+++ J.

On the 14th, attended the Select Quarterly Meeting held at Upper Evesham,
in which I had considerable to communicate,
but felt the spirit of opposition strong against me,
so that my service was indeed laborious,
but felt satisfied in having endeavored to relieve my mind faithfully amongst them.
I had to advert to and dwell somewhat upon the
necessity of becoming humbled before the Lord;
letting Him turn his hand upon us, then if He wash us, we will be wil

Oh, the self-righteous, self-exalted spirit that prevails in many ministers,
as well as elders, in our poor Society; not more in that place than in many others.
After meeting, dined with David Darnell and wife, who treated us very kindly.
Lodged with Mary Borton and daughters; the mother was in a declining state of health,
but very peaceful and resigned.

Next day, at Haddonfield Quarterly Meeting.
My mind was under great exercise in that large meeting;
bearing it until I felt it required of me to speak.
I arose, with these words--Oh, Haddonfield, Haddonfield,
the Lord hath a controversy with thee; the multitude of thy chariots,
thy horses and horsemen cannot save thee when the Lord riseth up to plead with thee.
Then I said in substance,
that the day of the Lord must come upon all that is high and lifted up,
upon all the oaks of Bashan, upon all the cedars of Lebanon,
and upon all pleasant pictures, upon every one that is high and lifted up,
and he shall be brought low.
I had a short, impressive warning to deliver to them,
exhorting them to flee to the strong tower for safety,
to humble themselves before the Lord, that it might be well with them, etc.
After the shutters were closed,
I had an encouraging testimony for the sincere and upright-hearted,
in and under which my mind was strengthened and
encouraged with this language--"`Why sayest thou,
oh Jacob, and speakest, oh Israel, my way is hid from the Lord,
and my judgment is passed over from my God? Hast thou not known, hast thou not heard,
that the everlasting God, the Lord, the Creator of the ends of the earth, fainteth not,
neither is weary? There is no searching of his understanding.
He giveth power to the faint; and to them that have no might, He increaseth strength.
Even the youths shall faint and be weary, and the young men shall utterly fall.
But they that wait upon the Lord shall renew their strength;
they shall mount up with wings as eagles; they shall run and not be weary,
and they shall walk and not faint.`"

My heart was enlarged in the love of the gospel towards those
present who were pressed down under discouragement,
and they were encouraged to lift up their heads in hope.
I felt greatly relieved after this meeting and very peaceful in mind.
Many Friends spoke affectionately to us after meeting,
toward whom the salutation of gospel love was felt to flow without respect of persons.

Dined at Henry Roberts`', where many Friends came.
After dinner, had a religious opportunity with a large company.
I encouraged the weary and heavy laden, and fainthearted, to trust in the Lord.

Took tea at _______, but felt little like eating, or enjoying conversation of any kind,
believing I should not be permitted to leave that house peacefully without
requesting a religious opportunity with the family and those present,
of whom there was a considerable number.
I had a close warning to some present to set their
spiritual houses in order for the final reckoning.
Then felt clear to leave them, and returned to Moorestown,
and lodged with our kind friend Hannah Warrington,
where we made our home during our stay within the limits of that Quarterly Meeting.
Several Friends, mostly aged and infirm, unable to get out,
wished us to make them a visit; and I feeling it right to do so, on Sixth-day afternoon,
the 16th, we made several calls on the class mentioned.
Seventh-day was employed mostly in the same way,
and I thought rightly so. It was truly an interesting visit to me,
as I thought I saw the hand of the Lord in it, leading us from place to place,
and I think generally acceptable to the visited.

First-day, the 18th.--Went from Moorestown to Haddonfield, six miles,
to attend that meeting.
My mind was deeply exercised therein, but I was silent throughout.
A woman Friend from a neighboring Quarterly Meeting,
took up most of the time in preaching and praying.
It was a very trying meeting to me, believing the cause was hurt by this individual.

Dined at Josiah Evans`'. After a religious opportunity in this family,
went to Joseph Snowden`'s. He having decidedly opposed in their Quarterly Select Meeting,
the liberty I asked,
to visit by appointment (when not convenient to attend as they
came in course) the meetings belonging to Haddonfield Quarter,
and to appoint some amongst those not in membership with us. I told Joseph and his wife,
I had no object in coming to see them,
only to comply with a sense of duty impressed upon my mind.
Now, if they had any counsel for me, whatever it might be,
I was willing to hear it. I felt disposed to
take the advice of the elders at home and abroad,
and if they thought I ought to return home, they need not be afraid to tell me so;
I had always loved good order and discipline, and tried to adhere to it. Joseph replied,
that he had no advice to give, but to encourage me to attend to the pointings of Truth;
he did not wish me to return home.
I told him I had been endeavoring to follow the pointings of Truth,
and I believed that led me to ask permission of
the Select members of that Quarterly Meeting,
to visit the meetings within its limits to which he was strongly opposed.
He said,
if I had come the week before I could have attended all
the Monthly Meetings as they occurred.
I let him know that was not in the line of my duty;
and further told him if he could feel free for
me to go to the meetings as they came in course,
and had unity enough to encourage, or be willing I should do so,
I could see no real ground to object to the appointment of meetings.
I thought he felt himself in a narrow place,
but I put the burden fairly on his shoulders,
and after some religious communication to his son and daughter, I left them,
feeling thankful I had been helped to make that visit, and to be faithful whilst there.
Oh, how sweet and precious the Truth is as we follow it; how it leads into faithfulness,
meekness, and all that is lovely.
Returned to Moorestown that evening,
but not without apprehensions that I had better remained at Haddoufield a little longer.

Next morning, the 20th of Sixth Month,
after a religious opportunity with dear Hannah Warrington,
her brother-inlaw and two nieces, we left Moorestown for Philadelphia.

On the 21st attended the Monthly Meeting for the Western District.
Truly it was a very laborious, trying service that fell to my lot.
It seemed as if everything was arrayed against me,
and suffering both before and after the shutters were closed, was my meat and my drink.
One woman Friend (and I think the only female elder there), showed us much kindness,
desiring my encouragment, said my service was hard amongst them,
but she believed called for.

My way now seemed hedged in on every side,
and I found patience and faith were necessary in no small degree,
in order to keep the right track.
I had been looking towards attending some meetings in the limits of Salem Quarter,
but the enemy was permitted to buffet me sore, and I was let down into the low dungeon.

Fifth-day 22nd.--Attended Arch Street Meeting, and was silent therein.
Went to Joseph Walton`'s in the afternoon and remained there till First-day,
not seeing anything to do, save making a visit to a young Friend,
who resided with her brother in the city.
There we had a free social visit, and also some communication on religious subjects.

First-day, attended Arch Street Meeting, and had some service therein, and felt satisfied.
Dined at Joseph S. Elkinton`'s and went with them to the
afternoon meeting for the Southern District,
but had nothing to communicate.
Lodged at Joseph Walton`'s. Believing it to be required of me
to visit the meetings in the limits of Salem Quarter,
we set out on Second-day afternoon the 26th, for Woodbury;
got there in the evening and lodged at Carlton Stokes`'. That night I was quite ill,
so that I slept but little,
and thought it not improbable that my remains might be laid there,
being threatened with a severe turn of the dysentery.
But my mind was kept so calm and quiet, that a song of praise filled my heart,
and I could desire nothing more than the Lord granted me at that time.

Next morning remained in bed until meeting time, then arose and went to meeting,
though scarcely able to walk.
It was their Monthly Meeting, and I could say I was glad I was there,
and others responded thereto.
After meeting, took the cars to Salem.
Were met by William Carpenter, who took us to his house,
where we were kindly treated by himself and wife.

Next day attended Salem Monthly Meeting, which was very small, it being harvest time,
and many absent.
I had some service in the way of the ministry,
but felt after meeting as if my work there was not done.
Dined at Martha Wistar`'s. and after resting awhile rode seventeen miles to Greenwich;
our kind Friend, William Carpenter, taking us in his conveyance.
Reached Clarkson Sheppard`'s about dark, and were truly thankful.
We were well cared for every way.
Hospitality without grudging or dissimulation, was shown us in no small measure.
Next day attended their Monthly Meeting, in which I had close service,
which has fallen to my lot very often in this visit,
so that very little pleasant bread has been my portion
in the various meetings which we have attended,
save as I have been led with the eye of faith to behold, that when this shaking is over,
when the Lord shall have melted and tried us,
he will beautify his sanctuary and make the place of his feet
glorious amongst this people as in the gathering of this society.
We made several family visits at Greenwich, and felt peace and satisfaction.
Returned to Salem on Sixth-day evening, our kind friend, Wilmon Bacon,
going with us. We were late in starting and were out after night,
there being as great a storm of rain as ever I was in; the night was extremely dark,
only when flashes of lightning enlightened the darkness,
but our Lord and Master brought us through without accident.
I regretted not stopping all night where we took tea, believing it was a miss,
but fearing the friend who was with us was in haste to return, it being harvest time,
I did not mention my feelings, and so went rather contrary to my best judgment.
I have always found the Master`'s intimations are to be preferred,
before all and everything else.

Attended Salem Meeting on First-day.
Great were the conflicts of my spirit, both before and after going into this meeting,
believing hard things would be required.
After sitting a considerable time under deep exercise, I arose with this query,
whether any did suppose they could stay at home in the middle
of the week and attend to their domestic concerns,
and come to meeting on First-day and go to sleep,
and thus offer acceptable sacrifice to God? And some
such were very critical too in their observations,
had nice ears, liked to hear eloquent sermons, when they heard preaching;
but I had a message for them in plain, simple language.
And then the Lord required me to take the shawl off my shoulders and tell them that
thus would the Lord strip them of the covering wherewith they were covered.
"`Woe unto him that covereth himself with a covering,
but not of my spirit saith the Lord.`"
He is not to be mocked; none can wrest themselves out of his holy hands,
when once he shall arise to plead with them in judgment unmingled with mercy.
I exhorted those who were thus at ease, to make haste, arise,
and shake themselves from the dust of the earth before it is too late.
The Lord is still disposed to have mercy.
"`Whilst ye have the light, walk in the light, work whilst it is day,
for the night cometh wherein no man can work.`"
When mercy and grace are withdrawn then we are left in darkness,
and have no more opportunity to work out our soul`'s salvation.
I spoke encouragingly to those who were striving lawfully for
the mastery over the corruptions of their fallen nature,
and over the temptations of the devil, believing there were such present.
The Lord did indeed weigh the mountains in scales, and the hills in a balance,
and give me that day to see and feel that there is nothing too hard for Him
to do. For my soul was bowed down as under the weight of mountains;
but thou O Lord, didst support me, I was as one pressed out of measure,
but thy hand did take hold of me and kept me from sinking below hope.
Let none ever distrust the power of the Lord in the hour of great extremity.
"`Trust in the Lord, O my soul! yea, trust in the Lord,
for in the Lord Jehovah is everlasting strength.`"

I left this meeting quiet and easy in mind,
after which I called at the house of a member in Salem.
It was impressed upon my mind that it was required of me to ask the father and
mother of this family to sit down awhile in silence with us. I had been before
impressed that I was the subject of scorn and derision by the woman of this house,
which made it hard for me to give up to this requisition;
but the Lord made hard things easy, and bitter things sweet.
I felt that I must not turn to the right hand, nor to the left,
but obey the orders of the Captain of Salvation.
The request was acceded to,
and I soon found my mind impressed with an exhortation to deliver first to the father,
and then to the mother, to become concerned for themselves,
and not put off the work of repentance and amendment of life.
Time is uncertain,
the necessity very great to have our day`'s work going on in the day time,
and exhorted them to be concerned to train up their
family in the nurture and admonition of the Lord.
I then left them, feeling greatly relieved,
and very thankful that I had attended to this duty.
They bade me farewell respectfully,
and I had cause to believe were satisfied with the visit.
I afterwards learned that this woman,
on being queried with by her mother if she was not
going to Monthly Meeting the fourth day previous,
replied no; that she did not want to hear a ranter preach,
alluding to my prospect of being there, for as such I had been represented to her.
Then I saw that my feelings had been correct,
and that the Lord had laid it upon me to preach in their house,
not having heard anything of her remarks.
Truly my soul has dwelt among lions, but the Lord hath stopped their mouths.
I had felt on entering that house when we first stopped in Salem,
that if any religious service was required of me there,
it would be like taking my life to give up thereto;
but the things that my soul refused have become my sorrowful meat.
Praise ye the Lord, ye who have known the bow of steel to be broken,
and the arms of your hands made strong by the hands of the mighty God of Jacob.
It is through good report and evil report, as deceivers and yet true,
that the tribulated servants of the Lord must pass along;
for if they have called the Master of the house Beelzebub,
what will they not say of them whom he hath called and appointed to run on his errands.
After the opportunity above mentioned,
dined at Caspar Wistar`'s. Had some religious service in the family,
and felt easy and peaceful.
Caspar and his wife both expressed satisfaction with the visit.

Took tea at George Abbott`'s,
had a religious opportunity in the family to the relief and peace of my mind,
and to the satisfaction of the visited.
It has rarely happened in this visit that my
Master whom I desired I think above all things,
faithfully to serve, suffered me to leave a family without a religious opportunity,
though my natural inclination would gladly have been excused therefrom.
Lodged that night at Martha Wistar`'s, but had I been faithful when there before,
we need not have returned at this time;
I endeavored to clear my mind towards this family.

Seventh Month 3rd.--Left Salem with a peaceful mind, and took the boat for Philadelphia.
Had a pleasant and beautiful ride on the great Delaware; got to Nathan Kite`'s about noon.
My mind had been under exercise in regard to attending the
meetings belonging to Muncy and Exeter Monthly Meetings,
branches of Philadelphia Quarterly Meeting.
I found I must stand resigned to go, although the weather was very warm,
and everything as to the outward seemed to be against
it. I mentioned the subject to my companions,
and to Nathan and Hannah Kite.
My companions expressed a willingness to go,
but Nathan and Hannah did not encourage or discourage,
leaving the matter entirely with myself.
I took that opportunity to ask Nathan Kite if I had gone
counter to his advice since I had been amongst them.
I said, didst thou not say,
thou wast willing I should visit the Monthly Meetings in the city? He said, Yes.
When I asked,
Didst thou not say thou wast willing I should visit the
Monthly Meetings in the limits of Caln Quarter.
"`Yes, perfectly.`"
Now I do not want to go counter to the advice of the elders,
but as the subject of going to Muncy was left with me, I must be wholly resigned to go,
so we were about preparing to set out next morning.
But after my mind had become fully resigned,
and I was making no other calculation but to go, the scale began to turn,
and turn it did, until the pointings of the Master`'s finger were directly homewards.
Oh, the goodness of my Heavenly Father in this release,
but I did not mention my feelings to my companions till next morning.
Arising early, I let them know our way was clear towards home,
as soon as arrangements could be made for leaving the city.
Having several times during our tarriance in the city sought an
opportunity to be a little time in Elizabeth Pitfield`'s company,
she being confined at home through indisposition, and having failed,
I now sent her word we were about to return home, and if she wished to see us,
we would be willing to spend a little time in her company.
The time set by herself for the visit, was four o`'clock, the 4th of the month.
We accordingly went at the time,
found her sitting up and ready to receive us. I informed her
that I had heard she had expressed a wish to see us,
and now if she had anything for us, I, or we,
were willing to hear it. We sat awhile in solemn silence,
in which the Master gave us an unspeakable evidence, that his presence was near,
to my humbling admiration, and then Elizabeth was commissioned to break that silence,
and express her feelings, which I found were in unison with my own,
being bound to acknowledge that the presence of the Master was to be felt and witnessed,
giving life, peace and satisfaction in the opportunity;
reviving for my encouragement this language: "`Fear not, for I am with thee;
be not dismayed, for I am thy God.
I will strengthen thee; yea, I will help thee; yea,
I will uphold thee with the right hand of my righteousness.`"
Before a word was spoken, this language ran through my mind,
feeling that we were permitted to realize it: "`Man did eat angels`' food.`"
We parted with Elizabeth in near affection,
and the language of Joseph ran through my mind, "`Doth my Father yet live.`"
I found my dear aged friend alive in the Truth, and rejoicing to find those alive too,
whom she may have (by insinuations and deceptions on the part of others) supposed,
torn to pieces by a wild, ranting spirit, as some were wont to represent me.

Oh! the wonder-working power of the Almighty? Who can fathom it? Who can
stay the bottles of heaven?`" Who can bind the sweet influences of Pleiades,
or loose the bands of Orion?`" He hath reserved the prerogative in
his own hands to take the wise in their own craftiness.
Oh, Philadelphia!
Philadelphia,
how hath my spirit been made to partake in the
midst of thee of the cup of deep suffering!
How have the mountains of exercise pressed sore upon me!
How have the enemies of Truth ploughed upon my back and made long their furrows--
how did my God give me up to be trodden down as the mire of the streets,
when no arm save that of Omnipotence could have sustained me under
the weight of exercise and distress meted out to me since my lot was
cast in thee--thou magnificent and populous city--once the habitation
of many worthy champions for the Truth;
now, alas! the residence of many under the name of Friends,
but not in the possession of the Truth "`as it is in Jesus.`"
Yet I believe there is a seed and remnant preserved.
Returned to Nathan Kite`'s and stayed till after tea.
Before leaving, I told Nathan, I had nothing to take back, or regret,
that I had said in their Yearly Meeting.
I said, moreover, we have had some favored opportunities together, and I trust,
there is still a feeling left in our hearts in which we can recommend one
another to the care and keeping of the Shepherd and Bishop of souls,
and bid each other farewell in the love of the gospel:
to which Nathan fully and freely assented; and we then shook hands and parted,
to meet perhaps, no more on earth.
At the same time Nathan said to me:
Mayest thou be comforted and strengthened when thou gets home.

There the Lord let me see his wonders in the deep;
there He kept my head above the waters, when the waves ran high and boisterous.
He showed me before I left my own habitation, that I must suffer those,
and there in that Golgotha his everlasting arms were underneath,
though nothing but the grain of living faith was vouchsafed, and felt to support,
and my heart hath praised Him, that I was accounted worthy to suffer with the oppressed,
down-trodden seed: whilst the frost consumed by night and the draught by day.
Praise ye the Lord.

Returned to Joseph Walton`'s, and spent the evening pleasantly with several Friends.
Next morning took leave of Joseph and his wife, their brothers, sisters and aged mother,
and left Philadelphia in the eight o`'clock train for home.
On my way this language was almost constantly in my mind:
"`With my staff I passed over this Jordan,
but now I am become two bands,`" having become united to a living remnant,
who felt as flesh of my flesh and bone of my bone;`" both among the aged,
the middle aged, and the dear youth,
whose prayers and good desires followed us homewards as the kindred of Joseph.
On my way home, where we lodged the last night, a young woman was playing on the piano.
I went to her and thus accosted her:
"`Wilt thou suffer the word of exhortation from a stranger.`"
She immediately stopped playing.
Then I laid before her the necessity of spending her
time in the fear of the Lord and to his honor and glory.
The tears came in her eyes, and we parted friendly.
Oh, the cross it is and has been thus to address others,
but my peace is concerned therein and I durst not withhold.
Went on my way rejoicing, but not without trembling for my own safety.
Our friends at home rejoiced to see us, and we them.
