== Chapter XI

[.chapter-synopsis]
* Death of Hannah Mitchell, and Hopeful Remarks
* Death of Ruth Conrow
* Death of William Bailey, and Remarks Thereon
* A Religious Visit to Pennsville and Short Creek Quarters, Extending to their Branches and Families
* A Religious Visit to Salem Quarter
* Its Branches and Some Families
* Death of Joseph Walker
* Death of Isaac Mitchell
* Death of Her Cousin, Joseph Branson, and Remarks Concerning Him
* Exercises Under a Sense of the Situation of Her Own Yearly Meeting

Second Month 29th, 1872.--On the 25th of last month, our beloved friend, Hannah Mitchell,
departed this life, in the thirty-fourth year of her age.

She was possessed of talents rather above ordinary,
and for several years previous to her death,
appeared to be bending her neck to the yoke of Christ;
and thus preparing for usefulness in the Church.
Her elder brethren and sisters watched the progress of her religious concern,
with feelings of hopeful expectation, that she might become,
if not a mother in our Israel,
a helper and companion of those who prefer the
welfare of Jerusalem above their chief joy.

When lo!
He that maketh the clouds his chariot, and treadeth upon the high places of the earth,
saw meet to cut the work short in righteousness,
and disappoint all our hopes as relates to the further
labors of this dear Friend in the Church militant.
Great were her exercises during her illness, not only on her own account,
but that of others also.
Fervently supplicating the Father of mercies on behalf
of every individual belonging to our little meeting,
that there might be a deepening in the root of life amongst all classes,
and that the anointed ministers might eye the
Captain of salvation in all their movements.
That they might be willing to go deep into the river of judgment,
to be able to bring up stones of memorial from thence,
and that their ministry might be baptizing, etc.
And also supplicated that other gospel ministers might be raised up amongst us,
that the feet of the gospel messengers might be
beautiful on the mountains of the Lord`'s holiness.
In her supplication in reference to the ministry, and on behalf of the ministers,
she said--"`The manna of yesterday will not suffice for today, it will stink;
there must be a renewed supply.`"

Oh Lord, my God! bless the exercises of this dear Friend to my soul.
Deal with me in such a way as will deepen me in the root of life.
Bless her exercises to others,
raise up and qualify those who may be able to take the places
of the standard-bearers whom thou art removing from our midst,
that there may be in this place according to the supplication of our
dear departed Friend--"`A little army of standard-bearers raised up,
for the support of those precious principles and
testimonies given us as a people to bear.`"
Amen, and amen.

Third Month 10th.--The exercises of my mind and
the burden resting upon it are at times great.
It seems to me, that judgments are hovering over us. Oh,
that they may be mingled with mercy.

Last week, attended the funeral of W. S., a young man who died at our Boarding School.
My mouth was opened in testimony at the house, and afterwards at the school meeting;
a little evidence given that I am not forsaken of the Lord;
praises belong unto Him for this evidence,
for surely He would not require me thus to speak to others,
if He had cast me off forever.

20th.--Last night, our friend Ruth Conrow, a member of our little meeting,
died very suddenly and unexpectedly.
Surely, the Lord is dealing with us in a remarkable manner,
removing from our midst one after another in quick succession,
giving us to see and feel that our life is indeed a vapor that must soon pass away.
Oh, that He may search us, try us, and deal with us,
that we may turn with the whole heart unto Him,
hath been and still is the desire of my heart for myself and others.

Sixth Month 15th.--This day, heard of the death of William Bailey,
which took place yesterday on the car in which he was travelling.
He was suddenly cut off in a few minutes after taking his seat.
Several years ago,
a deep and heart-felt concern came upon me to warn this man of
the necessity of being prepared for a sudden exit.
The first time it came before me,
and I had an opportunity of delivering the message to him,
I shrunk from the duty required, which occasioned much sorrow of heart on my part.
But again the command was given, and I obeyed; going to his house,
and delivering the message as faithfully as I could.
I told him that people were often suddenly killed on the cars,
but did not prophesy that he would be, only felt constrained to plead with him,
to set his spiritual accounts in order.

Oh, how my heart was impressed, and exercised on his behalf;
his wife took great offense at what I said,
and afterwards manifested the most bitter feeling towards me.
She too was suddenly removed from works to rewards,
taking a dose of chloroform.
She fell into a sleep from which she never awoke.
Thus both of them,
who were disconcerted at my plain and impressive
warning to be ready for the solemn change,
were suddenly cut off.
Oh, may I be in earnest to have my spiritual accounts in
readiness when the pale messenger is sent.

1873.--Having the unity and concurrence of my Monthly and Quarterly Meeting for
religious service within the limits of Pennsville and Short Creek Quarters,
I left home on the 16th of Eleventh Month, 1873,
in company with my cousins Joseph Branson and Abigail Sears, assistant companions,
and arrived at Pennsville in time to attend that Quarterly Meeting,
held on the 20th of said month.

Through much bodily infirmity and mental exercise,
I visited all the meetings composing that Quarter,
and had forty-six family opportunities, and returned in three weeks.
Having a hard cough and being otherwise indisposed,
I remained pretty much shut up through the winter,
except attending meetings at home as they came in course.

1874.--About the first of the Fourth Month, 1874, I received an injury of my spine which,
added to my previous infirmities, confined me to the house and bed for several weeks,
subjecting me to much bodily suffering.
But as soon as I was able to ride out and attend meetings,
I felt it right to engage in a family visit in the neighborhood,
and in the town of Flushing.
A concern to pay a religious visit to the inhabitants of the town generally,
in a family capacity,
had long rested with me. But now seeming to myself altogether inadequate to the task,
both as relates to strength of body and mind,
the impression was gently but forcibly brought home to my heart on this wise:
"`Now is the time, arise up and enter upon this visit; fear not,
for I the Lord will be unto thee strength in weakness,
and a present helper in the needful time--mouth and wisdom, tongue and utterance.`"
And as I set out and moved along from day to day in the prosecution of this visit,
I found the promises of the Lord wonderfully verified.

He did, indeed, often make a way for me amongst professors and profane,
where for a time there appeared to be no way to cast off my burden.
He stopped the mouths of gainsayers, and enabled me to deal honestly with all classes,
and to my great surprise,
when about leaving some families from whom we could least expect such a salutation;
we were thus accosted: "`We thank you for this visit.`"

Many times, on sitting down in a family, I felt my weakness to be so great,
both in mind and body, as scarcely to be able to keep my seat,
or to maintain that patience and composure which such an occasion requires.
But being enabled fervently to cry unto the Lord
for help and strength to keep in my right place,
and to be preserved from bringing a reproach upon the Truth,
He hath heard my cry and raised me up out of these low places,
making me to forget all my weaknesses,
and enabled me to plead with my fellow pilgrims
to come taste and see that the Lord is good,
and worthy to be served, honored and obeyed with an undivided heart;
richly rewarding those who love and serve Him,
even beyond all that they can ask or think.
And that He is a just as well as a merciful God, and will not acquit the guilty,
but requires all to bow their necks to the yoke of Christ, which if they refuse to do,
their portion must and will be according to his
own holy and righteous decision with those,
"`where their worm dieth not, and the fire is not quenched.`"

Having finished what was before me in the limits of our own Preparative Meeting,
I went to Guernsey, a branch of Flushing Monthly Meeting,
and visited a number of families in that neighborhood and about Freeport,
chiefly amongst those not members with Friends,
and appointed several meetings amongst other societies.
Oh! the depth of sorrow and tribulation that attended me in this engagement,
none knoweth but the Lord alone.
It was my desire to serve Him faithfully, and as He saw meet to blindfold me,
and lead me along day by day in this way, it was a great exercise of faith and patience.
Sometimes I was shut up for two or three weeks,
not seeing anything clearly to do but to attend meetings as they came in course.
This may have appeared to some like idling away my time,
but there were those who were deeply interested for the prosperity of Truth,
who were as Aarons and Hurs holding up my hands.

From Guernsey I went to Harrisville in the Eleventh Month,
to attend our Quarterly Meeting,
having a prospect that some service in the way
of family visiting and appointing some meetings,
would be required of me in the limits of Short Creek Monthly Meeting.
I saw at first but little opening,
yet felt it right to remain in the neighborhood and
wait to see what the Head of the Church required.

The next day after Quarterly Meeting,
I felt it right to request the liberty of visiting Dr. Comly and family,
residing in the town of Harrisville.
The request being granted by the Doctor, I made the visit on Seventh-day morning,
and felt that I had cast off a burden which had long rested upon me. I was
led and enabled to deal honestly with the doctor and his daughters,
not turning to the right hand or the left, to make my communication more palatable,
or less so than I believed the Lord would have it. O,
that those dwelling or resting upon dangerous ground would take heed in time,
before the day of mercy closes over their heads.

On First-day afternoon I had an appointed meeting at West
Grove--a few miles from Harrisville--amongst the Gurneyites,
having obtained liberty of some of the heads of the meeting to occupy their house.
At half-past two we went to the meeting-house,
and pretty soon the people began to collect, and the house became pretty well filled,
although the day was very rainy.
On our way to this meeting, I told my companions, Jqtm and Edith Smith,
that I did not expect much satisfaction, if any, in this meeting,
except what might arise from keeping my own proper place if I might be
favored and strengthened so to do. I thought the Gurneyites would avail
themselves of the opportunity of relieving their minds in their own house,
and I was not mistaken.
We had to listen to six communications from their own members,
and some of them quite lengthy; two in the form of prayer.
I sat amongst them under the painful impression that true silence in and
under which the heart is prepared to offer up living sacrifices to the Lord,
was very much lost sight of, and consequently experienced but little.
I could not feel it my place to sit altogether silently amongst them,
though but little opportunity was afforded me to speak.
The meeting held till nearly night.
In viewing it over, I felt well satisfied that I was there,
having done what I thought was my duty.
After this meeting, I remained at the house of my kind and sympathetic friends,
John and Edith Smith, not seeing any way to move with clearness for several days,
except attending the Monthly Meeting of Short Creek.
Soon after this my way appeared to open towards a few families in that neighborhood,
which I attended to under much weakness of body and exercise of mind;
and as I moved cautiously along, keeping my eye as well as I knew how,
to the Head of the Church, I was favored from day to day to feel satisfied,
and peaceful in the retrospect, and the field of labor widened,
until I visited all the families of Friends at Harrisville, Smithfield and Concord,
with two exceptions, these not being at home, and divers others, not members;
my dear friends, John and Edith Smith bearing me company.

After getting through in these places, my mind was turned towards Mt. Pleasant,
where no members belonging to our Yearly Meeting reside.
I had long felt a concern to visit some families
and individuals in that town and its vicinity,
and now the word of command was given me to go forth and fear not;
but great were my feelings of weakness and incompetency for the work,
but the Lord strengthened me in body and mind to bear up,
until He closed the way for further service.
When I had been one day out on this errand, the language sounded in my spiritual ear,
"`Make haste.`"
I therefore made haste, and after three day`'s engagement,
seeing nothing further with clearness but to attend Harrisville Meeting, I did so;
and after that was taken very sick with pneumonia,
which quickly prostrated my feeble frame,
and rendered me unable to return home for more than twelve months.
This trial of faith and patience none can fully comprehend but
those who have had similar trials to pass through;
but when in all human probability I was likely to have to remain months longer,
the Master opened the way for me, and I got home in midwinter,
and gradually improved in health, and in a few months got out to meeting again.
Great and marvellous are the works of the Lord, and that my soul knoweth right well.
During this illness at Harrisville,
I was very kindly cared for at the house of our friends
William and Mary T. Hall for seventeen weeks,
and the house of my cousins, Josiah and Deborah Hall for thirty-one weeks,
nothing they could do for me by day or by night, to make me comfortable,
was lacking on their part; may my Heavenly Father reward them for it.

In the foregoing account, I have omitted to insert in their proper places,
some exercises and incidents connected with this visit, which I think proper to record.

After finishing the family visit within the limits of Harrisville Preparative Meeting,
being at the house of my kind friends, John and Edith Smith,
on awaking early one morning,
a bright prospect and hope of being speedily released from
further service in that Monthly Meeting presented to my mind.
As I had not been looking for such a release, I was taken by surprise,
and very pleasant was the prospect.
Then self began to claim a reward of merit, and thus to reason:
"`Well I have endeavored so far to be faithful
to apprehended duty in this religious visit,
and have become pretty well resigned to do, or to suffer,
whatever the Master might require at my hands,
and now He is about to reward me with a speedy release from this arduous labor and
exercise of mind and body,`" and my heart leaped for joy as the prospect still
remained bright before me. Arising from my bed under these feelings,
accompanied with the impression that I must wait until towards
evening before I mentioned my prospect to John and Edith Smith,
next morning being the time set in my mind to start home,
if I continued to feel as I then did.
But towards evening the bright hope and joyful prospect began to fade,
and it soon vanished like the rainbow, and left no trace of its former brightness,
but left me cast down and disappointed, if not in a murmuring state of mind;
and I queried and reasoned thus,
"`What does this mean?`" I was not seeking after
or expecting such a release at this time,
but it was presented with such brightness, that I thought it might be real,
but behold it hath vanished!
Then I was given clearly to see that this was dispensed for my instruction,
and for the further trial of my faith.
I was led to consider how very joyful I felt under the prospect of being released
from the work and service unto which I had been called by my Divine Lord and Master,
and how sad I felt on being remanded back as it were to prison,
to suffer with and for the suffering seed, which is pressed down in the hearts of many,
as a cart loaded with sheaves,
contrasting my feelings when this prospect opened before me and when it closed;
I saw clearly that I was far from being able to say,
as many of our worthy predecessors have said, viz:
"`I am freely given up to serve the Lord.`"
I was instructed,
and saw that I had need to die daily and go down again and again into baptism unto death,
not only for the sake of others, but for my own safety and purification; and now,
instead of returning home, I went to Smithfield,
to visit the families of Friends of that meeting, and others as way opened,
and I had very relieving opportunities in some places,
particularly with Dr. William S. Bates and wife.
The doctor was once an active and prominent member of Ohio Yearly Meeting;
but after the separation in 1854, he left the society and joined the Presbyterians.
My feelings of exercise and the weight which rested on me before going to his house,
cannot well be described, but I found that I must not turn to the right hand or the left,
but declare the whole counsel if peace was obtained,
which I endeavored to do. The doctor was very respectful,
expressing his thankfulness for the visit,
and I felt thankful for the relief it afforded.
Truly it is good to wait upon the Lord for strength and ability to perform his will:
and none who thus wait will be disappointed.

After returning from Smithfield, I went to Concord,
attended the Monthly Meeting held there,
and then proceeded with the approbation of Friends to
visit the families of that Preparative Meeting,
and some others not members, to the relief and peace of my own mind.
How needful when engaged in such visits,
to attend closely to the openings and shuttings of the Holy Spirit,
that the perplexities and troubles arising from omissions and commissions may be avoided.

From Concord I returned to Harrisville to attend Short Creek Monthly Meeting,
in the Second Month, 1875, hoping to be ready to return home after Monthly Meeting.
My mind was so much in that direction that I could not feel
that resignation which would have enabled me to say,
The will of the Lord be done; so I became exceedingly tossed in mind,
feeling no settlement as to what would be best,
and in this state I went to meeting. The waves
and the billows seemed ready to swallow me up,
and I cried unto the Lord for help,
being as really in jeopardy in my spiritual condition
as the disciples were outwardly on the sea of Tiberias.
I felt that I would be willing to do anything for a quiet settlement of mind,
and when I was brought to this feeling, the Master rebuked the winds and waves,
and there was a great calm, so that it was marvellous in mine eyes;
then I quietly settled down to remain where I was,
and next day attended the funeral of Elizabeth Sidwell,
a Friend whom I had visited three weeks before, and who was then in usual health.
On my way to this funeral, calmness as a canopy covered my mind.
I desired to be no where else than where I was;
such is the mercy and goodness of God towards his poor dependent children,
the desire of whose hearts is, above all things, to do his holy will.
After the company were gathered at the house of the deceased,
I felt it right to revive this impressive language:
"`Let not thine heart be hasty to utter anything before God; for God is in heaven,
and thou upon earth; therefore let thy words be few;`" adding a few remarks,
expressing the desire I felt,
that all might experience the fulfillment of this language of the Most High,
through the mouth of his holy prophet: "`I create the fruit of the lips;
peace to him that is far off, and to him that is near,`" etc.

After this, several communications were offered in the form of prayer,
and several in the way of counsel.
After a move was made to close the opportunity, my mind was not easy.
The spirit of supplication rested upon me,
and I felt it required to give vocal utterance to my feelings,
and the Lord strengthened me in mind and body.
My soul was poured out in fervent prayer,
that the Lord would be pleased to turn his holy hand upon us,
in judgments mingled with mercy, no matter how hard the strokes might be,
so that we might be of the number, whom the Saviour would own,
before his Father and the holy angels, when done with time here below.
I felt sweet peace and consolation, after this dedication to the will of the Lord.
It has not been very often that the Lord required vocal supplication of me in public.
O what a solemn thing thus to approach Him;
may I live so under his holy fear and qualifying power as to offer no vain oblation.

I was one of the few women who ventured to the grave side, the weather being very cold;
but could not feel satisfied without again opening my mouth in a
warning voice towards some who were indulging in a false rest,
concluding their spiritual condition to be better than it really was;
exhorting them to awaken to the fearful reality of their situation.
To let judgment run down as waters, in the temple of their hearts,
that no disappointment might await them, in the solemn hour of reckoning.
My communication was short, but afforded relief and peace,
and I did not appear to suffer any bodily inconvenience
by thus exposing my frail tabernacle.

Another incident occurred which rests with me to leave on record.
It may do some one a little good (even if it never reaches the eyes of many)
in the way of warning and encouragement to endeavor as much as possible to
have their own wills slain under the most trying circumstances.
On returning late in the evening from Mt. Pleasant to Harrisville,
after having made several family visits in and around the town,
it rested with me that something more in that line might be required in that place,
yet these words ran through my mind so strongly and forcibly,
that I felt almost alarmed at my own thoughts, which were these, viz:
"`I would rather die, than go back to Mt. Pleasant.`"
I was afraid it proceeded from a want of true resignation to the Lord`'s will.
Next day I attended Harrisville Meeting,
and the way appeared entirely closed for any further service at Mt. Pleasant,
though I had been looking towards appointing a meeting in the town.
Soon after Harrisville Meeting, I was taken very ill, of which I have already spoken,
during which it often looked, that the Lord was about to give me my choice "`to die,
rather than go back to Mt. Pleasant.`"
I have never since felt it required of me to make any more religious visits there.

Fifth Month 9th, 1877. Left home to attend Salem Quarterly Meeting,
and the meetings composing it,
and to appoint a few meetings amongst those not in membership with us,
having the approbation and unity of my Monthly Meeting, and my cousins,
Jacob Holloway and Rebecca S. Branson, as assistant companions.
We reached Salem the same day we left home, going by railroad,
as my health was not sufficient to stand the journey in a carriage.
On the next day attended New Garden Meeting,
where I had considerable service to the-relief of my mind;
finding in this meeting a spirit of self-importance, with which I had to deal plainly,
and also to encourage the little ones.
After meeting, dined with Anna Edgerton, widow of the late Joseph Edgerton.
After dinner, felt my mind drawn to visit Dr. John Kite.
He is one of the number who left Philadelphia Yearly Meeting some years ago,
believing as he professed,
that they had so far identified themselves with the doctrines of Joseph John Gurney,
and the departures from ancient Quakerism,
that he could no longer be associated with such a body in religious fellowship.
The doctor has since seen that he was too fast in judging and acting,
and has returned to Friends,
giving an acknowledgment as I have learned since our visit to him.
I dealt very plainly, and also very tenderly with him,
recommending him to make a full surrender of the whole heart to the Lord,
believing if he did, hard things would be made easy, and bitter things sweet.
He appeared very glad of the visit,
and parted with us in a friendly and affectionate disposition.

We next called on Elizabeth Leeds,
one of the leaders in the separation referred to. She treated us respectfully,
but our visit with her was not as satisfactory as with Dr. Kite.
I thought she was in a restless and unhappy state of mind,
yet desiring to be thought otherwise.
I recommended silence before the Lord.
Stayed that night with our kind friends, Joseph and Rachel Stratton,
where I had the opportunity of once more meeting with and
enjoying the company of my aged and well beloved friend,
Sarah Lupton, Joseph Stratton`'s mother, who is lively in the best sense of the word,
having long been a worthy elder in the Society of Friends.
Next morning, after a religious opportunity in Joseph`'s family,
we went to Salem in order to attend the Select Quarterly Meeting,
held at two o`'clock that afternoon.
In this meeting my mouth was opened,
and my heart enlarged in the love of the gospel towards the little company then gathered,
expressing the desire and necessity, that we might all deepen in the root of life.
That elders might dwell where they could understand what to encourage,
and what to discourage in the line of the ministry,
and be faithful to the openings of Truth upon their minds,
so as to be helpful to the ministers.
That the ministers might dwell so low and humble
as to be willing to receive a word of counsel,
or rebuke, coming from a baptized elder, esteeming it as a kindness,
and as an excellent oil when and where the Master requires;
and that all might be in a disposition to follow out the command of our Saviour, "`If I,
your Lord and Master, have washed your feet,
ye ought also to wash one another`'s feet;`" thus are we
instructed to watch over one another for good,
willing to receive, as well as to give, counsel.
Much openness appeared in the minds of Friends to receive what I had to hand forth,
and I felt satisfied and peaceful after this meeting.

12th.--Attended the Quarterly Meeting for business,
and had considerable vocal service therein,
encouraging Friends not to faint or give out in this dark and gloomy day,
expressing my belief that the Lord will yet beautify his sanctuary,
and make the place of his feet glorious amongst a people
upholding the very doctrines and testimonies that the Society
of Friends was raised up to promulgate and support;
which they did in the midst of the most cruel persecution, standing firm and undaunted.
Even should all who now profess the name of Friends,
forsake and abandon those doctrines and testimonies,
not one jot or tittle of which we can rightly dispense with, or lightly esteem.
Much opened on my mind in this way to communicate in the forepart of the meeting,
and after the business was ended, I requested the shutters opened,
which was united with by men and women Friends.
I felt it required of me to revive the testimony of Francis Howgill,
contained in Sewel`'s history part 2nd, pages 14 and 15;
setting forth the answer of the Lord to this faithful
and dedicated servant concerning this people,
whom He raised up by the might of his power,
written not only for the encouragement of faithful Friends in that day and age,
but also for such in ages and generations to come;
and also for a solemn warning to all such as turn their
backs upon the precious truths as believed in,
and practised by faithful Friends in the rise of the Society, and ever since.

"`I will take their enemies; I will hurl them hither and thither,
as stones are hurled in a sling; and the memorial of this nation, which is holy unto me,
shall never be rooted out, but shall live through ages,
as a cloud of witnesses in generations to come,
and nations shall know they are my inheritance; and they shall know I am the living God,
who will plead their cause with all that riseth up in opposition against them.`"

The greatest enemies now to the Society, are those professing the name of Friends,
or Quakers, but who have discarded the Truth as held and practised by early Friends,
and by every true-hearted Friend from that day to this;
but the Lord will deal with these hypocritical professors,
and they will "`be as when a hungry man dreameth, and behold he eateth; but he awaketh,
and his soul is empty: or as when a thirsty man dreameth and behold he drinketh;
but he awaketh, and behold he is faint,
and his soul hath appetite;`" and they shall be "`tossed like
a ball into a large country,`" having no rest or foundation
that will stand them instead in the hour of trial,
and sore proving; and that in which they now glory will become their shame,
for they profess to have found an easier way to the kingdom of
heaven than by the way of the cross of Christ,
choosing their own crosses, and marking out their own course, and saying,
thus saith the Lord, albeit, He hath not spoken by them,
neither hath He any pleasure in the way they are taking.
Oh, how my soul has mourned, and still does, on account of these things.
But we who profess to be standing for the doctrines and
testimonies which these have forsaken,
will yet be tried as to a hair`'s breadth,
for great lukewarmness and indifference as to true and practical
Christianity is manifest amongst us. That the judgments of the Lord will
undoubtedly be poured out upon us unless there is a deepening in the root.
All classes are called upon to humble themselves as in dust and ashes before the Lord,
that our spiritual lives may be given us for a
prey when He ariseth to shake terribly the earth.

First-day the 13th, attended Springfield Meeting,
and had close dealings with the lukewarm and indifferent professors,
some of whom are wide awake to see and speak of the
faults of those whom they see running too fast,
and who are drawing nigh to God with their mouth, whilst their hearts are far from Him,
and yet are not sufficiently alive and awake to their own spiritual condition.

These were exhorted and admonished in the love of the
gospel to get down below the surface of things,
for the Lord will try every foundation, even as with the hail, rain and floods,
and all the buildings which are not founded on the immovable rock Christ Jesus,
must come to naught, no matter how fair and specious.
The remnant whose eye, and cry are unto the Lord for help and strength,
were encouraged to trust in Him, for He will never leave or forsake these.
He is not a man that He should lie, nor the son of man that He should repent,
but his promises are yea and amen forever.

After this meeting rode to Marlboro, about eighteen miles,
and lodged at John Brantingham`'s. Notice was given for a meeting next day at ten o`'clock.
At the time appointed, the few Friends belonging to that meeting met,
and after a time of silence,
I felt it right to encourage them to do their best to keep up their little meeting;
reviving the language, "`Where two or three are gathered together in my name,
there am I in the midst of them.`"
The children were encouraged to faithfulness,
and reminded that in the rise of the Society, when the parents were in prison,
the children kept up the meetings in some places.

Dined with Margaret Brantingham, a Friend in the ninety-seventh year of her age,
and had a meeting that evening in the town of Marlboro,
to the relief of my mind in a good degree.
The people were exhorted to get down deeper, and strive in the right way,
to become true and living worshippers.
Supplication unto the Father of Mercies was offered,
that He might deepen us in the root of life.
Next day returned to Salem,
but not without some misgivings with respect to the right time for leaving.
Oh, my soul, wait thou more faithfully upon the Lord,
that thou mayst carry no burdens that might be avoided by unreserved dedication.

16th.--Attended Salem Meeting, and afterwards rode to Middletown, fifteen miles,
and lodged at Ann Blackburn`'s. Next morning had a
religious opportunity with this widow and her family,
to the relief of my mind; and then rode to Carmel,
where a meeting was appointed to be held next day at ten o`'clock,
their usual hour for holding their meetings;
and I think the most suitable hour for morning meetings.

18th.--Attended the appointed meeting at Carmel,
and was favored to relieve my mind amongst those assembled.
Oh, the exercises and deep wadings that attend my mind as we pass along,
both in meetings and out of meetings; but the Lord is my helper,
or I should utterly faint and fail of strength, both in body and mind.
Yesterday, on passing a house,
my mind was impressed that I must call with the family living there,
though I then knew not whose residence it was.
We dined with this family today,
and had a religious opportunity with them to the relief and peace of my mind,
and I trust the labor will not be lost.

19th.--Attended Middleton Monthly Meeting,
and labored therein according to ability received, which afforded peace of mind.
Near the close of the meeting for business, I informed Friends,
that I felt a concern to appoint a meeting for the young and
youngish people belonging to Middleton and Carmel,
to be held next day, at some suitable hour in the afternoon, at Middleton.
It was appointed, and proved a relieving opportunity.
It was quite well attended,
and the Lord strengthened me beyond expectation to clear my mind amongst them.

21st.--Visited several families in the neighborhood of Middleton and Carmel,
though it was a close trial of faith and patience;
some things being hard to utter in some families,
which I believed was required of me to say,
but unreserved obedience is always rewarded with sweet peace in the Lord`'s own time.

22nd.--Left Carmel and Middleton this morning for Salem, with an easy mind.
But the watchword is, rejoice with trembling.
Reached the house of our kind friends, William and Ruth Fisher, about noon,
where we have made our home.

24th.--Attended Salem Monthly Meeting, in which I had close things to utter,
for it appeared to me (though there was a small remnant of rightly
exercised souls in that meeting towards whom sympathy was felt,
and to whom encouragement was given), that there were wounds, bruises,
and putrefying sores,
that would have to be laid open and probed to the bottom
before soundness and a healthy state could be experienced.
"`He that covereth his sins shall not prosper:
but whoso confesseth and forsaketh them shall have mercy.`"
I referred to Achan, who hid in his tent the golden wedge, and Babylonish garment,
which had to be searched out, and the transgressor punished,
before Israel could get the victory over their enemies.
These meetings are very exercising both to mind and body, but the Lord has been my helper.
Oh, that I may serve Him with a perfect heart and a willing mind.

25th.--Attended New Garden Monthly Meeting, an exercising time.
I arose with this passage--"`Confidence in an unfaithful man in time of trouble,
is like a broken tooth, and a foot out of joint.`"
We know what effect a broken tooth sometimes has upon the whole body,
unfit for use itself,
and often preventing the sound members from rightly performing their office.
So that the whole body may, and often does,
suffer weakness and pain in consequence of a broken tooth.
So in Society and meeting capacity, one unfaithful member,
occupying a conspicuous station,
may cripple and prevent a meeting from journeying forward in the right way,
and bring weakness and trouble upon the whole, if suffered to remain in its position,
and diseased condition.
And none can be at a loss to understand how a foot out of joint also
prevents the whole body from moving forward as in a healthy condition.
How necessary that all endeavor to keep their proper ranks and places in the Church;
that all may be edified together, and become one another`'s helpers and joy in the Lord.

26th.--Attended Springfield Monthly Meeting.
Much vocal and mental exercise fell to my lot in this meeting.
The necessity of a more lively engagement on the part of all classes,
to be found pursuing the right path appears to me greatly
wanting amongst us in every department of society.
Oh, when will we put on strength in the name of the Lord? Not until obedience keeps
pace with knowledge--not until we make use of the help graciously offered,
being faithful in the little, shall we be made rulers over more,
and become strong in the Lord and in the power of his might.

27th.--Attended an appointed meeting at Sandy Spring, at ten o`'clock A. M.,
and was favored to relieve my mind therein towards the few assembled;
after which returned to Salem.

28th.--Attended Salem Meeting, which was large;
David Heston and Joseph Walton from Philadelphia being present,
on their way to Colorado to visit the miners in that district of country.
David had considerable to say, and Joseph had a short testimony.
My mind was deeply exercised in this meeting,
and I could not feel satisfied to be altogether silent.

29th.--Visited some families in and around the town of Salem.
Close and hard things to utter were required of me in some of these opportunities,
but faithfulness was followed by the reward of peace.
Oh, the exercise of my spirit none knoweth but the Lord;
and He alone can strengthen for the work whereunto He calleth,
and none has a right to say what doest thou? or why hast thou made me
thus? "`Shall the axe boast itself against him that heweth therewith?
Or shall the saw magnify itself against him that shaketh it?`"

30th.--I was not well able to make any visits, so remained at the house of our friends,
William and Ruth Fisher, until the next day.
Then attended Salem Particular Meeting once more,
and had close work and exercise therein,
but encouragement was handed forth to the little wrestling remnant,
and supplication offered to the Father of mercies on behalf of all classes,
that we might deepen in the root of life.
After this meeting, I felt ready to start home, and left Salem about noon the same day,
arriving at Bridgeport that evening.

Lodged that night at the house of my cousin, Willam W. Holloway,
who (though not a member amongst Friends) treated us kindly and courteously;
his wife and children also, were very kind and respectful.

Next morning, I spoke a few words in the way of religious counsel in the family,
which was well received by parents and children, and afforded peace to my mind.
Then set out for home, but for want of faithfulness on my way,
being required to speak a few words of exhortation to some men at the Inn where we dined,
I made work for repentance.
When will I learn obedience by the things that I suffer?

Eleventh Month 7th,
1877.--My heart is greatly distressed on account of the
situation of things amongst us in a Society capacity,
and in our own little meeting.
The world seems to be swallowing us up;
many absent themselves from our week-day meetings, attending to their temporal business,
indifferent respecting the welfare of the immortal part.
Help, O Lord! for vain is the help of man.

9th.--Today, followed to the grave the remains of my beloved cousin, Joseph Walker,
an elder and member of our little meeting at Flushing.
At the house of the deceased, I felt constrained to revive this language:
"`Why stand ye here all the day idle;`" following it with some exhortation,
and felt peaceful and easy afterwards.

Oh, where are those who are preparing to fill up the broken ranks--to take the places
of those who are being removed from works to rewards--who have been supporting the
principles and testimonies of our religious Society? Alas! alas!
I see not whence they are to come; but the Lord can raise them up;
into his hands we must commit all as unto a faithful Creator,
who will do all things well.

Twelfth Month 22nd.--Today, I enter the seventieth year of my age.
It is marvellous, indeed, that my days have been thus lengthened out.
May the few that I may yet have to spend in this state
of mutability be wholly devoted to the Lord.
O Lord, have mercy upon me,
and preserve me from the snares of the enemy of my soul`'s peace;
wash me from all the filth and defilements of the flesh,
whatever strokes it may take to accomplish this great and glorious work,
that of complete sanctification.
Oh, heavenly Father! in the riches of thy mercy administer the baptisms needed,
that I may not be surprised or disappointed in the end.
Amen, and amen.

First Month 16th,
1878--Oh Lord! be pleased to look down with an
eye of compassionate regard upon my nephew,
and cast him not off in his sins and transgressions.
Oh, visit him in judgments mingled with mercy, that he may not become a castaway.
Amen, and amen.

Tenth Month 18th.--I attended all the sittings of our late Yearly Meeting,
held at Stillwater, near Barnesville, in the new house erected for the purpose.
The public meetings were largely attended, both on First and Fourth days.
On First-day afternoon, many could not find seats in the house,
which caused that meeting to be a little more disturbed than
it would have been if all could have been comfortably seated.
But the morning meeting, and the meeting on Fourth-day, were very quiet,
the people behaving with much propriety;
and I felt it right to appear on First-day morning, and on Fourth-day,
in a short testimony.

Although I have generally been silent on such occasions, and esteemed it a favor,
yet I labored under deep exercise for the arising of life in these meetings,
and for keeping down strange fire;
that ministers might not warm themselves with sparks of their own kindling,
and thus apprehend themselves called upon to speak when the Lord had not commanded.
Such preaching can never profit the people, however eloquent the discourse,
or however befitting the occasion in the view of the natural man.
William Penn says of the ministry--"`Without the life, ever so little is too much;
but with the life, much is not too much.`"

Eleventh Month 14th.--Slept but little last night, and spent the time whilst awake,
under much exercise and conflict of mind.
It feels to me that we shall meet with great calamities yet before we are humbled,
and rightly and duly concerned to give that glory and honor to God,
which is his due from his creature man,
and which it is our interest as well as duty to render unto Him.

Fourth Month 27th, 1879.--Yesterday, attended the funeral of our beloved friend,
Isaac Mitchell.
It was large and solemn.
The company met at the meeting-house,
in accordance with a proposition made by this dear Friend in our Preparative Meeting,
believing as he did,
that by adopting this practice much confusion and exposure to heat and cold, etc.,
might be avoided,
which often occurs at the house of the deceased for
want of room for all to be comfortably seated.
Moreover, it prevents unnecessary conversation,
which is often painful to the rightly exercised on such occasions.

I had to revive this Scripture passage as being
applicable to the deceased--"`Mark the perfect man,
and behold the upright, for the end of that man is peace.`"
I also revived the language of the apostle--"`By the grace of God I am,
what I am.`" As this light,
grace and Truth is followed (which is the gift
of God through Jesus Christ to fallen man),
we shall be led out of darkness, and from under the yoke of sin and transgression.
It is by following this purchased gift of grace,
that we become crucified to the world and the world unto us.
"`I am crucified with Christ (saith the apostle),
nevertheless, I live; yet not I, but Christ liveth in me;
and the life which I now live in the flesh, I live by the faith of the Son of God,
who loved me,
and gave himself for me.`" As we submit to the crucifying power of the cross of Christ,
we shall know the putting off of the old man with his deeds,
and the putting on of the new man,
which after God is created in righteousness and true holiness,
and experience our robes washed and made white in the blood of the Lamb,
and be prepared to be owned of Christ before his Father and the holy angels,
when done with time here below, and to ascribe glory,
thanksgiving and high renown unto the Lord God and the Lamb forever and forever more.

29th.--Some very weighty considerations press upon my spirit
in regard to future engagements in a religious visit,
which has at times been before me for years past.
Oh, that I may be kept from taking a wrong step, either backward or forward.
Dare I trust that I shall be thus kept? Oh, heavenly Father,
rather prepare me for the closing moment and take me hence,
than suffer me to bring reproach upon thy name and Truth, now in my declining years,
by stepping forward or backward in the way thou wouldst not have me go. Amen, and amen.

Seventh Month 8th.--What shall I say, tossed, tried and tempted on every hand;
and yet a little hope remains, that my gracious Creator will not forsake me,
unworthy as I am of the least of his favors.
Oh, thou who stretched forth thy merciful hand to save Peter from the watery grave,
have mercy, I pray thee, upon me in this critical time; yes, in this very critical time.

27th.--I have great cause for thankfulness and encouragement.
The Lord hath condescended to settle my mind at present,
with respect to a very important subject,
which has been for months pressing heavily upon me;
and although I do not feel released from the concern,
yet the time for opening it to my friends did not
appear in the light of Truth to be fully come.
Though it had seemed to me for months past, that it might be very near,
and a great conflict of mind was often my portion,
that I might be rightly directed and strengthened to do the will of the Lord,
and now I can truly say in the language of the Psalmist--The Lord hath heard my prayer,
He hath put gladness in my heart; He hath stilled the tempest.
Surely, if the Lord had not helped me,
I had been swallowed up amidst the waves of affliction and distress.
Bless the Lord, oh my soul, and all that is within me bless his holy name.

Fifth Month 27th,
1880.--I find that ten months have passed away
since I made the last entry in this little book,
and now what can I say? Worm Jacob!
Had not the Lord been my help, my soul had almost dwelt in silence.
Great conflicts at times have been my portion,
yet the Lord hath kept me from sinking into the gulf of despair.

My well-beloved cousin, Joseph Branson, departed this life on the 16th of last month,
aged forty-three years, three months and sixteen days.
Oh, what an unexpected bereavement to his dear parents, to his relatives,
and to the Church.
Truly he was one who might be justly compared to the salt of the earth,
and the light of the world, as Christ said of his disciples.
Joseph`'s example shone brightly in the midst of a crooked and perverse generation,
and no one could have just occasion to upbraid him,
or find fault with his example or precept--"`Mark the perfect man and behold the upright,
for the end of that man is peace.`"

First Month 6th, 1881.--I thought it might be allowable to record something further,
relative to my dear departed cousin, in connection with my own experience.
A few weeks before his departure, whilst I was sitting by his bedside,
he referred to his exercises on behalf of others
and of some religious opportunities in his room,
in which he had to use great plainness of speech towards those present.
I expressed my thankfulness that he was called upon,
and qualified to do something for the cause of Truth, in the way of counsel, etc.
That my own way was shut up in regard to the ministry,
that I thought I had no place with the people in this way in our little meeting.
Joseph quickly replied, "`I do not think so:
there is no one who has the least conception of thy secret,
silent exercises and conflicts of mind; repeating it twice, not the least conception;
but it will not be always thus with thee.`"

After his death, the dispensation under which I had been passing,
that of great conflict of mind and desertion, was changed,
and at his funeral my heart was lifted up in praise and thanksgiving unto the Lord,
for having released from the shackles of mortality his purified spirit,
and translated it into that holy and glorious city which
needeth not the light of the sun or moon to shine in it,
for the Lord God and the Lamb are the light thereof.
For several days after this,
praise and thanksgiving were the constant attendants of my mind;
and I seemed permitted to rejoice with the spirit of my departed cousin,
which words could not fully set forth.
Truly, times and seasons are in the hands of the Lord,
and such joyful emotions as I experienced on that
memorable occasion was as the meat of forty days.

Seventh Month 25th.--Several weeks ago I fell and injured the elbow-joint of my right arm.
Soon after, it commenced swelling and inflaming, and in a few days the whole arm,
from the shoulder to the ends of my fingers, became so swollen, inflamed and discolored,
as seriously to threaten my life.
But He who is justly termed the Controller of events,
saw meet to bless the endeavors for my relief,
and I am now able to use my arm and hand considerably, which to me, is marvellous,
considering the aspect it presented some weeks ago.
Truly it may be asked,
"`Is anything too hard for the Almighty?`" I have looked upon this dispensation,
and considered it administered in mercy,
to draw my mind into greater watchfulness and circumspection in regard to my thoughts,
words and deeds, and to remind me that at such a time,
as I think not the Son of man cometh.
Oh, that I may be ready to render up my accounts with joy,
whether the summons be sudden or otherwise.

Twelfth Month 17th.--If I live till the 22nd of this
month I shall have attained the age of seventy-three,
and I feel like adopting the language of my dear father a few months before his death,
viz: "`I am now nearly seventy-three years of age,
and what have I done to promote the great cause of
Truth and righteousness in the earth? Alas! but little,
although from my youth I have loved the Truth--yes, as early as my twelfth year,
the Lord was pleased to show me the beauty of holiness.
At that age I was left almost without human help to aid
or instruct me in the way of life and peace,
yet He that sticks closer than a brother, has never forsaken me. Blessed be his name.`"

I cannot say that I was left destitute of instrumental
help and instruction in my childhood and youth,
for I had godly parents,
whose concern was to train me up in the nurture and admonition of the Lord.
I return to my father`'s expression, viz: "`But when I remember my shortcomings,
I am afraid they will overbalance all.
Oh, what a fearful thing when weighed in the balance and found wanting;
I have nothing to depend upon but the Lord`'s mercy; teach me, Oh Lord,
to pray as thou taught thy disciples formerly.`"

In the closing up of the record of my dear father, taken from his diary,
after supplicating on his own behalf, and on the behalf of his children unitedly,
he thus writes, "`Oh, Lord, remember the afflicted daughter whom thou hast raised up,
as it were, from the dead, to proclaim thy gospel to the children of men.
Now, in her bodily affliction,
continue to support her mind under every proving dispensation,
that she may sing thy praise on the banks of deliverance.`"
O how precious to have been thus remembered
before the Throne of Grace by that godly parent;
and what cause for unspeakable gratitude to the Father of mercies,
that during the lapse of thirty-five years which have passed away since that prayer
on my behalf was recorded,`" in all my sins of omission and commission--in all the
heights and depths through which I have been permitted to pass,
the Lord hath not forsaken me, as I humbly hope and trust,
but still continues to extend mercy towards me;
and I earnestly crave to be ready for the summons of death,
and can again adopt the language of my departed parent,
written about two months before his decease, viz: "`Oh,
that my sun may set without a cloud!
Lord, if there be any wicked way in me do thou it away,
cleanse thou me from secret faults.
O Lord, remember mercy in judgment.
Thou canst, if thou wilt, make me clean.`"

Same date.--Our last Yearly Meeting was a time of much exercise to my mind,
and to many other Friends, old and young;
a great flow of words in the line of the ministry was witnessed amongst us,
though no strangers with minutes from other places were present.
Oh that we could learn what this meaneth: "`Be still and know that I am God.`"

I felt it required of me at the last sitting to visit men`'s meeting,
and having the full approbation of men and women Friends, I did,
and endeavored to relieve my mind.
I told Friends I feared we were losing ground in regard
to our testimony on the subject of silent worship.
That whenever we begin to conclude that we could not have a good meeting
without the intervention of words (no matter how large the company,
or who was present) we were getting upon anti-Christian and
anti-Quaker ground--that I had been grieved and distressed,
under the belief that we were becoming more and more superficial in our worship, etc.,
and much more to the same import, after which I felt much relieved.

Twelfth Month 22nd.--Today I enter the seventy-fourth year of my age.
How solemn the consideration, that I stand, as it were, on the very threshold of eternity.
Be pleased, Oh Lord, to enable me to watch and pray continually,
that I may spend the few remaining days or hours allotted me here below,
in the way that would be well pleasing in thy sight.
