== Chapter XII

[.chapter-synopsis]
* Exercises of the Yearly Meeting`'s Committee Relative to Impending Duty Towards Small Bodies of Friends Who Have Lately Withdrawn from Some of the Progressive Bodies, in a Testimony Against Their Unsoundness
* Considerations Also Included Touching Correspondence with the Smaller Body in New England
* A Religious Visit to the Meetings Constituting Ohio Yearly Meeting, Extending to Iowa And Kansas
* Death of Her Cousin, Elizabeth Smith
* Visited Her Aged Friend, Hannah Warrington, Of Moorestown, N. J.
* And Attended Some Meetings in that Vicinity
* Death of Her Brother-In-Law, Jesse Roberts, and Her Commendation of His Christian Virtues
* Attended the Orthodox Canada Yearly Meeting, and Visited Some of its Branches
* Death of Her Nephew, Benjamin Branson
* Death of Martha A. Wilson
* Death of Stephen Hobson
* A Religious Visit to the Orthodox Western Yearly Meeting
* A Tedious Illness

Fifth Month 31st,
1882.--The Committee appointed at our last Yearly Meeting to
take into consideration the situation of the scattered
remnants of Friends and what our present duty is,
as a Yearly Meeting in relation to those remnants,
and report the result of our deliberations to next Yearly Meeting, met at Stillwater,
and entered into a pretty full and free interchange of sentiment on the subject;
but were not able to unite upon any proposition to lay before the Yearly Meeting;
and adjourned to meet on Sixth-day preceding our next Yearly Meeting at three o`'clock p.m.
During our deliberations, I ventured to express in this committee my belief,
that our Yearly Meeting ought to place on its records a Minute,
stating that we as a Yearly Meeting had grievously erred in not having, many years ago,
recognized officially the Smaller Body (so called) of New England,
as the legitimate Yearly Meeting.
That I believed it was human policy, and a fearful cringing spirit,
that prevented us from doing our duty towards these Friends.
And now, after a lapse of thirty-six years, they having become very much reduced,
and somewhat scattered, no doubt in a great measure,
owing to the indifferent treatment they have received from
their brethren of Ohio and Philadelphia Yearly Meetings,
some want to send a committee to see if they are in a
condition to be acknowledged as a Yearly Meeting.
With respect to the few Friends who separated from Baltimore Yearly Meeting, in 1854,
because they could not for conscience`' sake own the Binns`' Yearly Meeting of Ohio,
Ohio Yearly Meeting turned its back on these Friends because Philadelphia Yearly
Meeting had previously done so. And thus another grievous error was committed,
and my judgment is and has been,
that we ought to humble ourselves so as to place upon our
records a Minute certifying our mistake in both these cases.
But we have yet to be tried and proven for our conduct
towards our faithful brethren and sisters,
as Joseph`'s brethren were tried and proven,
until they bowed and humbled themselves in the sight of God and man.
The Lord will not suffer sin to go unrequited,
and we will have to become humbled before we can prosper in the Truth,
and receive that supply of spiritual bread,
which is greatly lacking and needed amongst us.

Tenth Month 2nd.--Our Yearly Meeting closed last week.
I attended all the sittings, having been previously very ill for several weeks.
It seemed almost a miracle that I was enabled to do so. I had some service in vocal,
as well as in silent exercise in the meetings for worship and discipline.
In the public meeting on Fourth-day,
the language of the Apostle Paul in reference to his own ministry,
and that of his fellow apostles,
was brought before me in a way that I thought called for public expression,
to which I gave utterance: "`We preach not ourselves, but Christ Jesus the Lord;
and ourselves your servants for Jesus`' sake.`"
And again, in reference to the gospel which he preached, he said,
"`I neither received it of man, neither was I taught it,
but by the revelation of Jesus Christ.`"
Hence the true spring and ground of gospel ministry is that of being called unto,
and qualified therefor, by Christ Jesus, our Lord,
knowing Him to put forth and go before, to be mouth and wisdom, tongue and utterance.
All ministry without this Divine unction is nothing
better than sounding brass or a tinkling cymbal,
words without life, sound without substance, etc.
I exhorted the people to turn inward to the teachings
of the Holy Spirit in the temple of the heart;
as this is obeyed and followed we shall experience our spirits refreshed and
strengthened by the life-giving presence of Him who is the minister of the
sanctuary and true tabernacle which God hath pitched,
and not man.

Twelfth Month 22nd.--Today, I enter the seventy-fifth year of my age.
How solemn the consideration that my life has been thus lengthened out.
Oh, that I may be prepared with oil in my vessel for the midnight cry:
this is my chief and daily concern.

29th.--Hear my prayer, oh Lord, and incline thine ear unto my cry.
Save me from mine enemies and let them not have dominion over
me. I look for help from no other source but from thee.
Oh, pardon all my sins and pass by my transgressions, surely I am in great need and want,
wilt thou not be pleased to succor me, and help me;
blot out my transgressions from thy book of remembrance for Jesus Christ`'s sake.
Amen, and amen.

First Month 9th, 1883.--My soul is distressed,
what shall I do? I can do nothing but ask for mercy and help from thee, oh,
thou fountain and source of all true consolation.

Third Month 20th.--About the twenty-fourth year of my age,
it pleased my heavenly Father to open my understanding,
and give me a sight and sense of the fallen and degenerate condition of man by nature.
I then clearly saw that when Adam ate of the
forbidden fruit spiritual death came upon him,
according to the word of the Lord, viz:
"`In the day thou eatest thereof thou shalt surely die.`"
I saw that by this act of disobedience he lost the Divine image,
that state of purity and holiness in which he was created,
not in part only but wholly and entirely.
That he had no spiritual light or life, no sight or sense of anything good,
and consequently no power, capacity or inclination to do any good thing,
and in this state of death and darkness he must have remained,
shut out from the presence and favor of his Creator forever,
had not infinite Goodness sought him out and extended a
new visitation of light and life to his soul:
thus opening the door for his escape from this state of death and darkness,
and from all sin and transgression,
and this door I saw to be Christ Jesus the Lamb
slain from the foundation of the world in man.

Then understood I what this Scripture meaneth--"`For, as in Adam all die,
even so in Christ shall all be made alive;`" and my heart was greatly
humbled in and under the sight and sense then given me of the mercy
of God through Christ Jesus towards his creature man,
and I felt this mercy to be unspeakably great.

Fifth Month 18th.--Having obtained liberty from the Monthly and Quarterly
Meetings to pay a religious visit to the meetings of Ohio Yearly Meeting,
and to appoint some meetings amongst those not in membership with us,
my prospect is to start for Iowa on the 22nd inst.
If it were not for a grain of faith I should faint under the prospect,
but trust the Lord will keep me in the hollow of his holy hand,
and preserve me from stumbling.
Amen.

Ninth Month 26th.--On the 8th of last month,
I and the Friends accompanying me returned home from the west,
where we spent eleven weeks visiting Friends in Iowa and Kansas,
as Truth appeared to open the way;
and when this pointed homeward with sufficient clearness we hesitated not to return,
and did so in the enjoyment of health and peace of mind.

But what shall I now say of the mercy and goodness of God to usward in this
weighty and very important engagement? It is wonderful to reflect upon,
and to know the extension thereof manifested to a poor worm of the dust as I feel
myself to be. When my physical and mental powers seemed ready to fail me,
then, oh Lord my God,
thou didst indeed give me to see and to feel
that nothing is too hard for thee to perform.

Tenth Month 30th.--Oh, that my head were waters, and mine eyes a fountain of tears,
that I might weep day and night, not only for my own shortcomings and dwarfish state,
but for that of my people also!
Oh, the shakings and siftings that yet await us!
Who will be able to stand?

During my late visit in the West,
I had to tell Friends in some places that the shakings and siftings were not over.
At Quakerville, Kansas,
I was led in their Monthly Meeting to bring into
view the situation of the remnant of Jews,
who were left in the land when the great majority were carried into Babylon.
There was a gathering to this little remnant,
and they were encouraged to faithfulness that
the blessing of the Lord might rest upon them.
But their faith and allegiance was to be proven.
Ishmael got among them and slew Gedaliah and others of their chief men.
Then came the trial of their faith--they were in great consternation and
fear on account of this unexpected event and purposed to return into Egypt,
and though they were warned by the prophet Jeremiah to remain where they
were and assured that the blessing of the Lord would rest upon them,
yet they would not hearken unto him,
though they had entreated him to ask counsel of the Lord for them in this matter; and lo,
the scattering, confusion, weakness and wickedness that followed, etc.

I said there was still a remnant amongst the Society of Friends,
who have escaped Hicksism and Gurneyism, who, if faithful unto the Lord,
would be blessed, and be able to lift up the standard of primitive christianity,
as did our early Friends, and others would rally thereto;
but there were those who might be compared to Gedaliah and his men,
who were conspicuous amongst this remnant, and it seemed to me,
there were those present of this class,
who were in great danger of being slain by Ishmael, the son of the bond woman,
which is not to be heir with the son of the free woman.
When the first and fallen nature is given way to and
gets the uppermost room in the heart and keeps it,
then such as give way thereto lose their spiritual lives,
and become stumbling-blocks instead of way-marks.
But even when such events occur,
there is still hope for those who keep the eye to the Lord, and as He preserved Noah,
Daniel and Job amidst peculiar trials,
so will He preserve all those who put their trust in Him,
no matter what conflicts and trials may be permitted to come upon them.
So I encouraged Friends to keep the eye single to the Head of the Church,
that they might be able to stand when tried and proven as to a hair`'s breadth.

At Emporia and other places I had to warn Friends to stand
fast to the principles and testimonies of the Society,
when the Gedaliahs were slain for the want of
watchfulness and keeping under the power of Truth.
O treacherous self, if it be not slain,
how it will work the downfall of its possessors before they
are aware fully of the danger they are in. This visit to the
West was marked with many close trials and deep provings,
but I was often bound to acknowledge with the
Psalmist--"`Great and marvellous are thy works,
Lord God Almighty, just and true are all thy ways, thou King of saints.`"

Twelfth Month 22nd.--Today, I enter the seventy-sixth year of my age.
O Lord! thou only knowest for what purpose I am thus
permitted to continue in this state of probation;
purify and search me, oh Lord, and if there be any wicked way in me, do thou it away.

My dear brother Samuel and wife are now on a visit to
their relatives and Friends in this neighborhood.
Great are, and have been, my desires for this dear brother,
that the Lord would bring him to heartfelt sorrow and
repentance before he is taken out of this world.
Oh, heavenly Father,
be graciously pleased for thy mercy`'s sake to humble and contrite his heart before thee,
that his sins may all go beforehand to judgment,
and that he may be ready when thou callest him hence, to join the heavenly host,
in ascribing glory, honor,
thanksgiving and high renown unto thee and the Son of thy love forever.
Amen.

Same date.--I have been reading the Memoir of Thomas Kite.
How sweetly he passed out of this world.
I remember this dear Friend when he attended Ohio Yearly Meeting in 1836.
It was about the time of the apostasy of Elisha Bates,
and many hearts among the young, as well as those more advanced in years,
were greatly affected by this unexpected and mournful event.
Thomas Kite, during the Yearly Meeting, visited women`'s meeting,
and had a powerful and weighty testimony, calculated to soothe and comfort our hearts,
and to awaken us to a sight and sense of the indispensable
necessity of keeping the eye to the Master,
instead of the servant, in order for our establishment and settlement in the Truth.

He set forth in a very clear and impressive manner, the fallen,
dead and degenerate state of man by nature, and that nothing but keeping to the light,
grace and Truth in the heart, can preserve him one moment from sin and transgression,
no matter how highly he may have been favored as a gospel minister,
and that all his natural endowments and literary attainments must
become subservient to the law of the spirit of life in Christ Jesus,
if he be a true minister of the gospel.
This and much more of like import,
showing upon whom the dependence of ministers and hearers must be,
in order to maintain the unity of the spirit in the bond of peace,
fell from the lips of Thomas Kite at that time,
and made an impression on my youthful heart never to be erased;
so that I have often felt the tribute of gratitude to
arise to the Giver of every good and perfect gift,
when I have thought of this man, though I never had the privilege of speaking to him.

Ninth Month 13th,
1884.--I returned a few weeks since from a visit
to the meetings of Salem Quarterly Meeting,
having previously visited the meetings within the
limits of Stillwater and Pennsville Quarters.
During my visit to these meetings I had many religious opportunities in families,
and with individuals, and the Lord was graciously pleased to be with me,
often to my admiration; showing me from day to day my stepping-stones,
and strengthening me in mind and body to perform that which I believed to be required.
Blessed be his name.

Many and deep were the baptisms through which I was permitted to pass for my own sake,
and for that of others;
but as I kept to that grain of living faith mercifully vouchsafed,
I was enabled to pass along wearing the sackcloth inwardly,
and not appearing unto men to fast.
I sat three meetings in silence at Salem,
except a few words in their Monthly Meeting to one of the answers to the Queries.
But in the Quarterly Meeting I had considerable service.
The public meeting was very large,
and I believed it right to quote from the ninth chapter of Jeremiah, the 17th, 18th,
19th and 22nd verses.
I said the last verse quoted was remarkably verified during the late civil war,
and yet as a nation we are not humbled; we are proud, haughty and aspiring;
professing Christians are not humbled.
We are called to humble ourselves as in dust and ashes before the Lord,
that our spiritual life may be given us for a prey.
This and more on this wise,
I had to proclaim amongst them before the shutters were closed.

On First-day after Quarterly Meeting, again attended Salem Meeting,
and my mouth was opened amongst them.
I had to refer to the apostle`'s declaration to some who professed the Christian religion,
but did not walk answerable to their profession,
which called forth this striking language--"`The name
of God is blasphemed among the Gentiles through you.`"
In this day, when infidelity is increasing to such an alarming extent,
those who are professing the Christian religion have special
need to examine whether they are walking consistent with their
profession or casting stumbling blocks in the way of others,
giving occasion for the Truth as it is in Jesus to be evil spoken of.
Practical Christianity appears to me to be at a very low ebb in many places,
and I verily believe it might be said in this day,
that the name of Christ is blasphemed through the ungodly life
and disorderly walking of many highly professing Christians.
Very deep and painful were my exercises at Salem, as well as at other places,
in consideration of the state of things amongst us as a people,
and the state of Christianity in general.

"`Let not the wise man glory in his wisdom,
neither let the mighty man glory in his might, let not the rich man glory in his riches;
but let him that glorieth, glory in this, that he understandeth and knoweth me,
that I am the Lord, which exercise lovingkindness,
judgment and righteousness in the earth; for in these things I delight, saith the Lord.`"

Tenth Month 19th.--Attended the funeral of my beloved cousin, Elizabeth Smith,
relict of the late Samuel Smith.
She was in the ninety-second year of her age.
Her religious sensibility outlived the loss of almost every natural faculty of the mind.
She had been a practical Christian from her youth,
and the Lord was pleased to manifest his lovingkindness and
tender mercies towards her in the decline of life;
when her children and her friends had become strangers to her,
giving her strength of mind and body to praise his Holy
Name in the midst of affliction and privations.
She often repeated these lines--

[verse]
____
Thy name, oh God, be blessed,
Thy goodness be adored.
My soul has been distressed,
But thou hast peace restored.
____

Fifth Month 2nd, 1885.--Low in mind on various accounts,
but more especially on account of the backslidden state of our religious Society,
and the apathy of mind that appears to prevail with many relative to our situation.
The winter just past has been one of much bodily suffering, weakness and debility;
and strong cries and earnest petitions to our Father in heaven,
have been raised in my heart,
for faith and patience to endure what He saw meet to dispense;
and I think I feel humbly thankful for the relief recently witnessed from severe pain.
May my lamp be supplied with oil when the midnight cry is heard.
This is my greatest desire for myself and for others.

Sixth Month 8th.--Last night, after retiring to bed,
my mind became absorbed in thought and meditation,
relative to my own spiritual condition and the state, as it appears to me,
of our poor backslidden Society.
Oh, how benumbed and destitute of spiritual life we seem to
be. Whilst mourning on account of this condition,
a desire was begotten in my heart, yes, I might say, a fervent prayer,
that the Lord Jesus might sit as a refiner with fire, and as a fuller with soap,
in the temple of my heart,
and purge out everything that adds to this benumbed and lifeless condition,
that a ray of Divine light and life might again be experienced.
It then came into my heart to read the fourth Psalm,
which might throw some light upon my disconsolate condition; and had it been suitable,
I would have arisen from my bed and perused it, having no idea what it contained.
But on reading it this morning, my spirit was somewhat strengthened,
and encouraged by a revival of hope, that I might see brighter and better days.

I can truly say,
that the Lord hath heard my prayers and delivered me out of many
distresses and temptations in days and years that are past;
and shall I distrust his mercy and his power now in old age?
Oh no! let me never cast away my confidence in thee,
oh, my God, though unworthy of the very least of thy mercies.

Seventh Month 2nd.--I feel it a great favor to be relieved from severe pain,
with which I have been suffering for several days past.
Oh, for a grateful heart for this and all other blessings.
Previous to this attack of neuralgia, I spent some days at Guernsey,
especially on account of my dear cousin, Maria Cope, who is suffering with a cancer,
and no hope of relief only through death, or at least it appears so.

Eighth Month 22nd.--I have recently made a visit to my aged and well beloved friend,
Hannah Warrington, of Moorestown, N. J. To me it was a very precious visit.
Although I had repeatedly heard, that her intellectual faculties remained very bright,
and her spiritual vision clear and unclouded,
at the advanced age to which she had attained,
being now in the ninety-third year of her age,
yet I could not have fully understood the reality had I not visited her, so late in life.

Her memory of past and present events, and her capacity for embracing,
and conversing upon subjects of deep interest both to old and young,
and the ease and freedom with which she draws from the Treasury with
which she is entrusted by our divine Lord and Lawgiver,
things both new and old, to interest and instruct her fellow pilgrims,
is indeed wonderful.
Her voice is clear and pleasant, her articulation distinct,
and the whole mind apparently as strong and vigorous as in meridian age,
at least it appeared so to me and others who had the
privilege of being with her in our late visit.
She has long been a scholar in the school of Christ, and her storehouse of valuables,
derived from that source is extensive, and her ability to impart instruction to others,
great.
"`Blessed is the man that trusteth in the Lord, and whose hope the Lord is;
for he shall be as a tree planted by the waters,
and that spreadeth out her roots by the river, and shall not see when heat cometh,
but her leaf shall be green: and shall not be careful in the year of drought,
neither shall cease from yielding fruit.`"

Whilst on this visit I attended three meetings at Moorestown.
In their week-day meeting, the first I attended,
I felt it required of me to revive this Scripture--"`Oh earth, earth, earth,
hear the word of the Lord.`"
I said that I had greatly desired to be preserved from arraigning any one for accusation,
or condemnation, but felt that some present had need to consider the many warnings,
calls, and invitations given them to become loosened from the things of the world,
and to have their hearts and affections set on things above,
not knowing the day nor the hour when the summons of death would come;
some of these had felt the necessity of becoming extricated from the love of the world,
but had not yielded obedience to what they knew to be required,
and the call was still extended, "`Oh, earth, earth, earth, hear the word of the Lord.`"
My communication was short, but yielded peace.

I also attended Moorestown Meeting on the First-day following.
On Seventh-day evening, previous to this meeting, an elder called to see me,
and in the presence of several others, said to me,
that he hoped if I had anything for the young
people I would be faithful and let them have it,
that they were not as willing to take up the cross as would be desirable,
and he sometimes feared their older Friends had not patience enough with them, etc.
I was surprised, but held my peace: I thought,
if he wanted to close up my way in that meeting amongst old and young,
that he could not have taken more efficient measures to do so;
but I do not suppose that was his intention,
yet I concluded that he surely lacked that discretion which
should characterize the movements of a wise and discreet elder,
at least in the present case,
I being a stranger to nearly every young person in that meeting, and they to me;
it was surely premature for any one to tell me what,
or propose what I should say to them.

When meeting-time came, I was weighed down with exercise,
but was favored to keep my head above the waves.
At ten o`'clock the meeting assembled, and was quite a large gathering.
Soon after the meeting settled into silence my mind became
impressed with this language of the prophet Isaiah,
which I afterwards quoted: "`There shall be upon every high mountain,
and upon every high hill, rivers and streams of waters in the day of the great slaughter,
when the towers fall.
Moreover, the light of the moon shall be as the light of the sun,
and the light of the sun shall be as seven fold, as the light of seven days,
in the day that the Lord bindeth up the breach of his people,
and healeth the stroke of their wound.`"
I said there were those who often desired to feel more of the incomes
of Divine love and consolation flowing through their hearts,
such as they believed the true Christian, the humble followers of Christ experienced,
and in order to realize this, they must know the towers to fall, the first Adam slain,
which is of the earth, earthy;
all that opposes the coming and setting up of the Redeemer`'s kingdom in the heart,
brought down, and rooted out, and the mountain of the Lord`'s house,
established in the top of the mountains, and exalted above the hills;
that of having everything removed which prevents the
circulation of Divine life in the temple of the heart,
is a great and glorious work;
but indispensably requisite in order that we may
realize the fulfillment of this beautiful,
figurative language of the prophet.

On Third-day following, the Monthly Meeting of Chester, held at Moorestown, occurred,
which I attended, and had some close work amongst them.
I then felt my mind drawn out towards the young and youngish members present,
encouraging them to unreserved dedication to the will of the Lord--to keep
their eyes single to Him and they would be preserved from stumbling at the
stumbling-blocks cast in their way--they had many counsellors,
but few fathers and mothers--those who like Caleb and Joshua, wholly follow the Lord.
There were those present in the station of counsellors
who had never known the high places taken away.

Third Month 23rd, 1886.--On the 22nd of First Month last, my beloved brother,
Isaiah Branson, departed this life, aged eighty-seven years,
lacking one month and three days.
His physicians say that he died without any organic disease;
as ripe fruit drops from the tree in autumn.
He was attacked with slight spasms occasioned by
stagnation of the blood at the base of the brain.
He retained his mental faculties admirably,
and his children represent his end to have been very sweet and peaceful;
and I humbly trust, that through the mercy of God in Christ Jesus,
he is amongst the ransomed and redeemed of the Lord.

On the 16th inst., I attended the funeral of my brother-in-law, Jesse Roberts,
who died of pneumonia, after one week`'s illness, in the eighty-seventh year of his age.
He was sensible during his illness, and fully resigned to the will of the Lord;
appearing to have no prospect, nor any wish to recover.
He was a man of sound, discreet judgment,
whose long life was one of practical Christianity,
and this testimony concerning him was publicly borne at his funeral,
to which many no doubt set their seals.
"`Blessed are the dead, that die in the Lord, yea, saith the Spirit,
that they may rest from their labors and their works do follow them.`"

Fifth Month 31st.--I left home with the unity of the Monthly and Quarterly Meetings,
to make a religious visit to the Meetings of Canada Yearly Meeting, held at Pickering,
and was accompanied by my kind friends and relatives, Jacob Holloway and Abigail Sears.
We visited most of the meetings, and attended the Yearly Meeting also.
Although I had liberty to appoint meetings amongst those not in membership with Friends,
yet after getting into that province I felt that my
mission there was to be especially confined to Friends,
and this language was again and again revived:
"`Into any of the cities of the Samaritans enter ye not;
but go rather to the lost sheep of the house of Israel;`"
and when appointing meetings amongst Friends,
I felt no liberty to extend the invitation to others.
My business appeared to be to encourage Friends to build over against their own houses,
and thus to raise a practical standard in support of primitive Christianity.
All classes were invited to labor for the restoration of the waste places of our Zion,
that the Lord might again beautify his sanctuary and
make the place of his feet glorious amongst this people,
as in the rise of the Society.

Whilst out on this visit I kept no notes, not being able to write, having a hard cough,
and being quite feeble most of the time.
But I think it right to say, that the Shepherd of Israel was very near,
and kept my head above the waves and billows, which often threatened to overwhelm.
And I can say, as at other times,
"`Is anything too hard for the Lord God to perform? Trust in Him, Oh my soul,
in heights and in depths, for his mercy endureth forever.`"

I was favored to return from this visit with a peaceful mind,
having been absent from home just twenty-nine days.
On reaching home I found my beloved nephew, Benjamin Branson,
very low with pulmonary consumption,
and I had the satisfaction of spending a few days with him before his death,
and to witness his peaceful and quiet resignation to the will of the Lord;
and to hear him express,
that he felt no burden or condemnation resting upon him at that solemn hour,
and my own feelings being very comfortable
concerning his preparation for the final change,
for this favor I was made truly thankful.

Eighth Month 22nd.--I have been at home several weeks,
and no way has yet opened for the further accomplishment of the visit,
for which I was liberated in the Fifth Month last,
having had a severe turn of illness since my return from Canada.
I am still feeble, yet if the way opened for going West,
as my prospect included the meetings of the Western Yearly Meeting,
I should not hesitate on account of my health.
I desire to keep my eye single to the Head of the Church,
that I may not miss the right time for moving forward in this important embassy.

Tenth Month 11th.--I attended our late Yearly Meeting under much bodily weakness.
No way as yet opens for the prosecution of my Western visit; Oh,
that I may be kept in the true faith and patience,
not going before nor lagging behind my true Guide.

Eleventh Month 5th.--Since Yearly Meeting I have
attended the funeral of two of my relatives,
both in meridian age, and have cause to believe that they are both safely landed;
why should we weep for such? I feel more like rejoicing than weeping.
The conflicts of earth with them are over,
and that joy which is unspeakable and full of glory, inherited.
One of those removed was my beloved cousin, Martha A. Wilson;
her life was that of a practical Christian, and her death a triumphant one.
"`Weep not for me,
but weep for yourselves and your children,`" was the
language I felt it right to quote at her funeral,
with some accompanying remarks.
The other individual was one who had much to overcome,
and had overcome much by attending to the witness for Truth in her heart,
and though sin abounded, grace did much more abound,
and she was made more than conqueror over the enemies of her
own household through the mercy of God in Christ Jesus.
May none despair of that help which is richly in store for us,
whilst the day of mercy lasts, and will, if we lay hold of it,
redeem us from all that stands in our way of acceptance with the Beloved of souls.

24th.--I was much exercised in meeting today.
Some passages of Scripture and some considerations in regard
to true and acceptable worship pressed weightily upon my mind,
but my secret petition was, that I might be preserved from speaking a word unbidden,
and as I kept my eye to the Master,
I did not feel the command to hand forth anything to those present,
though several were at meeting who were not members,
and perhaps some who never attended a Friends`' Meeting before.
But I felt thankful that I was favored to keep under my
exercise without stepping forward unbidden in the ministry.
Oh what a close watch it takes neither to go before, nor lag behind the True Guide.

First Month 22nd, 1887.--This has been a very mild and beautiful winter day,
62° above zero; I walked out on the ground; my health this winter thus far very poor;
heart disease often threatening me with a sudden termination of my earthly pilgrimage;
but my greatest desire is to be ready for the final summons.

Third Month 14th.--The winter just passed has been mild
and open compared with the two preceding ones.
My health throughout has been very poor, great bodily weakness and at times severe pain,
has been my experience; this accompanied with a feeling of great poverty of spirit,
has been a trial of faith and patience, but doubtless dispensed for my good.
Never did my weakness and unworthiness stare me in the face
more continually and impressively than for some months past,
yet the ability has been afforded to intercede for mercy,
which is certainly a great favor; yes, by day and by night has this petition been raised.
Have mercy, Oh Lord, upon me, and prepare me for the final reckoning,
that I may not be cast off on the left hand.

On the evening of the 12th inst.,
this language was impressively and sweetly brought to remembrance: "`Trust in the Lord,
wait patiently for Him, and he shall strengthen thine heart; yea, I say,
trust in the Lord.`"

On the 13th attended our meeting,
and had to encourage those present to keep an ear open
to hear what the Spirit saith unto the churches,
that a true sense of their spiritual condition might be given them,
and the things few or many standing in their way of acceptance with the Lord removed,
that the candlestick might not be removed out of its place, or to this effect.
This short testimony afforded peace,
and I spent the afternoon quietly and comfortably in mind, yet quite weak in body.

Sixth Month 16th.--Since my last entry I have passed
through much bodily suffering and weakness;
but through all, the sustaining arm of the Lord hath been underneath,
and I have had at times to proclaim his goodness
and mercy in the assemblies of the people,
in religious meetings, and at funerals, etc.
Oh, the unworthiness and incompetency I feel for such engagements,
but obedience to his call and commandments has brought peace and quietness.

Seventh Month 20th.--Attended the funeral of Stephen Hobson,
a friend and merchant residing in our town.
He was the son of a worthy elder, to whom I was much attached.
I visited him a few days before his death, and was led to supplicate at his bedside,
that his affliction might be sanctified to him and to his family and friends,
and that the vital spark might not become extinct before a
preparation for the solemn change was experienced.
I told him we had a merciful High Priest,
and I believed if he kept his eye single he would be
enabled to do all the Lord required of him.
He twice expressed that he was glad I came, and soon after appeared near his end.

He had much to say by way of counsel and exhortation to his family,
and afterwards thanked the Lord that he had been
favored and strengthened to relieve his mind,
expressing also that he was favored with an evidence of acceptance.
The funeral was very large,
and I had to call upon those present to be in
earnest to make their calling and election sure,
setting forth the necessity of yielding obedience to
the Holy Spirit in the temple of our hearts,
in order that we might be such as the Lord Jesus
would own before his Father and the holy angels.
Great bodily weakness attends me,
but when the word of command is given to step forth in
the service of my Divine Lord and Master,
I dare not shrink or give back.

Tenth Month 6th.--At our last Monthly Meeting I returned the Minute granted me more
than a year ago for religious service in the limits of Western Yearly Meeting,
having visited nearly all the meetings composing it,
and attended the Yearly Meeting held last month;
and I may acknowledge the Lord was with me,
and strengthened me in body and mind to perform the service required, in a good degree,
to the relief of my mind,
yet many bitter cups were dispensed in view of the degeneracy from
primitive simplicity still apparent amongst us as a religious society.
Oh the mixture there, and elsewhere, with the spirit of the world.
I had to tell Friends that the shaking and sifting which has
been going on for years in our religious Society was not over.
An uncompromising spirit was called for by the Head of the Church on the part of Friends,
in support of the principles and testimonies, given us to bear,
and we would be sifted and tried until we become more and more
the people we profess to be. A very plain testimony was given
me to bear in the meeting of ministers and elders,
in relation to the ministry and the necessity of
knowing all our springs to be in the Lord.
I told them that I had been pained with some long communications in
testimony and supplication which I had witnessed since being amongst them.
I quoted William Penn`'s language, viz: "`I am concerned above all for public brethren.`"
And again in reference to the ministry, he says,
"`Ever so little without the life is too much; but much is not too much with the life.`"
I exhorted elders to get down deep where they
could discern what was of and from the Lord,
and what was not, that they might know what to encourage, and what to discourage.

Eleventh Month 30th.--I am confined at home by bodily indisposition,
while the rest of the family are at meeting.
It looks as if my time for attending meeting was nearly over.
Oh that I may be prepared for the solemn summons,
whenever and in whatever way it may come; this is my hourly concern.
I have suffered much during the past week,
and have felt fearful lest I should lose my rational
faculties in consequence of this severe pain in my head,
but I do earnestly crave that I may be favored to retain my senses,
whatever I may have to suffer.

Twelfth Month 22nd.--This is my eightieth birthday;
it is wonderful indeed that I have lived to this late period.
Oh Lord! be pleased to prepare me for the midnight cry,
no matter what it may cost me. Amen and amen.

[verse]
____
Hail thou my eightieth birthday,
The gift of God to me.
Clothed in a shining raiment
Thy early morn I see.

But still thou looks more solemn
Than birthdays of the past;
Perhaps an indication
That thou mayest be my last.

Thy noontide cold and stormy
Will soon have passed away,
But all is wisely ordered
By Him who rules the day.

Farewell my eightieth birthday,
Thy race is nearly run,
Whilst faith and hope and mercy
Attend thy setting sun.

Farewell now and forever,
We part to meet no more,
Nor would I ask another
This side the Heavenly shore.

I would not ask another,
But may thy will be done
In me, and by and through me,
Thou just and Holy One.
____

First Month 14th, 1888.--Oh Christendom!
Christendom! what wilt thou do when the anger of the Lord is
poured out upon thee in fury and in furious rebukes,
because of thy pride and the haughtiness of thine heart?

Third Month 6th.--Bless the Lord, oh my soul,
who has been with thee in the depths of affliction.

21st.--I am now able to walk about the house, after being confined most of the winter;
have been out at meeting once.
Being raised up again from the depths of affliction is indeed the Lord`'s doing,
and marvellous in mine eyes,
and I think it is marvellous in the eyes of those who
have waited on me during this affliction,
both Friends and physicians.
Oh, thou Searcher of hearts, enable me to be faithful to all thy requirings,
neither going before nor lagging behind the true Guide.
