== Chapter XIII.

[.chapter-synopsis]
* Paid a Religious Visit to the Yearly Meeting of the Smaller Body in New England, and Most of its Branches
* Attended Several Meetings in Philadelphia and Thereabouts, On Her Way Home
* A Plain and Searching Testimony at Arch Street Monthly Meeting
* Confinement by Indisposition
* A Religious Visit to the Meetings Constituting Salem Quarter
* Home Exercises, and Religious Service, When Physically Able, Within the Limits of Her Own Quarterly Meeting
* Permanently Declining Illness, and Spiritual Exercises of Her Last Days

Sixth Month 5th.--With Minutes of unity and approbation
from the Monthly and Quarterly Meetings,
I left home accompanied by my cousins, Jacob Holloway and Abigail Sears,
for the Yearly Meeting of New England.

Our friends, Joseph S. Elkinton and wife, of Philadelphia,
having previously given us a kind invitation to call with them on our way farther east,
and to home with them during our visit in the city,
we accepted the invitation and were very kindly treated;
Joseph accompanying us during our visit within their limits,
which we esteemed a special favor.

We arrived at Westerly, Rhode Island,
where New England Yearly Meeting is held (Smaller Body), on the morning of the 7th inst.,
and were conducted to the house of Anna A. Foster, widow of the late Ethan Foster,
where we were most kindly entertained during the time of the Yearly Meeting,
and afterwards whilst we remained in their limits.
Nine sittings of the Yearly Meeting,
including the sittings of the Select Meeting and the Meeting for Sufferings,
closed its session; all of which I attended.

That Yearly Meeting has appointed some women
Friends members of the Meeting for Sufferings.
We found a very small Yearly Meeting,
yet were comforted in the belief that the Lord has a seed there,
which is precious in his sight.
My mission amongst them appeared to be,
to encourage Friends to rally to that which gathered us to be a people,
to the praise and glory of God.
The leadings and teachings of the Holy Spirit, not only gathered us to be a people,
but also preserved our early Friends faithful in their allegiance to the Lord of lords,
and King of kings,
amidst the most cruel persecutions inflicted upon them by their enemies.
It matters not what our trials and temptations may be, inwardly or outwardly,
if we keep to the leadings and teachings of the Holy Spirit,
our spiritual live will be given us for a prey,
and we shall be made more than conquerors through Him that loved us,
and gave himself for us, Christ Jesus the righteous.

It was by keeping to the law of the Lord, that Noah,
Daniel and Job were preserved alive in the Truth, amidst the great trials,
temptations and provings permitted to come upon them; and if these three men were here,
"`they should deliver but their own souls by their
righteousness,`" they could save neither son nor daughter.

It was by keeping the eye single to the Lord and
waiting upon Him for the renewal of strength,
that John Wilbur was enabled to endure a fight of affliction amongst fake brethren,
which I believe has had no parallel in the religious Society of Friends,
from its rise to the present day,
and we doubt not that he is safely landed where the wicked cease from troubling,
and the weary are at rest, having received the end of his faith,
even the salvation of his soul,
and maintained his allegiance firm unto the Lord of lords, and King of kings,
unto the end of his days.

I exhorted Friends to keep up their meetings,
though their number in most places is very small,
remembering the promise of our Saviour--"`Where
two or three are gathered together in my name,
there am I in the midst of them.`"
If He is in our midst what can we ask more,
and without Him what are all things else? Nothing,
that will give us any comfort or consolation.
The principles and testimonies of ancient Quakerism are, as we have heard declared,
nothing more nor less than primitive Christianity revived,
and we cannot let fall any of these precious principles and testimonies,
without suffering great loss as individuals, and as a Society.
We have as much need to faithfully support them in this day and age,
as at any time since the rise of the Society.
Christendom and the world at large calls loudly and
impressively for this faithfulness on the part of Friends.
"`Watch ye, stand fast in the faith, quit you like men, be strong.`"
Put on the whole armor of God, that ye may be able to stand, and having done all,
to stand.
"`Stand therefore, having your loins girt about with Truth,`" and your lamps burning.

Thus I encouraged Friends to stand faithful,
believing there was a little remnant in those parts,
who amidst all the trials through which they have passed,
could adopt the language--"`Doubtless thou art our Father,
though Abraham be ignorant of us, and Israel acknowledge us not: thou, oh Lord,
art our Father, our Redeemer.`"
Yet there were those in this small Yearly Meeting,
who I believed were ashamed of the cross of Christ.
These were exhorted to a full surrender of the heart to the Lord,
and to bear in mind the words of our Saviour--
"`Whosoever shall be ashamed of me and of my words,
of him shall the Son of man be ashamed when He shall come in his own glory,
and in his Father`'s, and of the holy angels.`"
We must become practical cross-bearing Christians if we are
owned of Christ Jesus when done with this state of probation.

We attended the meetings of that Yearly Meeting, which are regularly kept up,
and visited most of the families belonging to them.
My mind was strongly attracted towards other places
where the meetings are not regularly kept up,
but the way did not open with sufficient clearness for
me to visit Friends in those neighborhoods,
hoping other messengers will be sent amongst them in the Lord`'s way and time
to the strengthening of their hands and hearts in every good word and work.

Having closed our visit in the limits of this Yearly Meeting,
we left Westerly on the 19th and took the cars for Philadelphia,
arriving there the same evening.

20th.--Attended Philadelphia Monthly Meeting for the Western District,
held at Twelfth Street.
There were two strangers present, ministers from Baltimore Yearly Meeting,
who had considerable to say.
The woman minister sat in the gallery,
but made little if any appearance of a Friend in her dress.
Though considerable time was occupied by these strangers,
yet I found opportunity to relieve my mind in a plain and clear testimony,
and the Truth rose into dominion over all opposition.

I arose with the language of Solomon--"`A just weight and balance are the Lord`'s;
all the weights of the bag are his work.`"
I said, it is a solemn consideration, that if the Lord turn the balance in our favor,
all the world cannot turn it against us; but if He turn it against us,
the whole world cannot turn it in our favor.
How important then that we be in earnest to have our
spiritual accounts in readiness for the final summons,
knowing judgment laid to the line and righteousness to
the plumb-line in the temple of our hearts,
being willing to be searched with the candle of the Lord,
and to have all our deeds brought to the light, and judged by the light;
as this becomes our living and heart-felt concern,
the prayer of our hearts will be on this wise--"`Search me, oh God, and know my heart;
try me, and know my thoughts.
And see if there be any wicked way in me, and lead me in the way everlasting.`"
It matters not how high and holy our profession is, if we are not practical Christians,
we are not the disciples of Christ,
not such as He will deign to own before his Father and the holy angels.

We must know the baptism of the fire and Holy
Ghost to cleanse our hearts from all the dross,
tin and reprobate silver, from all the filth and defilements of the flesh.
This is the only essential baptism,
that which purifies and cleanses the heart from all that the Lord`'s controversy is with.
This baptism we must experience if we become the
meek and self-denying followers of Christ Jesus,
our crucified, risen and glorified Redeemer.
Who are those concerning whom our Saviour made this impressive declaration? viz:
"`Many will say to me in that day, Lord, Lord, have we not prophesied in thy name,
and in thy name have cast out devils,
and in thy name done many wonderful works? And then will I profess unto them,
I never knew you: depart from me ye that work iniquity.`"
Were not these high professors of religion boasting of what great
things they had done in the name of Christ? Calling Him Lord,
Lord, and yet He had never known them as his humble, self-denying followers,
and therefore could not own them.

I came not amongst you to arraign any for condemnation, or accusation;
you are all strangers to me,
nevertheless I earnestly desire the salvation of all present.
I believe there are those here who are dissatisfied with the course they are pursuing,
and I would recommend such to turn inward to that light, grace and Truth,
a measure and manifestation of which is given to every man to profit withal.
That grace and Truth which gathered Friends to be a people to the glory of God;
and enabled them to endure the scoffs and frowns of the world,
and all the persecutions inflicted upon them, with Christian patience and fortitude,
rejoicing that they were counted worthy to suffer for the precious principles and
testimonies that many now bearing the name of Friends are trampling under foot.

William Dewsbury, who was a prisoner more than twenty years,
left this testimony on record, that he joyfully entered prisons as palaces,
and esteemed the bolts and locks as jewels.
As we have often heard said, so I believe,
that ancient Quakerism is primitive Christianity revived,
and as long as primitive Christianity has a practical advocate,
ancient Quakerism will live and not die.

Those who follow this light, grace and Truth of which I have spoken,
will not be disappointed; they will be given to see the right way,
and enabled to pursue it. Our Saviour said to
his disciples--"`If any man shall say unto you,
Lo here is Christ, or there; believe it not.
If they shall say unto you, Behold He is in the desert; go not forth:
behold He is in the secret chambers; believe it not.
For as the lightning cometh out of the east, and shineth even unto the west;
so shall also the coming of the Son of man be.`" When we see a
vivid flash of lightning from east to west we know what it is,
and whence it is,
there is no guessing about it. They that wait upon the Lord shall renew their strength;
they shall mount up with wings as eagles; they shall run and not be weary,
and they shall walk and not faint.
I encouraged all to take Christ`'s yoke upon them,
and learn of Him who is meek and lowly in heart,
and they shall find rest unto their souls.

Moreover, those who apostatized from the ancient principles and testimonies of Friends,
will find no settlement nor foundation in the Truth,
and the great and high profession they are making of faith in Christ,
and their boast of doing wonderful things in his name,
will be to their shame and confusion, when He shall profess unto them, I know you not.

Before men and women Friends separated to transact the business,
an aged Friend came to me,
and expressed in a feeling manner his unity and
satisfaction with my services amongst them.
The women`'s Clerk called for our Minutes before proceeding to other business,
and read them, and several expressed satisfaction with our company,
desiring we might feel all freedom amongst them.

In the last meeting I quoted the language--Watchman, what of the night? Watchman,
what of the night? And believing there were those
present inquiring of the watchmen the way to Zion,
these were directed and encouraged to return to Him from whom
as a religious Society we had greatly revolted.
So come into the obedience of faith, following the light of Truth in their hearts,
and they would find rest to their souls.

21st.--Attended Arch Street Preparative Meeting, and had considerable service therein,
to the relief of my mind.
On arising the second time to speak in this meeting,
I quoted the language--Blessed are they that hunger and thirst after righteousness,
for they shall be filled; and was proceeding,
when I noticed a woman on her feet near the door.
Supposing she was speaking, I sat down, being so deaf I could not hear;
but a Friend near me motioned to me to proceed, which I did,
and finished what was on my mind to say.

After the meeting closed, a young Friend spoke to this stranger,
and told her I was hard of hearing and did not know she was speaking.
She replied, it was all right,
and that she would like to have some conversation with
me. At a suitable time she was invited to our lodgings.
She told us she had been under great exercise of mind for a considerable time;
that I had spoken to her condition at Twelfth Street Meeting,
and she wished to have an opportunity with me. She belonged to the Methodist Society,
but was dissatisfied with that profession.
She had recently been reading George Fox`'s Journal,
and felt that her exercises of mind answered in some respects to his,
and she had been encouraged and strengthened by perusing his Journal.
She said the rebuke I gave her by arising and quoting the passage I did,
whilst she was speaking, was what she needed.
She had prayed that the Lord might rebuke her in whatever way He might choose,
and bring her into a conformity with his will.
She believed she needed to be brought into true silence and stillness before Him, etc.

I told her that was what she needed to learn, the lesson of true silence,
and as she attended to the Light of Christ in her heart, with which she had been visited,
she would be led along in a plain path, out of all entanglements,
and finally made more than conqueror through Him that loved us.
I commended her to God and the word of his grace,
which is able to build us up and give us an
inheritance amongst all them that are sanctified,
and thus we parted.

After this meeting at Arch Street, cousin Jacob went to see his children,
who lived about forty miles from the city; and cousin Abigail and myself,
accompanied by our kind friend, Joseph S. Elkinton, went to Moorestown, New Jersey,
and put up at our dear friend, Hannah Warrington`'s. Feeling the need of some rest,
and desiring to attend Moorestown Meeting, we tarried there until after First-day,
the 24th. We had a very pleasant, and I hope profitable,
stay with Hannah Warrington and nieces,
and a sweet visit with dear Martha R. Comfort and sisters
(Phebe and Lydia Roberts). Martha R. Comfort has since deceased,
making a happy and peaceful close.
She was a truly baptized elder, who had a clear vision,
and whose taste could discern perverse things.

Our friend, Hannah Warrington, is in the ninety-sixth year of her age.
She is frail in body, but able to get out to meetings quite frequently.
Her sight and hearing are remarkably good for one of her age,
and her intellectual faculties as much so. The strength and clearness
of her mind and memory surprises those who converse with her.
Having given up to serve the Lord in the days of her youth,
and having continued faithful in her allegiance
to Him throughout her life to the present time,
she is richly endowed with that wisdom from above which renders her company
and conversation very instructive and interesting to old and young.
Hannah Warrington maintained a firm and uncompromising
testimony against the heresy of Elias Hicks,
and no less so against the unsound and anti-Quaker doctrines of Joseph John Gurney,
whilst many others who profess to be standing firm for the ancient doctrines of Friends,
by compromising somewhat with Gurneyism and Gurneyites,
have become partially blind and shorn of their spiritual strength, but know it not.

24th.--Attended Moorestown Meeting; it was large, and I was favored therein,
to relieve my mind in a plain testimony for the Truth.

25th.--I parted with my dear friends at Moorestown; to meet no more in mutability.
May the Lord grant a preparation for a re-union in that holy and heavenly city,
into which nothing that is unclean can enter.

26th.--Attended Philadelphia Monthly Meeting for the Northern District.
I feel it right to express my belief, that the shaking, and sifting,
the turning and overturning which has been going on in our
Society for the last fifty or sixty years are not over:
we shall yet be more and more closely proven and tried,
especially those who are professing to stand firm for
the ancient doctrines and testimonies of Friends;
and my exhortation is that Friends may be able to endure what
is yet to come by deepening in the root of life;
"`Yet once more I shake not the earth only, but also heaven; and this word,
yet once more, signifieth the removing of those things that are shaken,
as of things that are made, that those things which cannot be shaken may remain.`"
We have need to be emptied and purged as from the gallery to the door;
all classes amongst us, that we may be able to say indeed and in truth, "`I am nothing,
Christ is all.`"
Human wisdom,
and human policy in the transaction of Church affairs must be rooted out from amongst us;
we cannot climb so high or burrow so deep in the earth,
but that the judgments of the Lord will overtake us;
we cannot wrest ourselves out of his hands,
and all who do not bow in mercy must bow in judgment.
"`That at the name of Jesus every knee should bow, of things in heaven,
and things in earth, and things under the earth;
and that every tongue should confess that Jesus Christ is Lord,
to the glory of God the Father.

27th.--Attended Birmingham Monthly Meeting, held at West Chester,
twenty-five miles from Philadelphia.
Quite a number of the Yearly Meeting`'s Committee were present,
having met there to arrange for carrying out the object of their appointment, viz:
to visit Subordinate Meetings, families, etc., and to appoint as they may see fit,
public meetings amongst those not in membership with Friends.

On taking my seat in this meeting, I felt a hope to arise,
that it might be right for me to sit through in silence,
and for a time it seemed that it would be realized.
But as I sat musing, the fire burned, and matter arose for communication,
and under a sense of duty I felt constrained to give utterance thereto,
and I arose and said:
It is recorded in the New Testament that there were two sisters named Martha and Mary,
and that Jesus loved them both; but Martha was cumbered about much serving,
whilst Mary sat at Jesus`' feet, and heard his word.
Martha requested Jesus to bid Mary help her, and received from the Saviour this rebuke,
"`Martha, Martha, thou art careful and troubled about many things.
But one thing is needful, and Mary hath chosen that good part,
which shall not be taken away from her.`"

Martha had not this promise given her;
we may suppose that Martha`'s trouble and care about
much serving was in regard to temporal matters;
but there is such a thing as being careful and
troubled about much serving in spiritual matters,
instead of sitting at the feet of Jesus to hear and obey his voice.
I have learned that the Enemy would just as
leave I would get up and preach a sound sermon,
inviting my fellow pilgrims to come taste and see that the Lord is good--
that He is worthy to be honored and obeyed with the whole heart--that He is
a rich rewarder of those who diligently seek and serve Him,
etc., provided the seal of Divine approbation is not upon it;
as if I were to preach an infidel sermon.
For the enemy very well knows that nothing but that which comes from God can draw to God.
He very well knows that the nearer the counterfeit resembles the reality,
or the true coin; the more it is calculated to draw to his kingdom,
and to scatter from the kingdom of Christ.

Friends,
there is such a thing as individuals becoming
entirely blind as to their spiritual condition;
this was the case with the church of the Laodiceans.
They thought they were rich, and increased with goods, and in need of nothing,
and knew not that they were wretched, and miserable, and poor, and blind, and naked;
and that their condition was loathsome in the sight of God,
and yet their state was not altogether a hopeless one.
The language of the Spirit to this Church was,`" I counsel thee to buy of me,
gold tried in the fire, that thou mayest be rich;
and white raiment that thou mayest be clothed,
and that the shame of thy nakedness do not appear, and anoint thine eyes with eye-salve,
that thou mayest see.`"

I make no allegations against any present; but Friends! we have had many warnings,
and do we not believe there are at this time, amongst those claiming the name of Friends,
individuals, and even whole meetings,
as blind to their spiritual condition as were the Laodiceans?
But let us remember that we have the same fallen nature as
these--the same unwearied enemy to contend with,
and we have only to turn away from the leadings and teachings of the Holy Spirit,
and follow the will and wisdom of man, to become as blind as they.

"`Let him that thinketh he standeth take heed lest he fall.`"
The Lord is no respecter of persons; there is no safety for any of us,
only by keeping the eye single unto Him,
and following the leadings and teachings of his Holy Spirit.
These He will preserve alive in the Truth.
These are able to detect the transformations of Satan, and will not be deceived thereby,
though they are many and various.
I exhorted the young people to turn inward and keep the eye to the Master,
that they might be able to discern what was of and from Him, and what was not.

28th.--Attended Philadelphia Monthly Meeting, held at Arch Street.
On arising to speak in this meeting,
I referred briefly to Ezekiel`'s vision by the river Chebar,
saying that this vision of the prophet concerning the wheels, represented to my mind,
the state of man as he stands in the fall,--his
lifeless and powerless condition spiritually,
and also his state and condition when raised out of the fall.
It must have been wonderful to the prophet, to behold wheels lifted up from the earth,
having the spirit of the living creatures in them, going straight forward,
turning not as they went, following the Spirit whithersoever it went,
for whither the Spirit went their spirit was to go; and it was cried in my hearing,
"`Oh wheel.`"
So man, quickened by the Holy Spirit, and following its leadings and teachings,
is raised up out of his natural, lifeless and fallen condition,
and enabled to pursue the path that leads to peace, happiness and everlasting glory,
notwithstanding all the hindering and letting things, cast into his way by the world,
the flesh and the devil.

Following the prophet in his vision, he saith, So the spirit lifted me up,
and took me away, and I went in bitterness, in the heat of my spirit;
but the hand of the Lord was strong upon me. And he was commanded to go,
and to speak unto the house of Israel all that the Lord commanded him to speak.
At the same time the Lord said unto him: But they will not hearken unto thee,
for they will not hearken unto me.

The above is the substance of what I said when I first spoke in this meeting.
I then took my seat, and after sitting awhile, I arose and said:

Now, Friends, I have a testimony to leave with you, and I must be faithful,
whether you are able to receive it or not.
There is, I believe, in this Yearly Meeting, a compromising spirit,
with which the Lord hath a controversy.
This spirit has arranged itself conspicuously on the side of ancient Quakerism,
both by word and writing, nevertheless, it practically ignores the Discipline,
by refusing or declining to put that official difference between the sound
and the unsound which the Discipline and the order of the gospel enjoin.
It allows all to go in and to come out of Meetings for Discipline on the same platform;
that is, without any official acknowledgment of the sound, or rejection of the unsound.
This spirit has its origin in the wisdom and policy of man.
It is also a fearful, cringing spirit, afraid to do right for fear of consequences.
I believe the Lord will turn and overturn, sift and shake,
until this spirit is rooted out,
even if it should leave but a very few standing plumb
for the Truth--comparable to the few berries,
in the outmost fruitful branches of the uppermost bough, (Isaiah, xvii:
6.) There are some amongst you, who are dissatisfied with this state of things,
but they are afraid to speak their minds,
lest they should lose caste or credit with others.

After this meeting,
I felt released from further service within the limits of Philadelphia Yearly Meeting,
except some plain talk with a few individuals, on the subject above referred to.

On the 29th, started for home, and arrived there safely on the 30th,
thankful for the favors bestowed whilst out on this visit,
and thankful for a safe return,
without feeling any burden of omission or commission resting upon me.

In reference to my testimony in Arch Street Monthly Meeting as given,
I think it right to say,
that it has now been thirty-three years since the
Gurneyites separated from Ohio Yearly Meeting,
and set up a separate Yearly Meeting, known by the name of the Binns`' Yearly Meeting.
This body is notorious for its anti-Quaker principles and practices,
denying the Light of Christ in the heart of man, (see criticism on the Ohio Minutes,
by Cyrus W. Harvey) they practice water baptism, singing in their meetings etc.
At the time of this separation in 1854, Benjamin Hoyle was Clerk of Ohio Yearly Meeting.
At the next Yearly Meeting of Philadelphia, epistles were presented to it,
from the two bodies claiming to be Ohio Yearly Meeting.
The epistle signed by Benjamin Hoyle was read and recorded by Philadelphia
Yearly Meeting as coming from the legitimate Yearly Meeting of Ohio.
That signed by Jonathan Binns was considered as coming from a body of separatists;
but notwithstanding the decision of Philadelphia
Yearly Meeting relative to these two bodies,
it has from that day to this allowed members of the Binns`'
Yearly Meeting to attend its meetings for discipline,
and ministers from that body have been frequent in
their attendance of Philadelphia Yearly Meeting,
and others equally unsound from other Yearly
Meetings who correspond with the Binns`' meeting,
are allowed to preach and pray in the meetings of Philadelphia Yearly Meeting,
visit subordinate meetings and families, etc.,
without any official action taken according to discipline and
true gospel order to prevent it. This is a lamentation,
and shall be for a lamentation, until the breach is stopped, or mended.

Since my return from this visit, my health has been very poor most of the time,
so that I have not been out to meeting very often,
yet I attended our late Yearly Meeting,
and was favored with strength to attend all the sittings.
During the meeting I visited men`'s meeting.

Twelfth Month 28th.--On the 22nd of this month I was eighty years old.
Great and marvellous are thy works, Lord God Almighty, just and true are all thy ways,
what shall I render unto thee for all thy benefits? for thou hast
encompassed me about from my childhood with innumerable blessings.

Second Month 1st, 1889.--This morning is very bright, calm and beautiful,
and the air invigorating, having been preceded by many days of cloudy,
rainy and stormy weather,
during which I have suffered great oppression with bronchial affection,
but feel much better this morning.
May I continue to trust the great "`I Am,`" through all storms and tempests,
inwardly and outwardly.

17th.--Still confined to the house by indisposition.
But my heart is greatly exercised for the welfare of our little meeting,
and for society at large.
Oh that we might deepen in the root of life,
that our candlestick be not removed out of its place.

25th.--Still confined to the house and mostly to my bed, under weakness and suffering,
all ordered in wisdom by the Father of mercies.
Greatly exercised for the members of our little meeting.

Third Month 3rd.--It is seven weeks today since I was out of the house;
during this time I have suffered much with neuralgia and bronchial affection,
but I trust I have been preserved from murmuring, "`I have great cause for thankfulness,
not only for intervals of comparative ease from pain and difficulty of breathing,
but for those seasons when the great Physician interposes his omnipotent hand,
and soothes this suffering tenement of clay,
and gives me to see and feel that nothing is too hard for Him to perform.
Blessed be his name.
He can bring low and raise up, according to his own will and good pleasure,
and none can stay his Almighty hand and power.
"`Bless the Lord, oh my soul, and all that is within me bless his holy name.`"

5th.--The outward creation is a theme for contemplation, wonder and admiration,
concerning the power, wisdom and goodness of the great Creator;
and in view of the Christian traveller,
the work of the Lord in the heart of man is no less marvellous.

6th.--I feel deeply and renewedly sensible of the natural depravity of the human heart,
and that every imagination of the thoughts of
the heart of man is evil and that continually,
in his unregenerate state;
and that nothing can give him a sight and sense of this depravity, but the grace of God,
which is his gift for man`'s salvation, through Jesus Christ our Lord;
and by following this light, grace and truth,
he becomes regenerated and born again of the incorruptible
seed and word of God that liveth and abideth forever.

Sixth Month 28th.--Today I returned home from a
visit to the meetings of Salem Quarterly Meeting,
having previously visited those of Stillwater, with a Minute obtained in the Fifth Month,
liberating me for the service.
I have, during these visits, appointed four meetings from amongst Friends,
all to the relief and peace of my mind.
But oh, the baptisms which it has cost me to appoint meetings amongst others,
being so very frail and weak for such engagements but I
must say that the Lord has been very gracious unto me,
and verified his promise, viz:
"`I will be with thee and strengthen thee as thou puts thy trust in
me.`" And verily I have found to my great admiration and satisfaction
that He has not forsaken me in times of great trial,
when the heavens were as brass, and the earth with her iron bars were round about me,
and I seemed enclosed as with hewn stone.
Truly He hath been strength in weakness and a present help in the needful time.
My soul doth magnify and praise his great and adorable name.

Great plainness of speech have I been led to use among my own people,
and to warn them of the judgments yet to come,
if we repent not of our many sins and grievous backslidings.

'`Seventh Month 23rd.--I attended Short Creek Monthly Meeting,
in which I felt it right to revive the language of the prophet Jeremiah,
"`Assemble yourselves, and let us go into the defenced cities.
Set up the standard toward Zion; retire, stay not.
The lion is come up from his thicket, and the destroyer of the Gentiles is on his way.`"
I had to express my belief that the Lord would yet try us as to an hair`'s breadth.
It matters not what we may profess,
as to be standing for the ancient doctrines and testimonies of Friends,
if we are not practical cross-bearing Christians, such as our early Friends were;
all our profession will avail us nothing.
I said there was amongst us a worldly compromising spirit, which if not rooted out,
would root out ancient Quakerism from our midst,
as surely as it had rooted out ancient Quakerism from the Gurneyites.
I exhorted Friends to get down deep and earnestly seek in that ability which
God giveth to build upon the sure foundation which can abide the storm,
quoting from Isaiah: "`My people shall dwell in a peaceable habitation,
and in sure dwellings, and in quiet resting places, when it shall hail,
coming down on the forest,`" etc.

Tenth Month 14th.--I attended all the sittings of our late Yearly Meeting,
which ended on the 4th inst.
I had but little vocal service therein.
There was a good deal of preaching on public meeting days,
and during the business transactions.
But this language was sounding in my ears: "`Be silent O all flesh, before the Lord;
for He is raised up out of his holy habitation.`"
Previous to our late Yearly Meeting I spent three weeks
in the limits of Guernsey Preparative Meeting,
a branch of Flushing Monthly Meeting.
Some of this time I was suffering too much with
neuralgia to attend to any religious service,
but was enabled to visit a number of families mostly among the Gurneyites,
which appeared to be well received, and afforded peace to my mind.
I also appointed a meeting for worship in that neighborhood for those people.
They generally attended and behaved with much propriety,
and I thought it might be said Truth reigned over all opposition.
I spoke of the spring of Gospel ministry, and of true and acceptable worship,
in a very plain way, contrasting the true and the false,
and showing the different results between the two,
and how the Lord Jesus spake of those who boasted of having prophesied in his name,
and in his name cast out devils, and in his name done many wonderful works.
I earnestly entreated those present to examine by the light of Christ in their hearts,
how their spiritual accounts are standing in the sight of the Lord,
who cannot be deceived,
and be willing to bear the baptisms of the fire
and Holy Ghost (the only essential baptism),
which will cleanse the heart from all the filth and defilements of the flesh,
and prepare it for the inscription of holiness unto the Lord.
For without holiness no man shall see the Lord.
It cost me much conflict of spirit to give up to appoint this meeting,
but I felt a great burden off my shoulders after it was over.
Blessed be the name of the Lord.

Eleventh Month 2nd.--I have been for nearly two weeks past unable to get out to meetings,
and suffering at times, with great difficulty of breathing.
But I do not feel like murmuring.
Blessed be the Lord, who I believe hath not forsaken me.

Twelfth Month 22nd.--Today I enter the eighty-second year of my age;
the day has been bright and beautiful, calm and mild as that of a southern clime.
But I am very frail and weak, not able to get to meeting, or scarcely walk alone.
But this has been the language of my heart:
"`Surely goodness and mercy have followed me all the
days of my life,`" and a humble hope pervades my heart,
that when the summons of death comes, the Lord will not cast me off,
but that through his mercy in Christ Jesus I may be permitted to land safely.
Oh blessed hope.

Third Month 19th,
1890.--"`Day unto day uttereth speech and night unto night showeth knowledge.`"
A fall of snow last night,
and this morning the earth is clothed in a beautiful white robe; every tree,
and every limb and twig, is loaded with beautiful white crystal flakes.
Oh thou great and holy One, what is man that thou art mindful of him,
or the son of man that thou visitest him.`"
Thy wisdom, power and goodness is seen in all thy works,
and made manifest to the eye of faith.
Shall I ever cease to trust in thy mercy and goodness in the most proving
and trying days and hours yet to be dispensed in this state of probation.
When the heavens seem as brass, and the earth with her iron bars are round about me,
apparently without possibility of change; give me, I entreat thee, patience to endure,
for I know thou canst change the dispensation at any moment thou seest fit.
I have proven thy lovingkindness, thy power and thy goodness,
and should I now cast away my confidence,
when the shackles of mortality are ready to drop off?
Thou knowest my weakness physically and mentally;
thou knowest I have no power to do aught to thy praise or glory,
only as thou strengthens me. Blessing, praise, glory,
honor and high renown be ascribed unto thee, now and forever.
Amen.

Fourth Month 13th.--I was taken with La Grippe one week ago, and have been very ill.
My cough at times threatening strangulation.
But the Lord who sitteth upon the flood, who sitteth King forever,
has been my helper and preserved my life thus far.
Blessed be his name.

20th.--This has been a beautiful day; the sky clear, the air pure and salubrious,
and the whole face of nature smiling with verdure and beauty.
But my own unworthiness to partake and to enjoy the bounties of a bountiful Giver,
and the condition of my people casts a gloom over all.
Some might say what do I mean by this? I mean that the
ingratitude apparent for the blessings conferred upon us,
the worldly mindedness, the pride and vanity, in short,
the want of practical Christianity amongst the people in general,
of every religious denomination, as well as the non-professor,
seems to me to threaten us with heavy judgments, both in Church and State.

I attended our little meeting today,
and felt that the prayer and confession of Nehemiah on behalf of himself and his people,
might well engage our thoughts.
Oh, the prostration of soul that is called for, that we may not be swallowed up.

Sixth Month 23rd.--Oh, Lord God, thou knowest my poverty, temptations and tried condition.
Be pleased, I entreat thee,
in thy great mercy to continue thy lovingkindness towards me, in rebukes, chastisements,
or in any way thou sees fit for my purification.
I have been holding a Minute for more than a year,
for religious service within our own Yearly Meeting, amongst Friends and others,
but for some months past my way has been closed up,
and I have not been able in body or mind to prosecute the visit further,
and yet not satisfied to return my Minute.
Great at times have been the conflicts of my spirit.
Oh, that I may be preserved from casting away my confidence in the Lord.

Yesterday, I was eighty-one years and six months old, and I can say,
hitherto the Lord hath helped me through many straits and difficulties,
and shall I now give out in my old age? Oh,
my soul rather chooses to bear anything thou mayest be pleased to dispense,
oh thou Holy One, than give way to doubting and despair.

It is about three months since I opened my mouth
in the ministry in our religious meetings,
or elsewhere, until yesterday.
Meeting with a man with whom I had some acquaintance some years ago,
and knowing him to be in a dark and disconsolate condition;
soon after shaking hands with him something arose on my mind to say to him,
and before leaving the Friend`'s house where I met him,
I spoke to him what was on my mind.
I told him that there was hope for us,
so long as the door of mercy was not closed against us,
no matter what our spiritual condition might be. That I
believed the door of mercy was not closed against him;
but the call was to arise, and shake himself, through the ability afforded,
from all that the Lord`'s controversy is with.
To bear the judgments of the Lord, in the temple of the heart,
that a preparation might be experienced for that holy and glorious
city whose walls are salvation and whose gates are praise,
and into which nothing that is unclean can enter.
He is one who left our Yearly Meeting some years ago with Joshua Maule and others,
and he has had a bitter cup to partake of since,
his wife having deserted him and living with another man, and casting him off.

I felt peaceful and easy after this little service, and this consideration arose, viz:
If the Master had wholly forsaken me He would not have
required and strengthened me for this little service.
Oh, that I may quietly wait and patiently hope for the return of the Beloved of souls.
I know that I need the fire and the hammer;
I know that I need renewed baptisms of a fiery nature.
Why then, oh my soul,
why recoil at these dispensations? Rather kiss the rod and bless the hand that wields it.

Seventh Month 22nd.--Oh, Holy Father, thou who hast all power in heaven and in the earth,
be pleased, I beseech thee,
to preserve me from the temptations of the adversary that surround my
pathway at the present time on the right hand and on the left,
that I may not now in the decline of life, after having experienced thy arm of power,
through all my life thus far to support, cast away my confidence in thee.
Oh, holy and blessed One, I do most ardently beseech thee,
through thy everlasting mercy in Christ Jesus to undertake for
me. Thou knowest my great weakness bodily and mentally,
and that I desire to be able to say, in deed and in truth--Thy kingdom come,
thy will be done, in earth as it is heaven.
Oh, hear the prayer of one of the weakest and most unworthy of thy creatures,
that I may put on strength in thy name,
and that the creature may be abased as in dust and ashes before thee.
Amen, and amen.

Tenth Month 14th.--It is now seven weeks since I
was suddenly prostrated with heart failure,
and my life often despaired of since, as well as often before.

[verse]
____
Oppressed and trembling, on the verge
Of death I often stand,
Whilst naught prevents the threatening stroke
But thy almighty hand.

The great Almighty, holy One,
How marvelous thy power,
Grant faith until my race is run,
To light the darkest hour.

In the dark watches of the night,
Oppressed I cry to thee;
And thou in mercy hears my prayer,
Relieves and strengthens me.

I will talk of thy goodness,
I will tell of thy might;
I will praise thee by day,
I will praise thee by night.

Thou bringest me low,
Thou raisest me up;
Embitters the draught,
And sweetens the cup.

Through unspeakable mercy
Thou deigns to control,
The dangers that threaten
My body and soul.

Every blade of grass,
Every leaf on the tree,
Unite in ascribing
Thanksgiving to thee.
____

Eleventh Month 23rd.--Attended meeting today for
the first time within the last three months.
During the interval I have been brought near to the grave.
But He who hath all power in heaven and in the earth,
hath raised me up again to proclaim his goodness and mercy,
his long suffering and kindness to the children of men.
Oh, that they might serve Him better and love Him above all.
I quoted in our meeting today, this passage, viz: "`If thou hast run with the footmen,
and they have wearied thee,
then how canst thou contend with horses? And if in the land of peace,
wherein thou trustedst, they wearied thee,
then how wilt thou do in the swelling of Jordan?`"

I felt that there were some present, who were pursuing a path, going along with others,
that did not bring peace of mind, and I exhorted them to stay their footsteps,
whilst strength and opportunity were offered,
lest temptations come upon them too strong to resist;
and they be left to themselves and overpowered thereby.
Continuing in a false rest when opportunity and a call
is given to wake up and come out of that condition,
what will such do, when the judgments of the Lord overtake them,
and no more opportunity given to make their calling and
election sure? The swellings of Jordan must overtake all;
but the righteous have an anchor to the soul, both sure and steadfast.
Oh, how ardent are my exercises for myself and fellow-pilgrims,
that we may turn unto the Lord with the whole heart.

Twelfth Month 6th.--Yesterday was a day to be remembered; great oppression,
and difficulty of breathing, caused by heart failure.
But the Lord was pleased to keep the vapor of life from becoming extinct.
Surely, I have many solemn warnings to be ready for a sudden call from works to rewards.
Oh, that I may not be weighed in the balance and found wanting at that solemn period.

22nd.--Today, I enter the eighty-third year of my age.
I wish to commemorate the goodness and mercy of God to my soul all my life long.

First Month 6th,
1891.--Dearest Father! grant patience to endure this great
affliction thou in thy wisdom hast permitted to come upon me,
so that I may not bring dishonor or reproach upon the Truth, by thought, word or deed.
Amen, and amen.

Second Month 9th.--Great is the Lord, and greatly to be praised,
and his greatness is unsearchable.
Praise Him all ye people.
In the depths of affliction I will praise thee.
Oh, keep me in the everlasting patience of thy saints.
Thou only knowest my weakness and suffering, and thou only canst give relief.
Praises, high praises, be ascribed to thy name; blessing, glory,
hallelujah and high renown.
Amen.

Third Month 28th.--Oh Lord, thou only knowest,
why thou hast permitted this sore and grievous affliction to come upon me, sanctify it,
I pray thee, to my soul, and to others in thy wisdom.
Give me patience, I entreat thee, to bear what is necessary for my refinement;
I go down into the deeps of oppression and physical distress, and my soul is troubled,
then thou hast compassion on me, and mitigates my distress.
Oh, Heavenly Father, be graciously pleased not to cast me off in this great extremity,
or allow me to bring reproach upon thy name, or the Truth I have espoused.

30th.--Thanks to thee, O Lord,
for the respite granted last night from severe suffering and distress.
Be pleased, I beseech thee, to enable me to endure more patiently what thou art pleased,
in thy wisdom to dispense, and give me implicit confidence to trust in thee,
in heights and in depths.

The following is an extract from a letter to a niece, same date, 30th:

[quote]
____
My love flows towards thee unabated through the waves and billows of deep affliction.
None but the Lord knows what this frail tabernacle is permitted to
suffer in the way of difficulty of breathing and great oppression,
and other things combined; but it is, I fully believe, in great wisdom dispensed,
and I can at times bless and praise his holy name through all,
and the language of my heart now is,
"`Oh! that men would bless the Lord for his goodness
and for his wonderful works to the children of men.`"

A little respite now and then from the oppression and distress is unexpectedly granted;
last night it was so, and left me in quiet sleep and repose,
which is indeed cause of deep gratitude of heart,
showing that the dear Master can change the dispensations whenever He sees meet.
Oh, that I may be fully prepared to say at all times, and under all circumstances,
'`Thy will be done.`' It is marvellous to me,
that I am able to write these lines to thee today.
____

31st.--I cannot look over my letter this morning to correct any mistakes.
Farewell, dear R., and all the rest!
Thy afflicted aunt, Ann Branson--yet trusting in the mercy of God through Christ Jesus.`"

Fourth Month 6th.--Bless the Lord, Oh, my soul, and all that is within me,
bless his holy name, who redeemeth thy life from destruction,
who crowneth thee with lovingkindness, who restoreth thy soul,
who leadeth me in paths of righteousness for his name`'s sake;
and though I walk through the valley of the shadow of death, I will fear no evil,
for thou art with me; thy rod and thy staff they comfort me.

This last entry was penned five days before her death,
which occurred at the residence of her sister-in-law, Juliann H. Branson, Flushing, Ohio,
Fourth Month 11th, 1891, in the eighty-third year of her age.
Her remains were interred in Friend`'s burying-ground on the afternoon of the 13th,
after a solemn meeting.
